<ul id="progNav">
    <li id="prog">
        <a href="/2018/programm/">Übersicht</a>
    </li>
    <li id="prog">
        <a href="/2018/programm/programm.php?day=1">Mittwoch</a>
    </li>
    <li id="prog">
        <a href="/2018/programm/programm.php?day=2">Donnerstag</a>
    </li>
    <li id="prog">
        <a href="/2018/programm/programm.php?day=3">Freitag</a>
    </li>
    <li id="prog">
        <a href="/2018/programm/programm.php?day=4">Samstag</a>
    </li>
    <li id="prog">
        <a href="/2018/programm/referenten.php">Referenten</a>
    </li>
    <!-- li id="prog">
        <a href="https://frab.fossgis-konferenz.de/de/2018/public/schedule" target="_blank">Programmseite</a>
    </li -->
</ul>
