<ul id="progNav">
    <li id="prog">
        <a href="/2018/programm/">Übersicht</a>
    </li>
    <li id="prog">
        <a href="/2018/programm/day1.php">Mittwoch</a>
    </li>
    <li id="prog">
        <a href="/2018/programm/day2.php">Donnerstag</a>
    </li>
    <li id="prog">
        <a href="/2018/programm/day3.php">Freitag</a>
    </li>
    <li id="prog">
        <a href="/2018/programm/day4.php">Samstag</a>
    </li>
    <li id="prog">
        <a href="/2018/programm/referenten.php">Referenten</a>
    </li>
</ul>
