<!doctype html>
<html lang="de">

<head>
	<?php include "../inc/meta.inc"; ?>

	<base href="<?php echo dirname($_SERVER['SCRIPT_NAME']); ?>">
	<title>OSM-Sonntag 10-16 Uhr – FOSSGIS 2021</title>

	<link rel="stylesheet" href="./css/normalize.css">
	<link rel="stylesheet" href="./css/base.css">
	<link rel="stylesheet" href="./css/print.css" media="print">
</head>

<body id="programm">
	<?php include "../inc/header.inc"; ?>

        <!-- This file was generated by a script. Do not edit this file in Git,
             edit contents in Pretalx, regenerate the PHP files and commit them
             in the Git repository of the website. -->
        <p><a href="programm/sonntag.php#session_3HU8JV">&#9668;&#9668; zurück zum Programm</a> </p>
        <h2 class='abstract-title'>OSM-Sonntag 10-16 Uhr</h2>
        <section>
            <p>
                <span class='abstract-sessiontype'>Diverses</span>                von <span class='abstract-speakers'>Frederik Ramm</span></p>
                                                                            <p><span class='abstract-time-heading'>Zeit: </span>Sonntag 06. Juni 10:00 Uhr
                <br><span class='abstract-room-heading'>Ort: </span>Bühne 1
                <br><span class='abstract-room-heading'>Dauer: </span>60 Minuten
            </p>

                        
            <p>Um 10 Uhr werden die Themen in Zeiten und Räume sortiert. Für das leibliche Wohl muss diesmal jeder selbst sorgen. Wir bitten um Anmeldung über das FOSSGIS-Konferenz-Teilnahmeanmeldesystem.</p>
        </section>


	<?php include "../inc/footer.inc"; ?>

</body>

</html>