<!doctype html>
<html lang="de">

<head>
	<?php include "../inc/meta.inc"; ?>

	<base href="<?php echo dirname($_SERVER['SCRIPT_NAME']); ?>">
	<title>Ein Ausblick auf das kommende GRASS GIS 8 – FOSSGIS 2021</title>

	<link rel="stylesheet" href="./css/normalize.css">
	<link rel="stylesheet" href="./css/base.css">
	<link rel="stylesheet" href="./css/print.css" media="print">
</head>

<body id="programm">
	<?php include "../inc/header.inc"; ?>

        <!-- This file was generated by a script. Do not edit this file in Git,
             edit contents in Pretalx, regenerate the PHP files and commit them
             in the Git repository of the website. -->
        <p><a href="programm/dienstag.php#session_7NRQSR">&#9668;&#9668; zurück zum Programm</a> </p>
        <h2 class='abstract-title'>Ein Ausblick auf das kommende GRASS GIS 8</h2>
        <section>
            <p>
                <span class='abstract-sessiontype'>Demo-Session</span>                von <span class='abstract-speakers'>Markus Neteler, Markus Metz</span></p>
                                                                            <p><span class='abstract-time-heading'>Zeit: </span>Dienstag 08. Juni 09:00 Uhr
                <br><span class='abstract-room-heading'>Ort: </span>Bühne 4
                <br><span class='abstract-room-heading'>Dauer: </span>55 Minuten
            </p>

                        
            <p>GRASS GIS ist ein modular aufgebautes geographisches Analyse-System. Es besteht aus mehreren Hundert Kern-Modulen und einer beständig wachsenden Zahl von Erweiterungs-Modulen (GRASS addons). Diese Module sind in erster Linie eigenständige Programme, die in der Befehlszeile aufgerufen werden. Zusätzlich gibt es eine eigene graphische Benutzeroberfläche, die in dieser Demo-Session vorgestellt werden soll. Wir werden mit der Darstellung von Raster- und Vektorkarten beginnen und dazu die verschiedenen Möglichkeiten zum Styling vorstellen. Zwei verschiedene Rasterkarten können visuell mit dem mapswipe Werkzeug und analytisch mit einem Scatterplot verglichen werden. In der Kartenansicht steht auch 3D-Visualisierung zur Verfügung, mit der z.B. Orthophotos über ein DEM gelegt werden können. Mit GRASS GIS können auch Zeitreihen erstellt, verarbeitet und über die graphische Benutzeroberfläche untersucht werden. Im Ausblick zeigen wir, wie GRASS GIS mit anderer Software wie QGIS, R, usw. zusammenarbeitet.</p>
        <div class='abstract-bio'>
            <h3 class='abstract-bio-name'>Markus Neteler</h3>
            <img class='abstract-speaker-avatar' src='/2021/avatars/GTQX8R_mn_bild_JoHempel_201709_Mundialis_MN_Cut_dsc_8483.jpg'>            <p>Dr. Markus Neteler ist Mitgründer von der mundialis GmbH &amp; Co KG in Bonn (https://www.mundialis.de/). Seine Interessenschwerpunkte sind Fernerkundung, Analyse großer Geodaten und Entwicklung freier und offener GIS, insbesondere GRASS GIS.</p>
        </div>
        <div class='abstract-bio'>
            <h3 class='abstract-bio-name'>Markus Metz</h3>
                        <p>langjähriger GRASS GIS Entwickler, gelegentliche Beiträge zu GDAL und QGIS, seit 3 Jahren bei mundialis</p>
        </div>
        </section>


	<?php include "../inc/footer.inc"; ?>

</body>

</html>