<!doctype html>
<html lang="de">

<head>
	<?php include "../inc/meta.inc"; ?>

	<base href="<?php echo dirname($_SERVER['SCRIPT_NAME']); ?>">
	<title>QGIS: Neue Overlay-Funktionen im Ausdruckseditor und Feldrechner – FOSSGIS 2021</title>

	<link rel="stylesheet" href="./css/normalize.css">
	<link rel="stylesheet" href="./css/base.css">
	<link rel="stylesheet" href="./css/print.css" media="print">
</head>

<body id="programm">
	<?php include "../inc/header.inc"; ?>

        <!-- This file was generated by a script. Do not edit this file in Git,
             edit contents in Pretalx, regenerate the PHP files and commit them
             in the Git repository of the website. -->
        <p><a href="programm/montag.php#session_7RHTEQ">&#9668;&#9668; zurück zum Programm</a> </p>
        <h2 class='abstract-title'>QGIS: Neue Overlay-Funktionen im Ausdruckseditor und Feldrechner</h2>
        <section>
            <p>
                <span class='abstract-sessiontype'>Workshop</span>
                                von <span class='abstract-speakers'>Stefan Giese</span></p>
                <p class='abstract-is-workshop'>Bitte melden Sie sich im <a href="https://pretix.eu/fossgis/2021/">Ticketshop</a> für diesen Workshop an, wenn Sie daran teilnehmen möchten.</p>                                                <p class='abstract-is-workshop'>Sie erhalten in der Woche vor der Konferenz eine E-Mail mit detaillierten Informationen zum Workshop sowie die Möglichkeit in einem Termin Ihre Technik auszuprobieren.</p>            <p><span class='abstract-time-heading'>Zeit: </span>Montag 07. Juni 14:00 Uhr
                <br><span class='abstract-room-heading'>Ort: </span>Workshop 2
                <br><span class='abstract-room-heading'>Dauer: </span>90 Minuten
            </p>

                        
            <p>QGIS bietet in seiner Benutzeroberfläche viele Funktionen und Einstellungsmöglichkeiten. Immer wieder begegnet man hier dem Ausdruckseditor, um z.B. Daten in einer Tabelle zu selektieren. Über den Ausdruckseditor lassen sich aber auch bestehende Attribute und Geometrien manipulieren sowie neue Attribute ableiten. Seit der Version 3.16 sind neue Overlay-Funktionen im Ausdruckseditor hinzugekommen. Mit diesen Funktionen lassen sich räumliche Relationen wie intersects, nearest, contains usw. zwischen verschiedenen Layern direkt verwenden, ohne dass die Daten zu neuen Layern processesiert werden müssen. Dies öffnet eine ganze Reihe von neuen Möglichkeiten bei der Darstellung und Verarbeitung von Geodaten in QGIS. Die Teilnehmenden können den Einsatz der neuen Funktionen im Feldrechner oder Ausdruckseditor an Schulungsnotebooks selbst ausprobieren und werden anhand von praktischen Übungsbeispielen durch die Materie geleitet. Von Vorteil sind Grundkenntnisse im Umgang mit Geodaten und Kenntnisse im Umgang mit QGIS.</p>
        <div class='abstract-bio'>
            <h3 class='abstract-bio-name'>Stefan Giese</h3>
                        <p>Ich bin Diplomgeologe und seit 2016 als GIS-Consultant und Projektleiter bei der WhereGroup in Bonn. Ich lebe und arbeite in Freiburg im Breisgau und beschäftige mich neben meiner Arbeit bei der WhereGroup mit der geophysikalischen Erkundung von archäologischen Bodendenkmälern.</p>
        </div>
        </section>


	<?php include "../inc/footer.inc"; ?>

</body>

</html>