<!doctype html>
<html lang="de">

<head>
	<?php include "../inc/meta.inc"; ?>

	<base href="<?php echo dirname($_SERVER['SCRIPT_NAME']); ?>">
	<title>Erfahrungen mit Online-Schulungen freier GIS-Software in Zeiten der Pandemie – FOSSGIS 2021</title>

	<link rel="stylesheet" href="./css/normalize.css">
	<link rel="stylesheet" href="./css/base.css">
	<link rel="stylesheet" href="./css/print.css" media="print">
</head>

<body id="programm">
	<?php include "../inc/header.inc"; ?>

        <!-- This file was generated by a script. Do not edit this file in Git,
             edit contents in Pretalx, regenerate the PHP files and commit them
             in the Git repository of the website. -->
        <p><a href="programm/dienstag.php#session_97WELW">&#9668;&#9668; zurück zum Programm</a> <a href="sessions/lightning_talks_3.php">&#9668; zurück zur Session</a></p>
        <h2 class='abstract-title'>Erfahrungen mit Online-Schulungen freier GIS-Software in Zeiten der Pandemie</h2>
        <section>
            <p>
                <span class='abstract-sessiontype'>Lightning Talk</span>                von <span class='abstract-speakers'>Jörg Thomsen</span></p>
                                                                            <p><span class='abstract-time-heading'>Zeit: </span>Dienstag 08. Juni 12:05 Uhr
                <br><span class='abstract-room-heading'>Ort: </span>Bühne 2
                <br><span class='abstract-room-heading'>Dauer: </span>5 Minuten
            </p>

                        
            <p>Seit der FOSSGIS 2020 mussten viele vor Ort-Veranstaltungen ausfallen, darunter auch zahlreiche Schulungen die ich für OSGEO-Software gebe (MapServer, Mapbender, QGIS, PostGIS, GeoServer, Goedaten-Infrastrukturen). Die Schulungen wurden in kurzer Zeit erfolgreich auf Online-Formate umgestellt. Was sollte beachtet werden, wenn Schulungen mit hohem Praxisanteil online durchgeführt werden? Welche Technik wird eingesetzt? Wie ist können die Übungen effektiv betreut werden?</p>
        </section>


	<?php include "../inc/footer.inc"; ?>

</body>

</html>