<!doctype html>
<html lang="de">

<head>
	<?php include "../inc/meta.inc"; ?>

	<base href="<?php echo dirname($_SERVER['SCRIPT_NAME']); ?>">
	<title>Geostyler Mapfile Parser – FOSSGIS 2021</title>

	<link rel="stylesheet" href="./css/normalize.css">
	<link rel="stylesheet" href="./css/base.css">
	<link rel="stylesheet" href="./css/print.css" media="print">
</head>

<body id="programm">
	<?php include "../inc/header.inc"; ?>

        <!-- This file was generated by a script. Do not edit this file in Git,
             edit contents in Pretalx, regenerate the PHP files and commit them
             in the Git repository of the website. -->
        <p><a href="programm/mittwoch.php#session_9AHNGW">&#9668;&#9668; zurück zum Programm</a> </p>
        <h2 class='abstract-title'>Geostyler Mapfile Parser</h2>
        <section>
            <p>
                <span class='abstract-sessiontype'>Vortrag</span>                von <span class='abstract-speakers'>Balthasar</span></p>
                                                                            <p><span class='abstract-time-heading'>Zeit: </span>Mittwoch 09. Juni 14:30 Uhr
                <br><span class='abstract-room-heading'>Ort: </span>Bühne 3
                <br><span class='abstract-room-heading'>Dauer: </span>20 Minuten
            </p>

                        
            <p>Es gibt eine grosse Vielfalt an Definitionen und Formaten graphischer Repräsentationen von räumlichen Informationen wie zum Beispiel QGIS Style File (QML), QGIS Layer Definition File (QLR) oder Styled Layer Descriptor (SLD) unter anderen. GeoStyler bietet ein intermediäres Format zur automatischen Übersetzung von Stilen zwischen unterschiedlichen Formaten.</p>
<p>In diesem Kontext wurde nun das GeoStyler Projekt um den Mapfile-Parser erweitert. Der GeoStyler Mapfile Parser wurde 2020 von Camptocamp als Case Study für das Bundesamt für Landestopographie (swisstopo) entwickelt. Aktuell ist es möglich, Mapfile Styles zu lesen und in andere verfügbare Geostyler Formate zu übersetzen.</p>
<p>Die Präsentation wird eine kleine Einführung in das GeoStyler Framework geben sowie den aktuellen Stand des Mapfile Parsing genauer erläutern. Abgerundet wird der Vortrag mit der Diskussion der gemachten Erfahrungen und einem Ausblick auf mögliche weitere Entwicklungen.</p>
        </section>


	<?php include "../inc/footer.inc"; ?>

</body>

</html>