<!doctype html>
<html lang="de">

<head>
	<?php include "../inc/meta.inc"; ?>

	<base href="<?php echo dirname($_SERVER['SCRIPT_NAME']); ?>">
	<title>Einführung in die Verwaltung von Geodaten in der PostgreSQL-Datenbank mit PostGIS – FOSSGIS 2021</title>

	<link rel="stylesheet" href="./css/normalize.css">
	<link rel="stylesheet" href="./css/base.css">
	<link rel="stylesheet" href="./css/print.css" media="print">
</head>

<body id="programm">
	<?php include "../inc/header.inc"; ?>

        <!-- This file was generated by a script. Do not edit this file in Git,
             edit contents in Pretalx, regenerate the PHP files and commit them
             in the Git repository of the website. -->
        <p><a href="programm/mittwoch.php#session_9R97S9">&#9668;&#9668; zurück zum Programm</a> </p>
        <h2 class='abstract-title'>Einführung in die Verwaltung von Geodaten in der PostgreSQL-Datenbank mit PostGIS</h2>
        <section>
            <p>
                <span class='abstract-sessiontype'>Workshop</span>
                                von <span class='abstract-speakers'>Astrid Emde</span></p>
                <p class='abstract-is-workshop'>Bitte melden Sie sich im <a href="https://pretix.eu/fossgis/2021/">Ticketshop</a> für diesen Workshop an, wenn Sie daran teilnehmen möchten.</p>                                                            <p><span class='abstract-time-heading'>Zeit: </span>Mittwoch 09. Juni 09:00 Uhr
                <br><span class='abstract-room-heading'>Ort: </span>Workshop 1
                <br><span class='abstract-room-heading'>Dauer: </span>90 Minuten
            </p>

                        
            <p>Dieser Workshop gibt Einsteiger:innen den ersten Einstieg in die Geodatenhaltung mit PostgreSQL/PostGIS. </p>
<p>Die ersten Schritte für den Umgang mit räumlichen Daten in der Datenbank werden erlernt.</p>
<p>Einfache SQLs werden erläutert und erstellt, das Datenmodell vermittelt und Visualisierung, Datenimport, Schnittstellen sowie Geodatenviewer werden behandelt.</p>
<p>Einführung PostgreSQL / PostGIS - Vorstellung der Möglichkeiten (Vektordaten, Rasterdaten)
Datenmodell
Visualisierung von Daten mit QGIS
Datenimport über QGIS DB Manager &amp; weitere Schnittstellen
Eintauchen in die Welt der PostGIS-Funktionen</p>
        <div class='abstract-bio'>
            <h3 class='abstract-bio-name'>Astrid Emde</h3>
                        <p>Astrid Emde war bisher bei allen FOSSGIS-Konferenzen dabei und freut sich auf die FOSSGIS 2021 in Rapperswil oder auch Online!</p>
<p>Sie befasst sich seit vielen Jahren mit Geodaten und FOSSGIS und hat schon zahlreiche Projekte vor allem im WebGIS-Bereich umgesetzt.</p>
<p>Sie weist Erfahrung mit PostgreSQL und PostGIS, MapServer, GeoServer, QGIS, QGIS Server und Mapbender auf. Weiterhin Apache Solr, OpenLayers, MapProxy, OGC Standards &amp; Skripting.</p>
<p>Astrid Emde arbeitet bei der WhereGroup in Bonn und hat schon viele Workshops und Präsentationen zu Mapbender, MapServer, GeoServer, PostgreSQL/PostGIS, OWS oder allgemein zum Aufbau einer GDI gehalten. Sie ist Dozentin der [FOSS Academy] (https://www.foss-academy.com), dem Schulungsinstitut der WhereGroup (https://www.wheregroup.com)</p>
<p>Seit über 10 Jahren engagiert sie sich im Mapbender-Projekt und gehört zum Mapbender Team (http://mapbender.org) und dem Mapbender PSC (Project Steering Committee).</p>
<p>Astrid Emde ist in der OSGeo Foundation (http://osgeo.org) aktiv. Sie ist 2010 zum Charter Member und 2017 in das OSGeo Board of Directors (Vorstand der OSGeo) und zur OSGeo Secretary gewählt worden. Dadurch übernimmt sie zahlreiche Aufgaben bei der OSGeo und ist darüber hinaus im Bereich Marketing, Presse, Community Meetings und OSGeoLive (http://live.osgeo.org/) aktiv. 2018 erhielt sie für ihr Engagement den Sol Katz Award der OSGeo.</p>
<p>Auch im FOSSGIS e.V. ist Astrid Emde aktiv. Sie gehört zum Team der jährlich stattfindenden FOSSGIS-Konferenz, engagiert sich in der Vereins-Öffentlichkeitsarbeit und der Organisation von Community Events (http://fossgis.de).</p>
        </div>
        </section>


	<?php include "../inc/footer.inc"; ?>

</body>

</html>