<!doctype html>
<html lang="de">

<head>
	<?php include "../inc/meta.inc"; ?>

	<base href="<?php echo dirname($_SERVER['SCRIPT_NAME']); ?>">
	<title>OpenLayers Anwender- &amp; Entwicklertreffen / BOF – FOSSGIS 2021</title>

	<link rel="stylesheet" href="./css/normalize.css">
	<link rel="stylesheet" href="./css/base.css">
	<link rel="stylesheet" href="./css/print.css" media="print">
</head>

<body id="programm">
	<?php include "../inc/header.inc"; ?>

        <!-- This file was generated by a script. Do not edit this file in Git,
             edit contents in Pretalx, regenerate the PHP files and commit them
             in the Git repository of the website. -->
        <p><a href="programm/montag.php#session_9RXAAA">&#9668;&#9668; zurück zum Programm</a> </p>
        <h2 class='abstract-title'>OpenLayers Anwender- &amp; Entwicklertreffen / BOF</h2>
        <section>
            <p>
                <span class='abstract-sessiontype'>Anwendertreffen / BoF</span>                von <span class='abstract-speakers'>Marc Jansen, Christian Mayer, Andreas Hocevar</span></p>
                                                                            <p><span class='abstract-time-heading'>Zeit: </span>Montag 07. Juni 16:00 Uhr
                <br><span class='abstract-room-heading'>Ort: </span>BoF 2
                <br><span class='abstract-room-heading'>Dauer: </span>60 Minuten
            </p>

                        
            <p>Wir wollen uns ohne große vorab feststehende Agenda treffen und unterhalten zum Thema OpenLayers. Zielgruppe sind Nutzer, Entwickler und solche die mehr Mitmachen wollen.</p>
<p>Wir werden sicherlich zunächst ein grobe Agenda gemeinsam entwickeln und dann schauen, wohin unser Treffen sich entwickelt. Alle Interessierten sind herzlich eingeladen.</p>
        <div class='abstract-bio'>
            <h3 class='abstract-bio-name'>Marc Jansen</h3>
                        <p>Ich bin seit vielen Jahren in der OpenSource GIS-Szene aktiv, als Entwickler (u.a. <a href="http://openlayers.org/">OpenLayers</a>, <a href="http://openlayers.org/">GeoExt</a>, <a href="https://github.com/terrestris/shogun">SHOGun</a> usw.), als konzeptuell Beitragender (u.a. <a href="https://github.com/terrestris/react-geo">react-geo</a>, <a href="https://geostyler.org/">GeoStyler</a> usw.), als Sprecher und Workshopleiter (international &amp; national), als OSGeo Charter Member und als Geschäftsführer der zwei Bonner Firmen <a href="https://www.terrestris.de/">terrestris</a> (OpenSource GIS-Lösungen, Beratungen und mehr) und <a href="https://www.mundialis.de/">mundialis</a> (Earth Observation &amp; Geo-Expertise mit freier Software).</p>
        </div>
        </section>


	<?php include "../inc/footer.inc"; ?>

</body>

</html>