<!doctype html>
<html lang="de">

<head>
	<?php include "../inc/meta.inc"; ?>

	<base href="<?php echo dirname($_SERVER['SCRIPT_NAME']); ?>">
	<title>Keynote: Nach Opendata bei swisstopo ist vor Geodata on stereoids. – FOSSGIS 2021</title>

	<link rel="stylesheet" href="./css/normalize.css">
	<link rel="stylesheet" href="./css/base.css">
	<link rel="stylesheet" href="./css/print.css" media="print">
</head>

<body id="programm">
	<?php include "../inc/header.inc"; ?>

        <!-- This file was generated by a script. Do not edit this file in Git,
             edit contents in Pretalx, regenerate the PHP files and commit them
             in the Git repository of the website. -->
        <p><a href="programm/montag.php#session_BBSDVU">&#9668;&#9668; zurück zum Programm</a> </p>
        <h2 class='abstract-title'>Keynote: Nach Opendata bei swisstopo ist vor Geodata on stereoids.</h2>
        <section>
            <p>
                                <span class='abstract-speakers'>David Oesch</span></p>
                            <p><span class='abstract-time-heading'>Zeit: </span>Montag 07. Juni 09:50 Uhr<br><span class='abstract-room-heading'>Ort: </span>Bühne 1</p>

                        
            <p>Basisdaten Landeskarten, Höhenmodell und Luft/Orthobilder schweizweit frei verfügbar - als Geodienste und Rohdatendownload. Dabei spielt und spielte OSS, OpenStandards und eine OpenMind Einstellung zu Technologien eine wichtige Rolle: Lessons learned .Ausblick: Digitalisierung Datenpublikation bei der Verwaltung konkret: Vom Word Formular zur Self Serving Spatial Data Infrastructure - Bundes Geodaten Infrastruktur on stereoids.</p>
        <div class='abstract-bio'>
            <h3 class='abstract-bio-name'>David Oesch</h3>
            <p>David Oesch studierte Geographie und Geschichte an der University of North Carolina at Greensboro und der Universität Bern. Sein Masterstudium in Geographie absolvierte er in Meteorologie / Klimatologie im Fachgebiet Fernerkundung. Während seiner Promotion initialisierte er die operative Verarbeitung von Satellitendaten für den Datenassimilationsprozess in numerischen Wettervorhersagemodellen. Mehrere Jahre war er als Service Manager bei Syngenta für agrarmeteorologische und klimatologische Produkte verantwortlich. Seit 2008 ist er als Senior Projektleiter für die Geodateninfrastruktur des Bundes bei swisstopo tätig und zuständig als ProductOwner für die Plattform geo.admin.ch.</p>
        </div>
        </section>


	<?php include "../inc/footer.inc"; ?>

</body>

</html>