<!doctype html>
<html lang="de">

<head>
	<?php include "../inc/meta.inc"; ?>

	<base href="<?php echo dirname($_SERVER['SCRIPT_NAME']); ?>">
	<title>Keynote: Geodata on Stereoids: Open-Government-Geodata und OSS – FOSSGIS 2021</title>

	<link rel="stylesheet" href="./css/normalize.css">
	<link rel="stylesheet" href="./css/base.css">
	<link rel="stylesheet" href="./css/print.css" media="print">
</head>

<body id="programm">
	<?php include "../inc/header.inc"; ?>

        <!-- This file was generated by a script. Do not edit this file in Git,
             edit contents in Pretalx, regenerate the PHP files and commit them
             in the Git repository of the website. -->
        <p><a href="programm/montag.php#session_BBSDVU">&#9668;&#9668; zurück zum Programm</a> </p>
        <h2 class='abstract-title'>Keynote: Geodata on Stereoids: Open-Government-Geodata und OSS</h2>
        <section>
            <p>
                <span class='abstract-sessiontype'>Vortrag</span>                von <span class='abstract-speakers'>David Oesch</span></p>
                                                                            <p><span class='abstract-time-heading'>Zeit: </span>Montag 07. Juni 09:25 Uhr
                <br><span class='abstract-room-heading'>Ort: </span>Bühne 1
                <br><span class='abstract-room-heading'>Dauer: </span>20 Minuten
            </p>

                        <p><a href="/2021/attachments/BBSDVU_FOSSGIS-2021-BBSDVU-Oesch_Keynote_h0fxJEY.pdf">Vortragsfolien (PDF) </a></p>
            <p>Basisdaten Landeskarten, Höhenmodell und Luft-/Orthobilder sind ab 1.3.2021 schweizweit frei verfügbar – als Geodienste und Rohdatendownload. Wenn zu Open Data – als Dienst oder als Rohdatensatz – die entsprechenden OSS-Werkzeuge bereitgestellt werden: dann wird das Potential erst freigesetzt.</p>
<p>Es wird auf die Rolle von OSS (Openlayers, Maplibre, VueJS), OpenStandards (Spatial Asset Temporal Catalog, OGC) und das Open Mindset bezüglich Technologien und Partnerschaften (OSM, SW Provider) in der Bereitstellung und Nutzung von amtlichen Geodaten eingegangen.</p>
        <div class='abstract-bio'>
            <h3 class='abstract-bio-name'>David Oesch</h3>
            <img class='abstract-speaker-avatar' src='/2021/avatars/MG3NLW.jpg'>            <p>David Oesch  studied geography and history at University of North Carolina at Greensboro and University of Bern. He completed his masters studies in geography in the meteorology and climatology on remote sensing methods. During his PhD studies initialized operational processing do ingest satellite data for data assimilation process in numerical weather forecast models. For several years he was responsible as service manager at Syngenta for agrarmeteorology and climatology products. Since 2008 he holds the position as a Senior Project Manager for Federal Geodata Data Infrastructure at swisstopo and set up and operates the geo.admin.ch platform.</p>
        </div>
        </section>


	<?php include "../inc/footer.inc"; ?>

</body>

</html>