<!doctype html>
<html lang="de">

<head>
	<?php include "../inc/meta.inc"; ?>

	<base href="<?php echo dirname($_SERVER['SCRIPT_NAME']); ?>">
	<title>In 60 Minuten zur eigenen Geo-App mit YAGA leaflet-ng2 – FOSSGIS 2021</title>

	<link rel="stylesheet" href="./css/normalize.css">
	<link rel="stylesheet" href="./css/base.css">
	<link rel="stylesheet" href="./css/print.css" media="print">
</head>

<body id="programm">
	<?php include "../inc/header.inc"; ?>

        <!-- This file was generated by a script. Do not edit this file in Git,
             edit contents in Pretalx, regenerate the PHP files and commit them
             in the Git repository of the website. -->
        <p><a href="programm/mittwoch.php#session_BPMCBG">&#9668;&#9668; zurück zum Programm</a> </p>
        <h2 class='abstract-title'>In 60 Minuten zur eigenen Geo-App mit YAGA leaflet-ng2</h2>
        <section>
            <p>
                <span class='abstract-sessiontype'>Demo-Session</span>                von <span class='abstract-speakers'>Arne Schubert, Stephan Herritsch</span></p>
                                                                            <p><span class='abstract-time-heading'>Zeit: </span>Mittwoch 09. Juni 11:30 Uhr
                <br><span class='abstract-room-heading'>Ort: </span>Bühne 4
                <br><span class='abstract-room-heading'>Dauer: </span>55 Minuten
            </p>

                        
            <p>Mit <a href="https://yagajs.org/">YAGA</a> <a href="https://github.com/yagajs/leaflet-ng2">leflet-ng2</a>, der granularen Integration von <a href="https://leafletjs.com/">Leaflet</a> in <a href="https://angular.io/">Angular.io</a>, und <a href="https://ionicframework.com/">Ionic</a> ist es spielend leicht eine Karten-App für alle gängigen mobilen Plattformen zu entwickeln. Es wird gezeigt wie Entwickler mit diesen Tools eine App im typische Look &amp; Feel der mobilen Plattformen in etwa 60 Minuten erstellen können. Ein <a href="https://basis.uni-bonn.de/qisserver/rds?state=verpublish&amp;status=init&amp;vmfile=no&amp;publishid=168685&amp;moduleCall=webInfo&amp;publishConfFile=webInfo&amp;publishSubDir=veranstaltung">Experiment mit Studierenden</a> hat gezeigt, dass selbst ohne Programmiererfahrungen es möglich ist innerhalb von 3 Tagen eine solche YAGA-App zu entwickeln. Den Teilnehmenden erwartet eine Live-Vorführung der Erstellung einer einfachen Geo-App, für die weitestgehend fast nur HTML-Kenntnisse von Nöten sind. Die Demo-Session-App soll im Anschluss der Vorführung zudem den Konfernzteilnehmenden über <a href="https://github.com/yagajs">GitHub</a> als Blaupause für eigene Projekte zur Verfügung gestellt werden. Diese Demo-Session soll in diesem Pandemie-Jahr als Ersatz für ein Workshop-Angebot dienen, da eine intensive Betreuung der Teilnehmeenden uns in einer reinen Online-Veranstaltung nicht in der gewohnten Qualität möglich ist.</p>
        <div class='abstract-bio'>
            <h3 class='abstract-bio-name'>Stephan Herritsch</h3>
            <p>Diplom Geograph <a href="https://stephan.herritsch.com/">Stephan Herritsch</a> ist Teil des <a href="https://yagajs.org/">YAGA-Development-Teams</a> <em>(Yet Another Geo Application)</em> und an der <a href="https://www.uni-bonn.de/">Rheinischen Friedrich-Wilhelms-Universität Bonn</a> tätig. Nach seiner Zeit am Bonner <a href="https://www.geographie.uni-bonn.de/">Geographischen Institut</a>, wo er zuletzt einen internationalen Masterstudiengang zusammen mit der <a href="https://ehs.unu.edu/">United Nations University</a> betreut hat, ist er jetzt im <a href="https://www.philfak.uni-bonn.de/de">Dekanat der Philosophischen Fakultät</a>.</p>
<p><a href="https://steve.yagajs.org/">Stephan Herritsch</a> ist Mitglied im <a href="https://www.fossgis.de/">FOSSGIS e.V.</a> und der <a href="https://www.geographie.uni-bonn.de/das-institut/netzwerke/bgg">Bonner Geographischen Gesellschaft</a>.</p>
        </div>
        </section>


	<?php include "../inc/footer.inc"; ?>

</body>

</html>