<!doctype html>
<html lang="de">

<head>
	<?php include "../inc/meta.inc"; ?>

	<base href="<?php echo dirname($_SERVER['SCRIPT_NAME']); ?>">
	<title>Einsatz von FOSS bei der Bewältigung der COVID-19 Krise in RLP – FOSSGIS 2021</title>

	<link rel="stylesheet" href="./css/normalize.css">
	<link rel="stylesheet" href="./css/base.css">
	<link rel="stylesheet" href="./css/print.css" media="print">
</head>

<body id="programm">
	<?php include "../inc/header.inc"; ?>

        <!-- This file was generated by a script. Do not edit this file in Git,
             edit contents in Pretalx, regenerate the PHP files and commit them
             in the Git repository of the website. -->
        <p><a href="programm/montag.php#session_BVZEKS">&#9668;&#9668; zurück zum Programm</a> </p>
        <h2 class='abstract-title'>Einsatz von FOSS bei der Bewältigung der COVID-19 Krise in RLP</h2>
        <section>
            <p>
                <span class='abstract-sessiontype'>Vortrag</span>                von <span class='abstract-speakers'>Armin Retterath</span></p>
                                                                            <p><span class='abstract-time-heading'>Zeit: </span>Montag 07. Juni 17:00 Uhr
                <br><span class='abstract-room-heading'>Ort: </span>Bühne 1
                <br><span class='abstract-room-heading'>Dauer: </span>20 Minuten
            </p>

                        
            <p>Zu Beginn der COVID-19 Krise im März 2020, gab es in Rheinland-Pfalz zunächst die Anforderung einer kartographischen Aufbereitung von Infektionszahlen auf Ebene der PLZ-Gebiete. Die Grundlage für das Verfahren bildete die tägliche Meldung auf Basis einer Exceltabelle, die per Mail verschickt wurde. Um dieses Verfahren zu verbessern, wurde vom Autor der Einsatz der Freien Open Source Krisenmanagement Software Sahana Eden vorgeschlagen. Die Software verfügt sowohl über Module für die Erfassung von Infektionsfällen, als auch über Möglichkeiten zur Kontaktnachverfolgung. Aufgrund der schon etablierten Meldewege bei den Kreisverwaltungen, wurde jedoch zunächst vom Einsatz für diese Anwendungsfälle abgesehen. </p>
<p>Die eigentliche Initiative für die Inbetriebnahme von Sahana war der dringende Bedarf der Zusammenführung der Personendaten aus verschiedenen Aquise-Kampagnen für Helfer. Diese sollten die Gesundheitsämter insbesondere bei der Kontaktnachverfolgung unterstützen. 
Ein weiterer Anwendungsfall ergab sich, als im Januar 2021 nach einer einfachen Lösung gesucht wurde, die Kosten für die Schnelltests von Erziehern und Lehrern zu übernehmen.  Bei beiden Anwendungsfällen werden auch Geodaten verwendet. Zum einen zur Erfassung der Wohnorte der Freiwilligen und der Adressen der Impfzentren sowie Gesundheitsämter, zum anderen zur kartographischen Darstellung der Lage der Teststellen (Praxen, Corona-Ambulanzen, ...) bei der Schnelltestvermittlung.
Im Vortrag werden die etablierten Prozesse am praktischen Beispiel vorgestellt und es wird erläutert, worauf man bei der Einrichtung solcher Verfahren achten muss.</p>
        <div class='abstract-bio'>
            <h3 class='abstract-bio-name'>Armin Retterath</h3>
                        <p>Armin Retterath ist Leiter des Bund/Länder Arbeitskreises Geodienste der GDI-DE sowie Architekt der Geodateninfrastruktur des Landes Rheinland-Pfalz. Er beschäftigt sich seit 2005 mit dem Aufbau und Betrieb von Geodateninfrastrukturen auf den unterschiedlichsten Ebenen der öffentlichen Verwaltung.</p>
        </div>
        </section>


	<?php include "../inc/footer.inc"; ?>

</body>

</html>