<!doctype html>
<html lang="de">

<head>
	<?php include "../inc/meta.inc"; ?>

	<base href="<?php echo dirname($_SERVER['SCRIPT_NAME']); ?>">
	<title>Ein Lastenfahrrad-Routing und -Index: CargoRocket – FOSSGIS 2021</title>

	<link rel="stylesheet" href="./css/normalize.css">
	<link rel="stylesheet" href="./css/base.css">
	<link rel="stylesheet" href="./css/print.css" media="print">
</head>

<body id="programm">
	<?php include "../inc/header.inc"; ?>

        <!-- This file was generated by a script. Do not edit this file in Git,
             edit contents in Pretalx, regenerate the PHP files and commit them
             in the Git repository of the website. -->
        <p><a href="programm/mittwoch.php#session_CQDB8M">&#9668;&#9668; zurück zum Programm</a> <a href="sessions/lightning_talks_4.php">&#9668; zurück zur Session</a></p>
        <h2 class='abstract-title'>Ein Lastenfahrrad-Routing und -Index: CargoRocket</h2>
        <section>
            <p>
                <span class='abstract-sessiontype'>Lightning Talk</span>                von <span class='abstract-speakers'>Henri Chilla</span></p>
                                                                            <p><span class='abstract-time-heading'>Zeit: </span>Mittwoch 09. Juni 12:10 Uhr
                <br><span class='abstract-room-heading'>Ort: </span>Bühne 1
                <br><span class='abstract-room-heading'>Dauer: </span>5 Minuten
            </p>

                        
            <p>OpenStreetMap enthält mittlerweile viele Attribute über den Zustand bzw. die Beschaffenheit von Straßen und Wegen, sowie zu Pollern und Bordsteinen. Diese Informationen haben wir verwendet um die Straßen in Baden-Württemberg auf ihre Lastenradfreundlichkeit zu bewerten. Da viele Teile der Infrastruktur noch nicht den Anforderungen von Lastenfahrrädern entsprechen, möchten wir in der bestehenden Infrastruktur Problemstellen identifizieren und durch Routing eine einfache Umfahrung ermöglichen. Hierfür haben unseren beide freien Produkte entwickelt: mit R berechnen wir den CargoBikeIndex und auf Basis von der Routing Software Graphhopper das CargoRocket Routing. Alle Erkenntnisse und Entwicklungen sind offen und frei verfügbar. Zusätzlich haben wir uns damit beschäftigt, wie fehlende Daten gesammelt werden können und den Einbezug von bestehenden Apps wie StreetComplete erprobt.</p>
        </section>


	<?php include "../inc/footer.inc"; ?>

</body>

</html>