<!doctype html>
<html lang="de">

<head>
	<?php include "../inc/meta.inc"; ?>

	<base href="<?php echo dirname($_SERVER['SCRIPT_NAME']); ?>">
	<title>Open Data, Open Source – Open End? – FOSSGIS 2021</title>

	<link rel="stylesheet" href="./css/normalize.css">
	<link rel="stylesheet" href="./css/base.css">
	<link rel="stylesheet" href="./css/print.css" media="print">
</head>

<body id="programm">
	<?php include "../inc/header.inc"; ?>

        <!-- This file was generated by a script. Do not edit this file in Git,
             edit contents in Pretalx, regenerate the PHP files and commit them
             in the Git repository of the website. -->
        <p><a href="programm/mittwoch.php#session_DCXBZY">&#9668;&#9668; zurück zum Programm</a> </p>
        <h2 class='abstract-title'>Open Data, Open Source – Open End?</h2>
        <section>
            <p>
                <span class='abstract-sessiontype'>Vortrag</span>                von <span class='abstract-speakers'>Prof. Paul Becker</span></p>
                                                                            <p><span class='abstract-time-heading'>Zeit: </span>Mittwoch 09. Juni 15:00 Uhr
                <br><span class='abstract-room-heading'>Ort: </span>Bühne 1
                <br><span class='abstract-room-heading'>Dauer: </span>20 Minuten
            </p>

                        
            <p>OSM-Daten und amtliche Geodaten verkörpern unterschiedliche Philosophien bezüglich der Datenerfassung. Sie ergänzen sich aber sehr gut, weshalb ein eindeutiger Trend zu erkennen ist: OSM-Daten werden bei immer mehr Bundesbehörden eingesetzt. Das BKG, der zentrale Geodatenbroker des Bundes, berät die Bundesbehörden und bemüht sich, den Stellenwert der OSM-Daten in der öffentlichen Verwaltung noch weiter zu erhöhen. Um dies zu erreichen, nimmt sich das BKG vor, neue Qualitätsprüfverfahren zu entwickeln und einzuführen, die über die für amtlichen Daten angewendeten Verfahren hinaus gehen. Im Vortrag wird dargestellt, was geplant ist und welche Perspektiven sich hiermit eröffnen.
Es wird auch über die Potentiale und Risiken der Entwicklung und Benutzung der Open Source Software bei einer Behörde berichtet.</p>
        <div class='abstract-bio'>
            <h3 class='abstract-bio-name'>Prof. Paul Becker</h3>
            <p><b>Präsident und Professor des Bundesamtes für Kartographie und Geodäsie (BKG) </b></p>
<p>Prof. Dr. Paul Becker ist seit April 2019 Präsident des Bundesamts für Kartographie und Geodäsie (BKG). Er war zuvor Vizepräsident beim Deutschen Wetterdienst (DWD) und Vertreter Deutschlands bei der Group on Earth Observation (GEO). Daneben hat er eine Honorarprofessur an der Goethe-Universität in Frankfurt am Main und einen Lehrauftrag an der Universität Hamburg inne.</p>
<p>Kontakt:
Richard-Strauss-Allee 11, 60598 Frankfurt a.M. 
Telefon: 069 6333-226 Fax: 069 6333-2100 
E-Mail: vorzimmerpraesident@bkg.bund.de</p>
        </div>
        </section>


	<?php include "../inc/footer.inc"; ?>

</body>

</html>