<!doctype html>
<html lang="de">

<head>
	<?php include "../inc/meta.inc"; ?>

	<base href="<?php echo dirname($_SERVER['SCRIPT_NAME']); ?>">
	<title>STAC - ein Ökosystem für raumzeitliche Daten – FOSSGIS 2021</title>

	<link rel="stylesheet" href="./css/normalize.css">
	<link rel="stylesheet" href="./css/base.css">
	<link rel="stylesheet" href="./css/print.css" media="print">
</head>

<body id="programm">
	<?php include "../inc/header.inc"; ?>

        <!-- This file was generated by a script. Do not edit this file in Git,
             edit contents in Pretalx, regenerate the PHP files and commit them
             in the Git repository of the website. -->
        <p><a href="programm/dienstag.php#session_DSUDXJ">&#9668;&#9668; zurück zum Programm</a> <a href="sessions/lightning_talks_3.php">&#9668; zurück zur Session</a></p>
        <h2 class='abstract-title'>STAC - ein Ökosystem für raumzeitliche Daten</h2>
        <section>
            <p>
                <span class='abstract-sessiontype'>Lightning Talk</span>                von <span class='abstract-speakers'>Matthias Mohr</span></p>
                                                                            <p><span class='abstract-time-heading'>Zeit: </span>Dienstag 08. Juni 12:00 Uhr
                <br><span class='abstract-room-heading'>Ort: </span>Bühne 2
                <br><span class='abstract-room-heading'>Dauer: </span>5 Minuten
            </p>

                        
            <p>SpatioTemporal Asset Catalog (STAC) ist ein offener und einfach erweiterbarer Standard um raumzeitliche Raster- und Vektordaten zu auszutauschen. Das primäre Ziel ist es raumzeitliche Daten einheitlich und einfach auffindbar zu machen. Dies soll insbesondere auch für fachfremde Nutzer über die für diesen Kreis bekannten Suchmaschinen wie Google und Bing möglich sein und proprietäre Portale und APIs ersetzen können. Dafür wurde eine interoperable Spezifikation und API geschaffen, die auch direkt für die Nutzung in der Cloud ausgelegt ist. Eine stetig wachsende Anzahl von offener Software erleichtert die Erstellung, Verwaltung, Veröffentlichung und Nutzung der Daten.</p>
        </section>


	<?php include "../inc/footer.inc"; ?>

</body>

</html>