<!doctype html>
<html lang="de">

<head>
	<?php include "../inc/meta.inc"; ?>

	<base href="<?php echo dirname($_SERVER['SCRIPT_NAME']); ?>">
	<title>Geoprozessierung und Change Detection: Wie kann die GIS Welt von fernerkundlichen Daten profitieren? – FOSSGIS 2021</title>

	<link rel="stylesheet" href="./css/normalize.css">
	<link rel="stylesheet" href="./css/base.css">
	<link rel="stylesheet" href="./css/print.css" media="print">
</head>

<body id="programm">
	<?php include "../inc/header.inc"; ?>

        <!-- This file was generated by a script. Do not edit this file in Git,
             edit contents in Pretalx, regenerate the PHP files and commit them
             in the Git repository of the website. -->
        <p><a href="programm/montag.php#session_EWDGBM">&#9668;&#9668; zurück zum Programm</a> </p>
        <h2 class='abstract-title'>Geoprozessierung und Change Detection: Wie kann die GIS Welt von fernerkundlichen Daten profitieren?</h2>
        <section>
            <p>
                <span class='abstract-sessiontype'>Vortrag</span>                von <span class='abstract-speakers'>Till Adams, Guido Riembauer</span></p>
                                                                            <p><span class='abstract-time-heading'>Zeit: </span>Montag 07. Juni 11:00 Uhr
                <br><span class='abstract-room-heading'>Ort: </span>Bühne 2
                <br><span class='abstract-room-heading'>Dauer: </span>20 Minuten
            </p>

                        
            <p>Der Satz „your Software is useless – without data“ (eure Software ist nutzlos – ohne Daten), den ein gewisser Schuyler Erle in einem Lightning Talk vor vielen Jahren auf einer FOSS4G-Konferenz in Richtung der Entwickler von GIS-Software abfeuerte, wurde mit Sicherheit schon oft zitiert, was ihn aber nicht weniger wahr macht. Insgesamt ist die Datenlage mit Aufkommen von OpenStreetMap, aber auch mit zunehmender Freistellung von öffentlichen Geodaten seit diesem Ausspruch wesentlich besser geworden. Eine weitere Geodatenquelle, die insbesondere in den letzten Jahren eine große Dynamik entwickelt hat, kommt aus der Fernerkundung.</p>
<p>Mit weiterer Verfügbarkeit von Fernerkundungsdaten, haben sich auch die Disziplin der Fernerkundung und die GIS-Welt immer weiter angenähert. Dies war auch auf der FOSSGIS Konferenz spürbar, so wurde die Fernerkundung auf den vergangenen FOSSGIS-Konferenzen, speziell in Zusammenhang vom europäischen Copernicus-Programm und den damit oft im Zusammenhang gemeinten Sentinel Daten immer wieder thematisiert. Besucher der FOSSGIS haben gelernt, wie das Copernicus Programm aufgebaut ist und welche Arten von Daten es gibt, ebenso wurden Systeme vorgestellt mit denen sich diese Daten verarbeiten lassen. Um aber einen wirklichen Überblick darüber zu bekommen, welche Möglichkeiten und Grenzen Open Source GI-Software in Kombination mit Daten und Methoden der Fernerkundung bieten und welche Lösungen sich daraus entwickeln lassen, dazu fehlte es meist an konkreten Beispielen. Der Talk will diese Lücke schließen und stellt einige Beispiele aus der Praxis vor.</p>
<p>Beispiel 1: Detektion von Oberflächenbeschaffenheiten aus Orthophotos.</p>
<p>Im konkreten Fallbeispiel geht es darum, potentiell mögliche (Erd-)Kabeltrassen über eine Kostenoberfläche automatisch zu berechnen. Die Basis dafür, ist ein möglichst hoch aufgelöster Geodatensatz, der Aufschluss über die Oberflächenbeschaffenheit, also Asphalt, Grünland, Wald (u.v.m.) gibt. Für die Oberflächendetektion spielt der sogenannte NDVI (normierter differenzierter Vegetationsindex) eine entscheidende Rolle, wenn es darum geht, Vegetation zu erkennen. Dieser lässt sich einfach mit GRASS GIS bestimmen und so entsprechende Flächen abgrenzen. Was aber tun, wenn die Luftbilder im Winter aufgenommen wurden? Hier kann die Kombination mit Sentinel-2 Daten aus dem Copernicus Programm helfen, auch wenn deren Auflösung wesentlich geringer ist, als die der Luftbilder. Natürlich können mit dem durch dieses Verfahren bereitgestellten Geodatensatz der Oberflächen auch andere Fragestellungen bearbeitet werden.</p>
<p>Beispiel 2: Landbedeckungsklassifizierung basierend auf Sentinel-2-Daten</p>
<p>Im Rahmen des Projekts „Inwertsetzung von Copernicus-Daten für die Raumbeobachtung“ (incora) wurde auf Basis von GRASS GIS und actinia ein Verfahren zur Erstellung von jährlichen Landbedeckungsklassifikationen für ganz Deutschland entwickelt. Die Ergebnisdaten haben eine räumliche Auflösung von 10m und repräsentieren die Klassen bebautes Gebiet, Grünland, Wald, Landwirtschaft, vegetationsloser Boden und Wasser. Das Verfahren basiert auf Zeitreihen von Sentinel-2-Daten aus dem Copernicus-Programm. Die für die Klassifikation benötigten Trainingsdaten werden regelbasiert aus Referenzdaten (z.B. aus OpenStreetMap) und den Sentinel-2-Szenen selbst erstellt. So kann die Verarbeitung flexibel auf verschiedene Jahre übertragen und vollautomatisch durchgeführt werden. Berechnet man je eine Klassifikation für verschiedene Jahre, so lassen sich damit natürlich Veränderungen in der Landbedeckung feststellen. Hier zeigen sich insbesondere Veränderungen der Klasse „bebautes Gebiet“, sodass sich Indikatoren zur Raumnutzung auf lokaler, regionaler und nationaler Ebene ableiten lassen. Die Klassifikationskarten sowie Ergebnisse der Veränderungsanalyse für die Jahre 2019 und 2016 stehen unter der Data licence Germany zum Download zur Verfügung.</p>
<p>Beispiel 3: Hochwassergefahrenkartierung mit Sentinel-1-Daten</p>
<p>Im Rahmen eines weiteren Projektes werden Prozessierketten in GRASS GIS erstellt, um unter Verwendung von Sentinel-1 Radardaten Hochwassergefahrenkarten am Beispiel Ecuadors zu erstellen. Zunächst werden für jede verfügbare Sentinel-1 Szene aus einem Zeitraum (bspw. ein Jahr) mit Hilfe eines automatischen Schwellenwertverfahrens Wasserflächen extrahiert und in GRASS GIS zu einem Data-Cube zusammengefasst. Daraus lassen sich Statistiken wie Hochwasserhäufigkeit und (gemeinsam mit Referenzdaten wie z.B. einem digitalen Geländemodell) mittlere Überflutungstiefe bestimmen. Die Unterscheidung zwischen permanenten Wasserflächen und Hochwassergebieten kann entweder automatisch über die Häufigkeit oder mit Hilfe eines Referenzdatensatzes erfolgen. Die Ergebniskarten dienen als wichtige Grundlage zum Informationsaustausch innerhalb des Sendai-Rahmenwerks zur Katastrophenvorsorge.</p>
        <div class='abstract-bio'>
            <h3 class='abstract-bio-name'>Till Adams</h3>
            <img class='abstract-speaker-avatar' src='/2021/avatars/89LJNE.jpg'>            <p>Till ist einer der Mitbegründer der deutschsprachigen FOSSGIS-Konferenzreihe und nahm 2005 an seiner ersten OSGeo-Konferenz in Minneapolis teil, noch bevor sie FOSS4G hieß. Till hat sich auch sehr für den Aufbau der lokalen und regionalen Community eingesetzt.</p>
<p>Hauptberuflich ist er Gründer der Firma terrestris, ein Open Source GIS Unternehmen mit Schwerpunkt auf webbasierter FOSS4G Softwareentwicklung, sowie von mundialis, einem auf Big Data und Fernerkundungsdatenverarbeitung fokussierten Unternehmen. Till arbeitet seit mehr als einem Jahrzehnt aktiv mit FOSS4G Software. Außerdem führt er in beiden Unternehmen agile Methoden ein.</p>
<p>Till war der Chair der FOSS4G 2016 in Bonn und ist nun Mitglied des Board of Directors der OSGeo. Till ist ebenfalls aktives Mitglied des FOSSGIS e.V. und im Vorstand von OSGeo-Europe vertreten.</p>
        </div>
        </section>


	<?php include "../inc/footer.inc"; ?>

</body>

</html>