<!doctype html>
<html lang="de">

<head>
	<?php include "../inc/meta.inc"; ?>

	<base href="<?php echo dirname($_SERVER['SCRIPT_NAME']); ?>">
	<title>Einstieg in die Entwicklung mit maplibre-gl-js – FOSSGIS 2021</title>

	<link rel="stylesheet" href="./css/normalize.css">
	<link rel="stylesheet" href="./css/base.css">
	<link rel="stylesheet" href="./css/print.css" media="print">
</head>

<body id="programm">
	<?php include "../inc/header.inc"; ?>

        <!-- This file was generated by a script. Do not edit this file in Git,
             edit contents in Pretalx, regenerate the PHP files and commit them
             in the Git repository of the website. -->
        <p><a href="programm/dienstag.php#session_FNFSMF">&#9668;&#9668; zurück zum Programm</a> </p>
        <h2 class='abstract-title'>Einstieg in die Entwicklung mit maplibre-gl-js</h2>
        <section>
            <p>
                <span class='abstract-sessiontype'>Workshop</span>
                                von <span class='abstract-speakers'>Tobias Weber, David Patzke</span></p>
                <p class='abstract-is-workshop'>Bitte melden Sie sich im <a href="https://pretix.eu/fossgis/2021/">Ticketshop</a> für diesen Workshop an, wenn Sie daran teilnehmen möchten.</p>                <p class='abstract-is-workshop'>Dieser Workshop wird browserbasiert durchgeführt. Zur Teilnahme benötigen Sie lediglich einen aktuellen Internet-Browser.</p>                                            <p><span class='abstract-time-heading'>Zeit: </span>Dienstag 08. Juni 11:00 Uhr
                <br><span class='abstract-room-heading'>Ort: </span>Workshop 1
                <br><span class='abstract-room-heading'>Dauer: </span>90 Minuten
            </p>

                        
            <p>Maplibre-gl-js ist ein Fork von mapbox-gl-js, welches seit letztem Jahr in neueren Versionen nicht mehr OpenSource ist. Anders als z.B. OpenLayers richtet es das Thema GIS konsequent weg von der gedruckten Karte hin Richtung Bildschirmgeräte aus. Dabei stehen neben Performance, Bedienbarkeit und visueller Attraktivität vor allem ein niedrigschwelliger Einstieg in die Entwicklung im Vordergrund. Wir helfen dabei den Einstieg in die Entwicklung mit MapLibre zu finden und entwickeln mit den Teilnehmern zusammen ein paar Beispielanwendungen, die die Leistungsfähigkeit der Library zeigen. Für Mapbox-Anwender gibt es auf Wunsch einen kurzen Exkurs, wie man von mapbox-gl-js auf maplibre-gl-js umsteigt.</p>
        <div class='abstract-bio'>
            <h3 class='abstract-bio-name'>Tobias Weber</h3>
            <p>Tobias Weber ist seit Januar 2021 Software Entwickler bei der WhereGroup GmbH (https://wheregroup.com) in Bonn. Als Full-Stack Developer hat er den letzten 15 Jahren diversen Projekten mit verschiedenen Technologien wie Javascript (client &amp; server), React, Vue.js, Docker, PHP, ExtJS, MySQL, Three.js gearbeitet. Während sich die Arbeit bei dem ehemaligen Arbeitgeber dahabtours GmbH auf die Entwicklung von CRM und Shop-Systemen konzentrierte, war er in seiner Freiberuflichen Arbeit bei dem Projekt Mujumaps auch mit der Einrichtung von OSM-Tile Servern beschäftigt. Bei seinem privaten Projekt Nametag Designer (www.nametag-designer.com) lag der Fokus seit 2 Jahren verstärkt auf der Entwicklung moderner Benutzeroberflächen mit dem frontend Framework React.</p>
        </div>
        </section>


	<?php include "../inc/footer.inc"; ?>

</body>

</html>