<!doctype html>
<html lang="de">

<head>
	<?php include "../inc/meta.inc"; ?>

	<base href="<?php echo dirname($_SERVER['SCRIPT_NAME']); ?>">
	<title>EASYDAB (Earth System Data Branding) - eine neue Kennzeichnung von qualitativ hochwertigen Geodaten – FOSSGIS 2021</title>

	<link rel="stylesheet" href="./css/normalize.css">
	<link rel="stylesheet" href="./css/base.css">
	<link rel="stylesheet" href="./css/print.css" media="print">
</head>

<body id="programm">
	<?php include "../inc/header.inc"; ?>

        <!-- This file was generated by a script. Do not edit this file in Git,
             edit contents in Pretalx, regenerate the PHP files and commit them
             in the Git repository of the website. -->
        <p><a href="programm/dienstag.php#session_GUN7HC">&#9668;&#9668; zurück zum Programm</a> </p>
        <h2 class='abstract-title'>EASYDAB (Earth System Data Branding) - eine neue Kennzeichnung von qualitativ hochwertigen Geodaten</h2>
        <section>
            <p>
                <span class='abstract-sessiontype'>Vortrag</span>                von <span class='abstract-speakers'>Anette Ganske</span></p>
                                                                            <p><span class='abstract-time-heading'>Zeit: </span>Dienstag 08. Juni 12:00 Uhr
                <br><span class='abstract-room-heading'>Ort: </span>Bühne 3
                <br><span class='abstract-room-heading'>Dauer: </span>20 Minuten
            </p>

                        
            <p>In den Geowissenschaften gibt es eine Vielzahl von wissenschaftlichen Aktivitäten, die sich mit den zahlreichen wichtigen Aspekten eines guten Forschungsdaten Managements befassen. Was bisher jedoch nur wenig untersucht und behandelt wurde, sind die einfache Auffindbarkeit und Wiederverwendung von qualitätsgeprüften Forschungsdaten. Dieser Aspekt wird durch das Earth System Data Branding (EASYDAB, https://www.easydab.de) aufgegriffen.</p>
<p>EASYDAB ist ein derzeit entwickeltes Branding für offene, FAIRe (Wilkinson et al, 2016) und qualitätsgeprüfte Daten aus den Erdsystemwissenschaften, die mit DataCite DOIs in einem Repositorium veröffentlicht werden. Mit EASYDAB gekennzeichnete Daten sind disziplinspezifisch standardisiert und haben umfangreiche Metadateninformationen. Dies wird vom veröffentlichenden Repositorium mithilfe von Prüfungen sichergestellt und die zugehörigen Landing Pages werden mit dem EASYDAB-Logo gekennzeichnet. Dadurch können Nachnutzer der Daten einfacher qualitative hochwertige Daten finden und Repositorien zeigen, dass sie geprüfte Daten mit hoher Qualität veröffentlichen.</p>
<p>Der erste Standard, der die EASYDAB- Bedingungen erfüllt, ist der ATMODAT-Standard für Atmosphärenmodelldaten (Ganske et al., 2020). Er enthält konkrete Empfehlungen und Anforderungen in Bezug auf die Prüfung, Veröffentlichung und verbesserte FAIRness von qualitätsgesicherten Daten. Die Spezifikationen umfassen u. a. reichhaltige Metadaten mit kontrollierten Vokabularen, strukturierte Landing Pages, Dateiformate (netCDF) und die Struktur innerhalb der Dateien. Menschen- und maschinenlesbare Landing Pages sind ein weiteres Kernelement, genauso wie Checklisten für Datenproduzenten und Datenkuratoren.</p>
<p>Für den weiteren Ausbau von qualitätsgesicherten Datenpublikationen soll EASYDAB mit weiteren Standards verwendet werden, wobei die Geowissenschaften hier ein großes Potential darstellen. Das Ziel ist, mit EASYDAB die Wiederverwendung von FAIRen, offenen, geprüften und hochwertigen Daten zu verbessern.</p>
<p>Literatur: </p>
<p>Wilkinson et al., 2016: The FAIR Guiding Principles for scientific data management and stewardship. Sci Data 3, 160018. https://doi.org/10.1038/sdata.2016.18 </p>
<p>Ganske etal., 2020: ATMODAT Standard (v3.0). https://doi.org/10.35095/WDCC/atmodat_standard_en_v3_0</p>
        <div class='abstract-bio'>
            <h3 class='abstract-bio-name'>Anette Ganske</h3>
            <img class='abstract-speaker-avatar' src='/2021/avatars/JYVBTS.jpg'>            <p>Anette Ganske ist Meteorologin und arbeitet für die Technische Informationsbibliothek (TIB) im Projekt AtMoDat. Dabei erforscht sie, wie man Geodaten so veröffentlicht, dass sie auffindbar, zugänglich, interoperabel und wiederverwendbar (=FAIR) sind.</p>
        </div>
        </section>


	<?php include "../inc/footer.inc"; ?>

</body>

</html>