<!doctype html>
<html lang="de">

<head>
	<?php include "../inc/meta.inc"; ?>

	<base href="<?php echo dirname($_SERVER['SCRIPT_NAME']); ?>">
	<title>GeoMapFish und QGIS Server – FOSSGIS 2021</title>

	<link rel="stylesheet" href="./css/normalize.css">
	<link rel="stylesheet" href="./css/base.css">
	<link rel="stylesheet" href="./css/print.css" media="print">
</head>

<body id="programm">
	<?php include "../inc/header.inc"; ?>

        <!-- This file was generated by a script. Do not edit this file in Git,
             edit contents in Pretalx, regenerate the PHP files and commit them
             in the Git repository of the website. -->
        <p><a href="programm/dienstag.php#session_GXKM7M">&#9668;&#9668; zurück zum Programm</a> </p>
        <h2 class='abstract-title'>GeoMapFish und QGIS Server</h2>
        <section>
            <p>
                <span class='abstract-sessiontype'>Vortrag</span>                von <span class='abstract-speakers'>Andrea Borghi, Cécile Vuilleumier</span></p>
                                                                            <p><span class='abstract-time-heading'>Zeit: </span>Dienstag 08. Juni 10:00 Uhr
                <br><span class='abstract-room-heading'>Ort: </span>Bühne 3
                <br><span class='abstract-room-heading'>Dauer: </span>20 Minuten
            </p>

                        
            <p>GeoMapFish ist eine Open Source Plattform für die Entwicklung von webbasierten geografischen Informationssystemen (WebGIS). Sie ist reich an Funktionalitäten, hochgradig anpassbar und basiert auf den neuesten Technologien und Standards in diesem Bereich. Sie bietet mehrere Schnittstellen: Desktop, Mobile, Administration und einige weitere für spezielle Zwecke (z.B. Anbindungen an spezifische Fachapplikationen) sowie eine API für die Integration von Karten in Anwendungen Dritter. Basierend auf den OGC-Standards (WMS, WFS) ermöglicht eine GeoMapFish-Anwendung die Übertragung von Geodaten in Form von Diensten für Desktop-Clients oder andere Web-Clients. Aktuell ist die Version 2.6 von GeoMapFish in Vorbereitung.
Als Backend-Kartenserver unterstützt GeoMapFish MapServer, QGIS Server und Geoserver. QGIS Server wurde zuerst mit Version 1.6 integriert. Ab GeoMapFish 2.2 wurden spezifischen QGIS Features benutzt und in letzter Zeit verwenden mehr und mehr GeoMapFish Projekte QGIS Server.
Mit QGIS Server wird die Konfiguration der Layers in QGIS Desktop definiert und in einem QGIS Projekt abgelegt. Die Symbologie wird dann direkt in GeoMapFish übernommen. Die Integration von Daten und die allfällige Änderungen der Konfiguration laufen dadurch reibungslos und profitieren von den vielen Vorteilen und Optionen von QGIS Desktop.
Das Access Control QGIS Plugin erlaubt eine feingranulare Rechtekontrolle über die Daten: gewisse Layer und Attribute können nur für gewisse Benutzer sichtbar sein. Die Konfiguration wird im QGIS Desktop eingestellt. Das Plugin erlaubt die Anbindung von externen Authentifizierungs- und Userverwaltungs-Systemen. Die Rechteverwaltung integriert sich kohärent auch mit anderen Karten-Quellen im Projekt.</p>
        <div class='abstract-bio'>
            <h3 class='abstract-bio-name'>Cécile Vuilleumier</h3>
            <img class='abstract-speaker-avatar' src='/2021/avatars/HNN8FP_Vuilleumier_Cecile-1_cropped_8QRA5k1.jpg'>            <p>Geospatial Developer bei Camptocamp</p>
        </div>
        </section>


	<?php include "../inc/footer.inc"; ?>

</body>

</html>