<!doctype html>
<html lang="de">

<head>
	<?php include "../inc/meta.inc"; ?>

	<base href="<?php echo dirname($_SERVER['SCRIPT_NAME']); ?>">
	<title>Geodateninfrastruktur mit Docker – FOSSGIS 2021</title>

	<link rel="stylesheet" href="./css/normalize.css">
	<link rel="stylesheet" href="./css/base.css">
	<link rel="stylesheet" href="./css/print.css" media="print">
</head>

<body id="programm">
	<?php include "../inc/header.inc"; ?>

        <!-- This file was generated by a script. Do not edit this file in Git,
             edit contents in Pretalx, regenerate the PHP files and commit them
             in the Git repository of the website. -->
        <p><a href="programm/mittwoch.php#session_HCWV3V">&#9668;&#9668; zurück zum Programm</a> </p>
        <h2 class='abstract-title'>Geodateninfrastruktur mit Docker</h2>
        <section>
            <p>
                <span class='abstract-sessiontype'>Workshop</span>
                                von <span class='abstract-speakers'>Otto Dassau, Tristan</span></p>
                <p class='abstract-is-workshop'>Bitte melden Sie sich im <a href="https://pretix.eu/fossgis/2021/">Ticketshop</a> für diesen Workshop an, wenn Sie daran teilnehmen möchten.</p>                                                <p class='abstract-is-workshop'>Sie erhalten in der Woche vor der Konferenz eine E-Mail mit detaillierten Informationen zum Workshop sowie die Möglichkeit in einem Termin Ihre Technik auszuprobieren.</p>            <p><span class='abstract-time-heading'>Zeit: </span>Mittwoch 09. Juni 11:00 Uhr
                <br><span class='abstract-room-heading'>Ort: </span>Workshop 1
                <br><span class='abstract-room-heading'>Dauer: </span>90 Minuten
            </p>

                        
            <p>Beim Geoinformatikbüro Dassau setzen wir schon länger auf die Vorteile
von Docker bei der Verwaltung unserer (Geodaten)Infrastruktur.
In der Produktion überzeugt die Skalierbarkeit und simple Wartung der Infrastruktur.
Die Möglichkeit, zur Testzwecken,  schnell verschiedene Konfigurationen der Infrastruktur aufzusetzen spart uns in der Entwicklung einiges an Zeit und Nerven.
Durch diesen Workshop sollen die Teilnehmer:innen befähigt werden selber mit (Geodaten)Infrastruktur in Docker zu experimentieren.
Dazu wollen wir zusammen eine Infrastruktur aufbauen bestehend aus einer PostGIS Datenbank und der GBD Websuite als WebGIS. Wir wollen auch zeigen, wie wir einzelne Komponenten unserer Infrastruktur austauschen können und so zum Beispiel unsere Daten im QGIS Webclient oder als WMS anbieten.</p>
<p>Für den Workshop sind Grundkenntnisse im Umgang mit der Kommandozeile auf Linux hilfreich.</p>
        <div class='abstract-bio'>
            <h3 class='abstract-bio-name'>Otto Dassau</h3>
            <img class='abstract-speaker-avatar' src='/2021/avatars/PPGCHK_26839619320a581e5177cf009d62e233'>            <p>Otto Dassau ist Gründer und Geschäftsführer der Geoinformatikbüro Dassau GmbH aus Düsseldorf. Er ist Diplom-Geograph und hat in Hannover Physische Geographie mit Schwerpunkt Geographische Informationssysteme studiert. Er ist seit über 20 Jahren aktiv in den Open Source GIS Projekten QGIS und GRASS GIS sowie dem FOSSGIS e.V. und der QGIS Anwendergruppe Deutschland. Zwischen 2008 und 2017 war er Mitglied im QGIS Project Steering Committee (PSC).</p>
        </div>
        </section>


	<?php include "../inc/footer.inc"; ?>

</body>

</html>