<!doctype html>
<html lang="de">

<head>
	<?php include "../inc/meta.inc"; ?>

	<base href="<?php echo dirname($_SERVER['SCRIPT_NAME']); ?>">
	<title>Wissenstransfer-Projekt SAPIENS: Satellitendaten für Planung, Industrie, Energiewirtschaft und Naturschutz – FOSSGIS 2021</title>

	<link rel="stylesheet" href="./css/normalize.css">
	<link rel="stylesheet" href="./css/base.css">
	<link rel="stylesheet" href="./css/print.css" media="print">
</head>

<body id="programm">
	<?php include "../inc/header.inc"; ?>

        <!-- This file was generated by a script. Do not edit this file in Git,
             edit contents in Pretalx, regenerate the PHP files and commit them
             in the Git repository of the website. -->
        <p><a href="programm/montag.php#session_HETRT7">&#9668;&#9668; zurück zum Programm</a> </p>
        <h2 class='abstract-title'>Wissenstransfer-Projekt SAPIENS: Satellitendaten für Planung, Industrie, Energiewirtschaft und Naturschutz</h2>
        <section>
            <p>
                <span class='abstract-sessiontype'>Vortrag</span>                von <span class='abstract-speakers'>Nora Meyer zu Erpen</span></p>
                                                                            <p><span class='abstract-time-heading'>Zeit: </span>Montag 07. Juni 14:30 Uhr
                <br><span class='abstract-room-heading'>Ort: </span>Bühne 3
                <br><span class='abstract-room-heading'>Dauer: </span>20 Minuten
            </p>

                        
            <p>Das von der Helmholtz-Stiftung geförderte Wissenstransfer-Projekt SAPIENS (Satellitendaten für Planung, Industrie, Energiewirtschaft und Naturschutz) vermittelt Fernerkundungs- und GIS-Kompetenzen über Web-Seminare, Lehrvideos und weitere E-Learning-Formate, in denen frei zugängliche Methoden und Daten priorisiert werden. Das Angebot frei verfügbarer Fernerkundungsdaten (z.B. Copernicus Programm) wächst zwar exponentiell an, aber die Nutzung ist bisher noch wenig in den Arbeitsalltag und in Entscheidungsprozesse der öffentlichen Verwaltung integriert. In unserem Vortrag möchten wir die Ziele des Projektes genauer erläutern und Erfahrungen sowohl zu Online-Kursdesign und -didaktik als auch zu Projektmanagement teilen. Außerdem geben wir eine Vorschau auf das größer angelegte, auf Fernerkundung fokussierte E-Learning-Projekt fern.LERN.</p>
        <div class='abstract-bio'>
            <h3 class='abstract-bio-name'>Nora Meyer zu Erpen</h3>
            <img class='abstract-speaker-avatar' src='/2021/avatars/S9F8RG.jpg'>            <p>Schon auf dem Gymnasium habe ich Erdkunde geliebt und aus Leidenschaft Geographie
studiert. Nach einer kurzen Stippvisite in der Wissenschaft bin ich 2009 in die
Privatwirtschaft zu Airbus Defence and Space gewechselt und habe an unterschiedlichsten Themen in der Erdfernerkundung gearbeitet. Nach über 11+ Jahren bei Airbus freue ich mich nun (seit Anfang 2021) meine Expertise im Wissenstransfer-Projekt SAPIENS am GeoForschungsZentrum Potsdam anzuwenden.  Ich bin der Überzeugung, dass freie Satellitendaten wichtige Ressourcen im Bereich Nachhaltigkeit sowie Klima- und Naturschutz sind und  möchte das Wissen um die Potenzial und den Umgang mit diesen Daten mit möglichst vielen interessierten Menschen teilen.</p>
        </div>
        </section>


	<?php include "../inc/footer.inc"; ?>

</body>

</html>