<!doctype html>
<html lang="de">

<head>
	<?php include "../inc/meta.inc"; ?>

	<base href="<?php echo dirname($_SERVER['SCRIPT_NAME']); ?>">
	<title>Einführung GeoServer – FOSSGIS 2021</title>

	<link rel="stylesheet" href="./css/normalize.css">
	<link rel="stylesheet" href="./css/base.css">
	<link rel="stylesheet" href="./css/print.css" media="print">
</head>

<body id="programm">
	<?php include "../inc/header.inc"; ?>

        <!-- This file was generated by a script. Do not edit this file in Git,
             edit contents in Pretalx, regenerate the PHP files and commit them
             in the Git repository of the website. -->
        <p><a href="programm/montag.php#session_HSF8MF">&#9668;&#9668; zurück zum Programm</a> </p>
        <h2 class='abstract-title'>Einführung GeoServer</h2>
        <section>
            <p>
                <span class='abstract-sessiontype'>Workshop</span>
                                von <span class='abstract-speakers'>Daniel Koch, Hannes Blitza</span></p>
                <p class='abstract-is-workshop'>Bitte melden Sie sich im <a href="https://pretix.eu/fossgis/2021/">Ticketshop</a> für diesen Workshop an, wenn Sie daran teilnehmen möchten.</p>                                <p class='abstract-is-workshop'>In diesem Workshop wird mit der aktuellen OSGeoLive gearbeitet, diese kann als Image von einem USB-Stick oder als virtuelle Maschine auf Ihrem Computer laufen. <a href="https://live.osgeo.org/de/index.html">Zur Installationsanleitung der OSGeoLive</a>.</p>                            <p><span class='abstract-time-heading'>Zeit: </span>Montag 07. Juni 14:00 Uhr
                <br><span class='abstract-room-heading'>Ort: </span>Workshop 1
                <br><span class='abstract-room-heading'>Dauer: </span>90 Minuten
            </p>

                        
            <p>Der GeoServer ist ein weit verbreiteter und einfach zu verwaltender Open-Source-Kartenserver, der die wichtigsten Standards des OGC wie WMS, WMTS, WFS oder WCS unterstützt. Er ermöglicht dabei die Veröffentlichung von Geodaten- und Kartendiensten aus zahlreichen Datenquellen wie den gängigen Datenbanken, dem GeoPackage oder (Cloud Optimized) dem GeoTIFF Format und ist durch diese breite Unterstützung von Inputdaten vielseitig einsetzbar. Die Verwaltung der Konfiguration wird durch seine übersichtliche Benutzeroberfläche erleichtert.</p>
<p>Dieser Workshop hat eine Einführung in die entscheidenden Konzepte und Funktionen des GeoServers zum Ziel und wird sich auf die wichtigsten Schritte der Publizierung eigener Kartendienste fokussieren. Dabei werden die Teilnehmer eigene Vektor- und Rasterdaten für den optimalen Einsatz im GeoServer vorbereiten, Daten aus diversen Quellen einbinden, diese als WMS und WFS Dienste bereitstellen und Layerstile über SLD (Styled Layer Descriptor) definieren.</p>
<p>Zielgruppe sind alle Interessierten, die die Möglichkeiten vom GeoServer kennenlernen wollen. Vorkenntnisse im GeoServer sind nicht notwendig.</p>
        <div class='abstract-bio'>
            <h3 class='abstract-bio-name'>Daniel Koch</h3>
            <img class='abstract-speaker-avatar' src='/2021/avatars/U7QH7V.jpg'>            <p>Lead Developer der terrestris GmbH &amp; Co. KG und OpenSource Enthusiast.</p>
        </div>
        <div class='abstract-bio'>
            <h3 class='abstract-bio-name'>Hannes Blitza</h3>
                        <p>Studium der Geographie in Marburg und Bonn. Mitarbeiter von terrestris in Bonn.</p>
        </div>
        </section>


	<?php include "../inc/footer.inc"; ?>

</body>

</html>