<!doctype html>
<html lang="de">

<head>
	<?php include "../inc/meta.inc"; ?>

	<base href="<?php echo dirname($_SERVER['SCRIPT_NAME']); ?>">
	<title>Neues von osm2pgsql – FOSSGIS 2021</title>

	<link rel="stylesheet" href="./css/normalize.css">
	<link rel="stylesheet" href="./css/base.css">
	<link rel="stylesheet" href="./css/print.css" media="print">
</head>

<body id="programm">
	<?php include "../inc/header.inc"; ?>

        <!-- This file was generated by a script. Do not edit this file in Git,
             edit contents in Pretalx, regenerate the PHP files and commit them
             in the Git repository of the website. -->
        <p><a href="programm/mittwoch.php#session_HTTWNG">&#9668;&#9668; zurück zum Programm</a> </p>
        <h2 class='abstract-title'>Neues von osm2pgsql</h2>
        <section>
            <p>
                <span class='abstract-sessiontype'>Langer Vortrag</span>                von <span class='abstract-speakers'>Jochen Topf</span></p>
                                                                            <p><span class='abstract-time-heading'>Zeit: </span>Mittwoch 09. Juni 11:00 Uhr
                <br><span class='abstract-room-heading'>Ort: </span>Bühne 1
                <br><span class='abstract-room-heading'>Dauer: </span>40 Minuten
            </p>

                        
            <p>Der Vortrag wird auf die Neuerungen bei osm2pgsql eingehen und zeigen, wie die neuen Features auf vielfältige Art genutzt werden können. Natürlich kann man sie zum Erzeugen von Bitmap- oder Vector-Tiles verwenden. Aber auch die Nutzung aus GIS-Programmen wie QGIS ist einfach möglich. Daneben können die Daten für geographische und statistische Analysen und für viele andere Dinge genutzt werden.</p>
        <div class='abstract-bio'>
            <h3 class='abstract-bio-name'>Jochen Topf</h3>
            <img class='abstract-speaker-avatar' src='/2021/avatars/LULDTS_2d4dfcdcde73aa5e2ffa4a9b3a7cb51d'>            <p>Jochen Topf ist seit vielen Jahren bei OpenStreetMap als Mapper und Software-Entwickler aktiv. Er ist der Autor des Flex-Outputs von osm2pgsql und betreut auch das Osmium Framework und viele andere OSM-Software.
Auch beruflich ist er als Software-Entwickler und Consultant im Bereich OpenStreetMap und der GIS-Welt unterwegs.</p>
        </div>
        </section>


	<?php include "../inc/footer.inc"; ?>

</body>

</html>