<!doctype html>
<html lang="de">

<head>
	<?php include "../inc/meta.inc"; ?>

	<base href="<?php echo dirname($_SERVER['SCRIPT_NAME']); ?>">
	<title>Teilautomatische Erkennung von Innenentwicklungspotenzialen mit QGIS und Python auf Basis von amtlichen Geodaten – FOSSGIS 2021</title>

	<link rel="stylesheet" href="./css/normalize.css">
	<link rel="stylesheet" href="./css/base.css">
	<link rel="stylesheet" href="./css/print.css" media="print">
</head>

<body id="programm">
	<?php include "../inc/header.inc"; ?>

        <!-- This file was generated by a script. Do not edit this file in Git,
             edit contents in Pretalx, regenerate the PHP files and commit them
             in the Git repository of the website. -->
        <p><a href="programm/mittwoch.php#session_JFLZLE">&#9668;&#9668; zurück zum Programm</a> </p>
        <h2 class='abstract-title'>Teilautomatische Erkennung von Innenentwicklungspotenzialen mit QGIS und Python auf Basis von amtlichen Geodaten</h2>
        <section>
            <p>
                <span class='abstract-sessiontype'>Vortrag</span>                von <span class='abstract-speakers'>Mirko Blinn</span></p>
                                                                            <p><span class='abstract-time-heading'>Zeit: </span>Mittwoch 09. Juni 14:30 Uhr
                <br><span class='abstract-room-heading'>Ort: </span>Bühne 2
                <br><span class='abstract-room-heading'>Dauer: </span>20 Minuten
            </p>

                        
            <p>Ein Ziel  der Deutschen Nachhaltigkeitsstrategie ist es, dass Wachstum der Siedelungs- und Verkehrsfläche zu begrenzen und so die Flächenneuinanspruchname insgesamt zu reduzieren  . Ein wichtiger Handlungsbaustein in diesem Zusammenhang ist die Nachverdichtung im Innenbereich. Zur Suche und Erfassung von Nachverdichtungspontenzialen setzen viele Kommunen bereits GIS gestützte Baulückenkataster ein. Die Kataster werden allerdings oft händisch geführt und variieren stark hinsichtlich Qualität und Quantität. 
Durch die zunehmende freie Bereitstellung von amtlichen Geodaten und der Weiterentwicklung von QGIS in den letzten Jahren ist es möglich Tools zu entwickeln, die Baulücken im Innenbereich automatisch erkennen und auf ihre grundsätzliche Eignung als Nachverdichtungspotenzial prüfen. 
Im Rahmen einer Masterarbeit an der Universität Bonn ist ein solches Tool auf Basis von QGIS und Python entwickelt worden, das in der Lage ist auf Grundlage von amtlichen Geodaten (Alkis, Basis-DLM und LOD2-Gebäudemodellen) Nachverdichtungspotzenziale automatisch zu erkennen und ihre Eignung als Wohnbaufläche zu prüfen. Beispielsweise wurde für die Ortslage „Köln“, also den linksrheinischen Bereich innerhalb des zweiten Ringes, ein theoretisches Nachverdichtungspotzenzial von ca. 155 Hektar ermittelt. 
 In diesen Vortrag soll die Funktionsweise des Tools näher vorgestellt werden. An einem Beispiel aus dem Forschungsprojekt NACHWUCHS der Universität Bonn wird gezeigt , wie das Tool praktisch genutzt werden kann und wie die gefunden Nachverdichtungspotenzial mit freien Geodaten beispielsweise aus OSM weiter untersucht und bewertet werden können.</p>
        </section>


	<?php include "../inc/footer.inc"; ?>

</body>

</html>