<!doctype html>
<html lang="de">

<head>
	<?php include "../inc/meta.inc"; ?>

	<base href="<?php echo dirname($_SERVER['SCRIPT_NAME']); ?>">
	<title>Workshop Open Database License – FOSSGIS 2021</title>

	<link rel="stylesheet" href="./css/normalize.css">
	<link rel="stylesheet" href="./css/base.css">
	<link rel="stylesheet" href="./css/print.css" media="print">
</head>

<body id="programm">
	<?php include "../inc/header.inc"; ?>

        <!-- This file was generated by a script. Do not edit this file in Git,
             edit contents in Pretalx, regenerate the PHP files and commit them
             in the Git repository of the website. -->
        <p><a href="programm/dienstag.php#session_JPJMT9">&#9668;&#9668; zurück zum Programm</a> </p>
        <h2 class='abstract-title'>Workshop Open Database License</h2>
        <section>
            <p>
                <span class='abstract-sessiontype'>Workshop</span>
                                von <span class='abstract-speakers'>Falk Zscheile</span></p>
                <p class='abstract-is-workshop'>Bitte melden Sie sich im <a href="https://pretix.eu/fossgis/2021/">Ticketshop</a> für diesen Workshop an, wenn Sie daran teilnehmen möchten.</p>                <p class='abstract-is-workshop'>Dieser Workshop wird browserbasiert durchgeführt. Zur Teilnahme benötigen Sie lediglich einen aktuellen Internet-Browser.</p>                                            <p><span class='abstract-time-heading'>Zeit: </span>Dienstag 08. Juni 09:00 Uhr
                <br><span class='abstract-room-heading'>Ort: </span>Workshop 1
                <br><span class='abstract-room-heading'>Dauer: </span>90 Minuten
            </p>

                        
            <p>Grundlagen Immaterialgüterrecht und Lizenzen 
- Informationen und ihr Schutz 
- Ausschließlichkeitsrechte und Lizenzierung 
- Lizenzen und Allgemeine Geschäftsbedingungen 
- Das Datenbankherstellerrecht, §§ 87a ff. UrhG</p>
        </section>


	<?php include "../inc/footer.inc"; ?>

</body>

</html>