<!doctype html>
<html lang="de">

<head>
	<?php include "../inc/meta.inc"; ?>

	<base href="<?php echo dirname($_SERVER['SCRIPT_NAME']); ?>">
	<title>Kartographierung von Businessdaten – FOSSGIS 2021</title>

	<link rel="stylesheet" href="./css/normalize.css">
	<link rel="stylesheet" href="./css/base.css">
	<link rel="stylesheet" href="./css/print.css" media="print">
</head>

<body id="programm">
	<?php include "../inc/header.inc"; ?>

        <!-- This file was generated by a script. Do not edit this file in Git,
             edit contents in Pretalx, regenerate the PHP files and commit them
             in the Git repository of the website. -->
        <p><a href="programm/mittwoch.php#session_JXMJBV">&#9668;&#9668; zurück zum Programm</a> </p>
        <h2 class='abstract-title'>Kartographierung von Businessdaten</h2>
        <section>
            <p>
                <span class='abstract-sessiontype'>Vortrag</span>                von <span class='abstract-speakers'>Marion Baumgartner, Gerber Benjamin</span></p>
                                                                            <p><span class='abstract-time-heading'>Zeit: </span>Mittwoch 09. Juni 12:00 Uhr
                <br><span class='abstract-room-heading'>Ort: </span>Bühne 2
                <br><span class='abstract-room-heading'>Dauer: </span>20 Minuten
            </p>

                        
            <p>Anhand einer Live-Anwendung wird ein Beispiel gezeigt, welches Business-Daten in einen geographischen Kontext stellt.</p>
<p>In der Anwendung werden die Business-Daten an geografische Punkte wie z.B Verkaufsstellen geknüpft. Damit können die vorhandenen Daten in geographische Regionen aggregiert und kartographisch dargestellt werden. Um die Nutzerfreundlichkeit zu unterstützen, werden nebst Karten auch Tabellen und Diagramme benutzt, um auf Einzelheiten der Aggregationen einzugehen. </p>
<p>Für die kartographischen Elemente wird OpenLayers verwendet. Für die Umsetzung der unterschiedlichen Diagramme wird d3 über die d3-helper Bibliothek verwendet. Die d3-helper Bibliothek ist eine Open-Source Bibliothek, welche aus der hier gezeigten Anwendung entstanden ist, da viele Diagramme in dem Tool die selbe Basis benutzen.</p>
<p>Die Präsentation zeigt anhand eines Beispiels wie kartografische und nicht-kartografische Data-Exploration kombiniert werden kann und die verwendeten Open Source Komponenten zu einem kompletten Business Intelligence Tool zusammenwachsen.</p>
        </section>


	<?php include "../inc/footer.inc"; ?>

</body>

</html>