<!doctype html>
<html lang="de">

<head>
	<?php include "../inc/meta.inc"; ?>

	<base href="<?php echo dirname($_SERVER['SCRIPT_NAME']); ?>">
	<title>MapFish Print: Eine serverseitige Druck-Komponente – FOSSGIS 2021</title>

	<link rel="stylesheet" href="./css/normalize.css">
	<link rel="stylesheet" href="./css/base.css">
	<link rel="stylesheet" href="./css/print.css" media="print">
</head>

<body id="programm">
	<?php include "../inc/header.inc"; ?>

        <!-- This file was generated by a script. Do not edit this file in Git,
             edit contents in Pretalx, regenerate the PHP files and commit them
             in the Git repository of the website. -->
        <p><a href="programm/dienstag.php#session_KDLGML">&#9668;&#9668; zurück zum Programm</a> </p>
        <h2 class='abstract-title'>MapFish Print: Eine serverseitige Druck-Komponente</h2>
        <section>
            <p>
                <span class='abstract-sessiontype'>Vortrag</span>                von <span class='abstract-speakers'>Björn Höfling</span></p>
                                                                            <p><span class='abstract-time-heading'>Zeit: </span>Dienstag 08. Juni 16:00 Uhr
                <br><span class='abstract-room-heading'>Ort: </span>Bühne 3
                <br><span class='abstract-room-heading'>Dauer: </span>20 Minuten
            </p>

                        
            <p>MapFish Print ist eine in Java geschriebene Open-Source-Software (BSD-2 Lizenz) zum Drucken von Karten. Als klassische Druck-Komponente ist MapFish Print bereits in vielen Open-Source Web-Mapping Frameworks integriert, z.B. in GeoMapFish.
MapFish Print lässt sich in einem klassischen Servlet-Container (z.B. Tomcat) als WAR-File deployen oder steht als Docker-Image zur Verfügung und lässt sich so in Cloud-Umgebungen integrieren.  MapFish Print steht auch als Bibliothek zur Verfügung und lässt sich dadurch in eigene Projekte integrieren.</p>
<p>MapFish Print unterstützt viele gängige Formate und Standards (z.B. WMS, WFS, WMTS, GeoJSON). Zudem bietet die Anwendung zahlreiche kartographische Gestaltungsmöglichkeiten wie Drehungen, Nordpfeile, Legenden oder Grids. Der Ausdruck wird über ein JasperReports-Template gestaltet und über eine YAML-Konfigurationsdatei definieren. Über einen JSON-Request wird dann vom Client der konkrete Druck-Inhalt (Layer, AOI, etc) übergeben.</p>
        <div class='abstract-bio'>
            <h3 class='abstract-bio-name'>Björn Höfling</h3>
            <p>Björn Höfling ist Mitarbeiter der Camptocamp Germany GmbH, Java-Entwickler, GIS-Experte, mag freie Software und offene Daten.</p>
        </div>
        </section>


	<?php include "../inc/footer.inc"; ?>

</body>

</html>