<!doctype html>
<html lang="de">

<head>
	<?php include "../inc/meta.inc"; ?>

	<base href="<?php echo dirname($_SERVER['SCRIPT_NAME']); ?>">
	<title>Konfiguration eines WFS-T mit MapServer und TinyOWS – FOSSGIS 2021</title>

	<link rel="stylesheet" href="./css/normalize.css">
	<link rel="stylesheet" href="./css/base.css">
	<link rel="stylesheet" href="./css/print.css" media="print">
</head>

<body id="programm">
	<?php include "../inc/header.inc"; ?>

        <!-- This file was generated by a script. Do not edit this file in Git,
             edit contents in Pretalx, regenerate the PHP files and commit them
             in the Git repository of the website. -->
        <p><a href="programm/montag.php#session_KR7VJQ">&#9668;&#9668; zurück zum Programm</a> </p>
        <h2 class='abstract-title'>Konfiguration eines WFS-T mit MapServer und TinyOWS</h2>
        <section>
            <p>
                <span class='abstract-sessiontype'>Demo-Session</span>                von <span class='abstract-speakers'>Jörg Thomsen</span></p>
                                                                            <p><span class='abstract-time-heading'>Zeit: </span>Montag 07. Juni 14:00 Uhr
                <br><span class='abstract-room-heading'>Ort: </span>Bühne 4
                <br><span class='abstract-room-heading'>Dauer: </span>55 Minuten
            </p>

                        
            <p>MapServer selbst kann keinen transaktionalen WFS bereit stellen. Mit dem Partner-Projekt TinyOWS ist das auf einfache Weise möglich. Dabei kann der TinyOWS auch über eine Map-Datei konfiguriert werden. Die Demo-Session zeigt wie das funktioniert. Darüber hinaus wird gezeigt wie TinyOWS als stand-alone-Anwendung über kurze XML-Dateien konfiguriert werden kann und wie über die Konfiguration des Webservers mehrere WFS parallel betrieben werden können.
Ein WFS-T mit XML-Konfiguration benötigt nur wenige Zeilen:
<tinyows online_resource="http://schulung.foss.academy/cgi-bin/tinyows"
  schema_dir="/usr/local/tinyows/schema/" check_schema="0"></p>
<p><pg host="localhost" user="xxxx" password="xxxx" dbname="mapserver" port="5432"/>
  <metadata name="TinyOWS Server" title="TinyOWS Server - Demo Service" /></p>
<p><layer retrievable="1" writable="1"  ns_prefix="tows" ns_uri="http://www.tinyows.org"
         name="ne_10m_urban_areas" title="World Administrative Urban Areas" />
</tinyows></p>
<p>Auch für eine TinyOWS-Konfiguration innerhalb einer Mapdatei sind nur wenige Einträge notwendig:
MAP
    NAME "TinyOWS"
    WEB
         METADATA
            "tinyows_schema_dir" "/usr/local/share/tinyows/schema/"
            "tinyows_onlineresource" "http://schulung.foss.academy/cgi-bin/tinyowsmapfile"
            "tinyows_check_schema" "0"
            ...
         END
    END
    LAYER
        ...
        METADATA
            'wfs_title' 'Urban Areas'
            'wfs_namespace_prefix' 'towsmap'
            'wfs_namespace_uri' 'http://www.mapserver.org/tinyows/'
            'wfs_srs' 'EPSG:4326'
            'tinyows_table'  'ne_10m_urban_areas'
            'tinyows_writable' '1'
            'tinyows_retrievable' '1'
        END
    END
END</p>
<p>Quellen
[1] https://mapserver.org/tinyows/
[2] https://github.com/MapServer/tinyows
[3] https://www.fossgis-konferenz.de/2012/programm/attachments/353_fossgis2012_tinyows.pdf</p>
        <div class='abstract-bio'>
            <h3 class='abstract-bio-name'>Jörg Thomsen</h3>
                        <p>Jörg Thomsen arbeitet seit dem Ende des letzten Jahrhunderts mit freier GI-Software und war bereits die FOSSGIS-Konferenz bereits mit gestaltet, als sie noch MapServer Anwender-Konferenz hieß.</p>
<p>In den vergangenen 20 Jahren hat Jörg Thomsen zahlreiche WebGIS-Projekte umgesetzt und noch mehr Teilnehmern in seinen Workshops und Schulungen die Themen PostgreSQL und PostGIS, MapServer, GeoServer, QGIS, QGIS Server und Mapbender näher gebracht.</p>
<p>Jörg Thomsen arbeitet bei der WhereGroup in Berlin und ist Dozent der [FOSS Academy] (https://www.foss-academy.com), dem Schulungsinstitut der WhereGroup (https://www.wheregroup.com)</p>
<p>Jörg Thomsen ist im FOSSGIS e.V. und der OSGeo Foundation (http://osgeo.org) aktiv.</p>
        </div>
        </section>


	<?php include "../inc/footer.inc"; ?>

</body>

</html>