<!doctype html>
<html lang="de">

<head>
	<?php include "../inc/meta.inc"; ?>

	<base href="<?php echo dirname($_SERVER['SCRIPT_NAME']); ?>">
	<title>Site Reliability Engineering (SRE) in Geo-Diensten – FOSSGIS 2021</title>

	<link rel="stylesheet" href="./css/normalize.css">
	<link rel="stylesheet" href="./css/base.css">
	<link rel="stylesheet" href="./css/print.css" media="print">
</head>

<body id="programm">
	<?php include "../inc/header.inc"; ?>

        <!-- This file was generated by a script. Do not edit this file in Git,
             edit contents in Pretalx, regenerate the PHP files and commit them
             in the Git repository of the website. -->
        <p><a href="programm/dienstag.php#session_KVX7EA">&#9668;&#9668; zurück zum Programm</a> <a href="sessions/lightning_talks_3.php">&#9668; zurück zur Session</a></p>
        <h2 class='abstract-title'>Site Reliability Engineering (SRE) in Geo-Diensten</h2>
        <section>
            <p>
                <span class='abstract-sessiontype'>Lightning Talk</span>                von <span class='abstract-speakers'>Arne Schubert, Stephan Herritsch</span></p>
                                                                            <p><span class='abstract-time-heading'>Zeit: </span>Dienstag 08. Juni 12:10 Uhr
                <br><span class='abstract-room-heading'>Ort: </span>Bühne 2
                <br><span class='abstract-room-heading'>Dauer: </span>5 Minuten
            </p>

                        
            <p><a href="https://en.wikipedia.org/wiki/Site_reliability_engineering">Site Reliability Engineering</a> (SRE) ist Google's Weg <a href="https://de.wikipedia.org/wiki/DevOps">DevOps</a> zu leben. Es ist eine Methode Services messbar stabil zu halten und gleichzeitig Innovativ zu bleiben, aber auch Faktoren zu entdecken, die die Weiterentwicklung ausbremsen. Das Thema spricht das Management, sowie Administratoren und Entwickler gleichermaßen an und ist eine Methode ein gemeinsames Verständnis und gegenseitiges Agreement sicherzustellen. In diesem Vortrag soll zunächst erklärt werden, was SRE ausmacht und wie es auf <a href="https://de.wikipedia.org/wiki/Geodateninfrastruktur">Geo-Daten-Infrastrukturen</a> (GDIs) angewendet werden kann.</p>
        </section>


	<?php include "../inc/footer.inc"; ?>

</body>

</html>