<!doctype html>
<html lang="de">

<head>
	<?php include "../inc/meta.inc"; ?>

	<base href="<?php echo dirname($_SERVER['SCRIPT_NAME']); ?>">
	<title>Ist Ground Truth nun unten oder oben? Vergleich von Satellitenbild- mit OpenStreetMap-Daten – FOSSGIS 2021</title>

	<link rel="stylesheet" href="./css/normalize.css">
	<link rel="stylesheet" href="./css/base.css">
	<link rel="stylesheet" href="./css/print.css" media="print">
</head>

<body id="programm">
	<?php include "../inc/header.inc"; ?>

        <!-- This file was generated by a script. Do not edit this file in Git,
             edit contents in Pretalx, regenerate the PHP files and commit them
             in the Git repository of the website. -->
        <p><a href="programm/montag.php#session_KXUK3W">&#9668;&#9668; zurück zum Programm</a> <a href="sessions/lightning_talks_1.php">&#9668; zurück zur Session</a></p>
        <h2 class='abstract-title'>Ist Ground Truth nun unten oder oben? Vergleich von Satellitenbild- mit OpenStreetMap-Daten</h2>
        <section>
            <p>
                <span class='abstract-sessiontype'>Lightning Talk</span>                von <span class='abstract-speakers'>Oiza Otaru, Nicola Jordan</span></p>
                                                                            <p><span class='abstract-time-heading'>Zeit: </span>Montag 07. Juni 17:15 Uhr
                <br><span class='abstract-room-heading'>Ort: </span>Bühne 2
                <br><span class='abstract-room-heading'>Dauer: </span>5 Minuten
            </p>

                        
            <p>In diesem Kurzbeitrag geht es um einen Vergleich von Satellitenbild-mit OpenStreetMap-Daten und zwar mit Hilfe von SwissDataCube und Datenprozessierung mittels Python (Jupyter Notebooks). SwissDataCube (SDC) nutzt die OpenDataCube-Open-Source-Technologie, um Zugang zu allen Landsat- und Sentinel-Daten zu bieten, welche die Schweiz abdecken. Das Ziel des Vergleichs-Experiments ist, am Beispiel von Siedlungsgrenzen die Möglichkeiten der Kombination beider Datenquellen auszuloten. </p>
<p>Ground Truth ("Bodenwirklichkeit", Feldvergleich) bezeichnet in der Fernerkundung und Kartografie direkt am Boden aufgenommene Informationen. Durch Ground-Truth-Daten ist es möglich, Satelliten- und Luftbilder präziser zu klassifizieren und das Ergebnis auf Korrektheit zu prüfen. OpenStreetMap (OSM) liefert solche Ground-Truth-Daten. </p>
<p>Auch umgekehrt kann ein solcher Vergleich Hinweise liefern, wo OSM-Daten - wie beispielsweise Gebäude und Siedlungsgebiete - fehlen! Ein aktuelle Herausforderung ist dabei das Auffinden und der technische Zugriff auf die Fernerkundungs- und OSM-Daten inklusive frühere Datenstände. Da sowohl für Sentinel- als auch für OSM historisierte Daten verfügbar sind, eröffnet dies weitere Analysemöglichkeiten.</p>
        </section>


	<?php include "../inc/footer.inc"; ?>

</body>

</html>