<!doctype html>
<html lang="de">

<head>
	<?php include "../inc/meta.inc"; ?>

	<base href="<?php echo dirname($_SERVER['SCRIPT_NAME']); ?>">
	<title>OpenStreetMap in Nationalparken – Chancen, Folgen und Herausforderungen – FOSSGIS 2021</title>

	<link rel="stylesheet" href="./css/normalize.css">
	<link rel="stylesheet" href="./css/base.css">
	<link rel="stylesheet" href="./css/print.css" media="print">
</head>

<body id="programm">
	<?php include "../inc/header.inc"; ?>

        <!-- This file was generated by a script. Do not edit this file in Git,
             edit contents in Pretalx, regenerate the PHP files and commit them
             in the Git repository of the website. -->
        <p><a href="programm/montag.php#session_LEQMEF">&#9668;&#9668; zurück zum Programm</a> </p>
        <h2 class='abstract-title'>OpenStreetMap in Nationalparken – Chancen, Folgen und Herausforderungen</h2>
        <section>
            <p>
                <span class='abstract-sessiontype'>Vortrag</span>                von <span class='abstract-speakers'>Anne Seltmann, Julia Zink</span></p>
                                                                            <p><span class='abstract-time-heading'>Zeit: </span>Montag 07. Juni 16:30 Uhr
                <br><span class='abstract-room-heading'>Ort: </span>Bühne 2
                <br><span class='abstract-room-heading'>Dauer: </span>20 Minuten
            </p>

                        
            <p>Nationalparke sind großräumige Schutzgebiete mit dem Ziel, natürliche Prozesse und Dynamik zu schützen, gleichzeitig bieten sie Raum für Forschung, Bildung und Naturerlebnis. Jedes Jahr besuchen mehrere Millionen Menschen die deutschen Nationalparke, viele davon nutzen mittlerweile OSM-basierte Anwendungen zur Planung von Aktivitäten oder zur Navigation im Gelände. Vor diesem Hintergrund beschäftigen sich immer mehr Schutzgebietsverwaltungen mit OpenStreetMap und sind daran interessiert, zu einer möglichst korrekten und vollständigen Datengrundlage beizutragen.
Wir stellen in diesem Praxisbericht die Situation in der OSM-Datenbank und im Gelände sowie unsere bisherige Arbeit als Behördenverteterinnen in zwei Nationalparken Deutschlands (Bayerischer Wald und Sächsische Schweiz) dar. 
An Beispielen möchten wir zeigen, wie sich digitale Wege-Informationen und POIs in Schutzgebieten bei hoher Frequentierung auswirken und welche Herausforderungen beim Editieren in OSM entstehen können. Gemeinsam mit der Community konnten wir bereits viele dieser Herausforderungen bewältigen und möchten von unseren Erfahrungen berichten.
Ziel unseres Beitrags ist es, Sensibilität für Schutzgebiete zu erzeugen und weiterhin den Austausch, Kontakt und die Zusammenarbeit zwischen OSM-Community und staatlichen Schutzgebieten zu fördern.</p>
        </section>


	<?php include "../inc/footer.inc"; ?>

</body>

</html>