<!doctype html>
<html lang="de">

<head>
	<?php include "../inc/meta.inc"; ?>

	<base href="<?php echo dirname($_SERVER['SCRIPT_NAME']); ?>">
	<title>Lightning Talks – FOSSGIS 2021</title>

	<link rel="stylesheet" href="./css/normalize.css">
	<link rel="stylesheet" href="./css/base.css">
	<link rel="stylesheet" href="./css/print.css" media="print">
</head>

<body id="programm">
	<?php include "../inc/header.inc"; ?>

        <!-- This file was generated by a script. Do not edit this file in Git,
             edit contents in Pretalx, regenerate the PHP files and commit them
             in the Git repository of the website. -->
        <p><a href="programm/montag.php#session_lightning_talks_0">&#9668; zurück zum Programm</a></p>
        <section>
        <h2 class='abstract-title'>Lightning Talks</h2>
        <p><span class='abstract-time-heading'>Zeit: </span>Montag 07. Juni 10:15 Uhr<br><span class='abstract-room-heading'>Ort: </span>Bühne 1</p>
        <p>Diese Session besteht aus den folgenden Programmpunkten:</p>
        <ul>
                    <li>Arnulf Christl: <span class='subsession-title'><a href="sessions/WSUSUX.php">Die Cloud hat Open Source gefressen</a></span>
                            </li>
                    <li>Astrid Emde: <span class='subsession-title'><a href="sessions/MQWM83.php">Warum Open Source-Projekte finanzielle Unterstützung benötigen</a></span>
                            </li>
                </ul>
        </section>


	<?php include "../inc/footer.inc"; ?>

</body>

</html>