<!doctype html>
<html lang="de">

<head>
	<?php include "../inc/meta.inc"; ?>

	<base href="<?php echo dirname($_SERVER['SCRIPT_NAME']); ?>">
	<title>Lightning Talks – FOSSGIS 2021</title>

	<link rel="stylesheet" href="./css/normalize.css">
	<link rel="stylesheet" href="./css/base.css">
	<link rel="stylesheet" href="./css/print.css" media="print">
</head>

<body id="programm">
	<?php include "../inc/header.inc"; ?>

        <!-- This file was generated by a script. Do not edit this file in Git,
             edit contents in Pretalx, regenerate the PHP files and commit them
             in the Git repository of the website. -->
        <p><a href="programm/dienstag.php#session_lightning_talks_2">&#9668; zurück zum Programm</a></p>
        <section>
        <h2 class='abstract-title'>Lightning Talks</h2>
        <p><span class='abstract-time-heading'>Zeit: </span>Dienstag 08. Juni 10:00 Uhr<br><span class='abstract-room-heading'>Ort: </span>Bühne 1</p>
        <p>Diese Session besteht aus den folgenden Programmpunkten:</p>
        <ul>
                    <li>Christian Mayer: <span class='subsession-title'><a href="sessions/QVK8J8.php">Massenkonvertieren kartographischer Stildokumente mit GeoStyler-CLI</a></span>
                            </li>
                    <li>Peter Heidelbach: <span class='subsession-title'><a href="sessions/ZLGACF.php">Der MapQonverter - Austausch zwischen ArcMap und QGIS</a></span>
                            </li>
                    <li>Sebastian M. Ernst: <span class='subsession-title'><a href="sessions/DF3TGM.php">Erfahrungen mit QEP 179: Über Paketierung, Abhängigkeiten, ungenutztes technisches Potential sowie die Notwendigkeit von fundierten Programmierkenntnissen bei der Benutzung von GUI-Anwendungen</a></span>
                            </li>
                </ul>
        </section>


	<?php include "../inc/footer.inc"; ?>

</body>

</html>