<!doctype html>
<html lang="de">

<head>
	<?php include "../inc/meta.inc"; ?>

	<base href="<?php echo dirname($_SERVER['SCRIPT_NAME']); ?>">
	<title>SensorThings – Von der Sensordaten-Verarbeitung im Backend bis zur Visualisierung im Masterportal – FOSSGIS 2021</title>

	<link rel="stylesheet" href="./css/normalize.css">
	<link rel="stylesheet" href="./css/base.css">
	<link rel="stylesheet" href="./css/print.css" media="print">
</head>

<body id="programm">
	<?php include "../inc/header.inc"; ?>

        <!-- This file was generated by a script. Do not edit this file in Git,
             edit contents in Pretalx, regenerate the PHP files and commit them
             in the Git repository of the website. -->
        <p><a href="programm/dienstag.php#session_LZJG7N">&#9668;&#9668; zurück zum Programm</a> </p>
        <h2 class='abstract-title'>SensorThings – Von der Sensordaten-Verarbeitung im Backend bis zur Visualisierung im Masterportal</h2>
        <section>
            <p>
                <span class='abstract-sessiontype'>Vortrag</span>                von <span class='abstract-speakers'>Dirk Rohrmoser</span></p>
                                                                            <p><span class='abstract-time-heading'>Zeit: </span>Dienstag 08. Juni 15:00 Uhr
                <br><span class='abstract-room-heading'>Ort: </span>Bühne 1
                <br><span class='abstract-room-heading'>Dauer: </span>20 Minuten
            </p>

                        
            <p>Aufgrund der fortschreitenden Digitalisierung und neuen Formen von Mobilität steigt der Bedarf in Öffentlichkeit, Wirtschaft und Verwaltung an intelligenten Lösungen zur Verarbeitung hochdynamischer Echtzeitdaten. Insbesondere in hochverdichteten, städtischen Räumen bieten sich vielversprechende Möglichkeiten durch den Einsatz von Sensorik und die Live-Darstellung der so gewonnenen Daten. Beispielsweise können Verkehrsflüsse oder Auslastungen von E-Mobility-Ladestandorten optimiert und damit übergeordnete Ziele wie die Verringerung von Emissionen erreicht werden. Dieser Vortrag stellt anhand von Anwendungsbeispielen der Freien und Hansestadt Hamburg vor, wie Sensordaten mit Open Source Technologien verarbeitet, verteilt und im Masterportal (www.masterportal.org) visualisiert werden.</p>
        </section>


	<?php include "../inc/footer.inc"; ?>

</body>

</html>