<!doctype html>
<html lang="de">

<head>
	<?php include "../inc/meta.inc"; ?>

	<base href="<?php echo dirname($_SERVER['SCRIPT_NAME']); ?>">
	<title>Einfacher Aufbau von Web-GIS-Anwendungen mit Mapbender – FOSSGIS 2021</title>

	<link rel="stylesheet" href="./css/normalize.css">
	<link rel="stylesheet" href="./css/base.css">
	<link rel="stylesheet" href="./css/print.css" media="print">
</head>

<body id="programm">
	<?php include "../inc/header.inc"; ?>

        <!-- This file was generated by a script. Do not edit this file in Git,
             edit contents in Pretalx, regenerate the PHP files and commit them
             in the Git repository of the website. -->
        <p><a href="programm/dienstag.php#session_MSMY3S">&#9668;&#9668; zurück zum Programm</a> </p>
        <h2 class='abstract-title'>Einfacher Aufbau von Web-GIS-Anwendungen mit Mapbender</h2>
        <section>
            <p>
                <span class='abstract-sessiontype'>Workshop</span>
                                von <span class='abstract-speakers'>Jörg Thomsen</span></p>
                <p class='abstract-is-workshop'>Bitte melden Sie sich im <a href="https://pretix.eu/fossgis/2021/">Ticketshop</a> für diesen Workshop an, wenn Sie daran teilnehmen möchten.</p>                <p class='abstract-is-workshop'>Dieser Workshop wird browserbasiert durchgeführt. Zur Teilnahme benötigen Sie lediglich einen aktuellen Internet-Browser.</p>                                            <p><span class='abstract-time-heading'>Zeit: </span>Dienstag 08. Juni 14:00 Uhr
                <br><span class='abstract-room-heading'>Ort: </span>Workshop 1
                <br><span class='abstract-room-heading'>Dauer: </span>90 Minuten
            </p>

                        
            <p>Mapbender ist ein Web-GIS-Client und ermöglicht das einfache Management von Kartendiensten, Anwendungsoberflächen und deren Benutzern. Der Workshop zu Mapbender richtet sich an Einsteiger und bietet einen Überblick über die Architektur und Komponenten von Mapbender. Mit Mapbender haben Sie die Möglichkeit Anwendungen zu erzeugen, ohne eine Zeile Code zu schreiben. Über die moderne graphische Administrationsoberfläche können bequem Anpassungen an den zahlreichen Funktionalitäten und am Design vorgenommen werden.</p>
<p>Im Workshop wird gezeigt, wie man mit Mapbender mit wenigen Klicks eine eigene WebMaping-Anwendung erstellen kann (WMS einbinden, Layertree, Legende, Druck). Seit der letzten FOSSGIS hat sich einiges im Mapbender-Projekt getan es wird auch auf die Neuerungen eingegangen (wiederverwendbare WMS-Konfigurationen / Layersets, individuelle Konfiguration von Elementen für dein Einsatz auf dem Desktop und auf mobilen Geräten). </p>
<p>Der Workshop wird online auf einer Mapbender-Installation auf einem Server des Projekts durchgeführt.</p>
        <div class='abstract-bio'>
            <h3 class='abstract-bio-name'>Jörg Thomsen</h3>
                        <p>Jörg Thomsen arbeitet seit dem Ende des letzten Jahrhunderts mit freier GI-Software und war bereits die FOSSGIS-Konferenz bereits mit gestaltet, als sie noch MapServer Anwender-Konferenz hieß.</p>
<p>In den vergangenen 20 Jahren hat Jörg Thomsen zahlreiche WebGIS-Projekte umgesetzt und noch mehr Teilnehmern in seinen Workshops und Schulungen die Themen PostgreSQL und PostGIS, MapServer, GeoServer, QGIS, QGIS Server und Mapbender näher gebracht.</p>
<p>Jörg Thomsen arbeitet bei der WhereGroup in Berlin und ist Dozent der [FOSS Academy] (https://www.foss-academy.com), dem Schulungsinstitut der WhereGroup (https://www.wheregroup.com)</p>
<p>Jörg Thomsen ist im FOSSGIS e.V. und der OSGeo Foundation (http://osgeo.org) aktiv.</p>
        </div>
        </section>


	<?php include "../inc/footer.inc"; ?>

</body>

</html>