<!doctype html>
<html lang="de">

<head>
	<?php include "../inc/meta.inc"; ?>

	<base href="<?php echo dirname($_SERVER['SCRIPT_NAME']); ?>">
	<title>LiDAR langsam: Jetzt erst recht? – FOSSGIS 2021</title>

	<link rel="stylesheet" href="./css/normalize.css">
	<link rel="stylesheet" href="./css/base.css">
	<link rel="stylesheet" href="./css/print.css" media="print">
</head>

<body id="programm">
	<?php include "../inc/header.inc"; ?>

        <!-- This file was generated by a script. Do not edit this file in Git,
             edit contents in Pretalx, regenerate the PHP files and commit them
             in the Git repository of the website. -->
        <p><a href="programm/montag.php#session_MTJ9R9">&#9668;&#9668; zurück zum Programm</a> <a href="sessions/lightning_talks_1.php">&#9668; zurück zur Session</a></p>
        <h2 class='abstract-title'>LiDAR langsam: Jetzt erst recht?</h2>
        <section>
            <p>
                <span class='abstract-sessiontype'>Lightning Talk</span>                von <span class='abstract-speakers'>Johannes Kröger</span></p>
                                                                            <p><span class='abstract-time-heading'>Zeit: </span>Montag 07. Juni 17:00 Uhr
                <br><span class='abstract-room-heading'>Ort: </span>Bühne 2
                <br><span class='abstract-room-heading'>Dauer: </span>5 Minuten
            </p>

                        
            <p>Ich erzähle kurz zum aktuellen Stand der Dinge in meinen <a href="https://fragdenstaat.de/anfrage/digitales-oberflachenmodell/">Bestrebungen amtliche LiDAR-Daten bzw. das digitale Oberflächenmodell der Stadt Hamburg über das Hamburgische Transparenzgesetz zu befreien</a>.</p>
<p>Stand Februar 2021 liegt der Fall dank <a href="https://www.fossgis.de/wiki/F%C3%B6rderantr%C3%A4ge/LGV_vs._Transparenzgesetz">Unterstützung durch den FOSSGIS e.V.</a> beim Rechtsamt der Behörde für Stadtentwicklung und Wohnen. Die dortige Bearbeitung des Falls wurde wegen der aktuellen Belastungslage verzögert und für das Frühjahr 2021 versprochen.</p>
<p>Der dritte Teil der LiDAR-Trilogie nach <a href="https://pretalx.com/fossgis2019/talk/MNKP8V/">Leider kein LiDAR?</a> (2019) und <a href="https://pretalx.com/fossgis2020/talk/RQMALK/">Leider immer noch kein LiDAR?</a>.</p>
        </section>


	<?php include "../inc/footer.inc"; ?>

</body>

</html>