<!doctype html>
<html lang="de">

<head>
	<?php include "../inc/meta.inc"; ?>

	<base href="<?php echo dirname($_SERVER['SCRIPT_NAME']); ?>">
	<title>Die Nutzung öffentlicher Geodaten in OpenStreetMap am Beispiel Land Brandenburg – FOSSGIS 2021</title>

	<link rel="stylesheet" href="./css/normalize.css">
	<link rel="stylesheet" href="./css/base.css">
	<link rel="stylesheet" href="./css/print.css" media="print">
</head>

<body id="programm">
	<?php include "../inc/header.inc"; ?>

        <!-- This file was generated by a script. Do not edit this file in Git,
             edit contents in Pretalx, regenerate the PHP files and commit them
             in the Git repository of the website. -->
        <p><a href="programm/mittwoch.php#session_MVPR79">&#9668;&#9668; zurück zum Programm</a> <a href="sessions/lightning_talks_4.php">&#9668; zurück zur Session</a></p>
        <h2 class='abstract-title'>Die Nutzung öffentlicher Geodaten in OpenStreetMap am Beispiel Land Brandenburg</h2>
        <section>
            <p>
                <span class='abstract-sessiontype'>Lightning Talk</span>                von <span class='abstract-speakers'>Christopher Lorenz</span></p>
                                                                            <p><span class='abstract-time-heading'>Zeit: </span>Mittwoch 09. Juni 12:00 Uhr
                <br><span class='abstract-room-heading'>Ort: </span>Bühne 1
                <br><span class='abstract-room-heading'>Dauer: </span>5 Minuten
            </p>

                        
            <p>Seit dem Jahr 2020 gibt es die Möglichkeiten Daten der Landesvermessung und Geobasisinformation Brandenburg zu nutzen. Dieser kurze Talk zeigt den Weg dorthin und sollte als Vorlage für andere Behörden oder Datenanbieter genutzt werden. 
Es wird dargestellt, wie im der lokalen Community zusammengearbeitet wurde und wie eine Nutzung trotz inkompatibler Lizenz "Datenlizenz Deutschland 2.0 Namensnennung dl/de/by-2.0" in OpenStreetMap möglich wurde.</p>
        </section>


	<?php include "../inc/footer.inc"; ?>

</body>

</html>