<!doctype html>
<html lang="de">

<head>
	<?php include "../inc/meta.inc"; ?>

	<base href="<?php echo dirname($_SERVER['SCRIPT_NAME']); ?>">
	<title>Tricks und Kniffe rund um den QGIS-Atlas – FOSSGIS 2021</title>

	<link rel="stylesheet" href="./css/normalize.css">
	<link rel="stylesheet" href="./css/base.css">
	<link rel="stylesheet" href="./css/print.css" media="print">
</head>

<body id="programm">
	<?php include "../inc/header.inc"; ?>

        <!-- This file was generated by a script. Do not edit this file in Git,
             edit contents in Pretalx, regenerate the PHP files and commit them
             in the Git repository of the website. -->
        <p><a href="programm/dienstag.php#session_N9X9CB">&#9668;&#9668; zurück zum Programm</a> </p>
        <h2 class='abstract-title'>Tricks und Kniffe rund um den QGIS-Atlas</h2>
        <section>
            <p>
                <span class='abstract-sessiontype'>Demo-Session</span>                von <span class='abstract-speakers'>Claas Leiner</span></p>
                                                                            <p><span class='abstract-time-heading'>Zeit: </span>Dienstag 08. Juni 14:00 Uhr
                <br><span class='abstract-room-heading'>Ort: </span>Bühne 4
                <br><span class='abstract-room-heading'>Dauer: </span>55 Minuten
            </p>

                        
            <p>Ein einfacher QGIS-Atlas ist schnell erstellt. 
Die präzise Steuerung von Blattschnitten, Seitenformaten, Drehungen, Beschriftungen, Sichtbarkeiten etc. ist nicht so ganz trivial. Die Demo-Session stellt einige Kniffe vor, mit denen sich  die Möglichkeiten des Atlas umfassend nutzen lassen.</p>
<p>Der QGIS-Atlas ist ein unfassbar umfangreiches Werkzeug, um Kartenserien oder Objekt-Berichte zu erstellen.  Die Demo-Session stellt einige Kniffe vor, mit denen sich  Möglichkeiten des Atlas umfassend nutzen lassen,
- Blattschnitt-Layer oder Geometrieobjekte als Abdeckungslayer?
- Blattschnitte für beliebige Maßstäbe und Papierformate über eine Modellertool erstellen.
- Drehung von Blattschnitte, die Trassen oder Flüssen folgen.
- Seitenausrichtung und Format anhand der Geometrie und Ausrichtung von Atlasobjekten steuern.
- Beziehungen zu verknüpften Layern auswerten.
- Atlas-Variablen verwenden.
- Sichtbarkeit von Layern und Atlas-Objekten über regelbasierte Darstellung und Kartenthemen 
  steuern
- etc.</p>
        <div class='abstract-bio'>
            <h3 class='abstract-bio-name'>Claas Leiner</h3>
            <p>Claas Leiner arbeitet miit seinem Büro GKG freiberuflich in Kassel und bietet Schulungen, Dienstleistungen und Support rund um die freien Geoinformationssysteme QGIS, GRASS, SpatiaLite, Postgis sowie GDAL/OGR an. Desweiteren bearbeitet er Aufträge zu Geodatenaufbereitung, -analysen und thematische Kartografie. Besonders verbunden ist er mit QGIS - als Mitglied des QGIS-Anwendervereins QGIS-DE, als Mitorganisator der QGIS-Anwendertreffen 2011 - 2018 sowie als Bronze-Sponsor des Projektes.</p>
        </div>
        </section>


	<?php include "../inc/footer.inc"; ?>

</body>

</html>