<!doctype html>
<html lang="de">

<head>
	<?php include "../inc/meta.inc"; ?>

	<base href="<?php echo dirname($_SERVER['SCRIPT_NAME']); ?>">
	<title>20 Jahre PostGIS - dazu 20 hilfreiche Tipps zu PostGIS und Neuigkeiten rund um das Projekt – FOSSGIS 2021</title>

	<link rel="stylesheet" href="./css/normalize.css">
	<link rel="stylesheet" href="./css/base.css">
	<link rel="stylesheet" href="./css/print.css" media="print">
</head>

<body id="programm">
	<?php include "../inc/header.inc"; ?>

        <!-- This file was generated by a script. Do not edit this file in Git,
             edit contents in Pretalx, regenerate the PHP files and commit them
             in the Git repository of the website. -->
        <p><a href="programm/montag.php#session_NL3FAN">&#9668;&#9668; zurück zum Programm</a> </p>
        <h2 class='abstract-title'>20 Jahre PostGIS - dazu 20 hilfreiche Tipps zu PostGIS und Neuigkeiten rund um das Projekt</h2>
        <section>
            <p>
                <span class='abstract-sessiontype'>Langer Vortrag</span>                von <span class='abstract-speakers'>Astrid Emde</span></p>
                                                                            <p><span class='abstract-time-heading'>Zeit: </span>Montag 07. Juni 16:00 Uhr
                <br><span class='abstract-room-heading'>Ort: </span>Bühne 3
                <br><span class='abstract-room-heading'>Dauer: </span>40 Minuten
            </p>

                        
            <p>Mit PostGIS 3.1 hat sich auch die GEOS Version geändert und hexagonale und quadratische Grids können erstellt werden. Dann geht der Blick ins Umfeld von PostGIS und die zwei Softwareprojeke pg_tileserv und pg_featureserv werden vorgestellt.</p>
        <div class='abstract-bio'>
            <h3 class='abstract-bio-name'>Astrid Emde</h3>
            <img class='abstract-speaker-avatar' src='/2021/avatars/XTSTXB.jpg'>            <p>Astrid Emde war bisher bei allen FOSSGIS-Konferenzen dabei und freut sich auf die FOSSGIS 2021 in Rapperswil oder auch Online!</p>
<p>Sie befasst sich seit vielen Jahren mit Geodaten und FOSSGIS und hat schon zahlreiche Projekte vor allem im WebGIS-Bereich umgesetzt.</p>
<p>Sie weist Erfahrung mit PostgreSQL und PostGIS, MapServer, GeoServer, QGIS, QGIS Server und Mapbender auf. Weiterhin Apache Solr, OpenLayers, MapProxy, OGC Standards &amp; Skripting.</p>
<p>Astrid Emde arbeitet bei der WhereGroup in Bonn und hat schon viele Workshops und Präsentationen zu Mapbender, MapServer, GeoServer, PostgreSQL/PostGIS, OWS oder allgemein zum Aufbau einer GDI gehalten. Sie ist Dozentin der [FOSS Academy] (https://www.foss-academy.com), dem Schulungsinstitut der WhereGroup (https://www.wheregroup.com)</p>
<p>Seit über 10 Jahren engagiert sie sich im Mapbender-Projekt und gehört zum Mapbender Team (http://mapbender.org) und dem Mapbender PSC (Project Steering Committee).</p>
<p>Astrid Emde ist in der OSGeo Foundation (http://osgeo.org) aktiv. Sie ist 2010 zum Charter Member und 2017 in das OSGeo Board of Directors (Vorstand der OSGeo) und zur OSGeo Secretary gewählt worden. Dadurch übernimmt sie zahlreiche Aufgaben bei der OSGeo und ist darüber hinaus im Bereich Marketing, Presse, Community Meetings und OSGeoLive (http://live.osgeo.org/) aktiv. 2018 erhielt sie für ihr Engagement den Sol Katz Award der OSGeo.</p>
<p>Auch im FOSSGIS e.V. ist Astrid Emde aktiv. Sie gehört zum Team der jährlich stattfindenden FOSSGIS-Konferenz, engagiert sich in der Vereins-Öffentlichkeitsarbeit und der Organisation von Community Events (http://fossgis.de).</p>
        </div>
        </section>


	<?php include "../inc/footer.inc"; ?>

</body>

</html>