<!doctype html>
<html lang="de">

<head>
	<?php include "../inc/meta.inc"; ?>

	<base href="<?php echo dirname($_SERVER['SCRIPT_NAME']); ?>">
	<title>Effizientes many-to-many ÖPNV-Routing mit gtfsrouter – FOSSGIS 2021</title>

	<link rel="stylesheet" href="./css/normalize.css">
	<link rel="stylesheet" href="./css/base.css">
	<link rel="stylesheet" href="./css/print.css" media="print">
</head>

<body id="programm">
	<?php include "../inc/header.inc"; ?>

        <!-- This file was generated by a script. Do not edit this file in Git,
             edit contents in Pretalx, regenerate the PHP files and commit them
             in the Git repository of the website. -->
        <p><a href="programm/mittwoch.php#session_PPWVU8">&#9668;&#9668; zurück zum Programm</a> </p>
        <h2 class='abstract-title'>Effizientes many-to-many ÖPNV-Routing mit gtfsrouter</h2>
        <section>
            <p>
                <span class='abstract-sessiontype'>Vortrag</span>                von <span class='abstract-speakers'>mark padgham</span></p>
                                                                            <p><span class='abstract-time-heading'>Zeit: </span>Mittwoch 09. Juni 09:00 Uhr
                <br><span class='abstract-room-heading'>Ort: </span>Bühne 3
                <br><span class='abstract-room-heading'>Dauer: </span>20 Minuten
            </p>

                        
            <p>gtfsrouter ist ein FOSS-Package für das Routing mit "General Transport Feed Specification" (GTFS) Daten. Das Package ist in der Sprache R geschrieben, mit hocheffizienten C++-Algorithmen. Dieser Vortrag wird zwei der besonderen Aspekte des gtfsrouter-Pakets vorstellen. Der erste ist die Fähigkeit, Transfer-Tabellen zu konstruieren, die benötigt werden, um die erwarteten Zeiten für den Transfer zwischen den verschiedenen Haltestellen innerhalb eines Transportsystems zu spezifizieren. Viele Feeds verfügen nicht über diese Tabellen, so dass sie nicht für Routing-Abfragen verwendet werden können. Die Fähigkeit, Umsteigetabellen zu erstellen, ermöglicht es auch, Feeds miteinander zu verbinden, was für Städte wichtig ist, in denen verschiedene Verkehrsbetriebe unabhängige Feeds bereitstellen. Der Vortrag wird sich hauptsächlich auf einen zweiten Aspekt des gtfsrouter-Programms konzentrieren, nämlich eine hocheffiziente Many-to-Many-Routing-Engine. Many-to-many-Routing mit Fahrplandaten wie GTFS-Daten unterscheidet sich stark von konventionellem Routing durch statische Netzwerke wie Straßen, und es gibt nur sehr wenige FOSS-Lösungen für solche Abfragen, so dass viele Entwickler versuchen, effiziente Lösungen durch Parallelisierung von One-to-One-Abfragen mit opentripplanner zu finden. Solche Lösungen sind jedoch zu langsam für effiziente Lösungen im großen Maßstab, da sie zum Beispiel viele Stunden oder sogar Tage benötigen, um die Fahrzeiten zwischen allen Bahnhofspaaren in Berlin abzufragen. Der neue gtfsrouter-Algorithmus reduziert die Berechnungszeiten auf Minuten statt auf Stunden und bietet Städten die Möglichkeit, umfassende Übersichten über ihr gesamtes Verkehrssystem zu erstellen.</p>
        </section>


	<?php include "../inc/footer.inc"; ?>

</body>

</html>