<!doctype html>
<html lang="de">

<head>
	<?php include "../inc/meta.inc"; ?>

	<base href="<?php echo dirname($_SERVER['SCRIPT_NAME']); ?>">
	<title>Massenkonvertieren kartographischer Stildokumente mit GeoStyler-CLI – FOSSGIS 2021</title>

	<link rel="stylesheet" href="./css/normalize.css">
	<link rel="stylesheet" href="./css/base.css">
	<link rel="stylesheet" href="./css/print.css" media="print">
</head>

<body id="programm">
	<?php include "../inc/header.inc"; ?>

        <!-- This file was generated by a script. Do not edit this file in Git,
             edit contents in Pretalx, regenerate the PHP files and commit them
             in the Git repository of the website. -->
        <p><a href="programm/dienstag.php#session_QVK8J8">&#9668;&#9668; zurück zum Programm</a> <a href="sessions/lightning_talks_2.php">&#9668; zurück zur Session</a></p>
        <h2 class='abstract-title'>Massenkonvertieren kartographischer Stildokumente mit GeoStyler-CLI</h2>
        <section>
            <p>
                <span class='abstract-sessiontype'>Lightning Talk</span>                von <span class='abstract-speakers'>Christian Mayer</span></p>
                                                                            <p><span class='abstract-time-heading'>Zeit: </span>Dienstag 08. Juni 10:00 Uhr
                <br><span class='abstract-room-heading'>Ort: </span>Bühne 1
                <br><span class='abstract-room-heading'>Dauer: </span>5 Minuten
            </p>

                        
            <p>Das Problem: Kartenstile existieren in vielen verschiedenen (zum Teil nicht standardisierten) Formaten und erschweren die Weiterentwicklung hin zu modernen Technologien. Wo möglich, sollte deshalb auf Standards gesetzt werden. Wie kann jedoch die Fülle an Stilformationen gebändigt werden und was wenn wenn der Datenbestand zu groß ist, um diesen manuell in ein standardisiertes Format zu überführen?</p>
<p>Die Lösung: GeoStyler-CLI. In diesem Talk wird live gezeigt, wie mit diesem Tool innerhalb weniger Minuten große Bestände von kartographischen Stildokumenten automatisiert konvertiert werden können.</p>
        </section>


	<?php include "../inc/footer.inc"; ?>

</body>

</html>