<!doctype html>
<html lang="de">

<head>
	<?php include "../inc/meta.inc"; ?>

	<base href="<?php echo dirname($_SERVER['SCRIPT_NAME']); ?>">
	<title>Soziale Medien, dezentrale Netzwerke und OpenStreetMap – FOSSGIS 2021</title>

	<link rel="stylesheet" href="./css/normalize.css">
	<link rel="stylesheet" href="./css/base.css">
	<link rel="stylesheet" href="./css/print.css" media="print">
</head>

<body id="programm">
	<?php include "../inc/header.inc"; ?>

        <!-- This file was generated by a script. Do not edit this file in Git,
             edit contents in Pretalx, regenerate the PHP files and commit them
             in the Git repository of the website. -->
        <p><a href="programm/montag.php#session_QWFKTH">&#9668;&#9668; zurück zum Programm</a> <a href="sessions/lightning_talks_1.php">&#9668; zurück zur Session</a></p>
        <h2 class='abstract-title'>Soziale Medien, dezentrale Netzwerke und OpenStreetMap</h2>
        <section>
            <p>
                <span class='abstract-sessiontype'>Lightning Talk</span>                von <span class='abstract-speakers'>pukkamustard</span></p>
                                                                            <p><span class='abstract-time-heading'>Zeit: </span>Montag 07. Juni 17:05 Uhr
                <br><span class='abstract-room-heading'>Ort: </span>Bühne 2
                <br><span class='abstract-room-heading'>Dauer: </span>5 Minuten
            </p>

                        
            <p>Das Internet schafft neue Möglichkeiten für partizipatives Kreieren und Kurieren von Wissen. Allerdings wird das Medium von grossen, kommerziellen Anbietern dominiert.</p>
<p>Kleine politische Gemeinden in der Schweiz und lokale Organisationen die sich für gemeinwohlorientierte Lebensweisen einsetzen sind vom Internet abgehängt. Entweder es muss zu Kosten der Datensicherheit und Datensouveränität auf kommerzielle Anbieter vertraut werden oder das zu erfassende Wissen passt schlichtweg nicht in das Schema von Google oder Facebook.</p>
<p>Im Rahmen der <a href="https://openengiadina.net/">openEngiadina</a> und <a href="https://dream.public.cat/">DREAM</a> Projekte erforschen und entwickeln wir Ideen und Technologien um einen nachhaltigen, sicheren und offenen Austausch über lokales Wissen zu ermöglichen. Kartographische Daten spielen dabei eine zentrale Rolle.</p>
<p>In diesem Vortrag möchten wir über die Projekte openEngiadina und DREAM berichten. Wir beschreiben die Anwendungen und unsere technischen Ansätze dafür, zum Beispiel die Verwendung von OpenStreetMap Daten als Linked Data, das Zusammenspiel mit dem ActivityPub Protokoll für dezentrale Soziale Netwzerke und die Anfragesprache Datalog.</p>
        </section>


	<?php include "../inc/footer.inc"; ?>

</body>

</html>