<!doctype html>
<html lang="de">

<head>
	<?php include "../inc/meta.inc"; ?>

	<base href="<?php echo dirname($_SERVER['SCRIPT_NAME']); ?>">
	<title>Baremaps: Kontextuelles Mapping in unerforschten Gebieten – FOSSGIS 2021</title>

	<link rel="stylesheet" href="./css/normalize.css">
	<link rel="stylesheet" href="./css/base.css">
	<link rel="stylesheet" href="./css/print.css" media="print">
</head>

<body id="programm">
	<?php include "../inc/header.inc"; ?>

        <!-- This file was generated by a script. Do not edit this file in Git,
             edit contents in Pretalx, regenerate the PHP files and commit them
             in the Git repository of the website. -->
        <p><a href="programm/dienstag.php#session_RAUJWM">&#9668;&#9668; zurück zum Programm</a> </p>
        <h2 class='abstract-title'>Baremaps: Kontextuelles Mapping in unerforschten Gebieten</h2>
        <section>
            <p>
                <span class='abstract-sessiontype'>Demo-Session</span>                von <span class='abstract-speakers'>Andrea Borghi</span></p>
                                                                            <p><span class='abstract-time-heading'>Zeit: </span>Dienstag 08. Juni 11:00 Uhr
                <br><span class='abstract-room-heading'>Ort: </span>Bühne 4
                <br><span class='abstract-room-heading'>Dauer: </span>55 Minuten
            </p>

                        
            <p>Heute wird die Veröffentlichung kontextbezogener Karten den Teams von Softwareingenieuren und Datenwissenschaftlern überlassen. Infolgedessen betreiben nur wenige Unternehmen (z. B. Google, Mapbox, Esri, Klokan) Pipelines zur Veröffentlichung solcher Karten und adressieren dabei die Bedürfnisse des Massenmarktes (z. B. Suche, Transport, Spiel), zum Nachteil der Nischenanbieter (z. B. Tiefbauunternehmen, Katastervermessungsbüros). Baremaps geht dieses Problem der Zugänglichkeit an, indem es DevOps-Praktiken für den Bereich der Geomatik nutzt und es Ingenieuren ermöglicht, Datenverarbeitungspipelines auf ihrem Desktop-Computer zu prototypisieren und sie mühelos in der Cloud einzusetzen. Wir glauben, dass die weitgehende Verfügbarkeit der kontextuellen Kartenabstraktion entscheidend ist, um Innovationen in unerforschten Bereichen (z. B. Stadtplanung) zu fördern. Baremaps ist unter der sehr freizügigen Apache 2 Lizenz veröffentlicht.
Tiling ist eine grundlegende Komponente des Web-Mappings, die es ermöglicht, nur die Daten herunterzuladen, die im Viewport des Benutzers angezeigt werden. Im Gegensatz zu Bitmaps werden Vektorkacheln auf dem Gerät des Nutzers gerendert, was es ermöglicht, dass sich Karten an den Kontext der Nutzer anpassen (z.B. Strassenkarten vs. öV-Karten) und sich dynamisch anpassen, wenn sich der Kontext ändert (z.B. beim Betreten eines Gebäudes). Edge Computing bringt die Daten physisch näher an den Benutzer heran, was die Latenzzeit reduziert und bei einer kontextbezogenen Karte die Benutzerfreundlichkeit verbessert.
Baremaps baut auf OpenStreetMap auf und verfügt über einen effizienten und parallelisierten Datenimporter von pbf nach postgis, der es erlaubt, benutzerdefinierte Transformationen (z.B. Geometrievereinfachungen) direkt beim Import der Daten in postgis hinzuzufügen.
Ein Webkartograph kann mit Baremaps sowohl seinen Stil als auch den Dateninhalt gleichzeitig entwickeln, indem er den eingebetteten Entwicklungsserver nutzt, um ein optimales Endergebnis zu erzielen.
Am Ende werden nur die Daten, die der Stil benötigt, verwendet und in die generierten Kacheln importiert. Die endgültigen Kacheln können vom Tiling-Prozessor nativ in Cloud-Umgebungen exportiert werden.</p>
<p>In dieser Demo zeigen wir, wie Baremaps für folgende Funktionen verwendet werden kann, um:
- Dynamische Bearbeitung von Daten und Stil (Anpassung)
- Parallelisierter Import
- Parallelisierter Export
- Kacheln in der Cloud veröffentlichen (s3://)
- Kacheln in einem produktiven Setup zu verwenden</p>
<p>Wir zeigen dabei als Beispiel openstreetmap-vecto, das auf Baremaps basiert.</p>
<p>Github Link: https://github.com/baremaps/baremaps</p>
        </section>


	<?php include "../inc/footer.inc"; ?>

</body>

</html>