<!doctype html>
<html lang="de">

<head>
	<?php include "../inc/meta.inc"; ?>

	<base href="<?php echo dirname($_SERVER['SCRIPT_NAME']); ?>">
	<title>Einführung in OpenStreetMap – FOSSGIS 2021</title>

	<link rel="stylesheet" href="./css/normalize.css">
	<link rel="stylesheet" href="./css/base.css">
	<link rel="stylesheet" href="./css/print.css" media="print">
</head>

<body id="programm">
	<?php include "../inc/header.inc"; ?>

        <!-- This file was generated by a script. Do not edit this file in Git,
             edit contents in Pretalx, regenerate the PHP files and commit them
             in the Git repository of the website. -->
        <p><a href="programm/montag.php#session_S7P93Z">&#9668;&#9668; zurück zum Programm</a> </p>
        <h2 class='abstract-title'>Einführung in OpenStreetMap</h2>
        <section>
            <p>
                <span class='abstract-sessiontype'>Vortrag</span>                von <span class='abstract-speakers'>Thomas Skowron</span></p>
                                                                            <p><span class='abstract-time-heading'>Zeit: </span>Montag 07. Juni 11:30 Uhr
                <br><span class='abstract-room-heading'>Ort: </span>Bühne 3
                <br><span class='abstract-room-heading'>Dauer: </span>20 Minuten
            </p>

                        
            <p>Für alle, die neu sind in der Welt der kollaborativen Weltkarte oder das Projekt eine Weile aus den Augen verloren haben, empfiehlt sich diese Session: Es wird gezeigt, woher OpenStreetMap kommt, wem es hilft und wo es hingeht.</p>
        <div class='abstract-bio'>
            <h3 class='abstract-bio-name'>Thomas Skowron</h3>
            <img class='abstract-speaker-avatar' src='/2021/avatars/9QQ9DG.jpg'>            <p>Thomas Skowron ist freier Softwareentwickler aus Köln. Er entwickelt GIS-Anwendungen mit und berät zum Einsatz von OpenStreetMap, zudem ist er Maintainer von ein paar Open Source-Projekten, unter anderem dem "OpenStreetMap Calendar".</p>
<p>Zu OpenStreetMap ist er 2011 gestoßen, hat auf etlichen Konferenzen Vorträge zum Thema OSM gehalten und in letzten Jahren vermehrt mit Vector Tile-Technologie gearbeitet.</p>
        </div>
        </section>


	<?php include "../inc/footer.inc"; ?>

</body>

</html>