<!doctype html>
<html lang="de">

<head>
	<?php include "../inc/meta.inc"; ?>

	<base href="<?php echo dirname($_SERVER['SCRIPT_NAME']); ?>">
	<title>Geo Engine: Explorative Datenanalyse mit raum-zeitlicher Workflowverarbeitung – FOSSGIS 2021</title>

	<link rel="stylesheet" href="./css/normalize.css">
	<link rel="stylesheet" href="./css/base.css">
	<link rel="stylesheet" href="./css/print.css" media="print">
</head>

<body id="programm">
	<?php include "../inc/header.inc"; ?>

        <!-- This file was generated by a script. Do not edit this file in Git,
             edit contents in Pretalx, regenerate the PHP files and commit them
             in the Git repository of the website. -->
        <p><a href="programm/dienstag.php#session_UKLUGE">&#9668;&#9668; zurück zum Programm</a> </p>
        <h2 class='abstract-title'>Geo Engine: Explorative Datenanalyse mit raum-zeitlicher Workflowverarbeitung</h2>
        <section>
            <p>
                <span class='abstract-sessiontype'>Vortrag</span>                von <span class='abstract-speakers'>Christian Beilschmidt</span></p>
                                                                            <p><span class='abstract-time-heading'>Zeit: </span>Dienstag 08. Juni 14:00 Uhr
                <br><span class='abstract-room-heading'>Ort: </span>Bühne 1
                <br><span class='abstract-room-heading'>Dauer: </span>20 Minuten
            </p>

                        
            <p>Die Geo Engine ist eine Plattform, die die Integration und die effiziente Verarbeitung raum-zeitlicher Daten bündelt und neueste Visualisierungs- und Analysemethoden intuitiv erschließt. Dies ermöglicht es Forschungsgruppen und Unternehmen, bisher ungenutzte Potenziale zu erschließen. Perspektivisch bieten wir die Plattform als cloud-basierten Dienst an und integrieren derzeit eine Deep-Learning-Anbindung.</p>
<p>Die Entwicklung basiert auf Forschungsergebnissen aus dem Bereich raum-zeitlicher Datenverarbeitung, die gebündelt im sog. VAT-System zusammengefasst wurden, wobei VAT für Visualisierung, Analyse und Transformation steht. Es wird derzeit in wissenschaftlichen Projekten eingesetzt, die sich auf die Umwelt- und Biodiversitätsmonitoring konzentrieren, wo es native Zeitreihenverarbeitung, die Kombination von Raster- und Vektordaten und eine Benutzeroberfläche bietet, die verknüpfte Ansichten zwischen Karten, Tabellen und Plots bietet. Darüber hinaus ermöglicht unsere Technologie die Erstellung maßgeschneiderter Apps, zum Beispiel für web-basierten Lernplattformen und Projektportale.</p>
<p>In diesem Vortrag zeigen wir die Grundlagen des Systems und dessen Eigenschaften auf. Dies illustrieren wir anhand von Beispielen aus bisherigen Projekten aus der Forschung. Zudem bieten wir einen Ausblick für die Geo Engine über die zukünftige Integration von Deep Learning und zeigen Einsatzmöglichkeiten für Projekte verschiedenster Art auf.</p>
        <div class='abstract-bio'>
            <h3 class='abstract-bio-name'>Christian Beilschmidt</h3>
            <img class='abstract-speaker-avatar' src='/2021/avatars/J3QWFM.jpg'>            <p>Christian Beilschmidt ist Informatiker und forschte während seiner Promotionszeit an der Philipps-Universität Marburg im Bereich Geo-Datenprozessierung und Machine Learning-Verfahren für die Aggregation raum-zeitlicher Daten. Er war zudem innerhalb von Projekten zu Biodiversitäts- und Umweltmonitoring maßgeblich an der Entwicklung einer web-basiertes Plattform zur raum-zeitlichen Verarbeitung, explorativen Analyse und Visualisierung von Big Spatial Data beteiligt. Derzeit arbeitet er im EXIST-Forschungstransfer-Projekt Geo Engine an einem Start-up, das diese Plattform zu einen cloud-basierten Dienst weiterentwickelt, der die Integration und die effiziente Verarbeitung raum-zeitlicher Daten bündelt und neueste Visualisierungs- und Analysemethoden, wie Deep-Learning, intuitiv erschließt.</p>
        </div>
        </section>


	<?php include "../inc/footer.inc"; ?>

</body>

</html>