<!doctype html>
<html lang="de">

<head>
	<?php include "../inc/meta.inc"; ?>

	<base href="<?php echo dirname($_SERVER['SCRIPT_NAME']); ?>">
	<title>3D-Punktwolken und Usability – FOSSGIS 2021</title>

	<link rel="stylesheet" href="./css/normalize.css">
	<link rel="stylesheet" href="./css/base.css">
	<link rel="stylesheet" href="./css/print.css" media="print">
</head>

<body id="programm">
	<?php include "../inc/header.inc"; ?>

        <!-- This file was generated by a script. Do not edit this file in Git,
             edit contents in Pretalx, regenerate the PHP files and commit them
             in the Git repository of the website. -->
        <p><a href="programm/dienstag.php#session_UVJ8N9">&#9668;&#9668; zurück zum Programm</a> </p>
        <h2 class='abstract-title'>3D-Punktwolken und Usability</h2>
        <section>
            <p>
                <span class='abstract-sessiontype'>Vortrag</span>                von <span class='abstract-speakers'>Güren Tan Dinga</span></p>
                                                                            <p><span class='abstract-time-heading'>Zeit: </span>Dienstag 08. Juni 17:00 Uhr
                <br><span class='abstract-room-heading'>Ort: </span>Bühne 1
                <br><span class='abstract-room-heading'>Dauer: </span>20 Minuten
            </p>

                        
            <p>Arbeitsabläufe zur Erfassung von 3D-Daten durch Laserscanner oder die Erzeugung von 3D-Punktwolken mit photogrammetrischen Verfahren sind seit einigen Jahren etabliert. Die Erfassung komplexer Formen und Szenen erfordern eine hochauflösende Erfassung, welche durch Punktwolken mit mehreren Milliarden Punkten zu einem hohen Datenvolumen führen. Diese wiederum erfordern performante Hardware zur Verarbeitung und Visualisierung. Weitere Herausforderungen liegen in der Visualisierung für Endverbraucher, die Weitergabe der Daten sowie die Ausgabeformate zustande. Während triangulierte 3D-Modelle als Alternative herangezogen werden können, führen diese bei einer zu geringen Punktdichte zu wenig repräsentativen Modellen. Aktuell in Entwicklung befindliche Software aus dem Open-Source Bereich ist meist nicht an Nutzergruppen angepasst, bietet aber -vor allem durch Eigeninitiative- bereits Möglichkeiten und Ansätze, den Kompromiss zwischen Visualisierung und Weitergabe zu schaffen.</p>
<p>Im Rahmen des Vortrags sollen mit PotreeConverter und PotreeViewer zwei Anwendungen aus dem OpenSource Bereich vorgestellt werden, die in Kombination mit einem simplen FrontEnd das Potential bergen, 3D-Punktwolken zugänglicher zu machen. Durch Anpassungen am Viewer können außerdem unterschiedliche Nutzergruppen bedient werden (bspw. mobile Anwender, deren Web-Ansicht der Punktwolke so vorkonfiguriert ist, dass Punktwolken nur in Ausschnitten geladen werden, sodass Datenvolumen eingespart werden kann).</p>
        <div class='abstract-bio'>
            <h3 class='abstract-bio-name'>Güren Tan Dinga</h3>
            <img class='abstract-speaker-avatar' src='/2021/avatars/UUD8SP.jpg'>            <ul>
<li>Wissenschaftlicher Mitarbeiter im <a href="http://www.geomatik-hamburg.de/g2lab/">g2lab</a> der HafenCity Universität Hamburg</li>
<li>Remote Sensing und Data Science mit Python als Arbeitsgebiete</li>
</ul>
        </div>
        </section>


	<?php include "../inc/footer.inc"; ?>

</body>

</html>