<!doctype html>
<html lang="de">

<head>
	<?php include "../inc/meta.inc"; ?>

	<base href="<?php echo dirname($_SERVER['SCRIPT_NAME']); ?>">
	<title>QGIS GRASS Plugin – FOSSGIS 2021</title>

	<link rel="stylesheet" href="./css/normalize.css">
	<link rel="stylesheet" href="./css/base.css">
	<link rel="stylesheet" href="./css/print.css" media="print">
</head>

<body id="programm">
	<?php include "../inc/header.inc"; ?>

        <!-- This file was generated by a script. Do not edit this file in Git,
             edit contents in Pretalx, regenerate the PHP files and commit them
             in the Git repository of the website. -->
        <p><a href="programm/mittwoch.php#session_VLZRZP">&#9668;&#9668; zurück zum Programm</a> </p>
        <h2 class='abstract-title'>QGIS GRASS Plugin</h2>
        <section>
            <p>
                <span class='abstract-sessiontype'>Workshop</span>
                                von <span class='abstract-speakers'>Klaus Mithöfer</span></p>
                <p class='abstract-is-workshop'>Bitte melden Sie sich im <a href="https://pretix.eu/fossgis/2021/">Ticketshop</a> für diesen Workshop an, wenn Sie daran teilnehmen möchten.</p>                                                <p class='abstract-is-workshop'>Sie erhalten in der Woche vor der Konferenz eine E-Mail mit detaillierten Informationen zum Workshop sowie die Möglichkeit in einem Termin Ihre Technik auszuprobieren.</p>            <p><span class='abstract-time-heading'>Zeit: </span>Mittwoch 09. Juni 14:00 Uhr
                <br><span class='abstract-room-heading'>Ort: </span>Workshop 1
                <br><span class='abstract-room-heading'>Dauer: </span>90 Minuten
            </p>

                        
            <p>GRASS GIS ist ein insbesondere für die Datenanalyse eine sehr umfangreiche Software mit raster- und vektororientierten Funktionen. GARSS GIS lässt sich sehr effektiv aus QGIS heraus über das GRASS Plugin nutzen. Der Workshop bieten Ihnen einen Einsteig in das Arbeiten mit GRASS. Im Workshop lernen das GRASS Konzept kennen und erstellen eine Projektdatenbank. Sie importieren ausgewählte Daten und lerne einzelne Werkzeuge zur Analyse von Raster- und Vektordaten kennen und exportieren die Ergebnisse. </p>
<p>Grundlegende Themen sind u.A.:
    • Überblick zur GRASS GIS Integration in QGIS
    • Aufbau einer GRASS GIS Projektumgebung
    • Import und Export von Raster- und Vektordaten
    • Werkzeuge von Raster- und Vektordaten</p>
        <div class='abstract-bio'>
            <h3 class='abstract-bio-name'>Klaus Mithöfer</h3>
            <img class='abstract-speaker-avatar' src='/2021/avatars/ST3EE7_klaus_MdEwTkX.jpeg'>            <p>Ich bin Geograf und Geoinformatiker und habe zu beginn meiner Karriere im Bereich Bodendaten und Bodenfunktionsbewertung mit GIS gearbeitet und meinen Fokus zunehmend auf Geoinformatik und Open Source GIS gesetzt. Nach einem Auslandsaufenthalt arbeite ich seit 2016 beim Geoinformatikbüro Dassau mit QGIS, GRASS GIS und PostGIS im Schwerpunkt Datenanalyse und Schulung.</p>
        </div>
        </section>


	<?php include "../inc/footer.inc"; ?>

</body>

</html>