<!doctype html>
<html lang="de">

<head>
	<?php include "../inc/meta.inc"; ?>

	<base href="<?php echo dirname($_SERVER['SCRIPT_NAME']); ?>">
	<title>react-geo - Mapping mit React – FOSSGIS 2021</title>

	<link rel="stylesheet" href="./css/normalize.css">
	<link rel="stylesheet" href="./css/base.css">
	<link rel="stylesheet" href="./css/print.css" media="print">
</head>

<body id="programm">
	<?php include "../inc/header.inc"; ?>

        <!-- This file was generated by a script. Do not edit this file in Git,
             edit contents in Pretalx, regenerate the PHP files and commit them
             in the Git repository of the website. -->
        <p><a href="programm/dienstag.php#session_WGCDEH">&#9668;&#9668; zurück zum Programm</a> </p>
        <h2 class='abstract-title'>react-geo - Mapping mit React</h2>
        <section>
            <p>
                <span class='abstract-sessiontype'>Workshop</span>
                                von <span class='abstract-speakers'>Jan Suleiman, Daniel Koch</span></p>
                <p class='abstract-is-workshop'>Bitte melden Sie sich im <a href="https://pretix.eu/fossgis/2021/">Ticketshop</a> für diesen Workshop an, wenn Sie daran teilnehmen möchten.</p>                                <p class='abstract-is-workshop'>In diesem Workshop wird mit der aktuellen OSGeoLive gearbeitet, diese kann als Image von einem USB-Stick oder als virtuelle Maschine auf Ihrem Computer laufen. <a href="http://live.osgeo.org/de/index.html">Zur Installationsanleitung der OSGeoLive</a>.</p>                            <p><span class='abstract-time-heading'>Zeit: </span>Dienstag 08. Juni 09:00 Uhr
                <br><span class='abstract-room-heading'>Ort: </span>Workshop 2
                <br><span class='abstract-room-heading'>Dauer: </span>90 Minuten
            </p>

                        
            <p>React - von facebook als OpenSource Projekt bereitgestellt - gehört seit vielen Jahren zu den meistgenutzten JavaScript Frameworks für die Entwicklung von Web-UI-Komponenten und hat durch seine einfache Erlernbarkeit, die Fokussierung auf modulare Komponenten und nicht zuletzt seine hohe Performance eine breite Community geschaffen. Die JavaScript Bibliothek react-geo koppelt die Mapping Funktionalität von OpenLayers - einer Bibliothek zur Einbindung und Interaktion von Karteninformationen - mit React und bietet eine Vielzahl von vorgefertigten Bausteinen wie z.B. eine Ortssuche, eine Maßstabsauswahl oder Mess- und Zeichenwerkzeuge für die Erstellung von hochmodernen, modularen WebGIS Frontends.</p>
<p>Dieser Workshop vermittelt die Grundlagen der aktuellsten Version von react-geo und bietet einen Einstieg in die Entwicklung eines WebGIS-Frontends mit React. Die Teilnehmer des Workshops lernen anhand einfacher Beispiele den Umgang mit einigen react-geo Komponenten, um auf Basis dieser eine kompakte Webapplikation zu entwickeln.</p>
<p>Dieser Workshop richtet sich an (zukünftige) Entwickler von WebGIS-Anwendungen, die React und OpenLayers in ihre Anwendung aufnehmen möchten. Vorkenntnisse in JavaScript-Entwicklung sind wünschenswert und sicherlich hilfreich, aber nicht zwingend erforderlich. Vorkenntnisse im Umgang mit React oder OpenLayers sind ebenfalls nicht erforderlich.</p>
        <div class='abstract-bio'>
            <h3 class='abstract-bio-name'>Jan Suleiman</h3>
                        <ul>
<li>M.Sc. Geoinformatics</li>
<li>Full-Stack Entwickler bei terrestris GmbH &amp; Co. KG</li>
<li>GeoStyler Kernentwickler</li>
<li>OpenSource Enthusiast</li>
<li>GitHub: <a href="https://github.com/jansule">jansule</a></li>
</ul>
        </div>
        <div class='abstract-bio'>
            <h3 class='abstract-bio-name'>Daniel Koch</h3>
            <img class='abstract-speaker-avatar' src='/2021/avatars/U7QH7V.jpg'>            <p>Lead Developer der terrestris GmbH &amp; Co. KG und OpenSource Enthusiast.</p>
        </div>
        </section>


	<?php include "../inc/footer.inc"; ?>

</body>

</html>