<!doctype html>
<html lang="de">

<head>
	<?php include "../inc/meta.inc"; ?>

	<base href="<?php echo dirname($_SERVER['SCRIPT_NAME']); ?>">
	<title>GDI im Container – FOSSGIS 2021</title>

	<link rel="stylesheet" href="./css/normalize.css">
	<link rel="stylesheet" href="./css/base.css">
	<link rel="stylesheet" href="./css/print.css" media="print">
</head>

<body id="programm">
	<?php include "../inc/header.inc"; ?>

        <!-- This file was generated by a script. Do not edit this file in Git,
             edit contents in Pretalx, regenerate the PHP files and commit them
             in the Git repository of the website. -->
        <p><a href="programm/montag.php#session_WSW7EC">&#9668;&#9668; zurück zum Programm</a> </p>
        <h2 class='abstract-title'>GDI im Container</h2>
        <section>
            <p>
                <span class='abstract-sessiontype'>Vortrag</span>                von <span class='abstract-speakers'>David Arndt</span></p>
                                                                            <p><span class='abstract-time-heading'>Zeit: </span>Montag 07. Juni 17:00 Uhr
                <br><span class='abstract-room-heading'>Ort: </span>Bühne 3
                <br><span class='abstract-room-heading'>Dauer: </span>20 Minuten
            </p>

                        
            <p>Der Regionalverband Ruhr hat in den letzten 2 Jahren die komplette GDI zu einer Microservice Architektur umgebaut. Die Vorteile, aber auch die Fallstricke, die es bei der Migration zu beachten gibt, sollen in diesem Vortrag behandelt werden. </p>
<p>Die Flexibilität, die eine Microservice Architektur bei der Entwicklung, dem Test und dem Betrieb mit sich bringt, soll in diesem Vortrag genauer vorgestellt werden.</p>
        <div class='abstract-bio'>
            <h3 class='abstract-bio-name'>David Arndt</h3>
            <img class='abstract-speaker-avatar' src='/2021/avatars/EZ33FT_csm_David_Arndt.jpg_c84a31a917_kewc1Mc.jpg'>            <p>Teamleiter Team Geodaten-Technik beim Regionalverband Ruhr in Essen</p>
<p>Konzeption und Betrieb der Geodateninfrastruktur des Regionalverbandes</p>
        </div>
        </section>


	<?php include "../inc/footer.inc"; ?>

</body>

</html>