<!doctype html>
<html lang="de">

<head>
	<?php include "../inc/meta.inc"; ?>

	<base href="<?php echo dirname($_SERVER['SCRIPT_NAME']); ?>">
	<title>GeoStyler Anwender- und Entwicklertreffen / BOF – FOSSGIS 2021</title>

	<link rel="stylesheet" href="./css/normalize.css">
	<link rel="stylesheet" href="./css/base.css">
	<link rel="stylesheet" href="./css/print.css" media="print">
</head>

<body id="programm">
	<?php include "../inc/header.inc"; ?>

        <!-- This file was generated by a script. Do not edit this file in Git,
             edit contents in Pretalx, regenerate the PHP files and commit them
             in the Git repository of the website. -->
        <p><a href="programm/mittwoch.php#session_XAMAXF">&#9668;&#9668; zurück zum Programm</a> </p>
        <h2 class='abstract-title'>GeoStyler Anwender- und Entwicklertreffen / BOF</h2>
        <section>
            <p>
                <span class='abstract-sessiontype'>Anwendertreffen / BoF</span>                von <span class='abstract-speakers'>Christian Mayer, Jan Suleiman, Daniel Koch</span></p>
                                                                            <p><span class='abstract-time-heading'>Zeit: </span>Mittwoch 09. Juni 11:30 Uhr
                <br><span class='abstract-room-heading'>Ort: </span>BoF 2
                <br><span class='abstract-room-heading'>Dauer: </span>60 Minuten
            </p>

                        
            <p>Wir wollen uns ohne große Agenda treffen und zum Thema GeoStyler unterhalten. Zielgruppe sind Nutzer, Entwickler und solche die mitmachen wollen.</p>
<p>Alle Interessierten sind herzlich eingeladen.</p>
        <div class='abstract-bio'>
            <h3 class='abstract-bio-name'>Jan Suleiman</h3>
                        <ul>
<li>M.Sc. Geoinformatics</li>
<li>Full-Stack Entwickler bei terrestris GmbH &amp; Co. KG</li>
<li>GeoStyler Kernentwickler</li>
<li>OpenSource Enthusiast</li>
<li>GitHub: <a href="https://github.com/jansule">jansule</a></li>
</ul>
        </div>
        <div class='abstract-bio'>
            <h3 class='abstract-bio-name'>Daniel Koch</h3>
            <img class='abstract-speaker-avatar' src='/2021/avatars/U7QH7V.jpg'>            <p>Lead Developer der terrestris GmbH &amp; Co. KG und OpenSource Enthusiast.</p>
        </div>
        </section>


	<?php include "../inc/footer.inc"; ?>

</body>

</html>