<!doctype html>
<html lang="de">

<head>
	<?php include "../inc/meta.inc"; ?>

	<base href="<?php echo dirname($_SERVER['SCRIPT_NAME']); ?>">
	<title>VectorTiles mithilfe von Tilemaker erstellen und nutzen – FOSSGIS 2021</title>

	<link rel="stylesheet" href="./css/normalize.css">
	<link rel="stylesheet" href="./css/base.css">
	<link rel="stylesheet" href="./css/print.css" media="print">
</head>

<body id="programm">
	<?php include "../inc/header.inc"; ?>

        <!-- This file was generated by a script. Do not edit this file in Git,
             edit contents in Pretalx, regenerate the PHP files and commit them
             in the Git repository of the website. -->
        <p><a href="programm/dienstag.php#session_Y8RGMT">&#9668;&#9668; zurück zum Programm</a> </p>
        <h2 class='abstract-title'>VectorTiles mithilfe von Tilemaker erstellen und nutzen</h2>
        <section>
            <p>
                <span class='abstract-sessiontype'>Vortrag</span>                von <span class='abstract-speakers'>Marcel Normann, Robert Klemm</span></p>
                                                                            <p><span class='abstract-time-heading'>Zeit: </span>Dienstag 08. Juni 12:00 Uhr
                <br><span class='abstract-room-heading'>Ort: </span>Bühne 1
                <br><span class='abstract-room-heading'>Dauer: </span>20 Minuten
            </p>

                        
            <p>Das Tilemaker-Projekt bietet eine ressourcenarme Erstellung von VectorTiles aus OpenStreetMap-Daten. </p>
<p>Das Tilemaker-Projekt unterstützt das OpenMapTile-Daten-Schema und ist somit kompatibel mit mehreren Kartenstilen für die Webanwendungen, die von der MapBox, MapLibre  oder der OpenLayers-JavaScript-Bibliothek unterstützt werden, sowie in nativen mobilen SDKs für iOS und Android.</p>
<p>Im Gegensatz zu anderen Ansätzen kommt Tilemaker dabei ohne den Umweg über eine Postgres-Datenbank aus. Dadurch ist dieser Prozessierungsschritt deutlich schneller und lässt sich auch in Cloud-Umgebungen kostengünstig umsetzen. Die erzeugten Kacheln können in verschiedenen Viewern wie Leaflet, OpenLayers, QGIS oder ArcGIS, etc. geöffnet werden. </p>
<p>Dieser Vortrag bietet einen Überblick über den Einsatz und Prozessierung bis zur Einbindung von VectorTiles in einer Webkarte. Weitere Ansätze für das unabhängige Einbinden, sowie das Styling von Vektorkacheln wird ebenfalls vorgestellt.</p>
        <div class='abstract-bio'>
            <h3 class='abstract-bio-name'>Marcel Normann</h3>
            <p>1999 im Zuge der DotCom-Blase als Quereinsteiger in die Software-Entwicklung gekommen, danach zahlreiche Stationen rund um das Thema Web-Entwicklungen. 2006 aus privatem Interesse Fernstudium Geoinformatik. Seit 2018 Leiter der Software-Entwicklungen bei der WhereGroup, seit 2020 technischer Leiter Gesamtfirma.</p>
        </div>
        <div class='abstract-bio'>
            <h3 class='abstract-bio-name'>Robert Klemm</h3>
            <p>Ich bin studierter Geoinformatiker und Kartograph und seit 2017 als GIS-Consultant und Entwickler bei der <a href="https://wheregroup.com">WhereGroup</a>nin Berlin tätig.</p>
<p>Ich weise Erfahrung mit PostgreSQL und PostGIS, Imposm, Mapnik, MapServer, GeoServer, QGIS, QGIS Server und Mapbender auf. Weiterhin in Apache, Solr, OpenLayers, MapProxy, OGC Standards, GraphHopper und im Skripting.</p>
        </div>
        </section>


	<?php include "../inc/footer.inc"; ?>

</body>

</html>