<!doctype html>
<html lang="de">

<head>
	<?php include "../inc/meta.inc"; ?>

	<base href="<?php echo dirname($_SERVER['SCRIPT_NAME']); ?>">
	<title>Wer hat an der Uhr gedreht? - Zeitbasierte Geodaten modellieren, abfragen und visualisieren – FOSSGIS 2021</title>

	<link rel="stylesheet" href="./css/normalize.css">
	<link rel="stylesheet" href="./css/base.css">
	<link rel="stylesheet" href="./css/print.css" media="print">
</head>

<body id="programm">
	<?php include "../inc/header.inc"; ?>

        <!-- This file was generated by a script. Do not edit this file in Git,
             edit contents in Pretalx, regenerate the PHP files and commit them
             in the Git repository of the website. -->
        <p><a href="programm/dienstag.php#session_YQYWVB">&#9668;&#9668; zurück zum Programm</a> </p>
        <h2 class='abstract-title'>Wer hat an der Uhr gedreht? - Zeitbasierte Geodaten modellieren, abfragen und visualisieren</h2>
        <section>
            <p>
                <span class='abstract-sessiontype'>Vortrag</span>                von <span class='abstract-speakers'>Jakob Miksch</span></p>
                                                                            <p><span class='abstract-time-heading'>Zeit: </span>Dienstag 08. Juni 14:30 Uhr
                <br><span class='abstract-room-heading'>Ort: </span>Bühne 1
                <br><span class='abstract-room-heading'>Dauer: </span>20 Minuten
            </p>

                        
            <p>Ein Großteil aller Geodaten enthält neben der räumlichen Information auch eine zeitliche Komponente. Beispielsweise werden Luftbildern an bestimmen Tagen aufgenommen oder ein Datensatz von Gebäuden ist mit dem entsprechenden Baujahr versehen. Dieser Vortrag gibt einen Überblick welche gängigen Möglichkeiten es gibt zeitliche Information abzuspeichern, wie das konkret für Vektor und Rasterdaten umgesetzt wird und welche Schwierigkeiten und Herausforderung in der Umsetzung zu erwarten sind.</p>
<p>Für die zeitlichen Abfrage von Geodaten stellen die verschiedenen Dienste des OGC (Open Geospatial Consortium) Schnittstellen zu Verfügung. Web Map Services (WMS) können mittels des standartisierem WMS-TIME zeitbasiert abgefragt werden. Dieser lässt neben einzelnen Zeitpunkten auch Zeiträume zu. Beim Web Feature Service (WFS) werden für zeitliche Abfrage der FILTER-Parameter verwendet. Dieser akzeptiert die standard-konformen OGC-Filter. </p>
<p>Softwareseitig werden die zeitbasierten OGC-Dienste im FOSSGIS-Umfeld breit unterstützt. Als Kartenserver eignen sich GeoServer und MapServer. Auf dem Desktop bietet QGIS seit Version 3.14 umfangreiche WMS-Time Funktionen. In Web-Browsern können sowohl OpenLayers als auch Leaflet für zeitliche Abfragen genutzt werden. 
Der Vortrag schließt mit einer Demonstration, wie im Projekt SAUBER zeitbasierte Dienste mittels GeoServer erstellt werden. Außerdem zeigen wir unseren auf Wegue (Vue.js und OpenLayers) basierenden Web-Client mit dem zeitliche Abfragen benutzerfreundlich durchgeführt werden können.</p>
        <div class='abstract-bio'>
            <h3 class='abstract-bio-name'>Jakob Miksch</h3>
            <img class='abstract-speaker-avatar' src='/2021/avatars/7RZJR9_9888e9fcab3126f81a68395e35b50b20'>            <p>Software Entwickler für Geo-Anwendungen bei <a href="www.meggsimum.de">Meggsimum</a> in Mutterstadt. Haupsächlich mit JavaScript, PostGIS, Shell, Python, GDAL/OGR und QGIS.</p>
<ul>
<li>Mitorganisator von <a href="http://maptime.io/salzburg/">Maptime Salzburg</a></li>
<li>OSGeo <a href="https://www.osgeo.org/member/miksch/">Charter Member</a></li>
</ul>
        </div>
        </section>


	<?php include "../inc/footer.inc"; ?>

</body>

</html>