<!doctype html>
<html lang="de">

<head>
	<?php include "../inc/meta.inc"; ?>

	<base href="<?php echo dirname($_SERVER['SCRIPT_NAME']); ?>">
	<title>Parkplatzzählung und Parkraumanalysen auf OSM-Basis – FOSSGIS 2021</title>

	<link rel="stylesheet" href="./css/normalize.css">
	<link rel="stylesheet" href="./css/base.css">
	<link rel="stylesheet" href="./css/print.css" media="print">
</head>

<body id="programm">
	<?php include "../inc/header.inc"; ?>

        <!-- This file was generated by a script. Do not edit this file in Git,
             edit contents in Pretalx, regenerate the PHP files and commit them
             in the Git repository of the website. -->
        <p><a href="programm/dienstag.php#session_ZA7MQV">&#9668;&#9668; zurück zum Programm</a> </p>
        <h2 class='abstract-title'>Parkplatzzählung und Parkraumanalysen auf OSM-Basis</h2>
        <section>
            <p>
                <span class='abstract-sessiontype'>Vortrag</span>                von <span class='abstract-speakers'>Alex Seidel</span></p>
                                                                            <p><span class='abstract-time-heading'>Zeit: </span>Dienstag 08. Juni 16:00 Uhr
                <br><span class='abstract-room-heading'>Ort: </span>Bühne 2
                <br><span class='abstract-room-heading'>Dauer: </span>20 Minuten
            </p>

                        
            <p>Im Zuge der Verkehrswende wird Verkehrsraum in vielen Städten neu verteilt oder zumindest politisch darüber gestritten. Gleichzeitig werden Verkehr und Mobilität unter Einbezug geographischer Daten immer zielgerichteter, sodass beispielsweise unnötige Verkehrswege verhindert werden können. Nicht nur in solchen Zusammenhängen werden Daten über die Anzahl und Verteilung von Auto-Parkplätzen eine immer wertvollere Ressource für Stadtentwicklung, Zivilgesellschaft oder Mobilitätsprojekte. Vielerorts gibt es noch gar kein systematisches Wissen, wo es wie viele Parkplätze gibt.</p>
<p>OSM ist ein optimales Werkzeug, um solche Daten zu erfassen und auswertbar zu machen. Im Berliner Stadtteil Neukölln haben wir demonstriert, wie urbaner Parkraum systematisch auf OSM-Basis kartiert und mit GIS und unter Einbezug externer offener Daten hochaufgelöst analysiert werden kann. Im Vortrag sollen die Herangehensweise und Ergebnisse des Projekts vorgestellt werden; wir haben aber auch viele Erfahrungen für die Mapping- und Auswertungspraxis gesammelt, die wir gern teilen möchten, damit Andere an anderen Orten bei Bedarf darauf aufbauen können.</p>
        <div class='abstract-bio'>
            <h3 class='abstract-bio-name'>Alex Seidel</h3>
            <img class='abstract-speaker-avatar' src='/2021/avatars/JYBMSF.jpg'>            <p>OSM-Mapper und Stadtgeograph aus Berlin.</p>
        </div>
        </section>


	<?php include "../inc/footer.inc"; ?>

</body>

</html>