<!doctype html>
<html lang="de">

<head>
	<?php include "../inc/meta.inc"; ?>

	<base href="<?php echo dirname($_SERVER['SCRIPT_NAME']); ?>">
	<title>Kartographische Generalisierung mit PostgreSQL und PostGIS am Beispiel – FOSSGIS 2021</title>

	<link rel="stylesheet" href="./css/normalize.css">
	<link rel="stylesheet" href="./css/base.css">
	<link rel="stylesheet" href="./css/print.css" media="print">
</head>

<body id="programm">
	<?php include "../inc/header.inc"; ?>

        <!-- This file was generated by a script. Do not edit this file in Git,
             edit contents in Pretalx, regenerate the PHP files and commit them
             in the Git repository of the website. -->
        <p><a href="programm/dienstag.php#session_ZKGABQ">&#9668;&#9668; zurück zum Programm</a> </p>
        <h2 class='abstract-title'>Kartographische Generalisierung mit PostgreSQL und PostGIS am Beispiel</h2>
        <section>
            <p>
                <span class='abstract-sessiontype'>Workshop</span>
                                von <span class='abstract-speakers'>Mathias Gröbe</span></p>
                <p class='abstract-is-workshop'>Bitte melden Sie sich im <a href="https://pretix.eu/fossgis/2021/">Ticketshop</a> für diesen Workshop an, wenn Sie daran teilnehmen möchten.</p>                                <p class='abstract-is-workshop'>In diesem Workshop wird mit der aktuellen OSGeoLive gearbeitet, diese kann als Image von einem USB-Stick oder als virtuelle Maschine auf Ihrem Computer laufen. <a href="http://live.osgeo.org/de/index.html">Zur Installationsanleitung der OSGeoLive</a>.</p>                            <p><span class='abstract-time-heading'>Zeit: </span>Dienstag 08. Juni 14:00 Uhr
                <br><span class='abstract-room-heading'>Ort: </span>Workshop 2
                <br><span class='abstract-room-heading'>Dauer: </span>90 Minuten
            </p>

                        
            <p>PostgreSQL und PostGIS bieten eine Vielzahl von Funktionen, die für kartographische Generalisierung verwendet werden können. An Beispielen soll gezeigt werden, wie sich mit PostGIS Funktionen beispielhaft die Generalisierungsoperatoren Auswahl, Typisieren und Vereinfachen implementieren lassen. Ziel ist ein auf Visualisierung optimiertes kartographisches Datenmodell auf Basis von OpenStreetMap-Daten zu erzeugen.</p>
        </section>


	<?php include "../inc/footer.inc"; ?>

</body>

</html>