<!doctype html>
<html lang="de">

<head>
	<?php include "../inc/meta.inc"; ?>

	<base href="<?php echo dirname($_SERVER['SCRIPT_NAME']); ?>">
	<title>Webassembly: Wo wir sind und wo es hingehen könnte – FOSSGIS 2021</title>

	<link rel="stylesheet" href="./css/normalize.css">
	<link rel="stylesheet" href="./css/base.css">
	<link rel="stylesheet" href="./css/print.css" media="print">
</head>

<body id="programm">
	<?php include "../inc/header.inc"; ?>

        <!-- This file was generated by a script. Do not edit this file in Git,
             edit contents in Pretalx, regenerate the PHP files and commit them
             in the Git repository of the website. -->
        <p><a href="programm/dienstag.php#session_ZVFZQQ">&#9668;&#9668; zurück zum Programm</a> <a href="sessions/lightning_talks_3.php">&#9668; zurück zur Session</a></p>
        <h2 class='abstract-title'>Webassembly: Wo wir sind und wo es hingehen könnte</h2>
        <section>
            <p>
                <span class='abstract-sessiontype'>Lightning Talk</span>                von <span class='abstract-speakers'>Michael Schmuki</span></p>
                                                                            <p><span class='abstract-time-heading'>Zeit: </span>Dienstag 08. Juni 12:15 Uhr
                <br><span class='abstract-room-heading'>Ort: </span>Bühne 2
                <br><span class='abstract-room-heading'>Dauer: </span>5 Minuten
            </p>

                        
            <p>Webassemblys Potential ist insbesondere für die Verarbeitung und Visualisierung von Geo-Daten noch nicht ausgeschöpft. In diesem Talk möchte ich Ihnen die aktuelle Adaption in FOSSGIS-Projekten, die technische Weiterentwicklung sowie mögliche Zukunftsszenarien von Webassembly aufzeigen.</p>
        </section>


	<?php include "../inc/footer.inc"; ?>

</body>

</html>