<!doctype html>
<html lang="de">

<head>
	<meta charset="utf-8">
<meta http-equiv="x-ua-compatible" content="ie=edge">
<meta name="description" content="Die FOSSGIS-Konferenz ist im D-A-CH Raum die führende Konferenz für Freie und Open Source Software für Geoinformationssysteme OpenStreetMap.">
<meta name="keywords" content="FOSSGIS, FOSSGIS-Konferenz, 2019, FOSSGIS-Konferenz 2019, Open Source, GIS, Konferenz, Geoinformatik, OpenStreetMap, HTW Dresden">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="apple-itunes-app" content="app-id=1453299630">

	<base href="/2020/sessions">
	<title>Einführung zu GDAL/OGR: Geodaten mit der Kommandozeile verarbeiten – FOSSGIS 2020</title>

	<link rel="stylesheet" href="./css/normalize.css">
	<link rel="stylesheet" href="./css/base.css">
	<link rel="stylesheet" href="./css/print.css" media="print">
</head>

<body id="programm">
	<header class="page-header">
	<a href="./" alt="FOSSGIS Konferenz 2020">
		<img class="page-logo" src="./img/fossgis2020-bollenhut.png">
	</a>
	<h1 class="page-title">
		FOSSGIS-Konferenz 2020<br>
		<span class="amp">Freiburg</span> <br>
		<span class="amp">11.&ndash;14. März</span>
	</h1>
</header>

<nav>
	<ul class="main">
		<li id="navHome">
			<a href="./">Startseite</a>
		</li>
		<!--<li id="navAnmeldung">
			<a href="./anmeldung/">Anmeldung</a>
		</li>-->
		<li id="navProgramm">
		<a href="./programm/">Programm</a>
		</li>
		<!--<li id="navAnreise">
			<a href="./anreise/">Anreise</a>
		</li>-->
		<li id="navStandort">
			<a href="./standort/">Standort</a>
		</li>
		<li id="navEvents">
			<a href="./socialevents/">Social Events</a>
		</li>
		<li id="navTeam">
			<a href="./loc/loc.php">Team</a>
		</li>
	</ul>
</nav>

<div class="hero">
	<figure>
		<img class="img-fluid" src="./img/freiburg.jpg" alt="Freiburg Luftbild">
		<figcaption>Photo: Pixaby</figcaption>
	</figure>
</div>

        <!-- This file was generated by a script. Do not edit this file in Git,
             edit contents in Pretalx, regenerate the PHP files and commit them
             in the Git repository of the website. -->
        <p><a href="programm/mittwoch.php#session_339AY9">&#9668;&#9668; zurück zum Programm</a> </p>
        <h2 class='abstract-title'>Einführung zu GDAL/OGR: Geodaten mit der Kommandozeile verarbeiten</h2>
        <section>
            <p>
                <span class='abstract-sessiontype'>Demo-Session</span> von                <span class='abstract-speakers'>Jakob Miksch</span></p>
                            <p><span class='abstract-time-heading'>Zeit: </span>Mittwoch 11. März 17:30 Uhr<br><span class='abstract-room-heading'>Ort: </span>HS Anatomie</p>

                        <div class="video-container">
                <a href="https://media.ccc.de/v/fossgis2020-2853-einfhrung-zu-gdal-ogr-geodaten-mit-der-kommandozeile-verarbeiten">
                    <img class="video-preview" src="video_previews/2853-hd.jpg" alt="Vorschaubild des Videos">
                    <div class="video-preview-overlay"></div>
                </a>
            </div>
                        
            <p><strong>GDAL/OGR</strong> ist eine Programm-Bibliothek die verschiedene <a href="https://gdal.org/drivers/vector/index.html">Vektor-</a> und <a href="https://gdal.org/drivers/raster/index.html">Rasterformate</a> lesen und schreiben kann. Sie ist in C/C++ geschrieben, allerdings kann man auch mit anderen Programmiersprachen wie Python oder R darauf zugreifen. Es gibt zahlreiche Programme für die <strong>Kommandozeile</strong> die in diesem Vortrag vorgestellt werden. Behandelt werden unter anderem folgende Themen:</p>
<ul>
<li>Virtuelle Raster erstellen mit <a href="https://gdal.org/programs/gdalbuildvrt.html">gdalbuildvrt</a></li>
<li>Raster Pyramiden bauen mit <a href="https://gdal.org/programs/gdaladdo.html">gdaladdo</a></li>
<li>Raster umprojezieren mit <a href="https://gdal.org/programs/gdalwarp.html">gdalwarp</a></li>
<li>Kacheln erzeugen mit <a href="https://gdal.org/programs/gdal2tiles.html">gdal2tiles.py</a></li>
<li>Informationen über Vektordaten erhalten mit <a href="https://gdal.org/programs/ogrinfo.html">ogrinfo</a></li>
<li>Vektordaten konvertieren und umprojezieren mit <a href="https://gdal.org/programs/ogr2ogr.html#ogr2ogr">ogr2ogr</a></li>
<li>Vorstellung von wichtigen Treibern wie CSV, PostGIS, GeoPackage, GPX</li>
<li>Überblick über fortgeschrittene Funktionen wie SQL, räumliche Begrenzung oder Filterung </li>
</ul>
<h5>Links</h5>
<ul>
<li><a href="https://jakobmiksch.eu/de/post/gdal_ogr/">Blogeintrag über GDAL/OGR</a> von Jakob Miksch</li>
<li><a href="https://av.tib.eu/media/43047">Vortrag</a> von Jakob Miksch auf der AGIT 2019</li>
<li><a href="https://gdal.org/">Website</a> von GDAL/OGR</li>
</ul>
        <div class='abstract-bio'>
            <h3 class='abstract-bio-name'>Jakob Miksch</h3>
            <p>Wissenschaftlicher Mitarbeiter im <a href="https://giscience.zgis.at/">GIScience Lab</a>, Fachbereich für Geoinformatik - Z_GIS,  Universität Salzburg.</p>
<ul>
<li>Website: <a href="https://jakobmiksch.eu/de/">jakobmiksch.eu</a></li>
<li>Twitter: <a href="https://twitter.com/JakobMiksch">@JakobMiksch</a></li>
<li>GitHub: <a href="https://github.com/jakobmiksch/">@JakobMiksch</a></li>
</ul>
        </div>
        </section>


	<footer>
	<ul class="main">
		<li>
			<a href="https://www.fossgis.de/impressum/">Impressum</a>
		</li>
		<li>
			<a href="./agb.php">AGB</a>
		</li>
		<li>
			<a href="https://www.fossgis.de/datenschutzerklärung">Datenschutzerklärung</a>
		</li>
	</ul>
</footer>

</body>

</html>