<!doctype html>
<html lang="de">

<head>
	<?php include "../inc/meta.inc"; ?>

	<base href="<?php echo dirname($_SERVER['SCRIPT_NAME']); ?>">
	<title>Daten sind draußen, QFieldCloud bringt sie herein – FOSSGIS 2020</title>

	<link rel="stylesheet" href="./css/normalize.css">
	<link rel="stylesheet" href="./css/base.css">
	<link rel="stylesheet" href="./css/print.css" media="print">
</head>

<body id="programm">
	<?php include "../inc/header.inc"; ?>

        <!-- This file was generated by a script. Do not edit this file in Git,
             edit contents in Pretalx, regenerate the PHP files and commit them
             in the Git repository of the website. -->
        <p><a href="programm/donnerstag.php#session_37LTRD">&#9668;&#9668; zurück zum Programm</a> <a href="sessions/lightning_talks_2.php">&#9668; zurück zur Session</a></p>
        <h2 class='abstract-title'>Daten sind draußen, QFieldCloud bringt sie herein</h2>
        <section>
            <p>
                <span class='abstract-sessiontype'>Lightning Talk</span> von                <span class='abstract-speakers'>Marco Bernasocchi</span></p>
                            <p><span class='abstract-time-heading'>Zeit: </span>Donnerstag 12. März 12:15 Uhr<br><span class='abstract-room-heading'>Ort: </span>HS Weismannhaus</p>

            
            <p>QFieldCloud ist eine Synchronisationplattform für QGIS und QField. QFieldCloud erlaubt Projekte und Daten nahtlos zu synchronisieren und diese mit Teammitgliedern zu teilen.
QField und QFieldCloud sind Open Source Projekte von OPENGIS.ch.</p>
        </section>


	<?php include "../inc/footer.inc"; ?>

</body>

</html>