<!doctype html>
<html lang="de">

<head>
	<?php include "../inc/meta.inc"; ?>

	<base href="<?php echo dirname($_SERVER['SCRIPT_NAME']); ?>">
	<title>Triff OSMler in deiner Nähe mit OSMCAL – FOSSGIS 2020</title>

	<link rel="stylesheet" href="./css/normalize.css">
	<link rel="stylesheet" href="./css/base.css">
	<link rel="stylesheet" href="./css/print.css" media="print">
</head>

<body id="programm">
	<?php include "../inc/header.inc"; ?>

        <!-- This file was generated by a script. Do not edit this file in Git,
             edit contents in Pretalx, regenerate the PHP files and commit them
             in the Git repository of the website. -->
        <p><a href="programm/donnerstag.php#session_3BSTMC">&#9668;&#9668; zurück zum Programm</a> <a href="sessions/lightning_talks_3.php">&#9668; zurück zur Session</a></p>
        <h2 class='abstract-title'>Triff OSMler in deiner Nähe mit OSMCAL</h2>
        <section>
            <p>
                <span class='abstract-sessiontype'>Lightning Talk</span> von                <span class='abstract-speakers'>Thomas Skowron</span></p>
                            <p><span class='abstract-time-heading'>Zeit: </span>Donnerstag 12. März 14:30 Uhr<br><span class='abstract-room-heading'>Ort: </span>HS Weismannhaus</p>

                        
            <p>Damit man nicht mehr Dinge im Wiki bearbeiten oder wiederfinden muss, gibt es jetzt den OSM Kalender. In dem Lightningtalk wird gezeigt, was OSMCAL ist, wie es funktioniert und wie man eigene Veranstaltungen hinzufügt.</p>
        </section>


	<?php include "../inc/footer.inc"; ?>

</body>

</html>