<!doctype html>
<html lang="de">

<head>
	<meta charset="utf-8">
<meta http-equiv="x-ua-compatible" content="ie=edge">
<meta name="description" content="Die FOSSGIS-Konferenz ist im D-A-CH Raum die führende Konferenz für Freie und Open Source Software für Geoinformationssysteme OpenStreetMap.">
<meta name="keywords" content="FOSSGIS, FOSSGIS-Konferenz, 2019, FOSSGIS-Konferenz 2019, Open Source, GIS, Konferenz, Geoinformatik, OpenStreetMap, HTW Dresden">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="apple-itunes-app" content="app-id=1453299630">

	<base href="/2020/sessions">
	<title>QGIS im Produktivbetrieb: Erfahrungsbericht zur Einführung von QGIS als professionelles Planungswerkzeug – FOSSGIS 2020</title>

	<link rel="stylesheet" href="./css/normalize.css">
	<link rel="stylesheet" href="./css/base.css">
	<link rel="stylesheet" href="./css/print.css" media="print">
</head>

<body id="programm">
	<header class="page-header">
	<a href="./" alt="FOSSGIS Konferenz 2020">
		<img class="page-logo" src="./img/fossgis2020-bollenhut.png">
	</a>
	<h1 class="page-title">
		FOSSGIS-Konferenz 2020<br>
		<span class="amp">Freiburg</span> <br>
		<span class="amp">11.&ndash;14. März</span>
	</h1>
</header>

<nav>
	<ul class="main">
		<li id="navHome">
			<a href="./">Startseite</a>
		</li>
		<!--<li id="navAnmeldung">
			<a href="./anmeldung/">Anmeldung</a>
		</li>-->
		<li id="navProgramm">
		<a href="./programm/">Programm</a>
		</li>
		<!--<li id="navAnreise">
			<a href="./anreise/">Anreise</a>
		</li>-->
		<li id="navStandort">
			<a href="./standort/">Standort</a>
		</li>
		<li id="navEvents">
			<a href="./socialevents/">Social Events</a>
		</li>
		<li id="navTeam">
			<a href="./loc/loc.php">Team</a>
		</li>
	</ul>
</nav>

<div class="hero">
	<figure>
		<img class="img-fluid" src="./img/freiburg.jpg" alt="Freiburg Luftbild">
		<figcaption>Photo: Pixaby</figcaption>
	</figure>
</div>

        <!-- This file was generated by a script. Do not edit this file in Git,
             edit contents in Pretalx, regenerate the PHP files and commit them
             in the Git repository of the website. -->
        <p><a href="programm/mittwoch.php#session_7BCWHD">&#9668;&#9668; zurück zum Programm</a> </p>
        <h2 class='abstract-title'>QGIS im Produktivbetrieb: Erfahrungsbericht zur Einführung von QGIS als professionelles Planungswerkzeug</h2>
        <section>
            <p>
                                <span class='abstract-speakers'>Thomas Baumann</span></p>
                            <p><span class='abstract-time-heading'>Zeit: </span>Mittwoch 11. März 15:30 Uhr<br><span class='abstract-room-heading'>Ort: </span>HS Rundbau</p>

                        <div class="video-container">
                <a href="https://media.ccc.de/v/fossgis2020-3117-qgis-im-produktivbetrieb-erfahrungsbericht-zur-einfhrung-von-qgis-als-professionelles-planungswerkzeug">
                    <img class="video-preview" src="video_previews/3117-hd.jpg" alt="Vorschaubild des Videos">
                    <div class="video-preview-overlay"></div>
                </a>
            </div>
                        
            <p>Seit Anfang 2016 habe ich bei einem mittelständischen Unternehmen QGIS als professionelles GIS mit Schwerpunkt Planung im Bereich des Breitbandausbaus eingeführt.</p>
<p>In diesem Vortrag würde ich gerne über den Weg berichten vom anfänglichen „fear, uncertainty and doubt“-Phänomen über erste Teilerfolge hin zu Akzeptanz von QGIS als etabliertes Werkzeug zur Unterstützung der Planer. Beleuchtet werden soll auch die technische Umsetzung mit Themen wie:</p>
<ul>
<li>Netzwerkinstallation von QGIS</li>
<li>Einsatz in virtualisierten Umgebungen</li>
<li>(Teil-)Automatisierung des Rollouts</li>
<li>hausinterne Plugin-Entwicklung und Plugin-Repositories</li>
<li>Einflussmöglichkeiten über PYQGIS_STARTUP und startup.py</li>
<li>Debugging von QGIS</li>
<li>Zusammenspiel mit externen QGIS-Entwicklern und -Support-Dienstleistern</li>
</ul>
<p>Der Vortrag beschäftigt sich explizit NICHT mit speziellen Plugins/Werkzeugen zur FTTX-Planung.</p>
        <div class='abstract-bio'>
            <h3 class='abstract-bio-name'>Thomas Baumann</h3>
            <p>https://twitter.com/neogis_de</p>
        </div>
        </section>


	<footer>
	<ul class="main">
		<li>
			<a href="https://www.fossgis.de/impressum/">Impressum</a>
		</li>
		<li>
			<a href="./agb.php">AGB</a>
		</li>
		<li>
			<a href="https://www.fossgis.de/datenschutzerklärung">Datenschutzerklärung</a>
		</li>
	</ul>
</footer>

</body>

</html>