<!doctype html>
<html lang="de">

<head>
	<?php include "../inc/meta.inc"; ?>

	<base href="<?php echo dirname($_SERVER['SCRIPT_NAME']); ?>">
	<title>GeoServer Vertiefung – FOSSGIS 2020</title>

	<link rel="stylesheet" href="./css/normalize.css">
	<link rel="stylesheet" href="./css/base.css">
	<link rel="stylesheet" href="./css/print.css" media="print">
</head>

<body id="programm">
	<?php include "../inc/header.inc"; ?>

        <!-- This file was generated by a script. Do not edit this file in Git,
             edit contents in Pretalx, regenerate the PHP files and commit them
             in the Git repository of the website. -->
        <p><a href="programm/freitag.php#session_7DJMEJ">&#9668;&#9668; zurück zum Programm</a> </p>
        <h2 class='abstract-title'>GeoServer Vertiefung</h2>
        <section>
            <p>
                <span class='abstract-sessiontype'>Workshop</span> von                <span class='abstract-speakers'>Daniel Koch, Hannes Blitza</span></p>
                <p class='abstract-is-workshop'>Bitte melden Sie sich im <a href="https://pretix.eu/fossgis/2020/">Ticketshop</a> für diesen Workshop an, wenn Sie daran teilnehmen möchten.</p>            <p><span class='abstract-time-heading'>Zeit: </span>Freitag 13. März 11:00 Uhr<br><span class='abstract-room-heading'>Ort: </span>SR R-110</p>

                        
            <p>Der GeoServer ist ein bekannter und vielerorts genutzter Open-Source-Kartenserver,
der viele OGC-Standards unterstützt. GeoServer ermöglicht die Veröffentlichung von
Geodaten- und Kartendiensten aus zahlreichen Datenquellen.</p>
<p>Nach Einrichtung der Serverumgebung und Installation des GeoServers ist die
Konfiguration von ersten WMS-, WCS- und WFS-Diensten intuitiv über ein
Webinterface möglich.</p>
<p>In diesem Workshop wird auf die erweiterten Konfigurationsmöglichkeiten und
Features des GeoServers eingegangen. Der Fokus liegt dabei auf den
unterschiedlichen Möglichkeiten einer möglichst automatisierten und auf die
konkrete Systemumgebung maßgeschneiderten Einrichtung. Dabei wird auch die
Konfiguration für einen Produktiveinsatz berücksichtigt werden.</p>
<p>Im Rahmen des Workshops werden u.a. folgende Themen behandelt:
- Installation und Optimierung, Installation von Erweiterungen
- Automatisierte Konfiguration von Workspaces, Stores, (zahlreichen) Layern und Styles über die REST-Schnittstelle
- Caching von Kartendiensten unter Einsatz des GeoWebCache (GWC)
- Performance-Tuning und sinnvolle Einstellungen für den Produktiveinsatz</p>
<p>Vorkenntnisse in einer Programmiersprache sind für diesen Workshop nicht notwendig.
Praktische Erfahrungen mit dem GeoServer sind von Vorteil, aber nicht zwingend erforderlich.</p>
        <div class='abstract-bio'>
            <h3 class='abstract-bio-name'>Hannes Blitza</h3>
            <p>employee at terrestris GmbH, Bonn.</p>
        </div>
        </section>


	<?php include "../inc/footer.inc"; ?>

</body>

</html>