<!doctype html>
<html lang="de">

<head>
	<meta charset="utf-8">
<meta http-equiv="x-ua-compatible" content="ie=edge">
<meta name="description" content="Die FOSSGIS-Konferenz ist im D-A-CH Raum die führende Konferenz für Freie und Open Source Software für Geoinformationssysteme OpenStreetMap.">
<meta name="keywords" content="FOSSGIS, FOSSGIS-Konferenz, 2019, FOSSGIS-Konferenz 2019, Open Source, GIS, Konferenz, Geoinformatik, OpenStreetMap, HTW Dresden">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="apple-itunes-app" content="app-id=1453299630">

	<base href="/2020/sessions">
	<title>GeoServer Vertiefung – FOSSGIS 2020</title>

	<link rel="stylesheet" href="./css/normalize.css">
	<link rel="stylesheet" href="./css/base.css">
	<link rel="stylesheet" href="./css/print.css" media="print">
</head>

<body id="programm">
	<header class="page-header">
	<a href="./" alt="FOSSGIS Konferenz 2020">
		<img class="page-logo" src="./img/fossgis2020-bollenhut.png">
	</a>
	<h1 class="page-title">
		FOSSGIS-Konferenz 2020<br>
		<span class="amp">Freiburg</span> <br>
		<span class="amp">11.&ndash;14. März</span>
	</h1>
</header>

<nav>
	<ul class="main">
		<li id="navHome">
			<a href="./">Startseite</a>
		</li>
		<!--<li id="navAnmeldung">
			<a href="./anmeldung/">Anmeldung</a>
		</li>-->
		<li id="navProgramm">
		<a href="./programm/">Programm</a>
		</li>
		<!--<li id="navAnreise">
			<a href="./anreise/">Anreise</a>
		</li>-->
		<li id="navStandort">
			<a href="./standort/">Standort</a>
		</li>
		<li id="navEvents">
			<a href="./socialevents/">Social Events</a>
		</li>
		<li id="navTeam">
			<a href="./loc/loc.php">Team</a>
		</li>
	</ul>
</nav>

<div class="hero">
	<figure>
		<img class="img-fluid" src="./img/freiburg.jpg" alt="Freiburg Luftbild">
		<figcaption>Photo: Pixaby</figcaption>
	</figure>
</div>

        <!-- This file was generated by a script. Do not edit this file in Git,
             edit contents in Pretalx, regenerate the PHP files and commit them
             in the Git repository of the website. -->
        <p><a href="programm/freitag.php#session_7DJMEJ">&#9668;&#9668; zurück zum Programm</a> </p>
        <h2 class='abstract-title'>GeoServer Vertiefung</h2>
        <section>
            <p>
                <span class='abstract-sessiontype'>Workshop</span> von                <span class='abstract-speakers'>Daniel Koch, Hannes Blitza</span></p>
                            <p><span class='abstract-time-heading'>Zeit: </span>Freitag 13. März 11:00 Uhr<br><span class='abstract-room-heading'>Ort: </span>SR R-110</p>

                        
            <p>Der GeoServer ist ein bekannter und vielerorts genutzter Open-Source-Kartenserver,
der viele OGC-Standards unterstützt. GeoServer ermöglicht die Veröffentlichung von
Geodaten- und Kartendiensten aus zahlreichen Datenquellen.</p>
<p>Nach Einrichtung der Serverumgebung und Installation des GeoServers ist die
Konfiguration von ersten WMS-, WCS- und WFS-Diensten intuitiv über ein
Webinterface möglich.</p>
<p>In diesem Workshop wird auf die erweiterten Konfigurationsmöglichkeiten und
Features des GeoServers eingegangen. Der Fokus liegt dabei auf den
unterschiedlichen Möglichkeiten einer möglichst automatisierten und auf die
konkrete Systemumgebung maßgeschneiderten Einrichtung. Dabei wird auch die
Konfiguration für einen Produktiveinsatz berücksichtigt werden.</p>
<p>Im Rahmen des Workshops werden u.a. folgende Themen behandelt:
- Installation und Optimierung, Installation von Erweiterungen
- Automatisierte Konfiguration von Workspaces, Stores, (zahlreichen) Layern und Styles über die REST-Schnittstelle
- Caching von Kartendiensten unter Einsatz des GeoWebCache (GWC)
- Performance-Tuning und sinnvolle Einstellungen für den Produktiveinsatz</p>
<p>Vorkenntnisse in einer Programmiersprache sind für diesen Workshop nicht notwendig.
Praktische Erfahrungen mit dem GeoServer sind von Vorteil, aber nicht zwingend erforderlich.</p>
        <div class='abstract-bio'>
            <h3 class='abstract-bio-name'>Hannes Blitza</h3>
            <p>employee at terrestris GmbH, Bonn.</p>
        </div>
        </section>


	<footer>
	<ul class="main">
		<li>
			<a href="https://www.fossgis.de/impressum/">Impressum</a>
		</li>
		<li>
			<a href="./agb.php">AGB</a>
		</li>
		<li>
			<a href="https://www.fossgis.de/datenschutzerklärung">Datenschutzerklärung</a>
		</li>
	</ul>
</footer>

</body>

</html>