<!doctype html>
<html lang="de">

<head>
	<?php include "../inc/meta.inc"; ?>

	<base href="<?php echo dirname($_SERVER['SCRIPT_NAME']); ?>">
	<title>Vektortile-Karten erstellen mit t-rex – FOSSGIS 2020</title>

	<link rel="stylesheet" href="./css/normalize.css">
	<link rel="stylesheet" href="./css/base.css">
	<link rel="stylesheet" href="./css/print.css" media="print">
</head>

<body id="programm">
	<?php include "../inc/header.inc"; ?>

        <!-- This file was generated by a script. Do not edit this file in Git,
             edit contents in Pretalx, regenerate the PHP files and commit them
             in the Git repository of the website. -->
        <p><a href="programm/freitag.php#session_7EPGZD">&#9668;&#9668; zurück zum Programm</a> </p>
        <h2 class='abstract-title'>Vektortile-Karten erstellen mit t-rex</h2>
        <section>
            <p>
                <span class='abstract-sessiontype'>Demo-Session</span> von                <span class='abstract-speakers'>Pirmin Kalberer</span></p>
                            <p><span class='abstract-time-heading'>Zeit: </span>Freitag 13. März 11:00 Uhr<br><span class='abstract-room-heading'>Ort: </span>HS Anatomie</p>

                        
            <p>Vektortiles haben das Potential, die bewährten Rasterkarten in vielen Bereichen abzulösen oder mindestens massgeblich zu ergänzen. Dieser Vortrag zeigt, wie Vektortiles generiert werden können und was dabei zu beachten ist. Weitere Themen sind das Styling der Karten mit Mapbox GL JSON und die Publikation mit OpenLayers 6 und Mapbox GL JS.</p>
        </section>


	<?php include "../inc/footer.inc"; ?>

</body>

</html>