<!doctype html>
<html lang="de">

<head>
	<?php include "../inc/meta.inc"; ?>

	<base href="<?php echo dirname($_SERVER['SCRIPT_NAME']); ?>">
	<title>Workshop Datenschutz und geographische Informationen – FOSSGIS 2020</title>

	<link rel="stylesheet" href="./css/normalize.css">
	<link rel="stylesheet" href="./css/base.css">
	<link rel="stylesheet" href="./css/print.css" media="print">
</head>

<body id="programm">
	<?php include "../inc/header.inc"; ?>

        <!-- This file was generated by a script. Do not edit this file in Git,
             edit contents in Pretalx, regenerate the PHP files and commit them
             in the Git repository of the website. -->
        <p><a href="programm/freitag.php#session_7KUG7F">&#9668;&#9668; zurück zum Programm</a> </p>
        <h2 class='abstract-title'>Workshop Datenschutz und geographische Informationen</h2>
        <section>
            <p>
                <span class='abstract-sessiontype'>Workshop</span> von                <span class='abstract-speakers'>Falk Zscheile</span></p>
                <p class='abstract-is-workshop'>Bitte melden Sie sich im <a href="https://pretix.eu/fossgis/2020/">Ticketshop</a> für diesen Workshop an, wenn Sie daran teilnehmen möchten. Workshopbuchungen sind auch nach der Ticketbuchung online und auf der Konferenz möglich.</p>            <p><span class='abstract-time-heading'>Zeit: </span>Freitag 13. März 08:00 Uhr<br><span class='abstract-room-heading'>Ort: </span>SR R-110</p>

            
            <p>Die Georeferenzierung von unterschiedlichsten Fachinformationen mit der Möglichkeit diese über die geographische Position in Beziehung zueinander zu setzen, macht das besondere Potential geographischer Informationen aus.</p>
<p>Sobald hier personenbezogene Informationen ins Spiel kommen, sind an die Verarbeitung geographischer Informationen besondere Anforderungen zu stellen.</p>
<p>Bei der Verknüpfung von Sachinformationen mit Grundstücken oder Adressen ist die Abgrenzung zwischen Sachinformation und personenbezogener Information besonders schwierig. Ein Personenbezug lässt sich hier über die entsprechenden Register (Kataster, Grundbuch) oder Adressverzeichnisse zu Eigentümern und Mietern herstellen.</p>
<p>Der Workshop gibt Anhaltspunkte für die Abgrenzung von personenbezogenen und sachbezogenen Informationen im Zusammenhang mit Grundstücken.</p>
<p>Liegen personenbezogenen geographische Informationen vor, so werden die formellen und materiellen Anforderungen der Datenschutzgrundverordnung an die Datenverarbeitung vorgestellt. Die soll Verarbeitern geographischer Informationen in die Lage versetzen, beurteilen zu können, ob im Hinblick auf den Datenschutz Handlungsbedarf besteht.</p>
        </section>


	<?php include "../inc/footer.inc"; ?>

</body>

</html>