<!doctype html>
<html lang="de">

<head>
	<meta charset="utf-8">
<meta http-equiv="x-ua-compatible" content="ie=edge">
<meta name="description" content="Die FOSSGIS-Konferenz ist im D-A-CH Raum die führende Konferenz für Freie und Open Source Software für Geoinformationssysteme OpenStreetMap.">
<meta name="keywords" content="FOSSGIS, FOSSGIS-Konferenz, 2019, FOSSGIS-Konferenz 2019, Open Source, GIS, Konferenz, Geoinformatik, OpenStreetMap, HTW Dresden">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="apple-itunes-app" content="app-id=1453299630">

	<base href="/2020/sessions">
	<title>Einführung in die Verwaltung von Geodaten in der PostgreSQL-Datenbank mit PostGIS – FOSSGIS 2020</title>

	<link rel="stylesheet" href="./css/normalize.css">
	<link rel="stylesheet" href="./css/base.css">
	<link rel="stylesheet" href="./css/print.css" media="print">
</head>

<body id="programm">
	<header class="page-header">
	<a href="./" alt="FOSSGIS Konferenz 2020">
		<img class="page-logo" src="./img/fossgis2020-bollenhut.png">
	</a>
	<h1 class="page-title">
		FOSSGIS-Konferenz 2020<br>
		<span class="amp">Freiburg</span> <br>
		<span class="amp">11.&ndash;14. März</span>
	</h1>
</header>

<nav>
	<ul class="main">
		<li id="navHome">
			<a href="./">Startseite</a>
		</li>
		<!--<li id="navAnmeldung">
			<a href="./anmeldung/">Anmeldung</a>
		</li>-->
		<li id="navProgramm">
		<a href="./programm/">Programm</a>
		</li>
		<!--<li id="navAnreise">
			<a href="./anreise/">Anreise</a>
		</li>-->
		<li id="navStandort">
			<a href="./standort/">Standort</a>
		</li>
		<li id="navEvents">
			<a href="./socialevents/">Social Events</a>
		</li>
		<li id="navTeam">
			<a href="./loc/loc.php">Team</a>
		</li>
	</ul>
</nav>

<div class="hero">
	<figure>
		<img class="img-fluid" src="./img/freiburg.jpg" alt="Freiburg Luftbild">
		<figcaption>Photo: Pixaby</figcaption>
	</figure>
</div>

        <!-- This file was generated by a script. Do not edit this file in Git,
             edit contents in Pretalx, regenerate the PHP files and commit them
             in the Git repository of the website. -->
        <p><a href="programm/donnerstag.php#session_7RFJ9N">&#9668;&#9668; zurück zum Programm</a> </p>
        <h2 class='abstract-title'>Einführung in die Verwaltung von Geodaten in der PostgreSQL-Datenbank mit PostGIS</h2>
        <section>
            <p>
                <span class='abstract-sessiontype'>Workshop</span> von                <span class='abstract-speakers'>Astrid Emde, Lina Dillmann</span></p>
                <p class='abstract-is-workshop'>Bitte melden Sie sich im <a href="https://pretix.eu/fossgis/2020/">Ticketshop</a> für diesen Workshop an, wenn Sie daran teilnehmen möchten.</p>            <p><span class='abstract-time-heading'>Zeit: </span>Donnerstag 12. März 15:30 Uhr<br><span class='abstract-room-heading'>Ort: </span>SR R-110</p>

                        <p><a href="/2020/attachments/7RFJ9N_fossgis-2020-workshop-postgresql-postgis-fuer-ei_l3w3cRh.md">Vortragsfolien (PDF) </a></p>
            <ul>
<li>Einführung PostgreSQL / PostGIS - Vorstellung der Möglichkeiten (Vektordaten, Rasterdaten)</li>
<li>Datenmodell</li>
<li>Visualisierung von Daten mit QGIS</li>
<li>Datenimport über QGIS DB Verwaltung &amp; weitere Schnittstellen</li>
<li>Eintauchen in die Welt der PostGIS-Funktionen</li>
</ul>
<p>Der Workshop nutzt <a href="https://live.osgeo.org/de/">OSGeoLive 13.0</a> und die globalen <a href="https://live.osgeo.org/de/overview/naturalearth_overview.html">Natural Earth Daten</a>.</p>
<ul>
<li>https://www.postgresql.org/</li>
<li>http://postgis.net/</li>
</ul>
<p>Dieser Workshop findet auch <a href="https://fossgis-konferenz.de/2020/sessions/RUEZJ7.php">am Freitag</a> statt.</p>
        <div class='abstract-bio'>
            <h3 class='abstract-bio-name'>Astrid Emde</h3>
            <p>Astrid Emde war bisher bei allen FOSSGIS-Konferenzen dabei und freut sich auf die FOSSGIS 2020 in Freiburg!</p>
<p>Sie befasst sich seit vielen Jahren mit Geodaten und FOSSGIS und hat schon zahlreiche Projekte vor allem im WebGIS-Bereich umgesetzt.</p>
<p>Sie weist Erfahrung mit PostgreSQL und PostGIS, MapServer, GeoServer, QGIS, QGIS Server und Mapbender auf. Weiterhin Apache Solr, OpenLayers, MapProxy, OGC Standards &amp; Skripting.</p>
<p>Astrid Emde arbeitet bei der <a href="https://wheregroup.com">WhereGroup</a> in Bonn und hat schon viele Workshops und Präsentationen zu Mapbender, MapServer, GeoServer, PostgreSQL/PostGIS, OWS oder allgemein zum Aufbau einer GDI gehalten. Sie ist Dozentin der [FOSS Academy] (https://www.foss-academy.com), dem Schulungsinstitut der WhereGroup (https://www.wheregroup.com)</p>
<p>Seit über 10 Jahren engagiert sie sich im <a href="https://mapbender.org">Mapbender</a>-Projekt und gehört zum Mapbender Team (http://mapbender.org) und dem Mapbender PSC (Project Steering Committee).</p>
<p>Astrid Emde ist in der <a href="https://osgeo.org">OSGeo</a> Foundation (http://osgeo.org) aktiv. Sie ist 2010 zum Charter Member und 2017 in das OSGeo Board of Directors (Vorstand der OSGeo) und zur OSGeo Secretary gewählt worden. Dadurch übernimmt sie zahlreiche Aufgaben bei der OSGeo und ist darüber hinaus im Bereich Marketing, Presse, Community Meetings und OSGeoLive (http://live.osgeo.org/) aktiv. 2018 erhielt sie für ihr Engagement den <a href="https://www.osgeo.org/community/awards/">Sol Katz Award der OSGeo</a>.</p>
<p>Auch im <a href="http://fossgis.de">FOSSGIS e.V.</a> ist Astrid Emde aktiv. Sie gehört zum Team der jährlich stattfindenden FOSSGIS-Konferenz, engagiert sich in der Vereins-Öffentlichkeitsarbeit und der Organisation von Community Events (http://fossgis.de).</p>
        </div>
        <div class='abstract-bio'>
            <h3 class='abstract-bio-name'>Lina Dillmann</h3>
            <p>Lina Dillmann ist zum zweiten Mal bei der FOSSGIS Konferenz dabei.</p>
<p>Die letzten Jahren war sie als User Interface &amp; User Experience Designerin tätig und hat allerlei Software entwickelt und optimiert. Mitte 2018 zog es sie zur WhereGroup in Bonn, wo sie im Requirements Engineering arbeitet.</p>
<p>Privat lebt sie seit 2012 ihr Organisationsfaible beim Webmontag Bonn aus und ist oft auf den Bonner (Tech-) Meetups zu finden, wo sie ihren Wissensdurst stillt.</p>
<p>Design, Kunst und Kultur liebt sie. Ein Buch hat sie immer dabei und praktiziert täglich Meditation und Yoga.</p>
<p>Sie ist Mitglied im FOSSGIS e.V. und bei den Digital Media Women e.V..</p>
        </div>
        </section>


	<footer>
	<ul class="main">
		<li>
			<a href="https://www.fossgis.de/impressum/">Impressum</a>
		</li>
		<li>
			<a href="./agb.php">AGB</a>
		</li>
		<li>
			<a href="https://www.fossgis.de/datenschutzerklärung">Datenschutzerklärung</a>
		</li>
	</ul>
</footer>

</body>

</html>