<!doctype html>
<html lang="de">

<head>
	<?php include "../inc/meta.inc"; ?>

	<base href="<?php echo dirname($_SERVER['SCRIPT_NAME']); ?>">
	<title>QGIS-Übersetzung – FOSSGIS 2020</title>

	<link rel="stylesheet" href="./css/normalize.css">
	<link rel="stylesheet" href="./css/base.css">
	<link rel="stylesheet" href="./css/print.css" media="print">
</head>

<body id="programm">
	<?php include "../inc/header.inc"; ?>

        <!-- This file was generated by a script. Do not edit this file in Git,
             edit contents in Pretalx, regenerate the PHP files and commit them
             in the Git repository of the website. -->
        <p><a href="programm/mittwoch.php#session_8D7WEC">&#9668;&#9668; zurück zum Programm</a> <a href="sessions/lightning_talks_1.php">&#9668; zurück zur Session</a></p>
        <h2 class='abstract-title'>QGIS-Übersetzung</h2>
        <section>
            <p>
                <span class='abstract-sessiontype'>Lightning Talk</span> von                <span class='abstract-speakers'>Bernhard Ströbl</span></p>
                            <p><span class='abstract-time-heading'>Zeit: </span>Mittwoch 11. März 18:10 Uhr<br><span class='abstract-room-heading'>Ort: </span>HS Rundbau</p>

            
            <p>Ein deutschsprachiges Handbuch ist ein Wunsch, der regelmäßig aus der Anwenderschaft an die QGIS-Anwendergruppe Deutschland herangetragen wird. Letztes Jahr hat sich eine Gruppe gebildet, die diese Übersetzung vorantreiben und aktuell halten will. Der Talk beleuchtet die technischen Herausforderungen, und die dafür gefundenen Lösungen und möchte weitere Anwender dazu motivieren, dem Übersetzungsteam beizutreten.</p>
        </section>


	<?php include "../inc/footer.inc"; ?>

</body>

</html>