<!doctype html>
<html lang="de">

<head>
	<?php include "../inc/meta.inc"; ?>

	<base href="<?php echo dirname($_SERVER['SCRIPT_NAME']); ?>">
	<title>WebGIS kleiner Gemeinden mit QGIS-Server und Lizmap – FOSSGIS 2020</title>

	<link rel="stylesheet" href="./css/normalize.css">
	<link rel="stylesheet" href="./css/base.css">
	<link rel="stylesheet" href="./css/print.css" media="print">
</head>

<body id="programm">
	<?php include "../inc/header.inc"; ?>

        <!-- This file was generated by a script. Do not edit this file in Git,
             edit contents in Pretalx, regenerate the PHP files and commit them
             in the Git repository of the website. -->
        <p><a href="programm/mittwoch.php#session_8WBR7B">&#9668;&#9668; zurück zum Programm</a> </p>
        <h2 class='abstract-title'>WebGIS kleiner Gemeinden mit QGIS-Server und Lizmap</h2>
        <section>
            <p>
                                <span class='abstract-speakers'>Günter Wagner</span></p>
                            <p><span class='abstract-time-heading'>Zeit: </span>Mittwoch 11. März 16:00 Uhr<br><span class='abstract-room-heading'>Ort: </span>HS Rundbau</p>

            
            <p>Die Anforderungen und Datenvoraussetzungen dieser kleinen Gemeinden (hier speziell in Südbaden) unterscheiden sich von größeren Städten / Strukturen. Warum benötigt eine kleine Gemeinde ein <strong>eigenes</strong> WebGIS und welche Daten stehen Ihr zur Verfügung?</p>
<p>Die technische Umsetzung mit den wesentlichen Komponenten QGIS, QGIS-Server, PostgreSQL/PostGIS und dem Web Client Lizmap wird skizziert und dabei die Gründe für die Auswahl dieser Komponenten erläutert.</p>
<p>Es wird auch gezeigt, wie GDI-ähnliche Strukturen die Zusammenarbeit der unterschiedlichen Ingenieurbüros mit der Gemeinde verbessern können und wie die Gemeinde auch im lokalen GIS davon profitieren kann.</p>
<p>Zum Abschluss wird der effektive Workflow vom lokalen QGIS-Projekt zur WebGIS-Anwendung anhand von Beispielanwendungen live gezeigt.</p>
        <div class='abstract-bio'>
            <h3 class='abstract-bio-name'>Günter Wagner</h3>
            <p>Günter Wagner betreut seit über 20 Jahren kleinere Gemeinden und Städte in Bezug auf CAD/GIS/WebGIS-Anwendungen und Dienstleistungen.</p>
<p>Individuelle, an die Bedürfnisse des Kunden angepasste Lösungen werden auf Basis von Standardkomponenten, möglichst aus dem Open-Source Bereich, realisiert. </p>
<p>Seit 2011 betreibt H. Wagner das Ingenieurbüro <a href="https://wagner-it.de">Wagner-IT</a>. Er ist Mitglied im FOSSGIS e.V. und QGIS-DE e.V. und unterstützt das QGIS-Projekt als Bronze-Sponsor.</p>
        </div>
        </section>


	<?php include "../inc/footer.inc"; ?>

</body>

</html>