<!doctype html>
<html lang="de">

<head>
	<meta charset="utf-8">
<meta http-equiv="x-ua-compatible" content="ie=edge">
<meta name="description" content="Die FOSSGIS-Konferenz ist im D-A-CH Raum die führende Konferenz für Freie und Open Source Software für Geoinformationssysteme OpenStreetMap.">
<meta name="keywords" content="FOSSGIS, FOSSGIS-Konferenz, 2019, FOSSGIS-Konferenz 2019, Open Source, GIS, Konferenz, Geoinformatik, OpenStreetMap, HTW Dresden">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="apple-itunes-app" content="app-id=1453299630">

	<base href="/2020/sessions">
	<title>WebGIS kleiner Gemeinden mit QGIS-Server und Lizmap – FOSSGIS 2020</title>

	<link rel="stylesheet" href="./css/normalize.css">
	<link rel="stylesheet" href="./css/base.css">
	<link rel="stylesheet" href="./css/print.css" media="print">
</head>

<body id="programm">
	<header class="page-header">
	<a href="./" alt="FOSSGIS Konferenz 2020">
		<img class="page-logo" src="./img/fossgis2020-bollenhut.png">
	</a>
	<h1 class="page-title">
		FOSSGIS-Konferenz 2020<br>
		<span class="amp">Freiburg</span> <br>
		<span class="amp">11.&ndash;14. März</span>
	</h1>
</header>

<nav>
	<ul class="main">
		<li id="navHome">
			<a href="./">Startseite</a>
		</li>
		<!--<li id="navAnmeldung">
			<a href="./anmeldung/">Anmeldung</a>
		</li>-->
		<li id="navProgramm">
		<a href="./programm/">Programm</a>
		</li>
		<!--<li id="navAnreise">
			<a href="./anreise/">Anreise</a>
		</li>-->
		<li id="navStandort">
			<a href="./standort/">Standort</a>
		</li>
		<li id="navEvents">
			<a href="./socialevents/">Social Events</a>
		</li>
		<li id="navTeam">
			<a href="./loc/loc.php">Team</a>
		</li>
	</ul>
</nav>

<div class="hero">
	<figure>
		<img class="img-fluid" src="./img/freiburg.jpg" alt="Freiburg Luftbild">
		<figcaption>Photo: Pixaby</figcaption>
	</figure>
</div>

        <!-- This file was generated by a script. Do not edit this file in Git,
             edit contents in Pretalx, regenerate the PHP files and commit them
             in the Git repository of the website. -->
        <p><a href="programm/mittwoch.php#session_8WBR7B">&#9668;&#9668; zurück zum Programm</a> </p>
        <h2 class='abstract-title'>WebGIS kleiner Gemeinden mit QGIS-Server und Lizmap</h2>
        <section>
            <p>
                                <span class='abstract-speakers'>Günter Wagner</span></p>
                            <p><span class='abstract-time-heading'>Zeit: </span>Mittwoch 11. März 16:00 Uhr<br><span class='abstract-room-heading'>Ort: </span>HS Rundbau</p>

                        <div class="video-container">
                <a href="https://media.ccc.de/v/fossgis2020-2994-webgis-kleiner-gemeinden-mit-qgis-server-und-lizmap">
                    <img class="video-preview" src="video_previews/2994-hd.jpg" alt="Vorschaubild des Videos">
                    <div class="video-preview-overlay"></div>
                </a>
            </div>
                        <p><a href="/2020/attachments/8WBR7B_Vortrag_WebGIS_Kleiner_Gemeinden_Guenter_Wagner_vOCC1Uq.pdf">Vortragsfolien (PDF) </a></p>
            <p>Die Anforderungen und Datenvoraussetzungen dieser kleinen Gemeinden (hier speziell in Südbaden) unterscheiden sich von größeren Städten / Strukturen. Warum benötigt eine kleine Gemeinde ein <strong>eigenes</strong> WebGIS und welche Daten stehen Ihr zur Verfügung?</p>
<p>Die technische Umsetzung mit den wesentlichen Komponenten QGIS, QGIS-Server, PostgreSQL/PostGIS und dem Web Client Lizmap wird skizziert und dabei die Gründe für die Auswahl dieser Komponenten erläutert.</p>
<p>Es wird auch gezeigt, wie GDI-ähnliche Strukturen die Zusammenarbeit der unterschiedlichen Ingenieurbüros mit der Gemeinde verbessern können und wie die Gemeinde auch im lokalen GIS davon profitieren kann.</p>
<p>Zum Abschluss wird der effektive Workflow vom lokalen QGIS-Projekt zur WebGIS-Anwendung anhand von Beispielanwendungen live gezeigt.</p>
        <div class='abstract-bio'>
            <h3 class='abstract-bio-name'>Günter Wagner</h3>
            <p>Günter Wagner betreut seit über 20 Jahren kleinere Gemeinden und Städte in Bezug auf CAD/GIS/WebGIS-Anwendungen und Dienstleistungen.</p>
<p>Individuelle, an die Bedürfnisse des Kunden angepasste Lösungen werden auf Basis von Standardkomponenten, möglichst aus dem Open-Source Bereich, realisiert. </p>
<p>Seit 2011 betreibt H. Wagner das Ingenieurbüro <a href="https://wagner-it.de">Wagner-IT</a>. Er ist Mitglied im FOSSGIS e.V. und QGIS-DE e.V. und unterstützt das QGIS-Projekt als Bronze-Sponsor.</p>
        </div>
        </section>


	<footer>
	<ul class="main">
		<li>
			<a href="https://www.fossgis.de/impressum/">Impressum</a>
		</li>
		<li>
			<a href="./agb.php">AGB</a>
		</li>
		<li>
			<a href="https://www.fossgis.de/datenschutzerklärung">Datenschutzerklärung</a>
		</li>
	</ul>
</footer>

</body>

</html>