<!doctype html>
<html lang="de">

<head>
	<meta charset="utf-8">
<meta http-equiv="x-ua-compatible" content="ie=edge">
<meta name="description" content="Die FOSSGIS-Konferenz ist im D-A-CH Raum die führende Konferenz für Freie und Open Source Software für Geoinformationssysteme OpenStreetMap.">
<meta name="keywords" content="FOSSGIS, FOSSGIS-Konferenz, 2019, FOSSGIS-Konferenz 2019, Open Source, GIS, Konferenz, Geoinformatik, OpenStreetMap, HTW Dresden">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="apple-itunes-app" content="app-id=1453299630">

	<base href="/2020/sessions">
	<title>QGIS-Kartografie-Verbesserungen 2019 – FOSSGIS 2020</title>

	<link rel="stylesheet" href="./css/normalize.css">
	<link rel="stylesheet" href="./css/base.css">
	<link rel="stylesheet" href="./css/print.css" media="print">
</head>

<body id="programm">
	<header class="page-header">
	<a href="./" alt="FOSSGIS Konferenz 2020">
		<img class="page-logo" src="./img/fossgis2020-bollenhut.png">
	</a>
	<h1 class="page-title">
		FOSSGIS-Konferenz 2020<br>
		<span class="amp">Freiburg</span> <br>
		<span class="amp">11.&ndash;14. März</span>
	</h1>
</header>

<nav>
	<ul class="main">
		<li id="navHome">
			<a href="./">Startseite</a>
		</li>
		<!--<li id="navAnmeldung">
			<a href="./anmeldung/">Anmeldung</a>
		</li>-->
		<li id="navProgramm">
		<a href="./programm/">Programm</a>
		</li>
		<!--<li id="navAnreise">
			<a href="./anreise/">Anreise</a>
		</li>-->
		<li id="navStandort">
			<a href="./standort/">Standort</a>
		</li>
		<li id="navEvents">
			<a href="./socialevents/">Social Events</a>
		</li>
		<li id="navTeam">
			<a href="./loc/loc.php">Team</a>
		</li>
	</ul>
</nav>

<div class="hero">
	<figure>
		<img class="img-fluid" src="./img/freiburg.jpg" alt="Freiburg Luftbild">
		<figcaption>Photo: Pixaby</figcaption>
	</figure>
</div>

        <!-- This file was generated by a script. Do not edit this file in Git,
             edit contents in Pretalx, regenerate the PHP files and commit them
             in the Git repository of the website. -->
        <p><a href="programm/donnerstag.php#session_8ZASBP">&#9668;&#9668; zurück zum Programm</a> </p>
        <h2 class='abstract-title'>QGIS-Kartografie-Verbesserungen 2019</h2>
        <section>
            <p>
                                <span class='abstract-speakers'>Andreas Neumann</span></p>
                            <p><span class='abstract-time-heading'>Zeit: </span>Donnerstag 12. März 13:30 Uhr<br><span class='abstract-room-heading'>Ort: </span>HS Rundbau</p>

                        <div class="video-container">
                <a href="https://media.ccc.de/v/fossgis2020-3079-qgis-kartografie-verbesserungen-2019">
                    <img class="video-preview" src="video_previews/3079-hd.jpg" alt="Vorschaubild des Videos">
                    <div class="video-preview-overlay"></div>
                </a>
            </div>
                        <p><a href="/2020/attachments/8ZASBP_QGIS_Kartografie-Verbesserungen_2019_-_FOSSGIS__LYHsMgv.pdf">Vortragsfolien (PDF) </a></p>
            <p>Im Vortrag werden Verbesserungen aus den folgenden Themenbereichen behandelt:</p>
<ul>
<li>Selektives Maskieren bei Beschriftungen und Symbolen</li>
<li>Zufalls-Muster</li>
<li>Hashed-Linie (Weiterentwicklung der Markierungslinie)</li>
<li>Beschriftungs-Verbesserungen</li>
<li>Geometrie-Generatoren</li>
<li>Dynamische Kartengitter</li>
<li>ev. GeoPDF-Export / Import</li>
</ul>
<p>Neben den eigentlichen neuen Funktionalitäten werden jeweils Beispiele aus der Praxis gezeigt. </p>
<p>Als Ausblick/Diskussion wird eine Liste möglicher weiterer Kartografie-Verbesserungen vorgestellt an denen in zukünftigen QGIS-Versionen gearbeitet werden könnte, mit dem Ziel Gleichgesinnte zu finden, die helfen die nötigen Spezifikationen zu schreiben oder zu verbessern, zu entwickeln oder mitzufinanzieren.</p>
        <div class='abstract-bio'>
            <h3 class='abstract-bio-name'>Andreas Neumann</h3>
            <p>Andreas ist Teammitglied des QGIS Projekts und Vorstandsmitglied (Kassier) von QGIS.ORG seit 2015. Hauptberuflich arbeitet er als Projekt-Leiter und Entwickler beim Amt für Geoinformation des Kantons Solothurn in der Schweiz.</p>
        </div>
        </section>


	<footer>
	<ul class="main">
		<li>
			<a href="https://www.fossgis.de/impressum/">Impressum</a>
		</li>
		<li>
			<a href="./agb.php">AGB</a>
		</li>
		<li>
			<a href="https://www.fossgis.de/datenschutzerklärung">Datenschutzerklärung</a>
		</li>
	</ul>
</footer>

</body>

</html>