<!doctype html>
<html lang="de">

<head>
	<meta charset="utf-8">
<meta http-equiv="x-ua-compatible" content="ie=edge">
<meta name="description" content="Die FOSSGIS-Konferenz ist im D-A-CH Raum die führende Konferenz für Freie und Open Source Software für Geoinformationssysteme OpenStreetMap.">
<meta name="keywords" content="FOSSGIS, FOSSGIS-Konferenz, 2019, FOSSGIS-Konferenz 2019, Open Source, GIS, Konferenz, Geoinformatik, OpenStreetMap, HTW Dresden">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="apple-itunes-app" content="app-id=1453299630">

	<base href="/2020/sessions">
	<title>FOSS konsequent nutzen – FOSSGIS 2020</title>

	<link rel="stylesheet" href="./css/normalize.css">
	<link rel="stylesheet" href="./css/base.css">
	<link rel="stylesheet" href="./css/print.css" media="print">
</head>

<body id="programm">
	<header class="page-header">
	<a href="./" alt="FOSSGIS Konferenz 2020">
		<img class="page-logo" src="./img/fossgis2020-bollenhut.png">
	</a>
	<h1 class="page-title">
		FOSSGIS-Konferenz 2020<br>
		<span class="amp">Freiburg</span> <br>
		<span class="amp">11.&ndash;14. März</span>
	</h1>
</header>

<nav>
	<ul class="main">
		<li id="navHome">
			<a href="./">Startseite</a>
		</li>
		<!--<li id="navAnmeldung">
			<a href="./anmeldung/">Anmeldung</a>
		</li>-->
		<li id="navProgramm">
		<a href="./programm/">Programm</a>
		</li>
		<!--<li id="navAnreise">
			<a href="./anreise/">Anreise</a>
		</li>-->
		<li id="navStandort">
			<a href="./standort/">Standort</a>
		</li>
		<li id="navEvents">
			<a href="./socialevents/">Social Events</a>
		</li>
		<li id="navTeam">
			<a href="./loc/loc.php">Team</a>
		</li>
	</ul>
</nav>

<div class="hero">
	<figure>
		<img class="img-fluid" src="./img/freiburg.jpg" alt="Freiburg Luftbild">
		<figcaption>Photo: Pixaby</figcaption>
	</figure>
</div>

        <!-- This file was generated by a script. Do not edit this file in Git,
             edit contents in Pretalx, regenerate the PHP files and commit them
             in the Git repository of the website. -->
        <p><a href="programm/freitag.php#session_9LDKZ3">&#9668;&#9668; zurück zum Programm</a> <a href="sessions/lightning_talks_5.php">&#9668; zurück zur Session</a></p>
        <h2 class='abstract-title'>FOSS konsequent nutzen</h2>
        <section>
            <p>
                <span class='abstract-sessiontype'>Lightning Talk</span> von                <span class='abstract-speakers'>Lars Roskoden</span></p>
                            <p><span class='abstract-time-heading'>Zeit: </span>Freitag 13. März 12:10 Uhr<br><span class='abstract-room-heading'>Ort: </span>HS Anatomie</p>

                        <div class="video-container">
                <a href="https://media.ccc.de/v/fossgis2020-4726-foss-konsequent-nutzen">
                    <img class="video-preview" src="video_previews/4726-hd.jpg" alt="Vorschaubild des Videos">
                    <div class="video-preview-overlay"></div>
                </a>
            </div>
                        <p><a href="/2020/attachments/9LDKZ3_lightning-talk-foss-nutzen-lars-roskoden_HqDom95.pdf">Vortragsfolien (PDF) </a></p>
            <p>Dieser Lightning Talk möchte neben den hier auf der Konferenz beleuchtenten FOSS im GIS-Bereich auf weitere FOSS-Anwendungen hinweisen, die man auch in anderen Lebenslagen als Endanwender nutzen kann.</p>
<p>FOSS ist gelebte Demokratie: viele Menschen entscheiden nach mehr oder weniger ausgiebigen Diskussionen zu einem bestimmten Thema innerhalb ihres Arbeits- bzw. Fachbereichs mehrheitlich über Regeln, Strategien und Ziele. Jedefrau kann sich einbringen.</p>
<p>Im GIS-Bereich sind in den letzten Jahren bzw. Jahrzehnten mit OpentStreetMap und QGIS zwei sehr erfolgreiche und andwenderfreundliche Sphären entstanden.</p>
<p>Doch auch in anderen Bereichen des alltäglichen digitalen Lebens finden FOSS-Entwicklungen statt, von denen ich hier einige Beispiele nennen möchte:</p>
<p>LineageOS statt Android​</p>
<p>F-Droid statt GooglePlayStore​</p>
<p>SearX statt Google-Suche</p>
<p>Mastodon statt Twitter​</p>
<p>Conversations statt WhatsApp​</p>
<p>Diaspora statt Facebook</p>
<p>Pixelfed statt Instagram</p>
<p>Nextcloud statt dropbox</p>
<p>PeerTube statt YouTube</p>
<p>nuudel statt doodle</p>
        </section>


	<footer>
	<ul class="main">
		<li>
			<a href="https://www.fossgis.de/impressum/">Impressum</a>
		</li>
		<li>
			<a href="./agb.php">AGB</a>
		</li>
		<li>
			<a href="https://www.fossgis.de/datenschutzerklärung">Datenschutzerklärung</a>
		</li>
	</ul>
</footer>

</body>

</html>