<!doctype html>
<html lang="de">

<head>
	<?php include "../inc/meta.inc"; ?>

	<base href="<?php echo dirname($_SERVER['SCRIPT_NAME']); ?>">
	<title>Neues zum Lyrk-Mapstyle; Was kommt danach? – FOSSGIS 2020</title>

	<link rel="stylesheet" href="./css/normalize.css">
	<link rel="stylesheet" href="./css/base.css">
	<link rel="stylesheet" href="./css/print.css" media="print">
</head>

<body id="programm">
	<?php include "../inc/header.inc"; ?>

        <!-- This file was generated by a script. Do not edit this file in Git,
             edit contents in Pretalx, regenerate the PHP files and commit them
             in the Git repository of the website. -->
        <p><a href="programm/freitag.php#session_ADEWD7">zurück zum Programm</a></p>
        <h2 class='abstract-title'>Neues zum Lyrk-Mapstyle; Was kommt danach?</h2>
        <section>
            <p>
                <span class='abstract-sessiontype'>Lightning Talk</span> von                <span class='abstract-speakers'>Robert Klemm</span></p>
            <p><span class='abstract-time-heading'>Zeit: </span>Freitag 13. März 09:05 Uhr<br><span class='abstract-room-heading'>Ort: </span>HS Weismannhaus</p>

            
            <p>Der <a href="https://github.com/lyrk/lyrk-mapstyle">Lyrk-Mapstyle</a>  ist ein OpenStreetMap-Kartenstyle, der auf dem OSM-Bright Style aufsetzt. Seit 2016 wurde das Projekt gestartet,  wurde in den letzten Jahren in neuer Version veröffentlicht.</p>
<p>Ich erkläre kurz welche Erneuerungen im letzten Release durchgeführt wurden und welche Herausforderungen in der Zukunft auf das Projekt warten.</p>
        </section>


	<?php include "../inc/footer.inc"; ?>

</body>

</html>