<!doctype html>
<html lang="de">

<head>
	<?php include "../inc/meta.inc"; ?>

	<base href="<?php echo dirname($_SERVER['SCRIPT_NAME']); ?>">
	<title>Einführung in GeoServer – FOSSGIS 2020</title>

	<link rel="stylesheet" href="./css/normalize.css">
	<link rel="stylesheet" href="./css/base.css">
	<link rel="stylesheet" href="./css/print.css" media="print">
</head>

<body id="programm">
	<?php include "../inc/header.inc"; ?>

        <!-- This file was generated by a script. Do not edit this file in Git,
             edit contents in Pretalx, regenerate the PHP files and commit them
             in the Git repository of the website. -->
        <p><a href="programm/donnerstag.php#session_BPWXKG">zurück zum Programm</a></p>
        <h2 class='abstract-title'>Einführung in GeoServer</h2>
        <section>
            <p>
                <span class='abstract-sessiontype'>Workshop</span> von                <span class='abstract-speakers'>Hannes Blitza, Daniel Koch</span></p>
            <p><span class='abstract-time-heading'>Zeit: </span>Donnerstag 12. März 08:00 Uhr<br><span class='abstract-room-heading'>Ort: </span>SR R-140</p>

            
            <p>Der GeoServer ist ein bekannter und vielerorts genutzter Open-Source-Kartenserver, der viele OGC-Standards unterstützt. GeoServer ermöglicht die Veröffentlichung von Geodaten- und Kartendiensten aus zahlreichen Datenquellen.</p>
<p>Dieser Workshop hat eine Einführung in die entscheidenden Konzepte und Funktionen des GeoServers zum Ziel und wird sich auf die wichtigsten Schritte der Publizierung eigener Kartendienste fokussieren. Dabei werden die Teilnehmer eigene Vektor- und Rasterdaten für den optimalen Einsatz im GeoServer vorbereiten, Daten aus diversen Quellen einbinden, diese als WMS und WFS Dienste bereitstellen und Layerstile über SLD (Styled Layer Descriptor) definieren.</p>
<p>Zielgruppe sind alle Interessierten, die die Möglichkeiten vom GeoServer kennenlernen wollen. Vorkenntnisse im GeoServer sind nicht notwendig.</p>
        </section>


	<?php include "../inc/footer.inc"; ?>

</body>

</html>