<!doctype html>
<html lang="de">

<head>
	<?php include "../inc/meta.inc"; ?>

	<base href="<?php echo dirname($_SERVER['SCRIPT_NAME']); ?>">
	<title>Geoprocessing mit OpenCaching – FOSSGIS 2020</title>

	<link rel="stylesheet" href="./css/normalize.css">
	<link rel="stylesheet" href="./css/base.css">
	<link rel="stylesheet" href="./css/print.css" media="print">
</head>

<body id="programm">
	<?php include "../inc/header.inc"; ?>

        <!-- This file was generated by a script. Do not edit this file in Git,
             edit contents in Pretalx, regenerate the PHP files and commit them
             in the Git repository of the website. -->
        <p><a href="programm/donnerstag.php#session_BYJJNM">&#9668;&#9668; zurück zum Programm</a> </p>
        <h2 class='abstract-title'>Geoprocessing mit OpenCaching</h2>
        <section>
            <p>
                                <span class='abstract-speakers'>Matthias Hinz</span></p>
                            <p><span class='abstract-time-heading'>Zeit: </span>Donnerstag 12. März 13:30 Uhr<br><span class='abstract-room-heading'>Ort: </span>HS Weismannhaus</p>

                        <p><a href="/2020//attachments/BYJJNM_Fossgis_hinz_processing_mit_opencaching_M94DeSW.pdf">Vortragsfolien</a></p>
            <p>OpenCaching.de ist die zweitgrößte Geocaching-Plattform in Mitteleuropa. Mit über 26.000 Geocaches, deren Metadaten über eine offene Web-API ausgelesen werden kann, eignet sie sich auch hervorragend als Lehrbeispiel für den Umgang mit Geodaten. Der Vortrag gibt einen kurzen Überblick über das Fallbeispiel im Onlinekurs, sowie über das Vorgehen und Ergebnisse der Analyse.</p>
<p>Inhalte der Geocaching-Datenbank sollen mit Landnutzungsdaten (CORINE Landcover) und Auszügen der Europäischen Statistik (EUROSTAT) verknüpft werden. Durch intelligentes Aufbereiten und Kontextualisierung der Daten werden Erkenntnisse über die Verteilung von Geocaches in Mitteleuropa gewonnen. Dabei werden fortgeschrittene Werkzeuge aus dem GeoIT-Bereich genutzt, darunter eine PostGIS-Datenbank, der QGIS Graphical Modeler, SQL-Queries und Python-Scripting.</p>
<p>Auf der offenen Lernplattform von OpenGeoEdu (https://learn.opengeoedu.de) ist die Analyse ausführlich beschrieben und kann von Interessierten selbst online durchgearbeitet werden. Im Rahmen des offenen Onlinekurses OpenGeoEdu kann dazu ein wissenschaftlicher Beleg eingereicht und mit Credit Points zertifiziert werden. Als offenes Lehrmaterial kann das Fallbeispiel auch durch Lehrende in GIS-Kursen oder Weiterbildungen eingebunden werden.</p>
        <div class='abstract-bio'>
            <h3 class='abstract-bio-name'>Matthias Hinz</h3>
            <p>Als wissenschaftlicher Angestellter an der Universität Rostock und studierter Geoinformatiker begeistere ich mich für Themen rund um (FOSS-)GIS, Open Data und E-Learning.
http://matthiashinz.eu/</p>
        </div>
        </section>


	<?php include "../inc/footer.inc"; ?>

</body>

</html>