<!doctype html>
<html lang="de">

<head>
	<?php include "../inc/meta.inc"; ?>

	<base href="<?php echo dirname($_SERVER['SCRIPT_NAME']); ?>">
	<title>Map Editor für individuelle amtliche Vektorkarten – FOSSGIS 2020</title>

	<link rel="stylesheet" href="./css/normalize.css">
	<link rel="stylesheet" href="./css/base.css">
	<link rel="stylesheet" href="./css/print.css" media="print">
</head>

<body id="programm">
	<?php include "../inc/header.inc"; ?>

        <!-- This file was generated by a script. Do not edit this file in Git,
             edit contents in Pretalx, regenerate the PHP files and commit them
             in the Git repository of the website. -->
        <p><a href="programm/donnerstag.php#session_CFXVAL">&#9668;&#9668; zurück zum Programm</a> </p>
        <h2 class='abstract-title'>Map Editor für individuelle amtliche Vektorkarten</h2>
        <section>
            <p>
                                <span class='abstract-speakers'>Sebastian Ratjens</span></p>
                            <p><span class='abstract-time-heading'>Zeit: </span>Donnerstag 12. März 11:00 Uhr<br><span class='abstract-room-heading'>Ort: </span>HS Rundbau</p>

            
            <p>Im Rahmen des Projekts "Basisvisualisierung" erprobt das  LGLN neue Visualisierungsmöglichkeiten für amtliche Daten im Internet, optimiert für die Nutzung auf mobilen Endgeräten.</p>
<p>Als ein Ergebnis des Projekts wird der Prototyp "Map Editor" entwickelt und als Open Source Software veröffentlicht. Es handelt sich dabei um eine Webanwendung zur Erstellung individueller Basiskarten und Kartenanwendungen, basierend auf Vector Tiles.</p>
<p>Der Map Editor ermöglicht die Anpassung der Vektorkarte durch die Auswahl vordefinierter Basisstylings und die individuelle Anpassung einzelner Layer und Layergruppen. Das Ziel ist es dabei nicht, einen vollumfänglichen Vector-Tile-Editor anzubieten, sondern eine einfache Anpassung amtlicher Karten auch für GIS-Laien zu ermöglichen. Die Karte kann zusätzlich um Funktionen erweitert werden, wie Infoabfragen, Adresssuche und Routing. Der Map Editor kann als "Software as a Service" genutzt werden, so dass die Karten und Anwendungen online erstellt und per URL in andere Kartenanwendungen und Webseiten eingebunden werden können.</p>
<p>Eine erste Verwendung findet der Map Editor bereits als Web-Frontend des Prototyps der AdV-Arbeitsgruppe "Smart Mapping", die sich auch mit der Entwicklung moderner Webkarten beschäftigt.</p>
<p>Neben der Vorstellung des Entwicklungsstandes des Prototyps, wird auch über die Herausforderungen berichtet, die es in diesem Projekt hinsichtlich der Veröffentlichung von Open Source Software, agiler Entwicklung und Einführung von Innovationen gibt.</p>
        </section>


	<?php include "../inc/footer.inc"; ?>

</body>

</html>