<!doctype html>
<html lang="de">

<head>
	<meta charset="utf-8">
<meta http-equiv="x-ua-compatible" content="ie=edge">
<meta name="description" content="Die FOSSGIS-Konferenz ist im D-A-CH Raum die führende Konferenz für Freie und Open Source Software für Geoinformationssysteme OpenStreetMap.">
<meta name="keywords" content="FOSSGIS, FOSSGIS-Konferenz, 2019, FOSSGIS-Konferenz 2019, Open Source, GIS, Konferenz, Geoinformatik, OpenStreetMap, HTW Dresden">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="apple-itunes-app" content="app-id=1453299630">

	<base href="/2020/sessions">
	<title>QGIS - Fortgeschrittene Datenvisualisierung mit Live-Layer-Effekten und Mischodi – FOSSGIS 2020</title>

	<link rel="stylesheet" href="./css/normalize.css">
	<link rel="stylesheet" href="./css/base.css">
	<link rel="stylesheet" href="./css/print.css" media="print">
</head>

<body id="programm">
	<header class="page-header">
	<a href="./" alt="FOSSGIS Konferenz 2020">
		<img class="page-logo" src="./img/fossgis2020-bollenhut.png">
	</a>
	<h1 class="page-title">
		FOSSGIS-Konferenz 2020<br>
		<span class="amp">Freiburg</span> <br>
		<span class="amp">11.&ndash;14. März</span>
	</h1>
</header>

<nav>
	<ul class="main">
		<li id="navHome">
			<a href="./">Startseite</a>
		</li>
		<!--<li id="navAnmeldung">
			<a href="./anmeldung/">Anmeldung</a>
		</li>-->
		<li id="navProgramm">
		<a href="./programm/">Programm</a>
		</li>
		<!--<li id="navAnreise">
			<a href="./anreise/">Anreise</a>
		</li>-->
		<li id="navStandort">
			<a href="./standort/">Standort</a>
		</li>
		<li id="navEvents">
			<a href="./socialevents/">Social Events</a>
		</li>
		<li id="navTeam">
			<a href="./loc/loc.php">Team</a>
		</li>
	</ul>
</nav>

<div class="hero">
	<figure>
		<img class="img-fluid" src="./img/freiburg.jpg" alt="Freiburg Luftbild">
		<figcaption>Photo: Pixaby</figcaption>
	</figure>
</div>

        <!-- This file was generated by a script. Do not edit this file in Git,
             edit contents in Pretalx, regenerate the PHP files and commit them
             in the Git repository of the website. -->
        <p><a href="programm/donnerstag.php#session_CKSRYB">&#9668;&#9668; zurück zum Programm</a> </p>
        <h2 class='abstract-title'>QGIS - Fortgeschrittene Datenvisualisierung mit Live-Layer-Effekten und Mischodi</h2>
        <section>
            <p>
                <span class='abstract-sessiontype'>Workshop</span> von                <span class='abstract-speakers'>Stefan Giese</span></p>
                            <p><span class='abstract-time-heading'>Zeit: </span>Donnerstag 12. März 11:00 Uhr<br><span class='abstract-room-heading'>Ort: </span>SR R-110</p>

                        
            <p>QGIS bietet zur Layergestaltung neben den Standardsymbolen und Klassifizierungen zusätzlich die Möglichkeit Daten mit verschiedenen Mischmodi und Effekten zu visualisieren. Hierbei kann zwischen Effekten auf Objektebene und Layerebene gewählt werden. In beiden Fällen kommt es zu Wechselwirkungen zwischen einzelnen Objekten eines Layers oder zwischen verschiedenen Kartenlayern. Über den Mischmodus können z.B. mehrere opake Ebenen gemischt werden, so dass Informationen aus an für sich undurchsichtigen Layern zusammen sichtbar werden. Effekte bieten die Möglichkeit bestimmte Objekte hervorzuheben und somit kartografische Visualisierungen zu erweitern. 
Unter Anderem behandelt der Workshop Themen wie:<br />
- Einführung in die verschiedenen Effekte auf Layer und Objekte
- Nutzungsmöglichkeiten Mischmodus
- Verwendung von Live Effekten zur Visualisierung spezieller Darstellungsformen.
Der Teilnehmer kann den Einsatz von Live Effects und Blending Modes anhand von umfangreichen Übungsdaten und von praktischen Übungsbeispielen selbst ausprobieren. Von Vorteil sind Grundkenntnisse im Umgang mit Geodaten und Kenntnisse im Umgang mit QGIS.</p>
        <div class='abstract-bio'>
            <h3 class='abstract-bio-name'>Stefan Giese</h3>
            <p>Ich bin Diplomgeologe und seit 2016 als GIS-Consultant und Projektleiter bei der WhereGroup in Bonn. Ich lebe und arbeite in Freiburg im Breisgau und beschäftige mich neben meiner Arbeit bei der WhereGroup mit der geophysikalischen Erkundung von archäologischen Bodendenkmälern.</p>
        </div>
        </section>


	<footer>
	<ul class="main">
		<li>
			<a href="https://www.fossgis.de/impressum/">Impressum</a>
		</li>
		<li>
			<a href="./agb.php">AGB</a>
		</li>
		<li>
			<a href="https://www.fossgis.de/datenschutzerklärung">Datenschutzerklärung</a>
		</li>
	</ul>
</footer>

</body>

</html>