<!doctype html>
<html lang="de">

<head>
	<?php include "../inc/meta.inc"; ?>

	<base href="<?php echo dirname($_SERVER['SCRIPT_NAME']); ?>">
	<title>MapServer Statusbericht – FOSSGIS 2020</title>

	<link rel="stylesheet" href="./css/normalize.css">
	<link rel="stylesheet" href="./css/base.css">
	<link rel="stylesheet" href="./css/print.css" media="print">
</head>

<body id="programm">
	<?php include "../inc/header.inc"; ?>

        <!-- This file was generated by a script. Do not edit this file in Git,
             edit contents in Pretalx, regenerate the PHP files and commit them
             in the Git repository of the website. -->
        <p><a href="programm/donnerstag.php#session_CWRZQH">&#9668;&#9668; zurück zum Programm</a> </p>
        <h2 class='abstract-title'>MapServer Statusbericht</h2>
        <section>
            <p>
                                <span class='abstract-speakers'>Jörg Thomsen</span></p>
                            <p><span class='abstract-time-heading'>Zeit: </span>Donnerstag 12. März 12:00 Uhr<br><span class='abstract-room-heading'>Ort: </span>HS Anatomie</p>

            
            <p>MapServer ist jetzt 26 alt wird nach wie vor vielfältig als WMS, WFS, WCS eingesetzt. Projekte aus seinem Umfeld (tiny-ows, MapCache) erweitern seine Funktionen. Außerdem wird auch MapServer selbst stetig weiter entwickelt und quasi ständig gibt es neue Funktionen und Konfigurationsmöglichkeiten zu entdecken.</p>
<p>MapServer als Software und Projekt wird kurz vorgestellt, gefolgt von einem Überblick über die wichtigsten Änderungen in der Konfiguration, die sich durch den Wechsel auf Version 7 ergeben haben, da es immer noch zahlreiche Projekte gibt, in denen ein Versionswechsel ansteht, darunter:</p>
<ul>
<li>Filter-Verhalten</li>
<li>Annotations</li>
<li>Übernahme von Attributen als Mapfile-Paramter</li>
</ul>
<p>Darüber hinaus wirft der Vortrag  einen Blick auf die Changelogs der 7er-Versionen und berücksichtigt auch die neuesten Entwicklungen, die sich bis zur FOSSGIS einstellen werden, darunter:</p>
<ul>
<li>Default Mapsize</li>
<li>MSSQL-Support</li>
<li>Variablen-Subistution</li>
</ul>
<p>Den Abschluss bildet ein Exkurs nach MapScript, in diesen Bereich hat sich 2019 einiges getan.</p>
        <div class='abstract-bio'>
            <h3 class='abstract-bio-name'>Jörg Thomsen</h3>
            <p>Jörg Thomsen arbeitet seit dem Ende des letzten Jahrhunderts mit freier GI-Software und war bereits die FOSSGIS-Konferenz bereits mit gestaltet, als sie noch MapServer Anwender-Konferenz hieß.</p>
<p>In den vergangenen 20 Jahren hat Jörg Thomsen zahlreiche WebGIS-Projekte umgesetzt und noch mehr Teilnehmern in seinen Workshops und Schulungen die Themen PostgreSQL und PostGIS, MapServer, GeoServer, QGIS, QGIS Server und Mapbender näher gebracht.</p>
<p>Jörg Thomsen arbeitet bei der WhereGroup in Berlin und ist Dozent der [FOSS Academy] (https://www.foss-academy.com), dem Schulungsinstitut der WhereGroup (https://www.wheregroup.com)</p>
<p>Jörg Thomsen ist im FOSSGIS e.V. und der OSGeo Foundation (http://osgeo.org) aktiv.</p>
        </div>
        </section>


	<?php include "../inc/footer.inc"; ?>

</body>

</html>