<!doctype html>
<html lang="de">

<head>
	<?php include "../inc/meta.inc"; ?>

	<base href="<?php echo dirname($_SERVER['SCRIPT_NAME']); ?>">
	<title>FAIRe Daten und FAIRe Software in der Biodiversitätsforschung – FOSSGIS 2020</title>

	<link rel="stylesheet" href="./css/normalize.css">
	<link rel="stylesheet" href="./css/base.css">
	<link rel="stylesheet" href="./css/print.css" media="print">
</head>

<body id="programm">
	<?php include "../inc/header.inc"; ?>

        <!-- This file was generated by a script. Do not edit this file in Git,
             edit contents in Pretalx, regenerate the PHP files and commit them
             in the Git repository of the website. -->
        <p><a href="programm/mittwoch.php#session_DH3H9D">&#9668;&#9668; zurück zum Programm</a> </p>
        <h2 class='abstract-title'>FAIRe Daten und FAIRe Software in der Biodiversitätsforschung</h2>
        <section>
            <p>
                                <span class='abstract-speakers'>Bernhard Seeger</span></p>
                            <p><span class='abstract-time-heading'>Zeit: </span>Mittwoch 11. März 16:00 Uhr<br><span class='abstract-room-heading'>Ort: </span>HS Anatomie</p>

                        <div class="video-container">
                <a href="https://media.ccc.de/v/fossgis2020-3523-faire-daten-und-faire-software-in-der-biodiversittsforschung">
                    <img class="video-preview" src="video_previews/3523-hd.jpg" alt="Vorschaubild des Videos">
                    <div class="video-preview-overlay"></div>
                </a>
            </div>
                        <p><a href="/2020//attachments/DH3H9D_FAIR_Data_FAIR_Software_j3Ol3P6.pdf">Vortragsfolien (PDF) </a></p>
            <p>Geo-Daten können durch unterschiedlichste Sensoren günstig erfasst und über das Internet allen zur Verfügung gestellt werden. Insbesondere im Bereich der Biodiversitätsforschung ergeben sich dadurch neue Möglichkeiten Methoden zu entwickeln und Erkenntnisse zu gewinnen, um dem drohenden Biodiversitätsverlust entgegenzutreten. Voraussetzung hierfür ist aber ein konsequent umgesetztes Forschungsdatenmanagement, bei dem die raumbezogenen Daten nach den FAIR Prinzipien verwaltet werden. Dabei ist FAIR ein Akronym für findability, accessibility, interoperability, und reusability. In Deutschland soll deshalb in den kommenden Jahren eine nationale Forschungsdateninfrastruktur (NFDI) entstehen, um insbesondere die Geo-Datenbestände von Wissenschaft und Forschung systematisch zu erschließen, nachhaltig zu sichern und zugänglich zu machen sowie auf nationaler und internationaler Ebene interdisziplinär zu vernetzen. NFDI setzt dabei nicht nur auf die reine Datenerfassung, sondern ebenfalls auf die nachhaltige Entwicklung und Austausch von Softwarewerkzeugen, um damit Forschungsergebnisse nachvollziehbar und reproduzierbar zu machen. Hierbei sollen in diesem Beitrag Antworten auf die Frage gegeben werden, wie die FAIR-Prinzipien sich auf Softwarewerkzeuge übertragen lassen, die für die skalierbare Verarbeitung und Analyse von Geo-Daten eingesetzt werden.</p>
        <div class='abstract-bio'>
            <h3 class='abstract-bio-name'>Bernhard Seeger</h3>
            <p>Bernhard Seeger ist Professor für Datenbanksysteme an der Philipps-Universität Marburg und beschäftigt sich seit mehr als 30 Jahren mit dem Thema Geo-Datenbanken. Seine Arbeiten umfassen Entwicklungen im Bereich Geo-Indexstrukturen, wie z. B. den in vielen Systemen implementierten R*-Baum, und Geo-Joins als auch CEP-Systeme (Complex Event Processing) mit Geo-Daten. Seit 10 Jahren beschäftigt er sich mit dem Thema Forschungsdatenmanagement für Biodiversitätsdaten und hat innerhalb des Infrastrukturprojekts <a href="https://www.gfbio.org/">GFBio</a> ein Web-basiertes Werkzeug zur raum-zeitlichen Verarbeitung, explorativen Analyse und Visualisierung von BIG Spatial Data entwickelt. Er ist derzeit Mitantragsteller von NFDI4Biodiversity, in dem das Forschungsdatenmanagement im Bereich der Biodiversität als Teil der geplanten Nationalen Forschungsdateninfrastruktur (NFDI) weiterentwickelt werden soll.</p>
        </div>
        </section>


	<?php include "../inc/footer.inc"; ?>

</body>

</html>