<!doctype html>
<html lang="de">

<head>
	<?php include "../inc/meta.inc"; ?>

	<base href="<?php echo dirname($_SERVER['SCRIPT_NAME']); ?>">
	<title>FAIRe Daten und FAIRe Software in der Biodiversitätsforschung – FOSSGIS 2020</title>

	<link rel="stylesheet" href="./css/normalize.css">
	<link rel="stylesheet" href="./css/base.css">
	<link rel="stylesheet" href="./css/print.css" media="print">
</head>

<body id="programm">
	<?php include "../inc/header.inc"; ?>

        <!-- This file was generated by a script. Do not edit this file in Git,
             edit contents in Pretalx, regenerate the PHP files and commit them
             in the Git repository of the website. -->
        <p><a href="programm/mittwoch.php#session_DH3H9D">&#9668;&#9668; zurück zum Programm</a> </p>
        <h2 class='abstract-title'>FAIRe Daten und FAIRe Software in der Biodiversitätsforschung</h2>
        <section>
            <p>
                                <span class='abstract-speakers'>Bernhard Seeger</span></p>
                            <p><span class='abstract-time-heading'>Zeit: </span>Mittwoch 11. März 16:00 Uhr<br><span class='abstract-room-heading'>Ort: </span>HS Anatomie</p>

            
            <p>Geo-Daten können durch unterschiedlichste Sensoren günstig erfasst und über das Internet allen zur Verfügung gestellt werden. Insbesondere im Bereich der Biodiversitätsforschung ergeben sich dadurch neue Möglichkeiten Methoden zu entwickeln und Erkenntnisse zu gewinnen, um dem drohenden Biodiversitätsverlust entgegenzutreten. Voraussetzung hierfür ist aber ein konsequent umgesetztes Forschungsdatenmanagement, bei dem die raumbezogenen Daten nach den FAIR Prinzipien verwaltet werden. Dabei ist FAIR ein Akronym für findability, accessibility, interoperability, und reusability. In Deutschland soll deshalb in den kommenden Jahren eine nationale Forschungsdateninfrastruktur (NFDI) entstehen, um insbesondere die Geo-Datenbestände von Wissenschaft und Forschung systematisch zu erschließen, nachhaltig zu sichern und zugänglich zu machen sowie auf nationaler und internationaler Ebene interdisziplinär zu vernetzen. NFDI setzt dabei nicht nur auf die reine Datenerfassung, sondern ebenfalls auf die nachhaltige Entwicklung und Austausch von Softwarewerkzeugen, um damit Forschungsergebnisse nachvollziehbar und reproduzierbar zu machen. Hierbei sollen in diesem Beitrag Antworten auf die Frage gegeben werden, wie die FAIR-Prinzipien sich auf Softwarewerkzeuge übertragen lassen, die für die skalierbare Verarbeitung und Analyse von Geo-Daten eingesetzt werden.</p>
        <div class='abstract-bio'>
            <h3 class='abstract-bio-name'>Bernhard Seeger</h3>
            <p>https://www.uni-marburg.de/de/fb12/arbeitsgruppen/dbs/team/personenseiten/bernhard-seeger</p>
<p>https://scholar.google.de/citations?user=Nc_AL5UAAAAJ&amp;hl=de&amp;oi=ao</p>
<p>Vielleicht noch ganz interessant für FOSSGIS ist, dass ich Mitautor eines Papers zum R*-Baum bin, der in vielen Systeme (wie z. B. SQLite) implementiert ist.</p>
        </div>
        </section>


	<?php include "../inc/footer.inc"; ?>

</body>

</html>