<!doctype html>
<html lang="de">

<head>
	<?php include "../inc/meta.inc"; ?>

	<base href="<?php echo dirname($_SERVER['SCRIPT_NAME']); ?>">
	<title>Bessere Höhenlinien aus Geländemodelle erstellen – FOSSGIS 2020</title>

	<link rel="stylesheet" href="./css/normalize.css">
	<link rel="stylesheet" href="./css/base.css">
	<link rel="stylesheet" href="./css/print.css" media="print">
</head>

<body id="programm">
	<?php include "../inc/header.inc"; ?>

        <!-- This file was generated by a script. Do not edit this file in Git,
             edit contents in Pretalx, regenerate the PHP files and commit them
             in the Git repository of the website. -->
        <p><a href="programm/freitag.php#session_DMVYS9">zurück zum Programm</a></p>
        <h2 class='abstract-title'>Bessere Höhenlinien aus Geländemodelle erstellen</h2>
        <section>
            <p>
                <span class='abstract-sessiontype'>Workshop</span> von                <span class='abstract-speakers'>Mathias Gröbe</span></p>
            <p><span class='abstract-time-heading'>Zeit: </span>Freitag 13. März 10:00 Uhr<br><span class='abstract-room-heading'>Ort: </span>SR R-140</p>

            
            <p>Höhenlinien sind eine wichtige kartographische Darstellungsmethode für das Relief in Karten. Die Erzeugung aus einem digitalen Höhenmodell ist im GIS schnell erledigt, aber oft graphisch weniger ansprechend.  Im Workshop werden Workflows mit QGIS und GDAL gezeigt wie man es besser machen kann um u.a. ästhetische Höhenlinien in eben Landschaften zu erhalten oder die Höhenlinien ggf. zu verdichten oder auszudünnen.</p>
        </section>


	<?php include "../inc/footer.inc"; ?>

</body>

</html>