<!doctype html>
<html lang="de">

<head>
	<?php include "../inc/meta.inc"; ?>

	<base href="<?php echo dirname($_SERVER['SCRIPT_NAME']); ?>">
	<title>Orchestrierung einer GDI über Docker – FOSSGIS 2020</title>

	<link rel="stylesheet" href="./css/normalize.css">
	<link rel="stylesheet" href="./css/base.css">
	<link rel="stylesheet" href="./css/print.css" media="print">
</head>

<body id="programm">
	<?php include "../inc/header.inc"; ?>

        <!-- This file was generated by a script. Do not edit this file in Git,
             edit contents in Pretalx, regenerate the PHP files and commit them
             in the Git repository of the website. -->
        <p><a href="programm/mittwoch.php#session_E8KJSG">&#9668;&#9668; zurück zum Programm</a> </p>
        <h2 class='abstract-title'>Orchestrierung einer GDI über Docker</h2>
        <section>
            <p>
                <span class='abstract-sessiontype'>Workshop</span> von                <span class='abstract-speakers'>Jan Suleiman, Daniel Koch</span></p>
                <p class='abstract-is-workshop'>Bitte melden Sie sich im <a href="https://pretix.eu/fossgis/2020/">Ticketshop</a> für diesen Workshop an, wenn Sie daran teilnehmen möchten.</p>            <p><span class='abstract-time-heading'>Zeit: </span>Mittwoch 11. März 15:00 Uhr<br><span class='abstract-room-heading'>Ort: </span>SR R-110</p>

            
            <p>Docker hat sich in vielen Bereichen zu einem äußerst nützlichen Werkzeug für den
isolierten Betrieb von Anwendungen über Containerisierung herausgestellt und
mittlerweile mehr als nur bewährt. Vorteile von Docker sind dabei u.a. die
Plattformunabhängigkeit, die Isolation von Anwendungen und deren Abhängigkeiten
an externe Systembibliotheken, die Versionierbarkeit der Container und nicht
zuletzt das einfache Deployment in verteilte Zielplattformen. Hierauf aufbauend
unterstützt Docker bei der Skalierbarkeit und dem Updateprozess von Applikationen
in allen verfügbaren Umgebungen, z.B. der Test-, Staging- und Produktivumgebung.
Für Entwickler stellt Docker eine hervorragende Ergänzung des Development-Setups
dar, indem z.B. ähnliche Bedingungen wie auf Produktivsystemen ohne großen Aufwand
hergestellt werden können.</p>
<p>Dieser Workshop soll den Teilnehmern zunächst eine kurze Einführung in Docker und
docker-compose geben. Hier werden neben den Grundkonzepten (u.a. Dockerfile, Container,
Image, Registry, …) einige hilfreiche Informationen zu Installation und Konfiguration
gegeben. Anschließend wird sukzessive eine leicht verständliche GDI, bestehend
aus einer PostGIS-Datenbank, eines GeoServers und eines WebGIS erstellt. Dabei wird
besonders auf die Kommunikation der Services untereinander, typische Konfigurationsoptionen
sowie Erweiterungsmöglichkeiten eingegangen.</p>
<p>Nach Bedarf können Vor- und Nachteile einer Docker-basierten Architektur für
spezifische Systeme diskutiert werden.</p>
<p>Zielgruppe des Workshops sind (GDI-)Administratoren, Anwender, Entwickler und
Entscheider, die Interesse an Docker und dessen Nutzung in den unterschiedlichen
Umgebungen und Lebenszyklen einer GDI oder auch im alltäglichen Gebrauch haben.</p>
<p>Kenntnisse über Docker und die verwendeten Komponenten der Beispiel-GDI sind nicht
zwingend erforderlich.</p>
<p>Informationen</p>
<ul>
<li>docker https://www.docker.com/</li>
<li>docker-compose https://docs.docker.com/compose/</li>
</ul>
        <div class='abstract-bio'>
            <h3 class='abstract-bio-name'>Jan Suleiman</h3>
            <p>https://github.com/jansule</p>
        </div>
        </section>


	<?php include "../inc/footer.inc"; ?>

</body>

</html>