<!doctype html>
<html lang="de">

<head>
	<?php include "../inc/meta.inc"; ?>

	<base href="<?php echo dirname($_SERVER['SCRIPT_NAME']); ?>">
	<title>Javascript-Bibliotheken zur Einbindung von historischen Umwelt- und Klimainformationen als Kartenlayer – FOSSGIS 2020</title>

	<link rel="stylesheet" href="./css/normalize.css">
	<link rel="stylesheet" href="./css/base.css">
	<link rel="stylesheet" href="./css/print.css" media="print">
</head>

<body id="programm">
	<?php include "../inc/header.inc"; ?>

        <!-- This file was generated by a script. Do not edit this file in Git,
             edit contents in Pretalx, regenerate the PHP files and commit them
             in the Git repository of the website. -->
        <p><a href="programm/donnerstag.php#session_EBMZWN">&#9668;&#9668; zurück zum Programm</a> </p>
        <h2 class='abstract-title'>Javascript-Bibliotheken zur Einbindung von historischen Umwelt- und Klimainformationen als Kartenlayer</h2>
        <section>
            <p>
                                <span class='abstract-speakers'>Michael Kahle</span></p>
                            <p><span class='abstract-time-heading'>Zeit: </span>Donnerstag 12. März 16:30 Uhr<br><span class='abstract-room-heading'>Ort: </span>HS Rundbau</p>

                        <div class="video-container">
                <a href="https://media.ccc.de/v/fossgis2020-3055-javascript-bibliotheken-zur-einbindung-von-historischen-umwelt-und-klimainformationen-als-kartenlayer">
                    <img class="video-preview" src="video_previews/3055-hd.jpg" alt="Vorschaubild des Videos">
                    <div class="video-preview-overlay"></div>
                </a>
            </div>
                        <p><a href="/2020//attachments/EBMZWN_Fossgis_Kahle_2020_CWDSpR7.pdf">Vortragsfolien (PDF) </a></p>
            <p>Das für jeden zugängliche (und erweiterbare) Webportal www.tambora.org bietet über 250000 zeitlich differenzierbare und räumlich verortete Ereignisse. Im mitteleuropäischen Bereich finden sich für die letzten tausend Jahre Einträge zu den Themen Klima (beispielsweise Hitze, Kälte, Niederschlag, ...), Phenologie (etwa Erntequalität, -quantität und -zeitpunkt) und sozioökonomische Auswirkungen (Preisentwicklungen, Hunger, Aufstände, …).</p>
<p>Um eigene Kartenapplikationen um Layer dieser Daten ergänzen zu können, werden Javascript-Bibliotheken für Leaflet und Openlayer vorgestellt. Die Anwendung der Bibliothek wird jeweils durch eine Anwendung verdeutlicht, wie z.B. ein <a href="https://climdata.github.io/cook2015">Dürre-Explorer</a>.</p>
        </section>


	<?php include "../inc/footer.inc"; ?>

</body>

</html>