<!doctype html>
<html lang="de">

<head>
	<?php include "../inc/meta.inc"; ?>

	<base href="<?php echo dirname($_SERVER['SCRIPT_NAME']); ?>">
	<title>PTNA: Qualitätssicherung für ÖPNV in OpenStreetMap – FOSSGIS 2020</title>

	<link rel="stylesheet" href="./css/normalize.css">
	<link rel="stylesheet" href="./css/base.css">
	<link rel="stylesheet" href="./css/print.css" media="print">
</head>

<body id="programm">
	<?php include "../inc/header.inc"; ?>

        <!-- This file was generated by a script. Do not edit this file in Git,
             edit contents in Pretalx, regenerate the PHP files and commit them
             in the Git repository of the website. -->
        <p><a href="programm/donnerstag.php#session_EMQGW7">&#9668;&#9668; zurück zum Programm</a> </p>
        <h2 class='abstract-title'>PTNA: Qualitätssicherung für ÖPNV in OpenStreetMap</h2>
        <section>
            <p>
                                <span class='abstract-speakers'>Toni Erdmann</span></p>
                            <p><span class='abstract-time-heading'>Zeit: </span>Donnerstag 12. März 16:00 Uhr<br><span class='abstract-room-heading'>Ort: </span>HS Weismannhaus</p>

            
            <p>Die Webseite von PTNA - Public Transport Network Analysis wird vorgestellt (https://ptna.openstreetmap.de).
Es wird erläutert wie Analysen für weitere Verkehrsverbünde aufgenommen werden können. </p>
<p>Der Vortrag soll ebenso einen Einblick in die laufende Arbeiten für die Analyse von GTFS-Daten geben. GTFS-Daten können zum Einen als Vorlage beim Mappen von Daten hilfreich sein: Positionen und andere Details von Haltestellen, Routen von Bussen, ...
GTFS-Daten können zum Anderen aber auch als Input für einen Soll-Ist-Vergleich herangezogen werden.</p>
        </section>


	<?php include "../inc/footer.inc"; ?>

</body>

</html>