<!doctype html>
<html lang="de">

<head>
	<meta charset="utf-8">
<meta http-equiv="x-ua-compatible" content="ie=edge">
<meta name="description" content="Die FOSSGIS-Konferenz ist im D-A-CH Raum die führende Konferenz für Freie und Open Source Software für Geoinformationssysteme OpenStreetMap.">
<meta name="keywords" content="FOSSGIS, FOSSGIS-Konferenz, 2019, FOSSGIS-Konferenz 2019, Open Source, GIS, Konferenz, Geoinformatik, OpenStreetMap, HTW Dresden">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="apple-itunes-app" content="app-id=1453299630">

	<base href="/2020/sessions">
	<title>Infrastruktur-Mappen mit dem (E-)Bike – FOSSGIS 2020</title>

	<link rel="stylesheet" href="./css/normalize.css">
	<link rel="stylesheet" href="./css/base.css">
	<link rel="stylesheet" href="./css/print.css" media="print">
</head>

<body id="programm">
	<header class="page-header">
	<a href="./" alt="FOSSGIS Konferenz 2020">
		<img class="page-logo" src="./img/fossgis2020-bollenhut.png">
	</a>
	<h1 class="page-title">
		FOSSGIS-Konferenz 2020<br>
		<span class="amp">Freiburg</span> <br>
		<span class="amp">11.&ndash;14. März</span>
	</h1>
</header>

<nav>
	<ul class="main">
		<li id="navHome">
			<a href="./">Startseite</a>
		</li>
		<!--<li id="navAnmeldung">
			<a href="./anmeldung/">Anmeldung</a>
		</li>-->
		<li id="navProgramm">
		<a href="./programm/">Programm</a>
		</li>
		<!--<li id="navAnreise">
			<a href="./anreise/">Anreise</a>
		</li>-->
		<li id="navStandort">
			<a href="./standort/">Standort</a>
		</li>
		<li id="navEvents">
			<a href="./socialevents/">Social Events</a>
		</li>
		<li id="navTeam">
			<a href="./loc/loc.php">Team</a>
		</li>
	</ul>
</nav>

<div class="hero">
	<figure>
		<img class="img-fluid" src="./img/freiburg.jpg" alt="Freiburg Luftbild">
		<figcaption>Photo: Pixaby</figcaption>
	</figure>
</div>

        <!-- This file was generated by a script. Do not edit this file in Git,
             edit contents in Pretalx, regenerate the PHP files and commit them
             in the Git repository of the website. -->
        <p><a href="programm/freitag.php#session_EVHGAH">&#9668;&#9668; zurück zum Programm</a> </p>
        <h2 class='abstract-title'>Infrastruktur-Mappen mit dem (E-)Bike</h2>
        <section>
            <p>
                                <span class='abstract-speakers'>Roman Härdi</span></p>
                            <p><span class='abstract-time-heading'>Zeit: </span>Freitag 13. März 13:30 Uhr<br><span class='abstract-room-heading'>Ort: </span>HS Rundbau</p>

                        <div class="video-container">
                <a href="https://media.ccc.de/v/fossgis2020-3009-infrastruktur-mappen-mit-dem-e-bike">
                    <img class="video-preview" src="video_previews/3009-hd.jpg" alt="Vorschaubild des Videos">
                    <div class="video-preview-overlay"></div>
                </a>
            </div>
                        <p><a href="/2020/attachments/EVHGAH_fossgis_2020_H_C3_A4rdi_Infrastruktur-Mappen_mit_dem_bYswQIU.pdf">Vortragsfolien (PDF) </a></p>
            <p>Was sind die Vorteile des (E-)Bike-Mapping? Wie kann man Objekte mit der Kamera am besten und schnellsten (während der Fahrt) erfassen und präzise georeferenzieren?
Ich zeige wie ich das Mappen mit GPS, Fotoapparat und E-Bike optimiert habe und welche Vorteile diese Art des Mappen bietet. 
Im zweiten Teil fokussiere ich auf die Vorteile und Abläufe für das Mappen von Infrastruktur (Gas-Pipeline, Stromnetze). Hier hat das Mappen mit dem Fahrrad große Vorteile: Es sind viele Orte fahrend zugänglich (wo andere Fahrzeuge nicht können oder nicht dürfen) und trotzdem kann ein großes Gebiet erfasst werden.
Im letzten Teil zeige ich welche Ideen und Optimierung ich mir wünschen würde. Zum Beispiel das automatische Aufzeichnen der «Holprigkeit» der Straße.</p>
        <div class='abstract-bio'>
            <h3 class='abstract-bio-name'>Roman Härdi</h3>
            <p>Mitglied des SOSM Vorstands. Elektroingenieur, Produktmanager. Mitglied der Feuerwehr Wangen an der Aare. Hobbies: OSM, Feuerwehr, Fotografieren, Amateurfunk.</p>
        </div>
        </section>


	<footer>
	<ul class="main">
		<li>
			<a href="https://www.fossgis.de/impressum/">Impressum</a>
		</li>
		<li>
			<a href="./agb.php">AGB</a>
		</li>
		<li>
			<a href="https://www.fossgis.de/datenschutzerklärung">Datenschutzerklärung</a>
		</li>
	</ul>
</footer>

</body>

</html>