<!doctype html>
<html lang="de">

<head>
	<?php include "../inc/meta.inc"; ?>

	<base href="<?php echo dirname($_SERVER['SCRIPT_NAME']); ?>">
	<title>Was ist Open Source? – FOSSGIS 2020</title>

	<link rel="stylesheet" href="./css/normalize.css">
	<link rel="stylesheet" href="./css/base.css">
	<link rel="stylesheet" href="./css/print.css" media="print">
</head>

<body id="programm">
	<?php include "../inc/header.inc"; ?>

        <!-- This file was generated by a script. Do not edit this file in Git,
             edit contents in Pretalx, regenerate the PHP files and commit them
             in the Git repository of the website. -->
        <p><a href="programm/mittwoch.php#session_EZAY3D">&#9668;&#9668; zurück zum Programm</a> </p>
        <h2 class='abstract-title'>Was ist Open Source?</h2>
        <section>
            <p>
                <span class='abstract-sessiontype'>Diverses</span> von                <span class='abstract-speakers'>Marco Lechner</span></p>
                            <p><span class='abstract-time-heading'>Zeit: </span>Mittwoch 11. März 11:25 Uhr<br><span class='abstract-room-heading'>Ort: </span>HS Anatomie</p>

                        <div class="video-container">
                <a href="https://media.ccc.de/v/fossgis2020-3693-was-ist-open-source-">
                    <img class="video-preview" src="video_previews/3693-hd.jpg" alt="Vorschaubild des Videos">
                    <div class="video-preview-overlay"></div>
                </a>
            </div>
                        
            <p>Open Source hat viele Facetten und es ranken sich inzwischen ebenso viele Mythen darum. Was davon richtig ist und was nicht stellen wir in einer kurzen Einführung zusammen. Der Vortrag richtet sich an alle, die mit Open Source bisher noch wenig Kontakt hatten und die Grundlagen verstehen möchten.</p>
<p>Open Source ist auf der einen Seite ein Entwicklungsmodell und auf der anderen ein Lizenzmodell. Zusammen bilden sie eine Kultur offener Entwicklungsgemeinschaften, die höchst effektiv arbeiten. Diese Kultur ist um ein Vielfaches effektiver, als proprietäre Modelle es je sein können. Ein einfaches Beispiel: Das Betriebssystem des Herstellers Apple basiert auf dem Open-Source-Unix FreeBSD. Es gibt halt einfach nichts besseres, und es selbst herzustellen wäre unendlich teuer, das hat sogar der hyper-proprietäre Hersteller Apple eingesehen.</p>
<p>Der Vortrag stellt die Geschichte der Entwicklung von Open Source vor und geht auf wichtige Grundlagen ein.</p>
<p>Ziel des FOSSGIS e.V. und der OSGeo ist die Förderung und Verbreitung freier Geographischer Informationssysteme (GIS) im Sinne Freier Software und Freier Geodaten. Dazu zählen auch Erstinformation und Klarstellung von typischen Fehlinformationen über Open Source und Freie Software, die sich über die Jahre festgesetzt haben.</p>
        <div class='abstract-bio'>
            <h3 class='abstract-bio-name'>Marco Lechner</h3>
            <p>Eigentlich bin ich ja lieber mit dem Rad, wahlweise Rennrad oder MTB, unterwegs. Hautsache es geht bergauf und als Belohnung dann auch wieder bergab. Hin und wieder greife ich aber auch zu den Laufschuhen. So kann ich schwungvoll ein wenig Grundwissen meiner Geographischen Ausbildung erzählen - zumindest solange mir noch die Luft dazu bleibt.</p>
        </div>
        </section>


	<?php include "../inc/footer.inc"; ?>

</body>

</html>