<!doctype html>
<html lang="de">

<head>
	<?php include "../inc/meta.inc"; ?>

	<base href="<?php echo dirname($_SERVER['SCRIPT_NAME']); ?>">
	<title>OSM-Daten in QGIS nutzen – FOSSGIS 2020</title>

	<link rel="stylesheet" href="./css/normalize.css">
	<link rel="stylesheet" href="./css/base.css">
	<link rel="stylesheet" href="./css/print.css" media="print">
</head>

<body id="programm">
	<?php include "../inc/header.inc"; ?>

        <!-- This file was generated by a script. Do not edit this file in Git,
             edit contents in Pretalx, regenerate the PHP files and commit them
             in the Git repository of the website. -->
        <p><a href="programm/mittwoch.php#session_FDAF37">&#9668;&#9668; zurück zum Programm</a> </p>
        <h2 class='abstract-title'>OSM-Daten in QGIS nutzen</h2>
        <section>
            <p>
                                <span class='abstract-speakers'>Astrid Emde</span></p>
                            <p><span class='abstract-time-heading'>Zeit: </span>Mittwoch 11. März 17:30 Uhr<br><span class='abstract-room-heading'>Ort: </span>HS Rundbau</p>

                        <p><a href="/2020//attachments/FDAF37_fossgis-2020-osm-daten-in-qgis-nutzen-astrid-em_bCv1SFI.pdf">Vortragsfolien</a></p>
            <p>Das Desktop GIS QGIS bietet zahlreiche Möglichkeiten für den Umgang mit Vektor-, Rasterdaten und Diensten.</p>
<p>Speziell für den Umgang mit OpenStreetMap-Daten liegen einige Möglichkeiten vor. Diese werden meist über Plugins bereitgestellt. </p>
<p>OSM-Daten können direkt über QuickOSM heruntergeladen werden. Suchmodule liegen vor, um in OSM-Daten zu suchen. OSM-Daten können über QuickMapServices als BaseMap verwendet werden. Routing auf OSM-Daten kann erfolgen. Auswertungen der OSM-Aktivität kann erfolgen. 3D-Karten können generiert werden und Vieles mehr.  </p>
<p>Dieser Vortrag bietet einen Überblick über die Möglichkeiten der Nutzung von OpenStreetMap-Daten in QGIS.</p>
        <div class='abstract-bio'>
            <h3 class='abstract-bio-name'>Astrid Emde</h3>
            <p>Astrid Emde war bisher bei allen FOSSGIS-Konferenzen dabei und freut sich auf die FOSSGIS 2020 in Freiburg!</p>
<p>Sie befasst sich seit vielen Jahren mit Geodaten und FOSSGIS und hat schon zahlreiche Projekte vor allem im WebGIS-Bereich umgesetzt.</p>
<p>Sie weist Erfahrung mit PostgreSQL und PostGIS, MapServer, GeoServer, QGIS, QGIS Server und Mapbender auf. Weiterhin Apache Solr, OpenLayers, MapProxy, OGC Standards &amp; Skripting.</p>
<p>Astrid Emde arbeitet bei der <a href="https://wheregroup.com">WhereGroup</a> in Bonn und hat schon viele Workshops und Präsentationen zu Mapbender, MapServer, GeoServer, PostgreSQL/PostGIS, OWS oder allgemein zum Aufbau einer GDI gehalten. Sie ist Dozentin der [FOSS Academy] (https://www.foss-academy.com), dem Schulungsinstitut der WhereGroup (https://www.wheregroup.com)</p>
<p>Seit über 10 Jahren engagiert sie sich im <a href="https://mapbender.org">Mapbender</a>-Projekt und gehört zum Mapbender Team (http://mapbender.org) und dem Mapbender PSC (Project Steering Committee).</p>
<p>Astrid Emde ist in der <a href="https://osgeo.org">OSGeo</a> Foundation (http://osgeo.org) aktiv. Sie ist 2010 zum Charter Member und 2017 in das OSGeo Board of Directors (Vorstand der OSGeo) und zur OSGeo Secretary gewählt worden. Dadurch übernimmt sie zahlreiche Aufgaben bei der OSGeo und ist darüber hinaus im Bereich Marketing, Presse, Community Meetings und OSGeoLive (http://live.osgeo.org/) aktiv. 2018 erhielt sie für ihr Engagement den <a href="https://www.osgeo.org/community/awards/">Sol Katz Award der OSGeo</a>.</p>
<p>Auch im <a href="http://fossgis.de">FOSSGIS e.V.</a> ist Astrid Emde aktiv. Sie gehört zum Team der jährlich stattfindenden FOSSGIS-Konferenz, engagiert sich in der Vereins-Öffentlichkeitsarbeit und der Organisation von Community Events (http://fossgis.de).</p>
        </div>
        </section>


	<?php include "../inc/footer.inc"; ?>

</body>

</html>