<!doctype html>
<html lang="de">

<head>
	<meta charset="utf-8">
<meta http-equiv="x-ua-compatible" content="ie=edge">
<meta name="description" content="Die FOSSGIS-Konferenz ist im D-A-CH Raum die führende Konferenz für Freie und Open Source Software für Geoinformationssysteme OpenStreetMap.">
<meta name="keywords" content="FOSSGIS, FOSSGIS-Konferenz, 2019, FOSSGIS-Konferenz 2019, Open Source, GIS, Konferenz, Geoinformatik, OpenStreetMap, HTW Dresden">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="apple-itunes-app" content="app-id=1453299630">

	<base href="/2020/sessions">
	<title>INSPIRE &#34;instant&#34; 2.x – FOSSGIS 2020</title>

	<link rel="stylesheet" href="./css/normalize.css">
	<link rel="stylesheet" href="./css/base.css">
	<link rel="stylesheet" href="./css/print.css" media="print">
</head>

<body id="programm">
	<header class="page-header">
	<a href="./" alt="FOSSGIS Konferenz 2020">
		<img class="page-logo" src="./img/fossgis2020-bollenhut.png">
	</a>
	<h1 class="page-title">
		FOSSGIS-Konferenz 2020<br>
		<span class="amp">Freiburg</span> <br>
		<span class="amp">11.&ndash;14. März</span>
	</h1>
</header>

<nav>
	<ul class="main">
		<li id="navHome">
			<a href="./">Startseite</a>
		</li>
		<!--<li id="navAnmeldung">
			<a href="./anmeldung/">Anmeldung</a>
		</li>-->
		<li id="navProgramm">
		<a href="./programm/">Programm</a>
		</li>
		<!--<li id="navAnreise">
			<a href="./anreise/">Anreise</a>
		</li>-->
		<li id="navStandort">
			<a href="./standort/">Standort</a>
		</li>
		<li id="navEvents">
			<a href="./socialevents/">Social Events</a>
		</li>
		<li id="navTeam">
			<a href="./loc/loc.php">Team</a>
		</li>
	</ul>
</nav>

<div class="hero">
	<figure>
		<img class="img-fluid" src="./img/freiburg.jpg" alt="Freiburg Luftbild">
		<figcaption>Photo: Pixaby</figcaption>
	</figure>
</div>

        <!-- This file was generated by a script. Do not edit this file in Git,
             edit contents in Pretalx, regenerate the PHP files and commit them
             in the Git repository of the website. -->
        <p><a href="programm/mittwoch.php#session_G7ZZ3Z">&#9668;&#9668; zurück zum Programm</a> </p>
        <h2 class='abstract-title'>INSPIRE &#34;instant&#34; 2.x</h2>
        <section>
            <p>
                <span class='abstract-sessiontype'>Workshop</span> von                <span class='abstract-speakers'>Armin Retterath</span></p>
                <p class='abstract-is-workshop'>Bitte melden Sie sich im <a href="https://pretix.eu/fossgis/2020/">Ticketshop</a> für diesen Workshop an, wenn Sie daran teilnehmen möchten.</p>            <p><span class='abstract-time-heading'>Zeit: </span>Mittwoch 11. März 10:30 Uhr<br><span class='abstract-room-heading'>Ort: </span>SR R-110</p>

                        
            <p>Im Rahmen des Workshops wird den Teilnehmern vermittelt, wie man mit Hilfe des vollständig auf FOSS-basierten GeoPortal.rlp eine INSPIRE-kompatible GDI aufbauen kann. Die Geoportal-Lösung steht hierzu in Form eines ISO-Images (debian 9) auf einem USB-Stick zur Verfügung. Alternativ gibt es auch ein Script, mit dessen Hilfe sich das Portal innerhalb von 5 Minuten auf einem debian 9 System installieren läßt.
Die Teilnehmer lernen dabei die Anforderungen der EU INSPIRE-Richtlinie an Dienste und Metadaten kennen und erhalten einen Einblick in die Funktionalitäten des GeoPortal.rlp.
Insbesondere wird auf folgende Module anhand praktischer Beispiele erläutert:</p>
<ul>
<li>OWS Registry</li>
<li>Metadatencache</li>
<li>OWS Monitoring</li>
<li>Erzeugung dynamischer Service-Metadaten</li>
<li>OWS Proxy</li>
<li>OGC API - Features Proxy</li>
<li>Metadatensuche über REST-API</li>
<li>verteilte Metadatensuche in externen Katalogen (Deuschland und INSPIRE)</li>
<li>Metadateneditor</li>
<li>CKAN-Schnittstelle (OpenData)</li>
<li>Synthetisierung von INSPIRE-Downloaddiensten auf Basis von ATOM-Feeds</li>
</ul>
        <div class='abstract-bio'>
            <h3 class='abstract-bio-name'>Armin Retterath</h3>
            <p>Armin Retterath ist Leiter des Bund/Länder Arbeitskreises Geodienste der GDI-DE sowie Architekt der Geodateninfrastruktur des Landes Rheinland-Pfalz. Er beschäftigt sich seit 2005 mit dem Aufbau und Betrieb von Geodateninfrastrukturen auf den unterschiedlichsten Ebenen der öffentlichen Verwaltung.</p>
        </div>
        </section>


	<footer>
	<ul class="main">
		<li>
			<a href="https://www.fossgis.de/impressum/">Impressum</a>
		</li>
		<li>
			<a href="./agb.php">AGB</a>
		</li>
		<li>
			<a href="https://www.fossgis.de/datenschutzerklärung">Datenschutzerklärung</a>
		</li>
	</ul>
</footer>

</body>

</html>