<!doctype html>
<html lang="de">

<head>
	<?php include "../inc/meta.inc"; ?>

	<base href="<?php echo dirname($_SERVER['SCRIPT_NAME']); ?>">
	<title>INSPIRE \"instant\" 2.x – FOSSGIS 2020</title>

	<link rel="stylesheet" href="./css/normalize.css">
	<link rel="stylesheet" href="./css/base.css">
	<link rel="stylesheet" href="./css/print.css" media="print">
</head>

<body id="programm">
	<?php include "../inc/header.inc"; ?>

        <!-- This file was generated by a script. Do not edit this file in Git,
             edit contents in Pretalx, regenerate the PHP files and commit them
             in the Git repository of the website. -->
        <p><a href="programm/mittwoch.php#session_G7ZZ3Z">&#9668;&#9668; zurück zum Programm</a> </p>
        <h2 class='abstract-title'>INSPIRE \"instant\" 2.x</h2>
        <section>
            <p>
                <span class='abstract-sessiontype'>Workshop</span> von                <span class='abstract-speakers'>Armin Retterath</span></p>
                <p class='abstract-is-workshop'>Bitte melden Sie sich im <a href="https://pretix.eu/fossgis/2020/">Ticketshop</a> für diesen Workshop an, wenn Sie daran teilnehmen möchten.</p>            <p><span class='abstract-time-heading'>Zeit: </span>Mittwoch 11. März 10:30 Uhr<br><span class='abstract-room-heading'>Ort: </span>SR R-110</p>

            
            <p>Im Rahmen des Workshops wird den Teilnehmern vermittelt, wie man mit Hilfe des vollständig auf FOSS-basierten GeoPortal.rlp eine INSPIRE-kompatible GDI aufbauen kann. Die Geoportal-Lösung steht hierzu in Form eines ISO-Images (debian 9) auf einem USB-Stick zur Verfügung. Alternativ gibt es auch ein Script, mit dessen Hilfe sich das Portal innerhalb von 5 Minuten auf einem debian 9 System installieren läßt.
Die Teilnehmer lernen dabei die Anforderungen der EU INSPIRE-Richtlinie an Dienste und Metadaten kennen und erhalten einen Einblick in die Funktionalitäten des GeoPortal.rlp.
Insbesondere wird auf folgende Module anhand praktischer Beispiele erläutert:
* OWS Registry
* Metadatencache
* OWS Monitoring
* Erzeugung dynamischer Service-Metadaten
* OWS Proxy
* OGC API - Features Proxy
* Metadatensuche über REST-API
* verteilte Metadatensuche in externen Katalogen (Deuschland und INSPIRE)
* Metadateneditor
* CKAN-Schnittstelle (OpenData)
* Synthetisierung von INSPIRE-Downloaddiensten auf Basis von ATOM-Feeds</p>
        </section>


	<?php include "../inc/footer.inc"; ?>

</body>

</html>