<!doctype html>
<html lang="de">

<head>
	<?php include "../inc/meta.inc"; ?>

	<base href="<?php echo dirname($_SERVER['SCRIPT_NAME']); ?>">
	<title>Neues vom Fossgis Routing Server – FOSSGIS 2020</title>

	<link rel="stylesheet" href="./css/normalize.css">
	<link rel="stylesheet" href="./css/base.css">
	<link rel="stylesheet" href="./css/print.css" media="print">
</head>

<body id="programm">
	<?php include "../inc/header.inc"; ?>

        <!-- This file was generated by a script. Do not edit this file in Git,
             edit contents in Pretalx, regenerate the PHP files and commit them
             in the Git repository of the website. -->
        <p><a href="programm/donnerstag.php#session_GCFPVF">&#9668;&#9668; zurück zum Programm</a> </p>
        <h2 class='abstract-title'>Neues vom Fossgis Routing Server</h2>
        <section>
            <p>
                <span class='abstract-sessiontype'>Lightning Talk</span> von                <span class='abstract-speakers'>Robert Klemm, Michael Spreng</span></p>
                            <p><span class='abstract-time-heading'>Zeit: </span>Donnerstag 12. März 14:35 Uhr<br><span class='abstract-room-heading'>Ort: </span>HS Weismannhaus</p>

            
            <p>Der Dienst routing.openstreetmap.de startete im 2018 als öffentlicher routing server auf OSRM Basis. Das Ziel: Routing auf openstreetmap.org auf Basis von OSRM anzubieten, mit einem Profil, dass von er community weiter verfeinert wird. Wir stellen vor, wie sich der dienst unterdessen entwickelt hat und wie er genutzt wird.</p>
        </section>


	<?php include "../inc/footer.inc"; ?>

</body>

</html>