<!doctype html>
<html lang="de">

<head>
	<meta charset="utf-8">
<meta http-equiv="x-ua-compatible" content="ie=edge">
<meta name="description" content="Die FOSSGIS-Konferenz ist im D-A-CH Raum die führende Konferenz für Freie und Open Source Software für Geoinformationssysteme OpenStreetMap.">
<meta name="keywords" content="FOSSGIS, FOSSGIS-Konferenz, 2019, FOSSGIS-Konferenz 2019, Open Source, GIS, Konferenz, Geoinformatik, OpenStreetMap, HTW Dresden">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="apple-itunes-app" content="app-id=1453299630">

	<base href="/2020/sessions">
	<title>Wegue - OpenLayers und Vue.js in der Praxis – FOSSGIS 2020</title>

	<link rel="stylesheet" href="./css/normalize.css">
	<link rel="stylesheet" href="./css/base.css">
	<link rel="stylesheet" href="./css/print.css" media="print">
</head>

<body id="programm">
	<header class="page-header">
	<a href="./" alt="FOSSGIS Konferenz 2020">
		<img class="page-logo" src="./img/fossgis2020-bollenhut.png">
	</a>
	<h1 class="page-title">
		FOSSGIS-Konferenz 2020<br>
		<span class="amp">Freiburg</span> <br>
		<span class="amp">11.&ndash;14. März</span>
	</h1>
</header>

<nav>
	<ul class="main">
		<li id="navHome">
			<a href="./">Startseite</a>
		</li>
		<!--<li id="navAnmeldung">
			<a href="./anmeldung/">Anmeldung</a>
		</li>-->
		<li id="navProgramm">
		<a href="./programm/">Programm</a>
		</li>
		<!--<li id="navAnreise">
			<a href="./anreise/">Anreise</a>
		</li>-->
		<li id="navStandort">
			<a href="./standort/">Standort</a>
		</li>
		<li id="navEvents">
			<a href="./socialevents/">Social Events</a>
		</li>
		<li id="navTeam">
			<a href="./loc/loc.php">Team</a>
		</li>
	</ul>
</nav>

<div class="hero">
	<figure>
		<img class="img-fluid" src="./img/freiburg.jpg" alt="Freiburg Luftbild">
		<figcaption>Photo: Pixaby</figcaption>
	</figure>
</div>

        <!-- This file was generated by a script. Do not edit this file in Git,
             edit contents in Pretalx, regenerate the PHP files and commit them
             in the Git repository of the website. -->
        <p><a href="programm/donnerstag.php#session_GHET3U">&#9668;&#9668; zurück zum Programm</a> </p>
        <h2 class='abstract-title'>Wegue - OpenLayers und Vue.js in der Praxis</h2>
        <section>
            <p>
                                <span class='abstract-speakers'>Jakob Miksch, Christian Mayer</span></p>
                            <p><span class='abstract-time-heading'>Zeit: </span>Donnerstag 12. März 16:00 Uhr<br><span class='abstract-room-heading'>Ort: </span>HS Rundbau</p>

                        <div class="video-container">
                <a href="https://media.ccc.de/v/fossgis2020-3060-wegue-openlayers-und-vue-js-in-der-praxis">
                    <img class="video-preview" src="video_previews/3060-hd.jpg" alt="Vorschaubild des Videos">
                    <div class="video-preview-overlay"></div>
                </a>
            </div>
                        <p><a href="/2020/attachments/GHET3U_2020_FOSSGIS_Wegue_VueJS_OpenLayers_MikschJ_May_FDVM4uE.pdf">Vortragsfolien (PDF) </a></p>
            <p>Wegue [1] ist eine Software zum Erstellen von modernen leichtgewichtigen WebGIS-Client-Anwendungen. Die Basis dafür sind die beiden Open Source JavaScript-Frameworks OpenLayers [2] und Vue.js [3]. OpenLayers übernimmt dabei das Lesen und die Darstellung der Geoinformationen als Karte und die Prozessierung der Geo-Objekte. Vue.js wird für die Strukturierung des Projektcodes (nach MVVM) genutzt und erlaubt die Erzeugung von eigenen Web-Komponenten.</p>
<p>Wegue verknüpft diese beiden Bibliotheken zu einer konfigurierbaren Vorlage für WebGIS-Anwendungen aller Art und stellt wiederverwendbare UI-Komponenten (z.B. Layer-Liste, FeatureInfo-Dialog, etc.) bereit.</p>
<p>Wegue wurde kurz nach der Projektgründung auf der FOSSGIS 2018 in Bonn präsentiert. Mittlerweile ist das Projekt gereift und in einigen Realweltprojekten zum Einsatz gekommen. Dabei ist es an vielen Stellen erweitert und verbessert worden und befindet sich aktuell auf dem Weg zur Version 1.0.</p>
<p>Der Vortrag gibt einen kurzen Überblick über das Wegue-Ökosystem sowie die Neuerungen der letzten Monate und zeigt wie Wegue-Anwendungen erstellt werden können. Außerdem werden einige Beispiele aus der Praxis präsentiert.</p>
<p>[1] https://github.com/meggsimum/wegue</p>
<p>[2] http://openlayers.org/</p>
<p>[3] https://vuejs.org/</p>
        <div class='abstract-bio'>
            <h3 class='abstract-bio-name'>Jakob Miksch</h3>
            <p>Wissenschaftlicher Mitarbeiter im <a href="https://giscience.zgis.at/">GIScience Lab</a>, Fachbereich für Geoinformatik - Z_GIS,  Universität Salzburg.</p>
<ul>
<li>Website: <a href="https://jakobmiksch.eu/de/">jakobmiksch.eu</a></li>
<li>Twitter: <a href="https://twitter.com/JakobMiksch">@JakobMiksch</a></li>
<li>GitHub: <a href="https://github.com/jakobmiksch/">@JakobMiksch</a></li>
</ul>
        </div>
        <div class='abstract-bio'>
            <h3 class='abstract-bio-name'>Christian Mayer</h3>
            <ul>
<li>Dipl.-Ing. Geoinformatik &amp; Vermessung</li>
<li>Gründer <a href="https://meggsimum.de">meggsimum</a></li>
<li>Softwareentwickler &amp; -architekt</li>
<li>❤ Open Source (Geospatial)</li>
<li>OpenLayers, Wegue, GeoExt, Vue.js, GeoStyler, GeoServer, PostGIS...</li>
<li>Sprecher &amp; Trainer</li>
<li>national &amp; international</li>
<li>OSGeo Foundation Charter Member</li>
</ul>
        </div>
        </section>


	<footer>
	<ul class="main">
		<li>
			<a href="https://www.fossgis.de/impressum/">Impressum</a>
		</li>
		<li>
			<a href="./agb.php">AGB</a>
		</li>
		<li>
			<a href="https://www.fossgis.de/datenschutzerklärung">Datenschutzerklärung</a>
		</li>
	</ul>
</footer>

</body>

</html>