<!doctype html>
<html lang="de">

<head>
	<?php include "../inc/meta.inc"; ?>

	<base href="<?php echo dirname($_SERVER['SCRIPT_NAME']); ?>">
	<title>2700 interaktive thematische Karten - Ein Fall für Vector Tiles! – FOSSGIS 2020</title>

	<link rel="stylesheet" href="./css/normalize.css">
	<link rel="stylesheet" href="./css/base.css">
	<link rel="stylesheet" href="./css/print.css" media="print">
</head>

<body id="programm">
	<?php include "../inc/header.inc"; ?>

        <!-- This file was generated by a script. Do not edit this file in Git,
             edit contents in Pretalx, regenerate the PHP files and commit them
             in the Git repository of the website. -->
        <p><a href="programm/mittwoch.php#session_GPMCKV">&#9668;&#9668; zurück zum Programm</a> </p>
        <h2 class='abstract-title'>2700 interaktive thematische Karten - Ein Fall für Vector Tiles!</h2>
        <section>
            <p>
                                <span class='abstract-speakers'>Pirmin Kalberer</span></p>
                            <p><span class='abstract-time-heading'>Zeit: </span>Mittwoch 11. März 15:00 Uhr<br><span class='abstract-room-heading'>Ort: </span>HS Anatomie</p>

            
            <p>Die Visualisierung des neuen Vogelatlas der Schweizer Vogelwarte zeigt bis zu sechs thematische Karten für über 400 Vogelarten. Dichte, Verteilung, Sichtungen und deren Entwicklung werden in thematischen Karten dargestellt. Dazu kommen 3D-Darstellungen, Vergleichsfunktionen, Einstellungen von Zeitperioden und weitere Funktionen.
Die geforderte hohe Interaktivität kann dank dem Einsatz von Vektor Tiles bei kleinem Resourcenbedarf erreicht werden. Sogar Rasterkarten wurden vektorisiert und mit Mapbox GL JS im nationalen Bezugsrahmen LV95 dargestellt. Der Vortrag zeigt die nötigen Schritte zur Aufbereitung der Vector Tiles mit Open Source Software und erläutert die programmatisch erzeugten Kartenstile.</p>
        </section>


	<?php include "../inc/footer.inc"; ?>

</body>

</html>