<!doctype html>
<html lang="de">

<head>
	<meta charset="utf-8">
<meta http-equiv="x-ua-compatible" content="ie=edge">
<meta name="description" content="Die FOSSGIS-Konferenz ist im D-A-CH Raum die führende Konferenz für Freie und Open Source Software für Geoinformationssysteme OpenStreetMap.">
<meta name="keywords" content="FOSSGIS, FOSSGIS-Konferenz, 2019, FOSSGIS-Konferenz 2019, Open Source, GIS, Konferenz, Geoinformatik, OpenStreetMap, HTW Dresden">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="apple-itunes-app" content="app-id=1453299630">

	<base href="/2020/sessions">
	<title>Pilgerstab in einer Hand, Brecheisen in der anderen: wie man Geodaten öffnet – FOSSGIS 2020</title>

	<link rel="stylesheet" href="./css/normalize.css">
	<link rel="stylesheet" href="./css/base.css">
	<link rel="stylesheet" href="./css/print.css" media="print">
</head>

<body id="programm">
	<header class="page-header">
	<a href="./" alt="FOSSGIS Konferenz 2020">
		<img class="page-logo" src="./img/fossgis2020-bollenhut.png">
	</a>
	<h1 class="page-title">
		FOSSGIS-Konferenz 2020<br>
		<span class="amp">Freiburg</span> <br>
		<span class="amp">11.&ndash;14. März</span>
	</h1>
</header>

<nav>
	<ul class="main">
		<li id="navHome">
			<a href="./">Startseite</a>
		</li>
		<!--<li id="navAnmeldung">
			<a href="./anmeldung/">Anmeldung</a>
		</li>-->
		<li id="navProgramm">
		<a href="./programm/">Programm</a>
		</li>
		<!--<li id="navAnreise">
			<a href="./anreise/">Anreise</a>
		</li>-->
		<li id="navStandort">
			<a href="./standort/">Standort</a>
		</li>
		<li id="navEvents">
			<a href="./socialevents/">Social Events</a>
		</li>
		<li id="navTeam">
			<a href="./loc/loc.php">Team</a>
		</li>
	</ul>
</nav>

<div class="hero">
	<figure>
		<img class="img-fluid" src="./img/freiburg.jpg" alt="Freiburg Luftbild">
		<figcaption>Photo: Pixaby</figcaption>
	</figure>
</div>

        <!-- This file was generated by a script. Do not edit this file in Git,
             edit contents in Pretalx, regenerate the PHP files and commit them
             in the Git repository of the website. -->
        <p><a href="programm/mittwoch.php#session_HEE3SU">&#9668;&#9668; zurück zum Programm</a> </p>
        <h2 class='abstract-title'>Pilgerstab in einer Hand, Brecheisen in der anderen: wie man Geodaten öffnet</h2>
        <section>
            <p>
                <span class='abstract-sessiontype'>Diverses</span> von                <span class='abstract-speakers'>Guillaume Rischard</span></p>
                            <p><span class='abstract-time-heading'>Zeit: </span>Mittwoch 11. März 13:45 Uhr<br><span class='abstract-room-heading'>Ort: </span>HS Rundbau</p>

                        <div class="video-container">
                <a href="https://media.ccc.de/v/fossgis2020-3235-pilgerstab-in-einer-hand-brecheisen-in-der-anderen-wie-man-geodaten-ffnet">
                    <img class="video-preview" src="video_previews/3235-hd.jpg" alt="Vorschaubild des Videos">
                    <div class="video-preview-overlay"></div>
                </a>
            </div>
                        
            <p>In der EU geben die PSI-Richtlinien von 2003 und 2013 jedem das Recht auf die Wiederverwendung von Daten aus dem öffentlichen Sektor. Oder tun sie das wirklich? Was sagt das Informationsweiterverwendungsgesetz, und was bedeutet es für uns? Was wird die Open Data Richtlinie von 2019, die bis 2021 umgesetzt sein muss, ermöglichen?</p>
<p>Sind solche Gesetze überhaupt notwendig? Im Urlaub im Kosovo tat Guillaume, was jeder normale Mensch tun würde - er begann zu kartographieren und nach offenen Geodaten zu suchen. Zusammen mit der örtlichen Community half er, die Kosovo-Katasterbehörde davon zu überzeugen, zum ersten Mal Daten freizugeben. Ohne Open Data Gesetze aber mit Import-Mapathons und Partnerschaften wurde OpenStreetMap zur besten Karte des Landes.</p>
<p>Zuvor war Guillaume der technische Leiter des luxemburgischen Projekts für ein Open Data Portal. Als er begann, war Luxemburg Schlusslicht im Open Data Index der EU. Es ist seitdem an erster Stelle und eines der Länder mit der offensten Geodatenpolitik - dank einer Kombination aus Familiengeschichte und OpenRailwayMap.</p>
        </section>


	<footer>
	<ul class="main">
		<li>
			<a href="https://www.fossgis.de/impressum/">Impressum</a>
		</li>
		<li>
			<a href="./agb.php">AGB</a>
		</li>
		<li>
			<a href="https://www.fossgis.de/datenschutzerklärung">Datenschutzerklärung</a>
		</li>
	</ul>
</footer>

</body>

</html>