<!doctype html>
<html lang="de">

<head>
	<?php include "../inc/meta.inc"; ?>

	<base href="<?php echo dirname($_SERVER['SCRIPT_NAME']); ?>">
	<title>Wie man offene Geodaten bekommt, jetzt! Meine Erfahrung in Luxemburg, in der EU und ausserhalb. – FOSSGIS 2020</title>

	<link rel="stylesheet" href="./css/normalize.css">
	<link rel="stylesheet" href="./css/base.css">
	<link rel="stylesheet" href="./css/print.css" media="print">
</head>

<body id="programm">
	<?php include "../inc/header.inc"; ?>

        <!-- This file was generated by a script. Do not edit this file in Git,
             edit contents in Pretalx, regenerate the PHP files and commit them
             in the Git repository of the website. -->
        <p><a href="programm/mittwoch.php#session_HEE3SU">&#9668;&#9668; zurück zum Programm</a> </p>
        <h2 class='abstract-title'>Wie man offene Geodaten bekommt, jetzt! Meine Erfahrung in Luxemburg, in der EU und ausserhalb.</h2>
        <section>
            <p>
                <span class='abstract-sessiontype'>Diverses</span> von                <span class='abstract-speakers'>Guillaume Rischard</span></p>
                            <p><span class='abstract-time-heading'>Zeit: </span>Mittwoch 11. März 13:45 Uhr<br><span class='abstract-room-heading'>Ort: </span>HS Rundbau</p>

            
            <p>Platzhalter um Platz zu halten Platzhalter um Platz zu halten Platzhalter um Platz zu halten Platzhalter um Platz zu halten</p>
        </section>


	<?php include "../inc/footer.inc"; ?>

</body>

</html>