<!doctype html>
<html lang="de">

<head>
	<meta charset="utf-8">
<meta http-equiv="x-ua-compatible" content="ie=edge">
<meta name="description" content="Die FOSSGIS-Konferenz ist im D-A-CH Raum die führende Konferenz für Freie und Open Source Software für Geoinformationssysteme OpenStreetMap.">
<meta name="keywords" content="FOSSGIS, FOSSGIS-Konferenz, 2019, FOSSGIS-Konferenz 2019, Open Source, GIS, Konferenz, Geoinformatik, OpenStreetMap, HTW Dresden">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="apple-itunes-app" content="app-id=1453299630">

	<base href="/2020/sessions">
	<title>Die Welt als runde Sache auf der ebenen Karte – FOSSGIS 2020</title>

	<link rel="stylesheet" href="./css/normalize.css">
	<link rel="stylesheet" href="./css/base.css">
	<link rel="stylesheet" href="./css/print.css" media="print">
</head>

<body id="programm">
	<header class="page-header">
	<a href="./" alt="FOSSGIS Konferenz 2020">
		<img class="page-logo" src="./img/fossgis2020-bollenhut.png">
	</a>
	<h1 class="page-title">
		FOSSGIS-Konferenz 2020<br>
		<span class="amp">Freiburg</span> <br>
		<span class="amp">11.&ndash;14. März</span>
	</h1>
</header>

<nav>
	<ul class="main">
		<li id="navHome">
			<a href="./">Startseite</a>
		</li>
		<!--<li id="navAnmeldung">
			<a href="./anmeldung/">Anmeldung</a>
		</li>-->
		<li id="navProgramm">
		<a href="./programm/">Programm</a>
		</li>
		<!--<li id="navAnreise">
			<a href="./anreise/">Anreise</a>
		</li>-->
		<li id="navStandort">
			<a href="./standort/">Standort</a>
		</li>
		<li id="navEvents">
			<a href="./socialevents/">Social Events</a>
		</li>
		<li id="navTeam">
			<a href="./loc/loc.php">Team</a>
		</li>
	</ul>
</nav>

<div class="hero">
	<figure>
		<img class="img-fluid" src="./img/freiburg.jpg" alt="Freiburg Luftbild">
		<figcaption>Photo: Pixaby</figcaption>
	</figure>
</div>

        <!-- This file was generated by a script. Do not edit this file in Git,
             edit contents in Pretalx, regenerate the PHP files and commit them
             in the Git repository of the website. -->
        <p><a href="programm/mittwoch.php#session_JV7GRQ">&#9668;&#9668; zurück zum Programm</a> </p>
        <h2 class='abstract-title'>Die Welt als runde Sache auf der ebenen Karte</h2>
        <section>
            <p>
                                <span class='abstract-speakers'>Wolfgang Hinsch</span></p>
                            <p><span class='abstract-time-heading'>Zeit: </span>Mittwoch 11. März 10:30 Uhr<br><span class='abstract-room-heading'>Ort: </span>HS Anatomie</p>

                        <div class="video-container">
                <a href="https://media.ccc.de/v/fossgis2020-3120-die-welt-als-runde-sache-auf-der-ebenen-karte">
                    <img class="video-preview" src="video_previews/3120-hd.jpg" alt="Vorschaubild des Videos">
                    <div class="video-preview-overlay"></div>
                </a>
            </div>
                        <p><a href="/2020/attachments/JV7GRQ_01_wolfgangHinsch_DieWeltAlsRundeSacheAufDerEbe_Vgrq34z.pdf">Vortragsfolien (PDF) </a></p>
            <p>Programme zur Kartenerstellung arbeiten mit sogenannten Koordinatenbezugssystemen (KBS), entweder explizit wie QGIS, das in der Lage ist, Layer mit unterschiedlichen KBS zur Laufzeit in ein Projekt-KBS umzurechnen, oder implizit wie viele Programme, die einfach die vorgegebenen x- und y-Werte als Koordinatensystem benutzen. In diesem Vortrag wird aufgezeigt, was notwendig und möglich ist, damit die runde Erdoberfläche auf einer ebenen Oberfläche wie einer Landkarte oder einem Bildschirm dargestellt werden kann. Über Begriffe wie Referenzellipsoid und Geoid wird auch auf die Höhenbestimmung eingegangen.
Auf Formeln und mathematische Einzelheiten wird nicht eingegangen.</p>
        <div class='abstract-bio'>
            <h3 class='abstract-bio-name'>Wolfgang Hinsch</h3>
            <p>Ich bin Vermessungsingeneur, seit 2008 bei OSM tätig und habe schon mehrere Vorträge, u.a. bei Fossgis und (Meta-)Nook in Lübeck gehalten.
Ich beschäftige mich vorwiegend mit der kartographischen Darstellung der OSM-Daten.</p>
        </div>
        </section>


	<footer>
	<ul class="main">
		<li>
			<a href="https://www.fossgis.de/impressum/">Impressum</a>
		</li>
		<li>
			<a href="./agb.php">AGB</a>
		</li>
		<li>
			<a href="https://www.fossgis.de/datenschutzerklärung">Datenschutzerklärung</a>
		</li>
	</ul>
</footer>

</body>

</html>