<!doctype html>
<html lang="de">

<head>
	<?php include "../inc/meta.inc"; ?>

	<base href="<?php echo dirname($_SERVER['SCRIPT_NAME']); ?>">
	<title>Erdbeben und OpenStreetMap – FOSSGIS 2020</title>

	<link rel="stylesheet" href="./css/normalize.css">
	<link rel="stylesheet" href="./css/base.css">
	<link rel="stylesheet" href="./css/print.css" media="print">
</head>

<body id="programm">
	<?php include "../inc/header.inc"; ?>

        <!-- This file was generated by a script. Do not edit this file in Git,
             edit contents in Pretalx, regenerate the PHP files and commit them
             in the Git repository of the website. -->
        <p><a href="programm/freitag.php#session_JYFVQL">zurück zum Programm</a></p>
        <h2 class='abstract-title'>Erdbeben und OpenStreetMap</h2>
        <section>
            <p>
                <span class='abstract-sessiontype'>Langer OpenStreetMap-Vortrag</span> von                <span class='abstract-speakers'>Danijel Schorlemmer</span></p>
            <p><span class='abstract-time-heading'>Zeit: </span>Freitag 13. März 13:00 Uhr<br><span class='abstract-room-heading'>Ort: </span>HS Rundbau</p>

            
            <p>Erdbeben bedrohen viele Regionen dieser Welt mit steigendem Risiko aufgrund von Urbanisierung und Industrialisierung. Für Resilienz- und Vorsorgemaßnahmen ist ein genaues Verständnis dieses Risikos in bezug auf Menschen und Werte notwendig. Expositionsmodelle, die Lage, Größe und Typ von Gebäuden, die Anzahl der Bewohner nach Tageszeit und den Wiederbeschaffungswert beschreiben, übersetzen gemessene oder prognostizierte Erdbebenerschütterungen in Verluste von Leben und Werten. </p>
<p>Hier stellen wir unser globales Expositionsmodell auf der Basis von OpenStreetMap vor. Dieses Modell versucht alle Expositionsindikatoren, wie die Anzahl der Stockwerke, die Nutzung, die Dachform, aus OpenStreetMap zu extrahieren. Aus den Indikatoren jedes einzelnen Gebäudes werden mithilfe von durch Experten festgelegten Regeln eine probabilistische Gebäudeklassifizierung errechnet. Diese beschreibt die möglichen Gebäudetypen und ihre Wahrscheinlichkeit. Gleichzeitig werden auch die weiteren Angaben (Größe, Anzahl der Bewohner nach Tageszeit und Wiederbeschaffungswert) probabilistisch ermittelt. In Bereichen unvollständiger Gebäudeabdeckung, werden klassische Expositionsmodelle, die aggregierte Gebäudeverteilungen beschreiben, mit unserem Modell überlagert. Durch die nahezu Echtzeitberechungen unseres Modells, profitieren wir vom Wachstum von OpenStreetMap direkt und, aufgrund der ungefähr 5 Millionen Gebäude, die pro Monat hinzugefügt werden, werden die unvollständigen Bereiche immer kleiner und durch unser gebäudegenaues Expositionsmodell ersetzt.</p>
        </section>


	<?php include "../inc/footer.inc"; ?>

</body>

</html>