<!doctype html>
<html lang="de">

<head>
	<meta charset="utf-8">
<meta http-equiv="x-ua-compatible" content="ie=edge">
<meta name="description" content="Die FOSSGIS-Konferenz ist im D-A-CH Raum die führende Konferenz für Freie und Open Source Software für Geoinformationssysteme OpenStreetMap.">
<meta name="keywords" content="FOSSGIS, FOSSGIS-Konferenz, 2019, FOSSGIS-Konferenz 2019, Open Source, GIS, Konferenz, Geoinformatik, OpenStreetMap, HTW Dresden">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="apple-itunes-app" content="app-id=1453299630">

	<base href="/2020/sessions">
	<title>Mr. Map - Open Source Service Registry – FOSSGIS 2020</title>

	<link rel="stylesheet" href="./css/normalize.css">
	<link rel="stylesheet" href="./css/base.css">
	<link rel="stylesheet" href="./css/print.css" media="print">
</head>

<body id="programm">
	<header class="page-header">
	<a href="./" alt="FOSSGIS Konferenz 2020">
		<img class="page-logo" src="./img/fossgis2020-bollenhut.png">
	</a>
	<h1 class="page-title">
		FOSSGIS-Konferenz 2020<br>
		<span class="amp">Freiburg</span> <br>
		<span class="amp">11.&ndash;14. März</span>
	</h1>
</header>

<nav>
	<ul class="main">
		<li id="navHome">
			<a href="./">Startseite</a>
		</li>
		<!--<li id="navAnmeldung">
			<a href="./anmeldung/">Anmeldung</a>
		</li>-->
		<li id="navProgramm">
		<a href="./programm/">Programm</a>
		</li>
		<!--<li id="navAnreise">
			<a href="./anreise/">Anreise</a>
		</li>-->
		<li id="navStandort">
			<a href="./standort/">Standort</a>
		</li>
		<li id="navEvents">
			<a href="./socialevents/">Social Events</a>
		</li>
		<li id="navTeam">
			<a href="./loc/loc.php">Team</a>
		</li>
	</ul>
</nav>

<div class="hero">
	<figure>
		<img class="img-fluid" src="./img/freiburg.jpg" alt="Freiburg Luftbild">
		<figcaption>Photo: Pixaby</figcaption>
	</figure>
</div>

        <!-- This file was generated by a script. Do not edit this file in Git,
             edit contents in Pretalx, regenerate the PHP files and commit them
             in the Git repository of the website. -->
        <p><a href="programm/freitag.php#session_K7VNXP">&#9668;&#9668; zurück zum Programm</a> </p>
        <h2 class='abstract-title'>Mr. Map - Open Source Service Registry</h2>
        <section>
            <p>
                                <span class='abstract-speakers'>Michel Peltriaux</span></p>
                            <p><span class='abstract-time-heading'>Zeit: </span>Freitag 13. März 10:00 Uhr<br><span class='abstract-room-heading'>Ort: </span>HS Rundbau</p>

                        <div class="video-container">
                <a href="https://media.ccc.de/v/fossgis2020-3015-mr-map-open-source-service-registry">
                    <img class="video-preview" src="video_previews/3015-hd.jpg" alt="Vorschaubild des Videos">
                    <div class="video-preview-overlay"></div>
                </a>
            </div>
                        
            <p>Als Herzstück einer jeden Geodateninfrastruktur sollte eine Service Registry - eine „Diensteregistrierungskomponente“ - stehen. Die Anforderungen an eine solche Registrierungskomponente sind vielfältig und mitunter aufgrund komplexer technischer Zusammenhänge nicht im Handumdrehen umzusetzen. Hierzu zählen u.a. die Registrierung von Web Map Services oder Web Feature Services in den jeweiligen technischen Standard, die Zugänglichkeit dieser für Außenstehende, Anforderungen an die Zugriffsbeschränkung ausgewählter Dienste oder einzelner Subelemente wie bspw. Layer, eine Gruppen- und Nutzerverwaltung, usw.
„Mr. Map“ wird seit April 2019 von der GDI-RP, mit Sitz in Koblenz, konzipiert und entwickelt und stellt eine Lösung für die technischen Anforderungen und Erwartungen des modernen Benutzers dar. Als Webapplikation läuft „Mr. Map“ plattformübergreifend und bietet bereits, neben den eingangs gelisteten Grundfunktionen einer Service Registry, zusätzliche Komponenten, wie bspw. eine Suchschnittstelle zur Anbindung an weitere Systeme wie Geoportale usw., ein internes Publisher-System zur Verteilung der Registrierungsrechte eigener Dienste auf andere Nutzer oder einen integrierten Metadateneditor, mit welchem nicht-technische Metadaten eines Dienstes bearbeitet werden können. </p>
<p>Im Vortrag werden die Motivation des Projektes, die Leitsätze der Entwicklung und des Designs und einige technische Hintergründe beleuchtet sowie Inhalte des bisherigen Entwicklungsstandes präsentiert.</p>
        </section>


	<footer>
	<ul class="main">
		<li>
			<a href="https://www.fossgis.de/impressum/">Impressum</a>
		</li>
		<li>
			<a href="./agb.php">AGB</a>
		</li>
		<li>
			<a href="https://www.fossgis.de/datenschutzerklärung">Datenschutzerklärung</a>
		</li>
	</ul>
</footer>

</body>

</html>