<!doctype html>
<html lang="de">

<head>
	<?php include "../inc/meta.inc"; ?>

	<base href="<?php echo dirname($_SERVER['SCRIPT_NAME']); ?>">
	<title>Mr. Map - Open Source Service Registry – FOSSGIS 2020</title>

	<link rel="stylesheet" href="./css/normalize.css">
	<link rel="stylesheet" href="./css/base.css">
	<link rel="stylesheet" href="./css/print.css" media="print">
</head>

<body id="programm">
	<?php include "../inc/header.inc"; ?>

        <!-- This file was generated by a script. Do not edit this file in Git,
             edit contents in Pretalx, regenerate the PHP files and commit them
             in the Git repository of the website. -->
        <p><a href="programm/freitag.php#session_K7VNXP">zurück zum Programm</a></p>
        <h2 class='abstract-title'>Mr. Map - Open Source Service Registry</h2>
        <section>
            <p>
                                <span class='abstract-speakers'>Michel Peltriaux</span></p>
            <p><span class='abstract-time-heading'>Zeit: </span>Freitag 13. März 09:00 Uhr<br><span class='abstract-room-heading'>Ort: </span>HS Rundbau</p>

            
            <p>Als Herzstück einer jeden Geodateninfrastruktur sollte eine Service Registry - eine „Diensteregistrierungskomponente“ - stehen. Die Anforderungen an eine solche Registrierungskomponente sind vielfältig und mitunter aufgrund komplexer technischer Zusammenhänge nicht im Handumdrehen umzusetzen. Hierzu zählen u.a. die Registrierung von Web Map Services oder Web Feature Services in den jeweiligen technischen Standard, die Zugänglichkeit dieser für Außenstehende, Anforderungen an die Zugriffsbeschränkung ausgewählter Dienste oder einzelner Subelemente wie bspw. Layer, eine Gruppen- und Nutzerverwaltung, usw.
„Mr. Map“ wird seit April 2019 von der GDI-RP, mit Sitz in Koblenz, konzipiert und entwickelt und stellt eine Lösung für die technischen Anforderungen und Erwartungen des modernen Benutzers dar. Als Webapplikation läuft „Mr. Map“ plattformübergreifend und bietet bereits, neben den eingangs gelisteten Grundfunktionen einer Service Registry, zusätzliche Komponenten, wie bspw. eine Suchschnittstelle zur Anbindung an weitere Systeme wie Geoportale usw., ein internes Publisher-System zur Verteilung der Registrierungsrechte eigener Dienste auf andere Nutzer oder einen integrierten Metadateneditor, mit welchem nicht-technische Metadaten eines Dienstes bearbeitet werden können. </p>
<p>Im Vortrag werden die Motivation des Projektes, die Leitsätze der Entwicklung und des Designs und einige technische Hintergründe beleuchtet sowie Inhalte des bisherigen Entwicklungsstandes präsentiert.</p>
        </section>


	<?php include "../inc/footer.inc"; ?>

</body>

</html>