<!doctype html>
<html lang="de">

<head>
	<meta charset="utf-8">
<meta http-equiv="x-ua-compatible" content="ie=edge">
<meta name="description" content="Die FOSSGIS-Konferenz ist im D-A-CH Raum die führende Konferenz für Freie und Open Source Software für Geoinformationssysteme OpenStreetMap.">
<meta name="keywords" content="FOSSGIS, FOSSGIS-Konferenz, 2019, FOSSGIS-Konferenz 2019, Open Source, GIS, Konferenz, Geoinformatik, OpenStreetMap, HTW Dresden">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="apple-itunes-app" content="app-id=1453299630">

	<base href="/2020/sessions">
	<title>GRASS GIS in der Cloud: Actinia-Geoprozessierung – FOSSGIS 2020</title>

	<link rel="stylesheet" href="./css/normalize.css">
	<link rel="stylesheet" href="./css/base.css">
	<link rel="stylesheet" href="./css/print.css" media="print">
</head>

<body id="programm">
	<header class="page-header">
	<a href="./" alt="FOSSGIS Konferenz 2020">
		<img class="page-logo" src="./img/fossgis2020-bollenhut.png">
	</a>
	<h1 class="page-title">
		FOSSGIS-Konferenz 2020<br>
		<span class="amp">Freiburg</span> <br>
		<span class="amp">11.&ndash;14. März</span>
	</h1>
</header>

<nav>
	<ul class="main">
		<li id="navHome">
			<a href="./">Startseite</a>
		</li>
		<!--<li id="navAnmeldung">
			<a href="./anmeldung/">Anmeldung</a>
		</li>-->
		<li id="navProgramm">
		<a href="./programm/">Programm</a>
		</li>
		<!--<li id="navAnreise">
			<a href="./anreise/">Anreise</a>
		</li>-->
		<li id="navStandort">
			<a href="./standort/">Standort</a>
		</li>
		<li id="navEvents">
			<a href="./socialevents/">Social Events</a>
		</li>
		<li id="navTeam">
			<a href="./loc/loc.php">Team</a>
		</li>
	</ul>
</nav>

<div class="hero">
	<figure>
		<img class="img-fluid" src="./img/freiburg.jpg" alt="Freiburg Luftbild">
		<figcaption>Photo: Pixaby</figcaption>
	</figure>
</div>

        <!-- This file was generated by a script. Do not edit this file in Git,
             edit contents in Pretalx, regenerate the PHP files and commit them
             in the Git repository of the website. -->
        <p><a href="programm/donnerstag.php#session_KNUBLU">&#9668;&#9668; zurück zum Programm</a> </p>
        <h2 class='abstract-title'>GRASS GIS in der Cloud: Actinia-Geoprozessierung</h2>
        <section>
            <p>
                                <span class='abstract-speakers'>Markus Neteler, Carmen Tawalika</span></p>
                            <p><span class='abstract-time-heading'>Zeit: </span>Donnerstag 12. März 16:00 Uhr<br><span class='abstract-room-heading'>Ort: </span>HS Anatomie</p>

                        <div class="video-container">
                <a href="https://media.ccc.de/v/fossgis2020-3030-grass-gis-in-der-cloud-actinia-geoprozessierung">
                    <img class="video-preview" src="video_previews/3030-hd.jpg" alt="Vorschaubild des Videos">
                    <div class="video-preview-overlay"></div>
                </a>
            </div>
                        
            <p>Ursprünglich GRaaS (GRASS as a Service) genannt, wurde actinia (https://actinia.mundialis.de) entwickelt, um die GRASS-GIS-Funktionalität über eine HTTPS REST API bereitzustellen. GRASS GIS Locations, Mapsets, Vektor- und Rasterdaten sowie raum-zeitliche Daten werden zu Ressourcen, die per REST verwaltet und visualisiert werden können. Mit den bestehenden (z.B. Landsat) und in den letzten Jahren neu entstehenden (Copernicus Sentinel) großen Geodatenpools, die Tag für Tag wachsen, soll actinia dem Paradigma folgen, Algorithmen zu den Clouddaten zu bringen. Actinia ermöglicht es, eine große Menge an Geoinformationen aufzubereiten, zu analysieren und bereitzustellen, ohne dass Kenntnisse der Daten, der Analyse, der geeigneten Software zur Automatisierung oder skalierbarer Hardware-Ressourcen erforderlich sind.</p>
<p>Einige der Funktionalitäten sind persistente und flüchtige Berechnung, Benutzerverwaltung zur Begrenzung von z.B. Pixeln, Prozessen und Berechnungsdauer sowie das Loggen von API-Aufrufen und verwendeten Ressourcen durch jeden Benutzer. Ein weiterer Vorteil ist die einfache Installation mit Docker. Bei der Installation in einer Cloud-Umgebung mit OpenShift oder Kubernetes verwaltet der integrierte Loadbalancer das Cluster automatisch.
Dem Geist von FOSS folgend sind wir stolz, ein OSGeo-Community-Projekt geworden zu sein und freuen uns auf die Erweiterung der actinia-Community.</p>
<p>Der Vortrag gibt eine Übersicht über Konzepte und grundlegende Funktionalitäten von Actinia.</p>
        <div class='abstract-bio'>
            <h3 class='abstract-bio-name'>Markus Neteler</h3>
            <p>Mitgründer von mundialis, Bonn (https://www.mundialis.de/)</p>
        </div>
        <div class='abstract-bio'>
            <h3 class='abstract-bio-name'>Carmen Tawalika</h3>
            <p>Geographin, Open Source-Anhängerin und Entwicklerin bei mundialis</p>
        </div>
        </section>


	<footer>
	<ul class="main">
		<li>
			<a href="https://www.fossgis.de/impressum/">Impressum</a>
		</li>
		<li>
			<a href="./agb.php">AGB</a>
		</li>
		<li>
			<a href="https://www.fossgis.de/datenschutzerklärung">Datenschutzerklärung</a>
		</li>
	</ul>
</footer>

</body>

</html>