<!doctype html>
<html lang="de">

<head>
	<meta charset="utf-8">
<meta http-equiv="x-ua-compatible" content="ie=edge">
<meta name="description" content="Die FOSSGIS-Konferenz ist im D-A-CH Raum die führende Konferenz für Freie und Open Source Software für Geoinformationssysteme OpenStreetMap.">
<meta name="keywords" content="FOSSGIS, FOSSGIS-Konferenz, 2019, FOSSGIS-Konferenz 2019, Open Source, GIS, Konferenz, Geoinformatik, OpenStreetMap, HTW Dresden">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="apple-itunes-app" content="app-id=1453299630">

	<base href="/2020/sessions">
	<title>Einsatz von XPlanung in der kommunalen Praxis - ein Werkstattbericht – FOSSGIS 2020</title>

	<link rel="stylesheet" href="./css/normalize.css">
	<link rel="stylesheet" href="./css/base.css">
	<link rel="stylesheet" href="./css/print.css" media="print">
</head>

<body id="programm">
	<header class="page-header">
	<a href="./" alt="FOSSGIS Konferenz 2020">
		<img class="page-logo" src="./img/fossgis2020-bollenhut.png">
	</a>
	<h1 class="page-title">
		FOSSGIS-Konferenz 2020<br>
		<span class="amp">Freiburg</span> <br>
		<span class="amp">11.&ndash;14. März</span>
	</h1>
</header>

<nav>
	<ul class="main">
		<li id="navHome">
			<a href="./">Startseite</a>
		</li>
		<!--<li id="navAnmeldung">
			<a href="./anmeldung/">Anmeldung</a>
		</li>-->
		<li id="navProgramm">
		<a href="./programm/">Programm</a>
		</li>
		<!--<li id="navAnreise">
			<a href="./anreise/">Anreise</a>
		</li>-->
		<li id="navStandort">
			<a href="./standort/">Standort</a>
		</li>
		<li id="navEvents">
			<a href="./socialevents/">Social Events</a>
		</li>
		<li id="navTeam">
			<a href="./loc/loc.php">Team</a>
		</li>
	</ul>
</nav>

<div class="hero">
	<figure>
		<img class="img-fluid" src="./img/freiburg.jpg" alt="Freiburg Luftbild">
		<figcaption>Photo: Pixaby</figcaption>
	</figure>
</div>

        <!-- This file was generated by a script. Do not edit this file in Git,
             edit contents in Pretalx, regenerate the PHP files and commit them
             in the Git repository of the website. -->
        <p><a href="programm/donnerstag.php#session_KU8UZS">&#9668;&#9668; zurück zum Programm</a> </p>
        <h2 class='abstract-title'>Einsatz von XPlanung in der kommunalen Praxis - ein Werkstattbericht</h2>
        <section>
            <p>
                                <span class='abstract-speakers'>Torsten Friebe, Michael Schulz</span></p>
                            <p><span class='abstract-time-heading'>Zeit: </span>Donnerstag 12. März 11:00 Uhr<br><span class='abstract-room-heading'>Ort: </span>HS Rundbau</p>

                        <div class="video-container">
                <a href="https://media.ccc.de/v/fossgis2020-3073-einsatz-von-xplanung-in-der-kommunalen-praxis-ein-werkstattbericht">
                    <img class="video-preview" src="video_previews/3073-hd.jpg" alt="Vorschaubild des Videos">
                    <div class="video-preview-overlay"></div>
                </a>
            </div>
                        <p><a href="/2020/attachments/KU8UZS_fossgis_xplanung_friebe_schulz_final_DyI0yMw.pdf">Vortragsfolien (PDF) </a></p>
            <p>Die Stadt Freiburg hat sich Ende 2018 auf den Weg gemacht, die digitale Bauleitplanung für Bebauungsplanverfahren auf die Verwendung des XÖV Standards XPlanung umzustellen, sowie das aktuelle Planungsrecht XPlanung-konform nach zu erfassen. Die Bereitstellung der erfassten Daten soll wiederum über OGC-Dienste unter Einbindung in ein zentrales Austausch- und Validierungsportal durchgeführt werden.</p>
<p>Die Präsentation zeigt die Erfahrungen und verschiedenen Schritte zur Umsetzung mit den eingesetzten FOSS-Werkzeugen, wie deegree, HALE, QGIS, PostgreSQL/PostGIS, sowie die Ergebnisse aber auch die Schwierigkeiten. </p>
<p>Die Einbindung der bereitgestellten Daten per XPlanung WMS- und WFS-Diensten in die Metadaten-Prozesse der GDI Freiburg unter Verwendung von GeoNetwork werden im Vortrag ebenfalls erörtert wie die Transformation in INSPIRE-PLU-Dienste.</p>
        <div class='abstract-bio'>
            <h3 class='abstract-bio-name'>Torsten Friebe</h3>
            <p>Torsten Friebe ist Committer und Mitglied des TMC im OSGeo-Projekt deegree (https://www.deegree.org). Seit 2011 ist er Gesellschafter und Geschäftsführer bei der lat/lon GmbH in Bonn.</p>
        </div>
        <div class='abstract-bio'>
            <h3 class='abstract-bio-name'>Michael Schulz</h3>
            <p>Stadt Freiburg, Digitales und IT</p>
        </div>
        </section>


	<footer>
	<ul class="main">
		<li>
			<a href="https://www.fossgis.de/impressum/">Impressum</a>
		</li>
		<li>
			<a href="./agb.php">AGB</a>
		</li>
		<li>
			<a href="https://www.fossgis.de/datenschutzerklärung">Datenschutzerklärung</a>
		</li>
	</ul>
</footer>

</body>

</html>