<!doctype html>
<html lang="de">

<head>
	<meta charset="utf-8">
<meta http-equiv="x-ua-compatible" content="ie=edge">
<meta name="description" content="Die FOSSGIS-Konferenz ist im D-A-CH Raum die führende Konferenz für Freie und Open Source Software für Geoinformationssysteme OpenStreetMap.">
<meta name="keywords" content="FOSSGIS, FOSSGIS-Konferenz, 2019, FOSSGIS-Konferenz 2019, Open Source, GIS, Konferenz, Geoinformatik, OpenStreetMap, HTW Dresden">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="apple-itunes-app" content="app-id=1453299630">

	<base href="/2020/sessions">
	<title>Lizmap Web Client und QGIS – FOSSGIS 2020</title>

	<link rel="stylesheet" href="./css/normalize.css">
	<link rel="stylesheet" href="./css/base.css">
	<link rel="stylesheet" href="./css/print.css" media="print">
</head>

<body id="programm">
	<header class="page-header">
	<a href="./" alt="FOSSGIS Konferenz 2020">
		<img class="page-logo" src="./img/fossgis2020-bollenhut.png">
	</a>
	<h1 class="page-title">
		FOSSGIS-Konferenz 2020<br>
		<span class="amp">Freiburg</span> <br>
		<span class="amp">11.&ndash;14. März</span>
	</h1>
</header>

<nav>
	<ul class="main">
		<li id="navHome">
			<a href="./">Startseite</a>
		</li>
		<!--<li id="navAnmeldung">
			<a href="./anmeldung/">Anmeldung</a>
		</li>-->
		<li id="navProgramm">
		<a href="./programm/">Programm</a>
		</li>
		<!--<li id="navAnreise">
			<a href="./anreise/">Anreise</a>
		</li>-->
		<li id="navStandort">
			<a href="./standort/">Standort</a>
		</li>
		<li id="navEvents">
			<a href="./socialevents/">Social Events</a>
		</li>
		<li id="navTeam">
			<a href="./loc/loc.php">Team</a>
		</li>
	</ul>
</nav>

<div class="hero">
	<figure>
		<img class="img-fluid" src="./img/freiburg.jpg" alt="Freiburg Luftbild">
		<figcaption>Photo: Pixaby</figcaption>
	</figure>
</div>

        <!-- This file was generated by a script. Do not edit this file in Git,
             edit contents in Pretalx, regenerate the PHP files and commit them
             in the Git repository of the website. -->
        <p><a href="programm/mittwoch.php#session_KYTHBD">&#9668;&#9668; zurück zum Programm</a> </p>
        <h2 class='abstract-title'>Lizmap Web Client und QGIS</h2>
        <section>
            <p>
                                <span class='abstract-speakers'>Günter Wagner</span></p>
                            <p><span class='abstract-time-heading'>Zeit: </span>Mittwoch 11. März 17:00 Uhr<br><span class='abstract-room-heading'>Ort: </span>HS Weismannhaus</p>

                        <div class="video-container">
                <a href="https://media.ccc.de/v/fossgis2020-4697-lizmap-web-client-und-qgis">
                    <img class="video-preview" src="video_previews/4697-hd.jpg" alt="Vorschaubild des Videos">
                    <div class="video-preview-overlay"></div>
                </a>
            </div>
                        <p><a href="/2020/attachments/KYTHBD_Vortrag_Lizmap_Web_Client_und_QGIS_Guenter_Wagn_9uA2lE6.pdf">Vortragsfolien (PDF) </a></p>
            <p>Der Lizmap Web Client der französischen Firma 3Liz ist in Deutschland leider kaum bekannt. Dabei bietet er den entscheidenden Vorteil, dass die gesamte Konfiguration im QGIS-Plugin vorgenommen wird. Zur Veröffentlichung wird nur das QGIS-Projektfile und eine autom. erstellte Konfigurationsdatei auf den Server übertragen.</p>
<p>Die Web-Anwendung stellt das QGIS-Projekt (inkl. Kartensymbole und Beschriftung) aufgrund der gemeinsame Rendering Engine von QGIS-Desktop und QGIS-Server 1:1 im Internet dar. Ferner können u.a. die Druckzusammenstellung incl. dem Atlasdruck und die Attributtabelle in der Web-Anwendung verwendet werden. Suchfunktionen können über Datenbankinhalte erstellt werden.</p>
<p>Die Benutzer-/Gruppen- und Projektverwaltung erfolgt komfortabel über das Backend des Clients im Web.  </p>
<p>Der Web-Client steht aktuell in der Version 3.3.4 für den QGIS-Server 3.4 auf Github zur Verfügung (Open-Source: Mozilla Public Licence) und unterstützt die OGC-Standards WMS, WFS-T, WMTS und WPS. </p>
<p>In dem Vortrag wird der Lizmap Client vorgestellt, die wesentliche Konfiguration eines Projektes gezeigt und beispielhaft ein QGIS-Projekt als Web-GIS-Projekt veröffentlicht.</p>
        <div class='abstract-bio'>
            <h3 class='abstract-bio-name'>Günter Wagner</h3>
            <p>Günter Wagner betreut seit über 20 Jahren kleinere Gemeinden und Städte in Bezug auf CAD/GIS/WebGIS-Anwendungen und Dienstleistungen.</p>
<p>Individuelle, an die Bedürfnisse des Kunden angepasste Lösungen werden auf Basis von Standardkomponenten, möglichst aus dem Open-Source Bereich, realisiert. </p>
<p>Seit 2011 betreibt H. Wagner das Ingenieurbüro <a href="https://wagner-it.de">Wagner-IT</a>. Er ist Mitglied im FOSSGIS e.V. und QGIS-DE e.V. und unterstützt das QGIS-Projekt als Bronze-Sponsor.</p>
        </div>
        </section>


	<footer>
	<ul class="main">
		<li>
			<a href="https://www.fossgis.de/impressum/">Impressum</a>
		</li>
		<li>
			<a href="./agb.php">AGB</a>
		</li>
		<li>
			<a href="https://www.fossgis.de/datenschutzerklärung">Datenschutzerklärung</a>
		</li>
	</ul>
</footer>

</body>

</html>