<!doctype html>
<html lang="de">

<head>
	<?php include "../inc/meta.inc"; ?>

	<base href="<?php echo dirname($_SERVER['SCRIPT_NAME']); ?>">
	<title>GeoPortal Koblenz – digital. vielschichtig. maßgebend. – FOSSGIS 2020</title>

	<link rel="stylesheet" href="./css/normalize.css">
	<link rel="stylesheet" href="./css/base.css">
	<link rel="stylesheet" href="./css/print.css" media="print">
</head>

<body id="programm">
	<?php include "../inc/header.inc"; ?>

        <!-- This file was generated by a script. Do not edit this file in Git,
             edit contents in Pretalx, regenerate the PHP files and commit them
             in the Git repository of the website. -->
        <p><a href="programm/mittwoch.php#session_L9NGAN">&#9668;&#9668; zurück zum Programm</a> </p>
        <h2 class='abstract-title'>GeoPortal Koblenz – digital. vielschichtig. maßgebend.</h2>
        <section>
            <p>
                                <span class='abstract-speakers'>Christine Dolezich, Andreas Weckbecker</span></p>
                            <p><span class='abstract-time-heading'>Zeit: </span>Mittwoch 11. März 16:00 Uhr<br><span class='abstract-room-heading'>Ort: </span>HS Weismannhaus</p>

            
            <p>Der digitale Stadtplan von Koblenz hat ein neues Kleid: den Online-Service „GeoPortal Koblenz“. Diese Web-Anwendung erweitert das eGovernment-Angebot der Stadt Koblenz und wurde mit dem Ziel einer zukünftigen INSPIRE-konformen Bereitstellung der städtischen Geodaten aufgebaut.</p>
<p>Hier finden sich raumbezogene Informationen aus den verschiedensten Themenbereichen im Stadtgebiet von Koblenz – dargestellt anhand unterschiedlicher aktueller, amtlicher Kartengrundlagen. Da Online-Kartendienste keinen amtlichen Charakter besitzen und die Urheberrechte in einigen Fällen nicht eindeutig sind, soll verwaltungsintern das Geoportal Koblenz eingesetzt werden. Der interne Einsatz geschieht einmal über das Portal (bzw. die applikationsgesteuerte Startseite) oder durch die Einbindung der Darstellungsdienste des vorgelagerten GeoServers. Damit ist der GeoServer ein zentraler Bestandteil einer neu entstehenden GDI Koblenz.</p>
<p>Auch extern ist das Geoportal (ursprünglich als Nachfolger des CityGuide konzipiert) verfügbar. Die Funktionen sind dort weitestgehend identisch. Die Datenbestände jedoch wurden reduziert, da nicht alle Informationen für die Öffentlichkeit bestimmt sind (z. B. historische Bodenrichtwerte). Künftig sollen die Bürger die Web-Map-Dienste ebenso in die eigene Software einbinden können. Zuvor soll ein Metadatenmanagement durch das Sachgebiet Geodatenmanagement und –bereitstellung des Amtes für Stadtvermessung und Bodenmanagment implementiert werden, um die INSPIRE-Konformität zu erreichen.</p>
<p>Das Geoportal Koblenz selbst fußt auf der OpenSource-Software Shogun II der Fa. terrestris. Aufgrund der IT-Architektur der Stadtverwaltung Koblenz existiert für die interne sowie für die externe Anwendung jeweils eine Instanz. Nach definierten Regelungen findet nächtlich eine Synchronisation des Frontends (Startseite), des Backends (GeoServer), der eigentlichen Anwendung sowie der Geodaten statt. In diesem Synchronisationsprozess werden die sensiblen Daten ausgespart. Für die Einbindung externe WMS-Dienste in die externe Anwendung ist ein White-Listing erforderlich, da der Provider keine offene Kommunikation mit nicht registrierten Diensten zulässt.</p>
<p>Aktuell wird intern an neuen Applikationen 
•   zur Information über alle städtische Liegenschaften (Verknüpfung zu CAFM-Software der Stadt Koblenz),
•   als Visualisierungskomponente der bestehenden städtischen Lichtwellenleiter, 
•   für die Grünflächendokumentation sowie
•   als Übersicht über die Punkte des städtischen Festpunkfeldes für den vermessungstechnischen Raumbezug<br />
gearbeitet. Letztere soll könnte bei der Arbeit auf den digitalen Feldbüchern im Außendienst eine Wertvolle Unterstützung darstellen, zumal die Festpunkte in der Postgres-Datenbank des GeoServers vorgehalten werden könnten.</p>
<p>Außerdem finden Überlegungen zur Bereitstellung maßgeschneiderter Applikationen für sachverständige Dritte mit einer vorgeschalteten Authentifizierung statt. </p>
<p>Im Gegensatz zu anderen Konzepten liegt in Koblenz die Hoheit über die Daten beim Betreiber des Portals. Durch das Hosting beim Kommunalen Gebietsrechenzentrum der Stadt Koblenz bestehen kurze Wege und es wird eine zeitnahe Unterstützung sowie eine hohe Datensicherheit gewährleistet. </p>
<p>Die Präsentation gibt vertiefte Einblicke zu genannten Thematik-</p>
        </section>


	<?php include "../inc/footer.inc"; ?>

</body>

</html>