<!doctype html>
<html lang="de">

<head>
	<meta charset="utf-8">
<meta http-equiv="x-ua-compatible" content="ie=edge">
<meta name="description" content="Die FOSSGIS-Konferenz ist im D-A-CH Raum die führende Konferenz für Freie und Open Source Software für Geoinformationssysteme OpenStreetMap.">
<meta name="keywords" content="FOSSGIS, FOSSGIS-Konferenz, 2019, FOSSGIS-Konferenz 2019, Open Source, GIS, Konferenz, Geoinformatik, OpenStreetMap, HTW Dresden">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="apple-itunes-app" content="app-id=1453299630">

	<base href="/2020/sessions">
	<title>FOSSGIS-Jeopardy – FOSSGIS 2020</title>

	<link rel="stylesheet" href="./css/normalize.css">
	<link rel="stylesheet" href="./css/base.css">
	<link rel="stylesheet" href="./css/print.css" media="print">
</head>

<body id="programm">
	<header class="page-header">
	<a href="./" alt="FOSSGIS Konferenz 2020">
		<img class="page-logo" src="./img/fossgis2020-bollenhut.png">
	</a>
	<h1 class="page-title">
		FOSSGIS-Konferenz 2020<br>
		<span class="amp">Freiburg</span> <br>
		<span class="amp">11.&ndash;14. März</span>
	</h1>
</header>

<nav>
	<ul class="main">
		<li id="navHome">
			<a href="./">Startseite</a>
		</li>
		<!--<li id="navAnmeldung">
			<a href="./anmeldung/">Anmeldung</a>
		</li>-->
		<li id="navProgramm">
		<a href="./programm/">Programm</a>
		</li>
		<!--<li id="navAnreise">
			<a href="./anreise/">Anreise</a>
		</li>-->
		<li id="navStandort">
			<a href="./standort/">Standort</a>
		</li>
		<li id="navEvents">
			<a href="./socialevents/">Social Events</a>
		</li>
		<li id="navTeam">
			<a href="./loc/loc.php">Team</a>
		</li>
	</ul>
</nav>

<div class="hero">
	<figure>
		<img class="img-fluid" src="./img/freiburg.jpg" alt="Freiburg Luftbild">
		<figcaption>Photo: Pixaby</figcaption>
	</figure>
</div>

        <!-- This file was generated by a script. Do not edit this file in Git,
             edit contents in Pretalx, regenerate the PHP files and commit them
             in the Git repository of the website. -->
        <p><a href="programm/freitag.php#session_LKNHLJ">&#9668;&#9668; zurück zum Programm</a> </p>
        <h2 class='abstract-title'>FOSSGIS-Jeopardy</h2>
        <section>
            <p>
                <span class='abstract-sessiontype'>Diverses</span> von                <span class='abstract-speakers'>Johannes Kröger</span></p>
                            <p><span class='abstract-time-heading'>Zeit: </span>Freitag 13. März 14:30 Uhr<br><span class='abstract-room-heading'>Ort: </span>HS Rundbau</p>

                        
            <p>Das FOSSGIS-Jeopardy bietet als Fortsetzung der OSM-Quizze der Vorjahre wieder spannende Fragen zu (mehr oder weniger) wissenswerten Fakten und vor allem viel Spaß für jung und alt, alt und neu.</p>
<p>Jede/r ist herzlich eingeladen mitzuraten, um das eigene Wissen im Umfeld von GIS, OpenStreetMap, Kartografie, FOSS zu testen und vielleicht auch etwas aufzufrischen.</p>
<p>Du kennst sämtliche Parameter der OpenLayers-API, kannst jede Karte lesen und übst zum Spaß EPSG-Codes? Beste Voraussetzungen den Vorjahressieger zu entthronen!</p>
        <div class='abstract-bio'>
            <h3 class='abstract-bio-name'>Johannes Kröger</h3>
            <p>🌍🌐</p>
        </div>
        </section>


	<footer>
	<ul class="main">
		<li>
			<a href="https://www.fossgis.de/impressum/">Impressum</a>
		</li>
		<li>
			<a href="./agb.php">AGB</a>
		</li>
		<li>
			<a href="https://www.fossgis.de/datenschutzerklärung">Datenschutzerklärung</a>
		</li>
	</ul>
</footer>

</body>

</html>