<!doctype html>
<html lang="de">

<head>
	<?php include "../inc/meta.inc"; ?>

	<base href="<?php echo dirname($_SERVER['SCRIPT_NAME']); ?>">
	<title>Neues vom GeoStyler – FOSSGIS 2020</title>

	<link rel="stylesheet" href="./css/normalize.css">
	<link rel="stylesheet" href="./css/base.css">
	<link rel="stylesheet" href="./css/print.css" media="print">
</head>

<body id="programm">
	<?php include "../inc/header.inc"; ?>

        <!-- This file was generated by a script. Do not edit this file in Git,
             edit contents in Pretalx, regenerate the PHP files and commit them
             in the Git repository of the website. -->
        <p><a href="programm/donnerstag.php#session_M73SCJ">&#9668;&#9668; zurück zum Programm</a> </p>
        <h2 class='abstract-title'>Neues vom GeoStyler</h2>
        <section>
            <p>
                                <span class='abstract-speakers'>Christian Mayer, Jan Suleiman</span></p>
                            <p><span class='abstract-time-heading'>Zeit: </span>Donnerstag 12. März 17:00 Uhr<br><span class='abstract-room-heading'>Ort: </span>HS Rundbau</p>

                        <div class="video-container">
                <a href="https://media.ccc.de/v/fossgis2020-3027-neues-vom-geostyler">
                    <img class="video-preview" src="video_previews/3027-hd.jpg" alt="Vorschaubild des Videos">
                    <div class="video-preview-overlay"></div>
                </a>
            </div>
                        <p><a href="/2020/attachments/M73SCJ_geostyler-fossgis-2020_yq5MU3N.pdf">Vortragsfolien (PDF) </a></p>
            <p>GeoStyler ist eine Open Source JavaScript-Bibliothek zur einfachen Erstellung von modernen
Web-Oberflächen zum kartographischen Stylen von Geodaten. Somit wird es dem Anwender
möglich ohne Programmierung und Editieren von Text-Dateien (XML und co.) Styling-Vorschriften
interaktiv zu gestalten und diese in diverse offene Style-Formate zu überführen.
Dazu können auch die zu stylenden Geodaten hochgeladen und verknüpft werden, so dass attribut-basierte Styles auf einfache Art erstellt werden können.</p>
<p>Aktuell werden im GeoStyler folgende Formate unterstützt:</p>
<p><strong>Style-Vorschriften</strong></p>
<ul>
<li>OGC SLD</li>
<li>OpenLayers Styles</li>
<li>QGIS Styles</li>
<li>Mapbox Styles</li>
</ul>
<p><strong>Geodaten-Formate</strong></p>
<ul>
<li>GeoJSON</li>
<li>OGC WFS</li>
<li>Shapefile</li>
</ul>
<p>Auf der FOSSGIS 2019 wurde das GeoStyler Projekt bereits präsentiert. In diesem Jahr sollen die Neuerungen des letzten Jahres anhand aktueller Beispiele, in denen der GeoStyler zum Einsatz kommt, präsentiert werden. Dazu gehört die u. a. die GeoStyler GeoServer Extension, die es erlaubt die Stile der GeoServer Layer direkt im GeoServer mittels graphischer Oberfläche zu editieren. Außerdem wird es einen Überblick über zukünftige Entwicklungen im Projekt gegeben.</p>
<p>Quellcode auf github: https://github.com/geostyler/geostyler</p>
<p>Online-Dokumentation: https://geostyler.github.io/geostyler/latest/index.html</p>
<p>Demo: https://www.geostyler.org</p>
        <div class='abstract-bio'>
            <h3 class='abstract-bio-name'>Christian Mayer</h3>
            <ul>
<li>Dipl.-Ing. Geoinformatik &amp; Vermessung</li>
<li>Gründer <a href="https://meggsimum.de">meggsimum</a></li>
<li>Softwareentwickler &amp; -architekt</li>
<li>❤ Open Source (Geospatial)</li>
<li>OpenLayers, Wegue, GeoExt, Vue.js, GeoStyler, GeoServer, PostGIS...</li>
<li>Sprecher &amp; Trainer</li>
<li>national &amp; international</li>
<li>OSGeo Foundation Charter Member</li>
</ul>
        </div>
        <div class='abstract-bio'>
            <h3 class='abstract-bio-name'>Jan Suleiman</h3>
            <p>https://github.com/jansule</p>
        </div>
        </section>


	<?php include "../inc/footer.inc"; ?>

</body>

</html>