<!doctype html>
<html lang="de">

<head>
	<?php include "../inc/meta.inc"; ?>

	<base href="<?php echo dirname($_SERVER['SCRIPT_NAME']); ?>">
	<title>QGIS 3 Einsteiger Workshop – FOSSGIS 2020</title>

	<link rel="stylesheet" href="./css/normalize.css">
	<link rel="stylesheet" href="./css/base.css">
	<link rel="stylesheet" href="./css/print.css" media="print">
</head>

<body id="programm">
	<?php include "../inc/header.inc"; ?>

        <!-- This file was generated by a script. Do not edit this file in Git,
             edit contents in Pretalx, regenerate the PHP files and commit them
             in the Git repository of the website. -->
        <p><a href="programm/mittwoch.php#session_MB9ZLH">&#9668;&#9668; zurück zum Programm</a> </p>
        <h2 class='abstract-title'>QGIS 3 Einsteiger Workshop</h2>
        <section>
            <p>
                <span class='abstract-sessiontype'>Workshop</span> von                <span class='abstract-speakers'>Otto Dassau, Tristan</span></p>
                <p class='abstract-is-workshop'>Bitte melden Sie sich im <a href="https://pretix.eu/fossgis/2020/">Ticketshop</a> für diesen Workshop an, wenn Sie daran teilnehmen möchten.</p>            <p><span class='abstract-time-heading'>Zeit: </span>Mittwoch 11. März 17:00 Uhr<br><span class='abstract-room-heading'>Ort: </span>SR R-100</p>

            
            <p>Zum Zeitpunkt der Konferenz ist QGIS 3.10 der zweite Long Term Stable (LTS) Release und QGIS 3.12. die gerade veröffentlichte, aktuelle QGIS Version. Für Interessierte, die QGIS noch nicht kennen, vermitteln wir anhand eines einfachen Workflows einen Überblick, wie man ein QGIS-Projekt aufbaut, Daten analysiert und editiert und am Ende eine ansprechende Karte erzeugt.</p>
<ul>
<li>Überblick zu QGIS Funktionalität und GUI</li>
<li>Aufbau eines Projektes</li>
<li>Umgang mit dem Thema Projektionen</li>
<li>Visualisieren und Analysieren von Vektor- und Rasterdaten</li>
<li>Attributmanagement und Digitalisierfunktionen</li>
<li>Integration von Kern- und externen Plugins</li>
<li>Layouten einer einfachen druckfertigen Karte</li>
</ul>
        </section>


	<?php include "../inc/footer.inc"; ?>

</body>

</html>