<!doctype html>
<html lang="de">

<head>
	<meta charset="utf-8">
<meta http-equiv="x-ua-compatible" content="ie=edge">
<meta name="description" content="Die FOSSGIS-Konferenz ist im D-A-CH Raum die führende Konferenz für Freie und Open Source Software für Geoinformationssysteme OpenStreetMap.">
<meta name="keywords" content="FOSSGIS, FOSSGIS-Konferenz, 2019, FOSSGIS-Konferenz 2019, Open Source, GIS, Konferenz, Geoinformatik, OpenStreetMap, HTW Dresden">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="apple-itunes-app" content="app-id=1453299630">

	<base href="/2020/sessions">
	<title>QGIS 3 Einsteiger Workshop – FOSSGIS 2020</title>

	<link rel="stylesheet" href="./css/normalize.css">
	<link rel="stylesheet" href="./css/base.css">
	<link rel="stylesheet" href="./css/print.css" media="print">
</head>

<body id="programm">
	<header class="page-header">
	<a href="./" alt="FOSSGIS Konferenz 2020">
		<img class="page-logo" src="./img/fossgis2020-bollenhut.png">
	</a>
	<h1 class="page-title">
		FOSSGIS-Konferenz 2020<br>
		<span class="amp">Freiburg</span> <br>
		<span class="amp">11.&ndash;14. März</span>
	</h1>
</header>

<nav>
	<ul class="main">
		<li id="navHome">
			<a href="./">Startseite</a>
		</li>
		<!--<li id="navAnmeldung">
			<a href="./anmeldung/">Anmeldung</a>
		</li>-->
		<li id="navProgramm">
		<a href="./programm/">Programm</a>
		</li>
		<!--<li id="navAnreise">
			<a href="./anreise/">Anreise</a>
		</li>-->
		<li id="navStandort">
			<a href="./standort/">Standort</a>
		</li>
		<li id="navEvents">
			<a href="./socialevents/">Social Events</a>
		</li>
		<li id="navTeam">
			<a href="./loc/loc.php">Team</a>
		</li>
	</ul>
</nav>

<div class="hero">
	<figure>
		<img class="img-fluid" src="./img/freiburg.jpg" alt="Freiburg Luftbild">
		<figcaption>Photo: Pixaby</figcaption>
	</figure>
</div>

        <!-- This file was generated by a script. Do not edit this file in Git,
             edit contents in Pretalx, regenerate the PHP files and commit them
             in the Git repository of the website. -->
        <p><a href="programm/mittwoch.php#session_MB9ZLH">&#9668;&#9668; zurück zum Programm</a> </p>
        <h2 class='abstract-title'>QGIS 3 Einsteiger Workshop</h2>
        <section>
            <p>
                <span class='abstract-sessiontype'>Workshop</span> von                <span class='abstract-speakers'>Otto Dassau, Tristan</span></p>
                            <p><span class='abstract-time-heading'>Zeit: </span>Mittwoch 11. März 17:00 Uhr<br><span class='abstract-room-heading'>Ort: </span>SR R-100</p>

                        
            <p>Zum Zeitpunkt der Konferenz ist QGIS 3.10 der zweite Long Term Stable (LTS) Release und QGIS 3.12. die gerade veröffentlichte, aktuelle QGIS Version. Für Interessierte, die QGIS noch nicht kennen, vermitteln wir anhand eines einfachen Workflows einen Überblick, wie man ein QGIS-Projekt aufbaut, Daten analysiert und editiert und am Ende eine ansprechende Karte erzeugt.</p>
<ul>
<li>Überblick zu QGIS Funktionalität und GUI</li>
<li>Aufbau eines Projektes</li>
<li>Umgang mit dem Thema Projektionen</li>
<li>Visualisieren und Analysieren von Vektor- und Rasterdaten</li>
<li>Attributmanagement und Digitalisierfunktionen</li>
<li>Integration von Kern- und externen Plugins</li>
<li>Layouten einer einfachen druckfertigen Karte</li>
</ul>
        <div class='abstract-bio'>
            <h3 class='abstract-bio-name'>Otto Dassau</h3>
            <p>Otto Dassau ist Geschäftsführer der Geoinformatikbüro Dassau GmbH aus Düsseldorf. Das Unternehmen ist spezialisiert auf Open Source basierte Lösungen zum Thema WebGIS, GIS und GDI und engagiert sich auf verschiedenen Ebenen intensiv für deren Weiterentwicklung. Seit 2001 ist er Mitglied im FOSSGIS e.V., er ist Gründungsmitglied der QGIS Anwendergruppe Deutschland e.V. und war zwischen 2007 und 2016 Mitglied des QGIS Project Steering Committees.</p>
        </div>
        </section>


	<footer>
	<ul class="main">
		<li>
			<a href="https://www.fossgis.de/impressum/">Impressum</a>
		</li>
		<li>
			<a href="./agb.php">AGB</a>
		</li>
		<li>
			<a href="https://www.fossgis.de/datenschutzerklärung">Datenschutzerklärung</a>
		</li>
	</ul>
</footer>

</body>

</html>