<!doctype html>
<html lang="de">

<head>
	<meta charset="utf-8">
<meta http-equiv="x-ua-compatible" content="ie=edge">
<meta name="description" content="Die FOSSGIS-Konferenz ist im D-A-CH Raum die führende Konferenz für Freie und Open Source Software für Geoinformationssysteme OpenStreetMap.">
<meta name="keywords" content="FOSSGIS, FOSSGIS-Konferenz, 2019, FOSSGIS-Konferenz 2019, Open Source, GIS, Konferenz, Geoinformatik, OpenStreetMap, HTW Dresden">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="apple-itunes-app" content="app-id=1453299630">

	<base href="/2020/sessions">
	<title>WPS für kommunale GDIs - Eine Fallstudie über den Mehrwert von Web Processing Services (WPS) am Beispiel der Geodateninfrastruktur Freiburg (GDI-FR) – FOSSGIS 2020</title>

	<link rel="stylesheet" href="./css/normalize.css">
	<link rel="stylesheet" href="./css/base.css">
	<link rel="stylesheet" href="./css/print.css" media="print">
</head>

<body id="programm">
	<header class="page-header">
	<a href="./" alt="FOSSGIS Konferenz 2020">
		<img class="page-logo" src="./img/fossgis2020-bollenhut.png">
	</a>
	<h1 class="page-title">
		FOSSGIS-Konferenz 2020<br>
		<span class="amp">Freiburg</span> <br>
		<span class="amp">11.&ndash;14. März</span>
	</h1>
</header>

<nav>
	<ul class="main">
		<li id="navHome">
			<a href="./">Startseite</a>
		</li>
		<!--<li id="navAnmeldung">
			<a href="./anmeldung/">Anmeldung</a>
		</li>-->
		<li id="navProgramm">
		<a href="./programm/">Programm</a>
		</li>
		<!--<li id="navAnreise">
			<a href="./anreise/">Anreise</a>
		</li>-->
		<li id="navStandort">
			<a href="./standort/">Standort</a>
		</li>
		<li id="navEvents">
			<a href="./socialevents/">Social Events</a>
		</li>
		<li id="navTeam">
			<a href="./loc/loc.php">Team</a>
		</li>
	</ul>
</nav>

<div class="hero">
	<figure>
		<img class="img-fluid" src="./img/freiburg.jpg" alt="Freiburg Luftbild">
		<figcaption>Photo: Pixaby</figcaption>
	</figure>
</div>

        <!-- This file was generated by a script. Do not edit this file in Git,
             edit contents in Pretalx, regenerate the PHP files and commit them
             in the Git repository of the website. -->
        <p><a href="programm/freitag.php#session_MF7FZD">&#9668;&#9668; zurück zum Programm</a> </p>
        <h2 class='abstract-title'>WPS für kommunale GDIs - Eine Fallstudie über den Mehrwert von Web Processing Services (WPS) am Beispiel der Geodateninfrastruktur Freiburg (GDI-FR)</h2>
        <section>
            <p>
                                <span class='abstract-speakers'>Gunnar Ströer</span></p>
                            <p><span class='abstract-time-heading'>Zeit: </span>Freitag 13. März 12:00 Uhr<br><span class='abstract-room-heading'>Ort: </span>HS Rundbau</p>

                        <div class="video-container">
                <a href="https://media.ccc.de/v/fossgis2020-3000-wps-fr-kommunale-gdis-eine-fallstudie-ber-den-mehrwert-von-web-processing-services-wps-am-beispiel-der-geodateninfrastruktur-freiburg-gdi-fr-">
                    <img class="video-preview" src="video_previews/3000-hd.jpg" alt="Vorschaubild des Videos">
                    <div class="video-preview-overlay"></div>
                </a>
            </div>
                        <p><a href="/2020/attachments/MF7FZD_Praesentation_Stroeer_200312_RkIIcJ2.pdf">Vortragsfolien (PDF) </a></p>
            <p>Der Aufbau kommunaler Geodateninfrastrukturen (GDI) wurde in den letzten Jahren, nicht zuletzt aufgrund der Betroffenheit durch die INSPIRE-Richtlinie, vorangetrieben. Dabei hat sich der Ansatz einer dienstorientierten Architektur (SOA) auf Basis der offenen Standards des OGC bewährt. Gleichzeitig weckt die zunehmende Digitalisierung kommunaler Verwaltungen den Bedarf an der Automatisierung auch komplexer und in verschiedenste Fachdisziplinen hineinreichende Prozessabläufe.</p>
<p>Der 2007 durch das OGC verabschiedete Web Processing Service (WPS) Standard kann für die Implementierung von Prozessen herangezogen werden, und hat das Potenzial kommunale, im Sinne der Digitalisierung anzupassende Prozessabläufe mit einer GDI zu verbinden, und bisher nicht erreichbare fachfremde Verfahren an den Vorteilen einer GDI teilhaben zu lassen. Ob die tatsächliche Implementierung und Nutzung von Prozessen auf Basis von WPS für eine kommunale GDI geeignet ist und Vorteile hat wurde im Rahmen einer Studie anhand eines komplexen und real existierenden Anwendungsfalls untersucht.</p>
<p>Das Szenario des Anwendungsfalls umfasst die Evakuierungsplanung bei der Kampfmittelbeseitigung. Dabei spielt eine am Fraunhofer Ernst-Mach-Institut entwickelte externe Komponente zur Explosionssimulation und Druckwellenausbreitung eine besondere Rolle, mit der ein Evakuierungsradius kleiner als bisher gezogen werden kann. Insgesamt wurden bei der Realisierung acht verschiedene WPS-Prozesse implementiert und miteinander verkettet. Die Untersuchung hinsichtlich der Eignung von WPS in einer kommunalen GDI wurde zum einen an der tatsächlichen Umsetzung gemessen, und zum anderen an drei allgemeinen Kriterien festgemacht: Wiederverwendbarkeit, Kompatibilität und Benutzerfreundlichkeit.</p>
        <div class='abstract-bio'>
            <h3 class='abstract-bio-name'>Gunnar Ströer</h3>
            <p>Nach seinem Studium des Vermessungswesen in Dresden und einem Ausflug auf dem Gebiet der Archäoastronomie hat es Gunnar Ströer in die Schwarzwaldmetropole Freiburg im Breisgau verschlagen. Dort leitet er den Aufbau und Betrieb der kommunalen Geodateninfrastruktur, bei der überwiegend Open Source/OSGeo Komponenten zum Einsatz kommen.</p>
<p>Mail: gunnar.stroeer@posteo.de</p>
        </div>
        </section>


	<footer>
	<ul class="main">
		<li>
			<a href="https://www.fossgis.de/impressum/">Impressum</a>
		</li>
		<li>
			<a href="./agb.php">AGB</a>
		</li>
		<li>
			<a href="https://www.fossgis.de/datenschutzerklärung">Datenschutzerklärung</a>
		</li>
	</ul>
</footer>

</body>

</html>