<!doctype html>
<html lang="de">

<head>
	<meta charset="utf-8">
<meta http-equiv="x-ua-compatible" content="ie=edge">
<meta name="description" content="Die FOSSGIS-Konferenz ist im D-A-CH Raum die führende Konferenz für Freie und Open Source Software für Geoinformationssysteme OpenStreetMap.">
<meta name="keywords" content="FOSSGIS, FOSSGIS-Konferenz, 2019, FOSSGIS-Konferenz 2019, Open Source, GIS, Konferenz, Geoinformatik, OpenStreetMap, HTW Dresden">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="apple-itunes-app" content="app-id=1453299630">

	<base href="/2020/sessions">
	<title>FOSS in der Cloud – FOSSGIS 2020</title>

	<link rel="stylesheet" href="./css/normalize.css">
	<link rel="stylesheet" href="./css/base.css">
	<link rel="stylesheet" href="./css/print.css" media="print">
</head>

<body id="programm">
	<header class="page-header">
	<a href="./" alt="FOSSGIS Konferenz 2020">
		<img class="page-logo" src="./img/fossgis2020-bollenhut.png">
	</a>
	<h1 class="page-title">
		FOSSGIS-Konferenz 2020<br>
		<span class="amp">Freiburg</span> <br>
		<span class="amp">11.&ndash;14. März</span>
	</h1>
</header>

<nav>
	<ul class="main">
		<li id="navHome">
			<a href="./">Startseite</a>
		</li>
		<!--<li id="navAnmeldung">
			<a href="./anmeldung/">Anmeldung</a>
		</li>-->
		<li id="navProgramm">
		<a href="./programm/">Programm</a>
		</li>
		<!--<li id="navAnreise">
			<a href="./anreise/">Anreise</a>
		</li>-->
		<li id="navStandort">
			<a href="./standort/">Standort</a>
		</li>
		<li id="navEvents">
			<a href="./socialevents/">Social Events</a>
		</li>
		<li id="navTeam">
			<a href="./loc/loc.php">Team</a>
		</li>
	</ul>
</nav>

<div class="hero">
	<figure>
		<img class="img-fluid" src="./img/freiburg.jpg" alt="Freiburg Luftbild">
		<figcaption>Photo: Pixaby</figcaption>
	</figure>
</div>

        <!-- This file was generated by a script. Do not edit this file in Git,
             edit contents in Pretalx, regenerate the PHP files and commit them
             in the Git repository of the website. -->
        <p><a href="programm/donnerstag.php#session_MNKHF8">&#9668;&#9668; zurück zum Programm</a> </p>
        <h2 class='abstract-title'>FOSS in der Cloud</h2>
        <section>
            <p>
                                <span class='abstract-speakers'>Daniel Koch, Carmen Tawalika</span></p>
                            <p><span class='abstract-time-heading'>Zeit: </span>Donnerstag 12. März 15:30 Uhr<br><span class='abstract-room-heading'>Ort: </span>HS Anatomie</p>

                        <div class="video-container">
                <a href="https://media.ccc.de/v/fossgis2020-3037-foss-in-der-cloud">
                    <img class="video-preview" src="video_previews/3037-hd.jpg" alt="Vorschaubild des Videos">
                    <div class="video-preview-overlay"></div>
                </a>
            </div>
                        
            <p>Mit den täglich wachsenden Geodatenpools, z.B. angereichert durch das Copernicus oder Landsat Programm, steigen die Anforderungen an Hard- und Software für die Geodatenprozessierung (nicht nur) im Bereich der Fernerkundung stetig an. Lokale Installationen können dabei die Datenmengen und Anforderungen an Echtzeit-Analysten kaum stemmen und sind daher in den letzten Jahren vermehrt durch verteilte Systeme in der Cloud abgelöst worden. Dieser Trend macht auch vor dem Bereich der FOSS keinen Halt und hat sich seither etabliert.
Dieser Vortrag soll einen Überblick über die Konzepte des Cloud Computings, der verfügbaren Tools und Voraussetzungen der serviceorientierten Architektur für eine erfolgreiche Skalierbarkeit geben. Anschließend wird anhand eines konkreten Beispiels basierend auf den Komponenten actinia, GRASS GIS, GeoServer und SHOGun demonstriert wie diese für einen reibungslosen Betrieb in der Cloud angepasst werden müssen. Abgerundet wird der Vortrag durch Erfahrungen und daraus abgeleiteten Empfehlungen, die während der Vorbereitung und zur Laufzeit der Architektur gesammelt wurden.</p>
        <div class='abstract-bio'>
            <h3 class='abstract-bio-name'>Carmen Tawalika</h3>
            <p>Geographin, Open Source-Anhängerin und Entwicklerin bei mundialis</p>
        </div>
        </section>


	<footer>
	<ul class="main">
		<li>
			<a href="https://www.fossgis.de/impressum/">Impressum</a>
		</li>
		<li>
			<a href="./agb.php">AGB</a>
		</li>
		<li>
			<a href="https://www.fossgis.de/datenschutzerklärung">Datenschutzerklärung</a>
		</li>
	</ul>
</footer>

</body>

</html>