<!doctype html>
<html lang="de">

<head>
	<?php include "../inc/meta.inc"; ?>

	<base href="<?php echo dirname($_SERVER['SCRIPT_NAME']); ?>">
	<title>Das OSGeo Datacube Community Project rasdaman – FOSSGIS 2020</title>

	<link rel="stylesheet" href="./css/normalize.css">
	<link rel="stylesheet" href="./css/base.css">
	<link rel="stylesheet" href="./css/print.css" media="print">
</head>

<body id="programm">
	<?php include "../inc/header.inc"; ?>

        <!-- This file was generated by a script. Do not edit this file in Git,
             edit contents in Pretalx, regenerate the PHP files and commit them
             in the Git repository of the website. -->
        <p><a href="programm/donnerstag.php#session_MWDS79">&#9668;&#9668; zurück zum Programm</a> </p>
        <h2 class='abstract-title'>Das OSGeo Datacube Community Project rasdaman</h2>
        <section>
            <p>
                <span class='abstract-sessiontype'>Demo-Session</span> von                <span class='abstract-speakers'>pebau</span></p>
                            <p><span class='abstract-time-heading'>Zeit: </span>Donnerstag 12. März 15:30 Uhr<br><span class='abstract-room-heading'>Ort: </span>HS Anatomie</p>

            
            <p>Datenwürfel ("datacubes") erlauben multi-dimensionale raum-zeitliche Rasterdaten einheitlich zu modellieren und über Web-Dienste anzubieten, insbesondere über die OGC Standards Web Coverage Service (WCS) und Web Coverage Processing Service (WCPS), welche beide z.B. in INSPIRE vorgesehen sind. Die rasdaman-Technologie ist das historisch erste Array-Datenbanksystem,  OGC WCS Referenzimplementierung, seit vielen Jahren auf OSGeo Live und seit 2019 auch OSGeo Community Project. 
Wir geben einen Überblick über die rasdaman-Anfragesprache (welche inzwischen Teil des ISO SQL Standards geworden ist), die Systemarchitektur, Anwendungen auf Basis von rasdaman sowie einen Kurzüberblick über den WCS/WCPS-Standard zur Extraktion und Prozessierung von multi-dimensionalen Rasterdaten. Öffentlich zugängliche Live-Demos unterstützen die Darstellung.</p>
        </section>


	<?php include "../inc/footer.inc"; ?>

</body>

</html>