<!doctype html>
<html lang="de">

<head>
	<meta charset="utf-8">
<meta http-equiv="x-ua-compatible" content="ie=edge">
<meta name="description" content="Die FOSSGIS-Konferenz ist im D-A-CH Raum die führende Konferenz für Freie und Open Source Software für Geoinformationssysteme OpenStreetMap.">
<meta name="keywords" content="FOSSGIS, FOSSGIS-Konferenz, 2019, FOSSGIS-Konferenz 2019, Open Source, GIS, Konferenz, Geoinformatik, OpenStreetMap, HTW Dresden">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="apple-itunes-app" content="app-id=1453299630">

	<base href="/2020/sessions">
	<title>Kartenherstellung zwischen Lizenzen, Daten, Programmcode und Darstellung – FOSSGIS 2020</title>

	<link rel="stylesheet" href="./css/normalize.css">
	<link rel="stylesheet" href="./css/base.css">
	<link rel="stylesheet" href="./css/print.css" media="print">
</head>

<body id="programm">
	<header class="page-header">
	<a href="./" alt="FOSSGIS Konferenz 2020">
		<img class="page-logo" src="./img/fossgis2020-bollenhut.png">
	</a>
	<h1 class="page-title">
		FOSSGIS-Konferenz 2020<br>
		<span class="amp">Freiburg</span> <br>
		<span class="amp">11.&ndash;14. März</span>
	</h1>
</header>

<nav>
	<ul class="main">
		<li id="navHome">
			<a href="./">Startseite</a>
		</li>
		<!--<li id="navAnmeldung">
			<a href="./anmeldung/">Anmeldung</a>
		</li>-->
		<li id="navProgramm">
		<a href="./programm/">Programm</a>
		</li>
		<!--<li id="navAnreise">
			<a href="./anreise/">Anreise</a>
		</li>-->
		<li id="navStandort">
			<a href="./standort/">Standort</a>
		</li>
		<li id="navEvents">
			<a href="./socialevents/">Social Events</a>
		</li>
		<li id="navTeam">
			<a href="./loc/loc.php">Team</a>
		</li>
	</ul>
</nav>

<div class="hero">
	<figure>
		<img class="img-fluid" src="./img/freiburg.jpg" alt="Freiburg Luftbild">
		<figcaption>Photo: Pixaby</figcaption>
	</figure>
</div>

        <!-- This file was generated by a script. Do not edit this file in Git,
             edit contents in Pretalx, regenerate the PHP files and commit them
             in the Git repository of the website. -->
        <p><a href="programm/mittwoch.php#session_MYTFXF">&#9668;&#9668; zurück zum Programm</a> </p>
        <h2 class='abstract-title'>Kartenherstellung zwischen Lizenzen, Daten, Programmcode und Darstellung</h2>
        <section>
            <p>
                                <span class='abstract-speakers'>Falk Zscheile</span></p>
                            <p><span class='abstract-time-heading'>Zeit: </span>Mittwoch 11. März 15:30 Uhr<br><span class='abstract-room-heading'>Ort: </span>HS Anatomie</p>

                        <div class="video-container">
                <a href="https://media.ccc.de/v/fossgis2020-3101-kartenherstellung-zwischen-lizenzen-daten-programmcode-und-darstellung">
                    <img class="video-preview" src="video_previews/3101-hd.jpg" alt="Vorschaubild des Videos">
                    <div class="video-preview-overlay"></div>
                </a>
            </div>
                        <p><a href="/2020/attachments/MYTFXF_2020_fossgis_vortrag_kartenerstellung_praesi_bI8zwZA.pdf">Vortragsfolien (PDF) </a></p>
            <p>In seiner Grundkonzeption geht das Urheberrecht davon aus, dass ein Werk auch eine stoffliche Einheit bildet. Das Gemälde befindet sich auf einer Leinwand, der Text auf einer Buchseite. Auf den ersten Blick ist dies auch in der digitalen Welt nicht anders. Text oder Grafik befinden sich in einer Datei, die dargestellt wird. Auf den zweiten Blick ist die Lage nicht mehr ganz so klar. Bei der Darstellung digitaler Inhalte ist immer auch Software beteiligt. Software genießt aber selbst ebenfalls Urheberrechtsschutz. Datenbanken mit geographischen Informationen und Darstellungeregeln für den Renderer können ebenfalls durchs Urheberrechtsgesetz geschützt sein. Wenn etwas durch das Urheberrechtsgesetz geschützt ist, dann ist eine Nutzung nur unter Berücksichtigung der jeweiligen Lizenz/Nutzungsbedingung möglich. Doch welche Lizenz setzt sich am Ende durch, wenn mehrere Copyleftlizenzen für Software, Daten und Rendererregeln bei der Kartenherstellung aufeinander treffen? Der Vortrag gibt Antworten auf diese Frage ...</p>
        </section>


	<footer>
	<ul class="main">
		<li>
			<a href="https://www.fossgis.de/impressum/">Impressum</a>
		</li>
		<li>
			<a href="./agb.php">AGB</a>
		</li>
		<li>
			<a href="https://www.fossgis.de/datenschutzerklärung">Datenschutzerklärung</a>
		</li>
	</ul>
</footer>

</body>

</html>