<!doctype html>
<html lang="de">

<head>
	<?php include "../inc/meta.inc"; ?>

	<base href="<?php echo dirname($_SERVER['SCRIPT_NAME']); ?>">
	<title>Schneller, besser, leichter - PostGIS 3 – FOSSGIS 2020</title>

	<link rel="stylesheet" href="./css/normalize.css">
	<link rel="stylesheet" href="./css/base.css">
	<link rel="stylesheet" href="./css/print.css" media="print">
</head>

<body id="programm">
	<?php include "../inc/header.inc"; ?>

        <!-- This file was generated by a script. Do not edit this file in Git,
             edit contents in Pretalx, regenerate the PHP files and commit them
             in the Git repository of the website. -->
        <p><a href="programm/donnerstag.php#session_NHUAP9">&#9668;&#9668; zurück zum Programm</a> </p>
        <h2 class='abstract-title'>Schneller, besser, leichter - PostGIS 3</h2>
        <section>
            <p>
                                <span class='abstract-speakers'>Felix Kunde</span></p>
                            <p><span class='abstract-time-heading'>Zeit: </span>Donnerstag 12. März 13:30 Uhr<br><span class='abstract-room-heading'>Ort: </span>HS Anatomie</p>

            
            <p>Seit Jahren gehört PostGIS zum Repertoire von Entwicklern und Firmen bei der Verwaltung und Analyse von Geodaten. Neuere Datenbanksysteme und Bibliotheken orientieren sich daher bei Funktionen (und ihrer Benennung) meist zuerst an der beliebten PostgreSQL-Erweiterung. 2018 kam neue Dynamik in das Projekt als weitere Kernentwickler dazu stießen, um zunächst vor allem die bestehende Code-Basis zu stabilisieren. Schnell war bei diesem Prozess eine Schwelle erreicht, die größerer Veränderungen bedurfte und damit den Sprung auf eine neue Hauptversion rechtfertigte. Die Release-Notes von PostGIS 3 beinhalten daher weniger große neue Funktionalitäten wie beim 2.0 Release, sondern unzählige Detailverbesserungen und Weichensteller für die Zukunft. Im Vortrag wird eine ausgewogene Schnittmenge aus beidem präsentiert und erklärt, warum das neue PostGIS unbedingt zusammen mit dem neuen PostgreSQL 12 verwendet werden sollte.</p>
        </section>


	<?php include "../inc/footer.inc"; ?>

</body>

</html>