<!doctype html>
<html lang="de">

<head>
	<meta charset="utf-8">
<meta http-equiv="x-ua-compatible" content="ie=edge">
<meta name="description" content="Die FOSSGIS-Konferenz ist im D-A-CH Raum die führende Konferenz für Freie und Open Source Software für Geoinformationssysteme OpenStreetMap.">
<meta name="keywords" content="FOSSGIS, FOSSGIS-Konferenz, 2019, FOSSGIS-Konferenz 2019, Open Source, GIS, Konferenz, Geoinformatik, OpenStreetMap, HTW Dresden">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="apple-itunes-app" content="app-id=1453299630">

	<base href="/2020/sessions">
	<title>Schneller, besser, leichter - PostGIS 3 – FOSSGIS 2020</title>

	<link rel="stylesheet" href="./css/normalize.css">
	<link rel="stylesheet" href="./css/base.css">
	<link rel="stylesheet" href="./css/print.css" media="print">
</head>

<body id="programm">
	<header class="page-header">
	<a href="./" alt="FOSSGIS Konferenz 2020">
		<img class="page-logo" src="./img/fossgis2020-bollenhut.png">
	</a>
	<h1 class="page-title">
		FOSSGIS-Konferenz 2020<br>
		<span class="amp">Freiburg</span> <br>
		<span class="amp">11.&ndash;14. März</span>
	</h1>
</header>

<nav>
	<ul class="main">
		<li id="navHome">
			<a href="./">Startseite</a>
		</li>
		<!--<li id="navAnmeldung">
			<a href="./anmeldung/">Anmeldung</a>
		</li>-->
		<li id="navProgramm">
		<a href="./programm/">Programm</a>
		</li>
		<!--<li id="navAnreise">
			<a href="./anreise/">Anreise</a>
		</li>-->
		<li id="navStandort">
			<a href="./standort/">Standort</a>
		</li>
		<li id="navEvents">
			<a href="./socialevents/">Social Events</a>
		</li>
		<li id="navTeam">
			<a href="./loc/loc.php">Team</a>
		</li>
	</ul>
</nav>

<div class="hero">
	<figure>
		<img class="img-fluid" src="./img/freiburg.jpg" alt="Freiburg Luftbild">
		<figcaption>Photo: Pixaby</figcaption>
	</figure>
</div>

        <!-- This file was generated by a script. Do not edit this file in Git,
             edit contents in Pretalx, regenerate the PHP files and commit them
             in the Git repository of the website. -->
        <p><a href="programm/donnerstag.php#session_NHUAP9">&#9668;&#9668; zurück zum Programm</a> </p>
        <h2 class='abstract-title'>Schneller, besser, leichter - PostGIS 3</h2>
        <section>
            <p>
                                <span class='abstract-speakers'>Felix Kunde, Marco Hugentobler</span></p>
                            <p><span class='abstract-time-heading'>Zeit: </span>Donnerstag 12. März 13:30 Uhr<br><span class='abstract-room-heading'>Ort: </span>HS Anatomie</p>

                        <div class="video-container">
                <a href="https://media.ccc.de/v/fossgis2020-3063-schneller-besser-leichter-postgis-3">
                    <img class="video-preview" src="video_previews/3063-hd.jpg" alt="Vorschaubild des Videos">
                    <div class="video-preview-overlay"></div>
                </a>
            </div>
                        <p><a href="/2020/attachments/NHUAP9_postgis-v3_2WUSed2.pdf">Vortragsfolien (PDF) </a></p>
            <p>Seit Jahren gehört PostGIS zum Repertoire von Entwicklern und Firmen bei der Verwaltung und Analyse von Geodaten. Neuere Datenbanksysteme und Bibliotheken orientieren sich daher bei Funktionen (und ihrer Benennung) meist zuerst an der beliebten PostgreSQL-Erweiterung. 2018 kam neue Dynamik in das Projekt als weitere Kernentwickler dazu stießen, um zunächst vor allem die bestehende Code-Basis zu stabilisieren. Schnell war bei diesem Prozess eine Schwelle erreicht, die größerer Veränderungen bedurfte und damit den Sprung auf eine neue Hauptversion rechtfertigte. Die Release-Notes von PostGIS 3 beinhalten daher weniger große neue Funktionalitäten wie beim 2.0 Release, sondern unzählige Detailverbesserungen und Weichensteller für die Zukunft. Im Vortrag wird eine ausgewogene Schnittmenge aus beidem präsentiert und erklärt, warum das neue PostGIS unbedingt zusammen mit dem neuen PostgreSQL 12 verwendet werden sollte.</p>
        </section>


	<footer>
	<ul class="main">
		<li>
			<a href="https://www.fossgis.de/impressum/">Impressum</a>
		</li>
		<li>
			<a href="./agb.php">AGB</a>
		</li>
		<li>
			<a href="https://www.fossgis.de/datenschutzerklärung">Datenschutzerklärung</a>
		</li>
	</ul>
</footer>

</body>

</html>