<!doctype html>
<html lang="de">

<head>
	<?php include "../inc/meta.inc"; ?>

	<base href="<?php echo dirname($_SERVER['SCRIPT_NAME']); ?>">
	<title>Mitgliederversammlung FOSSGIS e.V. – FOSSGIS 2020</title>

	<link rel="stylesheet" href="./css/normalize.css">
	<link rel="stylesheet" href="./css/base.css">
	<link rel="stylesheet" href="./css/print.css" media="print">
</head>

<body id="programm">
	<?php include "../inc/header.inc"; ?>

        <!-- This file was generated by a script. Do not edit this file in Git,
             edit contents in Pretalx, regenerate the PHP files and commit them
             in the Git repository of the website. -->
        <p><a href="programm/donnerstag.php#session_PH3E8X">&#9668;&#9668; zurück zum Programm</a> </p>
        <h2 class='abstract-title'>Mitgliederversammlung FOSSGIS e.V.</h2>
        <section>
            <p>
                <span class='abstract-sessiontype'>Diverses</span> von                <span class='abstract-speakers'>FOSSGIS Konferenz</span></p>
                            <p><span class='abstract-time-heading'>Zeit: </span>Donnerstag 12. März 18:00 Uhr<br><span class='abstract-room-heading'>Ort: </span>HS Weismannhaus</p>

            <p class='abstract-novideo'><img class="abstract-novideo-img" src="./img/novideo-dark.svg" height="25" alt="ohne Videoaufzeichnung"> Dieser Programmbeitrag wird nicht aufgezeichnet.</p>
                        
            <p>Alle Mitglieder sind herzlich eingeladen, teilzunehmen und sich zu beteiligen. Einige Themen stehen auf der Agenda. Wir laden ein zum Kennenlernen, zur Diskussion, Abstimmung &amp; Neuwahlen. Getränke werden gestellt und es wird für alle Pizza bestellt. Wir freuen uns über zahlreiches Erscheinen.</p>
        </section>


	<?php include "../inc/footer.inc"; ?>

</body>

</html>