<!doctype html>
<html lang="de">

<head>
	<?php include "../inc/meta.inc"; ?>

	<base href="<?php echo dirname($_SERVER['SCRIPT_NAME']); ?>">
	<title>Offene Smart Farming Produkte aus offenen Satellitendaten – FOSSGIS 2020</title>

	<link rel="stylesheet" href="./css/normalize.css">
	<link rel="stylesheet" href="./css/base.css">
	<link rel="stylesheet" href="./css/print.css" media="print">
</head>

<body id="programm">
	<?php include "../inc/header.inc"; ?>

        <!-- This file was generated by a script. Do not edit this file in Git,
             edit contents in Pretalx, regenerate the PHP files and commit them
             in the Git repository of the website. -->
        <p><a href="programm/donnerstag.php#session_PHJ8VG">&#9668;&#9668; zurück zum Programm</a> </p>
        <h2 class='abstract-title'>Offene Smart Farming Produkte aus offenen Satellitendaten</h2>
        <section>
            <p>
                                <span class='abstract-speakers'>Sven Bingert, Martin Weis, Christian Bauer</span></p>
                            <p><span class='abstract-time-heading'>Zeit: </span>Donnerstag 12. März 10:00 Uhr<br><span class='abstract-room-heading'>Ort: </span>HS Anatomie</p>

            
            <p>Das Projekt <a href="https://open-forecast.eu/">Open Forecast</a> entwickelt eine generische Infrastruktur zur Verarbeitung offener Daten auf High-Perfomance-Computing-Systemen (HPC). Diese Infrastruktur wird anhand zweier Anwendungsfälle aufgebaut. Der erste Anwendungsfall untersucht die Möglichkeit, eine Vorhersage zur Feinstaubbelastung im Großraum Stuttgart zu berechnen. Die offenen Daten des Citizen-Science Projekts "luftdaten.info" sollen dabei zur Evaluierung des Modells herangezogen werden. Das Feinstaubmodell selbst basiert auf einem 3D Klimamodell mit großskaligen Wetterdaten als Eingabewerten sowie einem Geländemodell als untere Randbedingung. Aktuell untersucht wird die Einbeziehung von weiteren Feinstaubquellen, die beispielsweise aus Verkehrsdaten gewonnen werden.</p>
<p>Der zweite Anwendungsfall leitet Produkte für die Landwirtschaft (Smart Farming) aus frei verfügbaren Satellitendaten ab. Hierzu werden multispektrale <a href="https://www.esa.int/Applications/Observing_the_Earth/Copernicus/Sentinel-2">Sentinel-2</a> Daten der <a href="https://www.esa.int/Applications/Observing_the_Earth/Copernicus">ESA Copernicus Mission</a> verwendet. Dazu wurden die angebotenen Satellitendaten vorverarbeitet (u. a. Atmospärenkorrektur) und Datenprodukte wie zum Beispiel spezifische Vegetationsindizes oder Mosaike erstellt. Diese dienen als Proxy für Aussagen über den Status der grünen Vegetation oder der Pflanzengesundheit. Des weiteren wird ein anueller Index gerechnet, der die Beurteilung der Landnutzung über mehrere Jahre hinweg erlaubt.</p>
<p>Die Ergebnisse aus dem Projekt sollen wieder als offene Datenproduke, OGC- und INSPIRE-konforme Geodatendienste konforme Schnittstellen verfügbar gemacht werden. Im Fokus steht die Nutzbarkeit der Produkte in GIS über Webservices. Wir präsentieren in unserem Beitrag den aktuellen Stand der Verarbeitungskette unter der Verwendung der Software sen2agri, die von der ESA zur Bearbeitung von Sentinel-2 Daten bereitgestellt wird.</p>
        </section>


	<?php include "../inc/footer.inc"; ?>

</body>

</html>