<!doctype html>
<html lang="de">

<head>
	<meta charset="utf-8">
<meta http-equiv="x-ua-compatible" content="ie=edge">
<meta name="description" content="Die FOSSGIS-Konferenz ist im D-A-CH Raum die führende Konferenz für Freie und Open Source Software für Geoinformationssysteme OpenStreetMap.">
<meta name="keywords" content="FOSSGIS, FOSSGIS-Konferenz, 2019, FOSSGIS-Konferenz 2019, Open Source, GIS, Konferenz, Geoinformatik, OpenStreetMap, HTW Dresden">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="apple-itunes-app" content="app-id=1453299630">

	<base href="/2020/sessions">
	<title>Mannheimer Mapathons: Integration fördern, humanitäre Hilfe leisten – FOSSGIS 2020</title>

	<link rel="stylesheet" href="./css/normalize.css">
	<link rel="stylesheet" href="./css/base.css">
	<link rel="stylesheet" href="./css/print.css" media="print">
</head>

<body id="programm">
	<header class="page-header">
	<a href="./" alt="FOSSGIS Konferenz 2020">
		<img class="page-logo" src="./img/fossgis2020-bollenhut.png">
	</a>
	<h1 class="page-title">
		FOSSGIS-Konferenz 2020<br>
		<span class="amp">Freiburg</span> <br>
		<span class="amp">11.&ndash;14. März</span>
	</h1>
</header>

<nav>
	<ul class="main">
		<li id="navHome">
			<a href="./">Startseite</a>
		</li>
		<!--<li id="navAnmeldung">
			<a href="./anmeldung/">Anmeldung</a>
		</li>-->
		<li id="navProgramm">
		<a href="./programm/">Programm</a>
		</li>
		<!--<li id="navAnreise">
			<a href="./anreise/">Anreise</a>
		</li>-->
		<li id="navStandort">
			<a href="./standort/">Standort</a>
		</li>
		<li id="navEvents">
			<a href="./socialevents/">Social Events</a>
		</li>
		<li id="navTeam">
			<a href="./loc/loc.php">Team</a>
		</li>
	</ul>
</nav>

<div class="hero">
	<figure>
		<img class="img-fluid" src="./img/freiburg.jpg" alt="Freiburg Luftbild">
		<figcaption>Photo: Pixaby</figcaption>
	</figure>
</div>

        <!-- This file was generated by a script. Do not edit this file in Git,
             edit contents in Pretalx, regenerate the PHP files and commit them
             in the Git repository of the website. -->
        <p><a href="programm/freitag.php#session_PWE3PX">&#9668;&#9668; zurück zum Programm</a> </p>
        <h2 class='abstract-title'>Mannheimer Mapathons: Integration fördern, humanitäre Hilfe leisten</h2>
        <section>
            <p>
                                <span class='abstract-speakers'>Robert Danziger</span></p>
                            <p><span class='abstract-time-heading'>Zeit: </span>Freitag 13. März 11:00 Uhr<br><span class='abstract-room-heading'>Ort: </span>HS Weismannhaus</p>

                        <div class="video-container">
                <a href="https://media.ccc.de/v/fossgis2020-2975-mannheimer-mapathons-integration-frdern-humanitre-hilfe-leisten">
                    <img class="video-preview" src="video_previews/2975-hd.jpg" alt="Vorschaubild des Videos">
                    <div class="video-preview-overlay"></div>
                </a>
            </div>
                        <p><a href="/2020/attachments/PWE3PX_FOSSGIS20_Danzinger_20min_kKcvTO1.pdf">Vortragsfolien (PDF) </a></p>
            <p>Mit dem Ziel weitere Projekte dieser Art in Deutschland -- oder anderswo -- anzuregen,  wird die Präsentation vor allem beschreiben, was überhaupt gemacht wird, wie alles organisiert ist und wie die Teilnehmenden es beurteilen. Bis Ende 2019 wurden 20 Mapathons veranstaltet. U.a. hat dieser Erfolg dazu geführt, dass CartONG ein sehr ähnliches Projekt 2018-2019 in Frankreich durchführte. Momentan wird über einen Antrag zur Erweiterung der Projektidee auf europäischer Ebene diskutiert.</p>
        <div class='abstract-bio'>
            <h3 class='abstract-bio-name'>Robert Danziger</h3>
            <p>Nach seiner Ankunft 1976 in Mannheim arbeitete er von 1978 bis 1982 als Juniorprofessor für Sozialwissenschaften an der Universität Mannheim. In 1980 promovierte er (Politikwissenschaft) an der State Univ. of New York at Buffalo. Er nahm 1982 eine Stelle im IT-Service des Europäischen Hochschulinstituts in Florenz (einer Einrichtung der EU und der Mitgliedstaaten) an. Seit 2013 in Mannheim im Ruhestand, studiert er mehrere Jahre Kartographie- und Geoinformatik an der Universität Heidelberg.
2016 begann er eine ehrenamtliche Zusammenarbeit mit der französischen NGO CartONG (in Chambéry) und ist derzeit im Vorstand tätig.
Weitere aktive Engagements: als Folge einer Westafrikareise 2006, initiierte er ein Bildungsprojekt in Larabanga, Ghana. Das Projekt hat sich weiterentwickelt und seit 2017 arbeitet er daran, ein lokales Kollektiv in Kartierungskompetenzen auszubilden, die für die Entwicklung des Tourismus in der Gegend unerlässlich sind.</p>
        </div>
        </section>


	<footer>
	<ul class="main">
		<li>
			<a href="https://www.fossgis.de/impressum/">Impressum</a>
		</li>
		<li>
			<a href="./agb.php">AGB</a>
		</li>
		<li>
			<a href="https://www.fossgis.de/datenschutzerklärung">Datenschutzerklärung</a>
		</li>
	</ul>
</footer>

</body>

</html>