<!doctype html>
<html lang="de">

<head>
	<?php include "../inc/meta.inc"; ?>

	<base href="<?php echo dirname($_SERVER['SCRIPT_NAME']); ?>">
	<title>Grafische Prozessmodellierung mit QGIS – FOSSGIS 2020</title>

	<link rel="stylesheet" href="./css/normalize.css">
	<link rel="stylesheet" href="./css/base.css">
	<link rel="stylesheet" href="./css/print.css" media="print">
</head>

<body id="programm">
	<?php include "../inc/header.inc"; ?>

        <!-- This file was generated by a script. Do not edit this file in Git,
             edit contents in Pretalx, regenerate the PHP files and commit them
             in the Git repository of the website. -->
        <p><a href="programm/mittwoch.php#session_RERSW7">&#9668;&#9668; zurück zum Programm</a> </p>
        <h2 class='abstract-title'>Grafische Prozessmodellierung mit QGIS</h2>
        <section>
            <p>
                <span class='abstract-sessiontype'>Workshop</span> von                <span class='abstract-speakers'>Claas Leiner</span></p>
                <p class='abstract-is-workshop'>Bitte melden Sie sich im <a href="https://pretix.eu/fossgis/2020/">Ticketshop</a> für diesen Workshop an, wenn Sie daran teilnehmen möchten.</p>            <p><span class='abstract-time-heading'>Zeit: </span>Mittwoch 11. März 15:00 Uhr<br><span class='abstract-room-heading'>Ort: </span>SR R-100</p>

            
            <p>QGIS bietet über die Werkzeugkiste eine mächtige und umfangreiche Umgebung zur Geodatenverarbeitung, die auch Werkzeuge aus GRASS, GDAL/OGR sowie Saga einbindet und den Pendants aus der proprietärer Software-Welt in nichts nachsteht. Mit der grafischen Prozessmodellierung steht ein Werkzeug zur Automatisierung von Abläufen zur Verfügung, welches zugleich eine hervorragende Hilfe bei der Dokumentation und Prüfung wiederkehrender Abläufe in der Geodatenverarbeitung ist. Auch lassen sich Funktionen bauen, die es direkt in QGIS nicht gibt.
Im Workshop lernen die Teilnehmer/innen einen Geodatenverarbeitungsprozess mit Abfragen, Berechnungen, Überlagerungswerkzeugen, Dissolve etc. unter Nutzung der grafischen Prozessmodellierung zu entwerfen und zu testen. Es wird das gleiche inhaltliche Beispiel verwendet, wie beim Workshop Geodatenverarbeitung mit SQL, so dass sich interessante Vergleichsmöglichkeiten ergeben.</p>
        <div class='abstract-bio'>
            <h3 class='abstract-bio-name'>Claas Leiner</h3>
            <p>Claas Leiner arbeitet miit seinem Büro GKG freiberuflich in Kassel und
bietet Schulungen, Dienstleistungen und Support rund um die freien Geoinformationssysteme QGIS, GRASS, SpatiaLite, Postgis sowie GDAL/OGR an. Desweiteren bearbeitet er Aufträge zu Geodatenaufbereitung, -analysen und thematische Kartografie.
Besonders verbunden ist er mit QGIS - als Mitglied des QGIS-Anwendervereins QGIS-DE, als Mitorganisator der QGIS-Anwendertreffen 2011 - 2018 sowie als Bronze-Sponsor des Projektes.</p>
        </div>
        </section>


	<?php include "../inc/footer.inc"; ?>

</body>

</html>