<!doctype html>
<html lang="de">

<head>
	<meta charset="utf-8">
<meta http-equiv="x-ua-compatible" content="ie=edge">
<meta name="description" content="Die FOSSGIS-Konferenz ist im D-A-CH Raum die führende Konferenz für Freie und Open Source Software für Geoinformationssysteme OpenStreetMap.">
<meta name="keywords" content="FOSSGIS, FOSSGIS-Konferenz, 2019, FOSSGIS-Konferenz 2019, Open Source, GIS, Konferenz, Geoinformatik, OpenStreetMap, HTW Dresden">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="apple-itunes-app" content="app-id=1453299630">

	<base href="/2020/sessions">
	<title>Umgang mit vorhandenen und fehlenden Relevanzinformationen in OpenStreetMap-Kartenstilen – FOSSGIS 2020</title>

	<link rel="stylesheet" href="./css/normalize.css">
	<link rel="stylesheet" href="./css/base.css">
	<link rel="stylesheet" href="./css/print.css" media="print">
</head>

<body id="programm">
	<header class="page-header">
	<a href="./" alt="FOSSGIS Konferenz 2020">
		<img class="page-logo" src="./img/fossgis2020-bollenhut.png">
	</a>
	<h1 class="page-title">
		FOSSGIS-Konferenz 2020<br>
		<span class="amp">Freiburg</span> <br>
		<span class="amp">11.&ndash;14. März</span>
	</h1>
</header>

<nav>
	<ul class="main">
		<li id="navHome">
			<a href="./">Startseite</a>
		</li>
		<!--<li id="navAnmeldung">
			<a href="./anmeldung/">Anmeldung</a>
		</li>-->
		<li id="navProgramm">
		<a href="./programm/">Programm</a>
		</li>
		<!--<li id="navAnreise">
			<a href="./anreise/">Anreise</a>
		</li>-->
		<li id="navStandort">
			<a href="./standort/">Standort</a>
		</li>
		<li id="navEvents">
			<a href="./socialevents/">Social Events</a>
		</li>
		<li id="navTeam">
			<a href="./loc/loc.php">Team</a>
		</li>
	</ul>
</nav>

<div class="hero">
	<figure>
		<img class="img-fluid" src="./img/freiburg.jpg" alt="Freiburg Luftbild">
		<figcaption>Photo: Pixaby</figcaption>
	</figure>
</div>

        <!-- This file was generated by a script. Do not edit this file in Git,
             edit contents in Pretalx, regenerate the PHP files and commit them
             in the Git repository of the website. -->
        <p><a href="programm/mittwoch.php#session_S8HCFT">&#9668;&#9668; zurück zum Programm</a> </p>
        <h2 class='abstract-title'>Umgang mit vorhandenen und fehlenden Relevanzinformationen in OpenStreetMap-Kartenstilen</h2>
        <section>
            <p>
                                <span class='abstract-speakers'>Michael Reichert</span></p>
                            <p><span class='abstract-time-heading'>Zeit: </span>Mittwoch 11. März 15:30 Uhr<br><span class='abstract-room-heading'>Ort: </span>HS Weismannhaus</p>

                        <div class="video-container">
                <a href="https://media.ccc.de/v/fossgis2020-3125-umgang-mit-vorhandenen-und-fehlenden-relevanzinformationen-in-openstreetmap-kartenstilen">
                    <img class="video-preview" src="video_previews/3125-hd.jpg" alt="Vorschaubild des Videos">
                    <div class="video-preview-overlay"></div>
                </a>
            </div>
                        <p><a href="/2020/attachments/S8HCFT_reichert_relevanzinformationen_KhbRCKu.pdf">Vortragsfolien (PDF) </a></p>
            <p>Bei bestimmten Featureklassen ist auch in der automatisierten Kartographie die Trennung von wichtigen und weniger wichtigen Features von Bedeutung, gerade dann, wenn in kleineren Maßstäben der Platz knapp wird oder die Karte nicht überfrachtet werden soll. Das gilt auch für Kartenstile, mit denen aus OpenStreetMap-Daten Karten gerendert werden. Dabei macht die Art und Weise, wie OpenStreetMap-Daten erfasst werden, es dem Kartographen manchmal nicht gerade leicht, nur die wichtigen Features einer Featureklasse darzustellen. Für manche Features existieren in OpenStreetMap Tag, die die Bedeutung entweder direkt angeben oder mithilfe derer die Bedeutung recht einfach ermittelt werden kann. Bei manchen ist die Auswertung der Relevanzinformationen einfach, bei manchen ist sie anspruchsvoll. Straßen und Siedlungen sind ein Beispiel für ersteres, wobei es selbst bei Siedlungen noch mehrer Möglichkeiten gibt, die Relevanz zu bestimmen. Bei Gipfeln ist die Bestimmung der Dominanz etwas aufwendiger.</p>
<p>Es gibt aber auch Objekte in OSM, bei denen keine Informationen direkt erfasst werden, die sich zur Ableitung einer Rangfolge eignen. Meist liegt es daran, dass solche Informationen nicht dem Überprüfbarkeitskriterium bei OSM genügen. In diese Kategorie fallen unter anderen Bahnhöfe und Flughäfen.</p>
<p>Im ersten Teil des Vortrags wird vorstellt, wie verschiedene Open-Source-Kartenstile für OSM-Daten vorhandenen Relevanzinformationen für Straßen, Siedlungen und Gipfel nutzen bzw. wie sie mit dem Fehlen oder der Nichtbenutzbarkeit dieser Informationen bei Bahnhöfe, Flughäfen und Flüssen umgehen. Auch die Folgen dieser Entscheidungen auf die Aktualisierbarkeit der Daten wird aufgezeigt.</p>
<p>Im zweiten Teil des Vortrags wird am Beispiel des OpenRailwayMap-Infrastrukturstils, der kürzlich auf CartoCSS portiert worden ist, gezeigt, wie für bei Haltestellen des öffenentlichen Personenverkehrs mit in OSM erfassten Routenrelationen bewertet werden.</p>
        </section>


	<footer>
	<ul class="main">
		<li>
			<a href="https://www.fossgis.de/impressum/">Impressum</a>
		</li>
		<li>
			<a href="./agb.php">AGB</a>
		</li>
		<li>
			<a href="https://www.fossgis.de/datenschutzerklärung">Datenschutzerklärung</a>
		</li>
	</ul>
</footer>

</body>

</html>