<!doctype html>
<html lang="de">

<head>
	<meta charset="utf-8">
<meta http-equiv="x-ua-compatible" content="ie=edge">
<meta name="description" content="Die FOSSGIS-Konferenz ist im D-A-CH Raum die führende Konferenz für Freie und Open Source Software für Geoinformationssysteme OpenStreetMap.">
<meta name="keywords" content="FOSSGIS, FOSSGIS-Konferenz, 2019, FOSSGIS-Konferenz 2019, Open Source, GIS, Konferenz, Geoinformatik, OpenStreetMap, HTW Dresden">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="apple-itunes-app" content="app-id=1453299630">

	<base href="/2020/sessions">
	<title>Gefahrenbewertung im Radverkehr mittels Crowdsourcing von Geoinformationen – FOSSGIS 2020</title>

	<link rel="stylesheet" href="./css/normalize.css">
	<link rel="stylesheet" href="./css/base.css">
	<link rel="stylesheet" href="./css/print.css" media="print">
</head>

<body id="programm">
	<header class="page-header">
	<a href="./" alt="FOSSGIS Konferenz 2020">
		<img class="page-logo" src="./img/fossgis2020-bollenhut.png">
	</a>
	<h1 class="page-title">
		FOSSGIS-Konferenz 2020<br>
		<span class="amp">Freiburg</span> <br>
		<span class="amp">11.&ndash;14. März</span>
	</h1>
</header>

<nav>
	<ul class="main">
		<li id="navHome">
			<a href="./">Startseite</a>
		</li>
		<!--<li id="navAnmeldung">
			<a href="./anmeldung/">Anmeldung</a>
		</li>-->
		<li id="navProgramm">
		<a href="./programm/">Programm</a>
		</li>
		<!--<li id="navAnreise">
			<a href="./anreise/">Anreise</a>
		</li>-->
		<li id="navStandort">
			<a href="./standort/">Standort</a>
		</li>
		<li id="navEvents">
			<a href="./socialevents/">Social Events</a>
		</li>
		<li id="navTeam">
			<a href="./loc/loc.php">Team</a>
		</li>
	</ul>
</nav>

<div class="hero">
	<figure>
		<img class="img-fluid" src="./img/freiburg.jpg" alt="Freiburg Luftbild">
		<figcaption>Photo: Pixaby</figcaption>
	</figure>
</div>

        <!-- This file was generated by a script. Do not edit this file in Git,
             edit contents in Pretalx, regenerate the PHP files and commit them
             in the Git repository of the website. -->
        <p><a href="programm/donnerstag.php#session_SBUNBG">&#9668;&#9668; zurück zum Programm</a> </p>
        <h2 class='abstract-title'>Gefahrenbewertung im Radverkehr mittels Crowdsourcing von Geoinformationen</h2>
        <section>
            <p>
                                <span class='abstract-speakers'>Rafael Hologa, Nils Riach</span></p>
                            <p><span class='abstract-time-heading'>Zeit: </span>Donnerstag 12. März 11:00 Uhr<br><span class='abstract-room-heading'>Ort: </span>HS Weismannhaus</p>

            <p class='abstract-novideo'><img class="abstract-novideo-img" src="./img/novideo-dark.svg" height="25" alt="ohne Videoaufzeichnung"> Dieser Programmbeitrag wird nicht aufgezeichnet.</p>
                        <p><a href="/2020/attachments/SBUNBG_hologa_riach_fossgis_public__sKwQaHz.pdf">Vortragsfolien (PDF) </a></p>
            <p>Das enorme Potential von Geodaten, die durch Laien erfasst werden, wird u.a. in vielen Citizen Science Projekten dokumentiert. Auch in dieser Arbeit wird durch das Crowdsourcing von Geoinformationen zu Gefahren im Radverkehr in Freiburg im Breisgau beleuchtet, ob solche geographischen Bürgerinformationen einen Mehrwert liefern und Geofachdaten sinnvoll ergänzen können.</p>
<p>In der vorgestellten Studie wurden von Radfahrern gemeldete Gefahren entlang von zufällig ausgewählten Routen im Stadtgebiet von Freiburg gesammelt. Für die Erhebung der Meldungen fand die Open-Source-Software KoBo Toolbox Anwendung, da sie eine systematische Erfassung und Aggregation von  Geodaten via Smartphone in Echtzeit ermöglicht. Bei der Kartierung stand die individuelle Gefahrenwahrnehmung von Radfahrern im Vordergrund.</p>
<p>Der auf diese Weise generierte Datenpool wurde hinsichtlich räumlicher Verteilungsmuster untersucht, um aufzuzeigen, wo spezifische Gefahren von der Gesellschaft wahrgenommen werden. Dabei sollte geklärt werden, ob Zusammenhänge zwischen gemeldeten Gefahren und städtischen Infrastrukturen festzustellen sind. Darüber hinaus wurden die individuellen Meldungen mit tatsächlichen Gefahren abgeglichen. Diese ließen sich aus Statistiken zu Unfallorten mit Beteiligung von Radfahrern ableiten.</p>
<p>Als Ergebnis kann gezeigt werden, dass die gemeinsame Analyse von Unfallstatistiken und Crowd generierten Meldungen vielversprechende Zugänge zur Identifikation von Gefahren-Hot-Spots im Stadtgebiet eröffnet. Somit verdeutlicht die Zusammenschau beider Informationspools, dass die crowdsourced Meldungen in Planungsprozessen zur Optimierung des Radverkehrs genutzt werden können.</p>
<p>Insgesamt zeigt sich, dass durch die räumliche Verschneidung von Geofachdaten und von Laien generierter Geoinformationen ein informativer Mehrwert entsteht. Somit ergänzen Informationen individueller Prägungen amtlich standardisierte Geoinformation um gesellschaftliche Raumwahrnehmungen.</p>
        </section>


	<footer>
	<ul class="main">
		<li>
			<a href="https://www.fossgis.de/impressum/">Impressum</a>
		</li>
		<li>
			<a href="./agb.php">AGB</a>
		</li>
		<li>
			<a href="https://www.fossgis.de/datenschutzerklärung">Datenschutzerklärung</a>
		</li>
	</ul>
</footer>

</body>

</html>