<!doctype html>
<html lang="de">

<head>
	<meta charset="utf-8">
<meta http-equiv="x-ua-compatible" content="ie=edge">
<meta name="description" content="Die FOSSGIS-Konferenz ist im D-A-CH Raum die führende Konferenz für Freie und Open Source Software für Geoinformationssysteme OpenStreetMap.">
<meta name="keywords" content="FOSSGIS, FOSSGIS-Konferenz, 2019, FOSSGIS-Konferenz 2019, Open Source, GIS, Konferenz, Geoinformatik, OpenStreetMap, HTW Dresden">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="apple-itunes-app" content="app-id=1453299630">

	<base href="/2020/sessions">
	<title>QGIS - A SPARQLing Unicorn? Eine Einführung in Linked Open Geodata zur Integration von RDF in QGIS Plugins – FOSSGIS 2020</title>

	<link rel="stylesheet" href="./css/normalize.css">
	<link rel="stylesheet" href="./css/base.css">
	<link rel="stylesheet" href="./css/print.css" media="print">
</head>

<body id="programm">
	<header class="page-header">
	<a href="./" alt="FOSSGIS Konferenz 2020">
		<img class="page-logo" src="./img/fossgis2020-bollenhut.png">
	</a>
	<h1 class="page-title">
		FOSSGIS-Konferenz 2020<br>
		<span class="amp">Freiburg</span> <br>
		<span class="amp">11.&ndash;14. März</span>
	</h1>
</header>

<nav>
	<ul class="main">
		<li id="navHome">
			<a href="./">Startseite</a>
		</li>
		<!--<li id="navAnmeldung">
			<a href="./anmeldung/">Anmeldung</a>
		</li>-->
		<li id="navProgramm">
		<a href="./programm/">Programm</a>
		</li>
		<!--<li id="navAnreise">
			<a href="./anreise/">Anreise</a>
		</li>-->
		<li id="navStandort">
			<a href="./standort/">Standort</a>
		</li>
		<li id="navEvents">
			<a href="./socialevents/">Social Events</a>
		</li>
		<li id="navTeam">
			<a href="./loc/loc.php">Team</a>
		</li>
	</ul>
</nav>

<div class="hero">
	<figure>
		<img class="img-fluid" src="./img/freiburg.jpg" alt="Freiburg Luftbild">
		<figcaption>Photo: Pixaby</figcaption>
	</figure>
</div>

        <!-- This file was generated by a script. Do not edit this file in Git,
             edit contents in Pretalx, regenerate the PHP files and commit them
             in the Git repository of the website. -->
        <p><a href="programm/donnerstag.php#session_SQDQHJ">&#9668;&#9668; zurück zum Programm</a> <a href="sessions/lightning_talks_2.php">&#9668; zurück zur Session</a></p>
        <h2 class='abstract-title'>QGIS - A SPARQLing Unicorn? Eine Einführung in Linked Open Geodata zur Integration von RDF in QGIS Plugins</h2>
        <section>
            <p>
                <span class='abstract-sessiontype'>Lightning Talk</span> von                <span class='abstract-speakers'>Florian Thiery, Timo Homburg</span></p>
                            <p><span class='abstract-time-heading'>Zeit: </span>Donnerstag 12. März 12:10 Uhr<br><span class='abstract-room-heading'>Ort: </span>HS Weismannhaus</p>

                        <div class="video-container">
                <a href="https://media.ccc.de/v/fossgis2020-2990-qgis-a-sparqling-unicorn-eine-einfhrung-in-linked-open-geodata-zur-integration-von-rdf-in-qgis-plugins">
                    <img class="video-preview" src="video_previews/2990-hd.jpg" alt="Vorschaubild des Videos">
                    <div class="video-preview-overlay"></div>
                </a>
            </div>
                        <p><a href="/2020/attachments/SQDQHJ_2020_03_12_FOSSGIS2020_SPARQLunicorn_Wr8HDSZ.pdf">Vortragsfolien (PDF) </a></p>
            <p>Die Linked Open Data Cloud bietet seit vielen Jahren große Datenrepositorien im WWW an, die für verschiedene Zwecke von unterschiedlichen Communities genutzt werden können. Die Stärke von Linked Open Data (LOD) ist hierbei die Verknüpfung von Informationen aus unterschiedlichsten dezentral gehosteten Wissensdomänen. Für die Geoinformatik haben sich beispielsweise community-basierende Datenrepositorien wie <a href="http://wikidata.org">Wikidata</a>, <a href="http://linkedgeodata.org">LinkedGeoData</a> oder <a href="https://wiki.dbpedia.org">DBpedia</a> gebildet. Zudem bieten Gazetteer-Repositorien wie <a href="https://www.geonames.org">Geonames</a> oder <a href="https://pleiades.stoa.org">Pleiades</a> für den zeitgeschichtlichen Raum, aber auch administrative Provider wie der <a href="https://data.ordnancesurvey.co.uk">Ordnance Survey UK</a> und <a href="http://data.geohive.ie">Ordnance Survey Ireland</a>, ihre Geodaten als LOD an. Leider haben all diese Ressourcen in der Geo-Community bisher leider nur niederrangige Bedeutung erlangt. Den Grund dafür sehen wir in einem nicht vorhandenen Support von GIS Applikationen für die Verarbeitung von LOD. <em>Triplestores</em> und <em>SPARQL</em> werden zur Zeit weder von <em>GIS</em> Software, <em>GeoServer</em> Implementierungen oder <em>OGC</em>-Services unterstützt. Die Linked Data Serialisierung <a href="https://geojson.org/geojson-ld/">GeoJSON-LD</a> birgt zwar aufgrund einiger noch offener Issues Herausforderungen, wird allerdings nicht oft wie seine ‘unsemantische Schwester’ <em>GeoJSON</em>, in Applikationen genutzt. Genau hier setzt das <a href="https://plugins.qgis.org/plugins/sparqlunicorn">SPARQLing Unicorn QGIS Plugin</a> an, welches die Ausführung von Linked Data Anfragen in (Geo)SPARQL an ausgewählte Triplestores und geofähigen SPARQL Endpoints ermöglicht. Die Ergebnisse werden in GeoJSON Layer konvertiert, sodass sie direkt in QGIS nutzbar sind. Für die Zukunft soll das <em>SPARQLing Unicorn Plugin</em> mit extrahierten Konzepten ausgewählter Ontologien Benutzern die Möglichkeit bieten, einfache Abfragen wie “Gib mir alle Flughäfen in BOUNDINGBOX mit direkt verbundenen Relationen” oder “Gib mir alle Flughäfen in LAND_X” automatisch zu generieren und somit das Laden dynamischer Inhalte der Datenrepositorien erleichtern. Es ist erwünscht, dass die Geocommunity aktiv an der (Weiter-)Entwicklung des Plugins teilnimmt und so die Welt der LOD im Geokontext weiter bekannt macht. Dazu steht der Quellcode frei auf <a href="https://github.com/sparqlunicorn/sparqlunicornGoesGIS">Github</a> zur Erweiterung zur Verfügung. Der Vortrag gibt einen Einstieg in die Modellierung von Linked Open (Geo-)Data, in die Abfragesprache SPARQL, deren Erweiterung GeoSPARQL, bestehende (Geo-)Ressourcen in der Linked Open Data Cloud, sowie die Funktionsweise des <em>SPARQLing Unicorn QGIS Plugins</em>, dessen zukünftige Erweiterungen und aktuelle Entwicklungen in der Erweiterung der jeweiligen Standards. Das Unicorn freut sich auf Mithilfe aus der Geo-Community!</p>
        </section>


	<footer>
	<ul class="main">
		<li>
			<a href="https://www.fossgis.de/impressum/">Impressum</a>
		</li>
		<li>
			<a href="./agb.php">AGB</a>
		</li>
		<li>
			<a href="https://www.fossgis.de/datenschutzerklärung">Datenschutzerklärung</a>
		</li>
	</ul>
</footer>

</body>

</html>