<!doctype html>
<html lang="de">

<head>
	<?php include "../inc/meta.inc"; ?>

	<base href="<?php echo dirname($_SERVER['SCRIPT_NAME']); ?>">
	<title>Schraffuren die sich an der längsten Objektkante orientieren – FOSSGIS 2020</title>

	<link rel="stylesheet" href="./css/normalize.css">
	<link rel="stylesheet" href="./css/base.css">
	<link rel="stylesheet" href="./css/print.css" media="print">
</head>

<body id="programm">
	<?php include "../inc/header.inc"; ?>

        <!-- This file was generated by a script. Do not edit this file in Git,
             edit contents in Pretalx, regenerate the PHP files and commit them
             in the Git repository of the website. -->
        <p><a href="programm/mittwoch.php#session_TUAHKX">&#9668;&#9668; zurück zum Programm</a> <a href="sessions/lightning_talks_1.php">&#9668; zurück zur Session</a></p>
        <h2 class='abstract-title'>Schraffuren die sich an der längsten Objektkante orientieren</h2>
        <section>
            <p>
                <span class='abstract-sessiontype'>Lightning Talk</span> von                <span class='abstract-speakers'>Claas Leiner</span></p>
                            <p><span class='abstract-time-heading'>Zeit: </span>Mittwoch 11. März 18:00 Uhr<br><span class='abstract-room-heading'>Ort: </span>HS Rundbau</p>

                        <div class="video-container">
                <a href="https://media.ccc.de/v/fossgis2020-3077-schraffuren-die-sich-an-der-lngsten-objektkante-orientieren">
                    <img class="video-preview" src="video_previews/3077-hd.jpg" alt="Vorschaubild des Videos">
                    <div class="video-preview-overlay"></div>
                </a>
            </div>
                        <p><a href="/2020/None">Vortragsfolien (PDF) </a></p>
            <p>Gebäude können sehr lang gestreckt sein. Und da sie nicht immer in die gleiche Richtung verlaufen, sehen Gebäudeschraffuren oft merkwürdig aus. Hier wenige ganz lange Striche, dort ganz viele kurze. 
Mit einem kleinen QGIS-Modellertool lässt sich der Drehwinkel finden, der die Schraffur immer an der längsten Gebäudekante ausrichtet. Das geht natürlich auch für andere Objekte.</p>
        </section>


	<?php include "../inc/footer.inc"; ?>

</body>

</html>