<!doctype html>
<html lang="de">

<head>
	<meta charset="utf-8">
<meta http-equiv="x-ua-compatible" content="ie=edge">
<meta name="description" content="Die FOSSGIS-Konferenz ist im D-A-CH Raum die führende Konferenz für Freie und Open Source Software für Geoinformationssysteme OpenStreetMap.">
<meta name="keywords" content="FOSSGIS, FOSSGIS-Konferenz, 2019, FOSSGIS-Konferenz 2019, Open Source, GIS, Konferenz, Geoinformatik, OpenStreetMap, HTW Dresden">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="apple-itunes-app" content="app-id=1453299630">

	<base href="/2020/sessions">
	<title>Geodaten jonglieren mit ogr2ogr – FOSSGIS 2020</title>

	<link rel="stylesheet" href="./css/normalize.css">
	<link rel="stylesheet" href="./css/base.css">
	<link rel="stylesheet" href="./css/print.css" media="print">
</head>

<body id="programm">
	<header class="page-header">
	<a href="./" alt="FOSSGIS Konferenz 2020">
		<img class="page-logo" src="./img/fossgis2020-bollenhut.png">
	</a>
	<h1 class="page-title">
		FOSSGIS-Konferenz 2020<br>
		<span class="amp">Freiburg</span> <br>
		<span class="amp">11.&ndash;14. März</span>
	</h1>
</header>

<nav>
	<ul class="main">
		<li id="navHome">
			<a href="./">Startseite</a>
		</li>
		<!--<li id="navAnmeldung">
			<a href="./anmeldung/">Anmeldung</a>
		</li>-->
		<li id="navProgramm">
		<a href="./programm/">Programm</a>
		</li>
		<!--<li id="navAnreise">
			<a href="./anreise/">Anreise</a>
		</li>-->
		<li id="navStandort">
			<a href="./standort/">Standort</a>
		</li>
		<li id="navEvents">
			<a href="./socialevents/">Social Events</a>
		</li>
		<li id="navTeam">
			<a href="./loc/loc.php">Team</a>
		</li>
	</ul>
</nav>

<div class="hero">
	<figure>
		<img class="img-fluid" src="./img/freiburg.jpg" alt="Freiburg Luftbild">
		<figcaption>Photo: Pixaby</figcaption>
	</figure>
</div>

        <!-- This file was generated by a script. Do not edit this file in Git,
             edit contents in Pretalx, regenerate the PHP files and commit them
             in the Git repository of the website. -->
        <p><a href="programm/donnerstag.php#session_TVAGUN">&#9668;&#9668; zurück zum Programm</a> </p>
        <h2 class='abstract-title'>Geodaten jonglieren mit ogr2ogr</h2>
        <section>
            <p>
                <span class='abstract-sessiontype'>Workshop</span> von                <span class='abstract-speakers'>Claas Leiner</span></p>
                <p class='abstract-is-workshop'>Bitte melden Sie sich im <a href="https://pretix.eu/fossgis/2020/">Ticketshop</a> für diesen Workshop an, wenn Sie daran teilnehmen möchten.</p>            <p><span class='abstract-time-heading'>Zeit: </span>Donnerstag 12. März 13:30 Uhr<br><span class='abstract-room-heading'>Ort: </span>SR R-110</p>

                        
            <p>QGIS kann kann über die Schnittstelle GDAL/OGR praktisch sämtliche relevanten Geodatenformate lesen und sehr viele auch schreiben. Es gibt einige Datenformate, mit denen Nutzer/innen es häufiger zu tun bekommen, die jedoch als Arbeitsformat ungeeignet sind.
Dazu gehören insbesondere das NAS-XML-Format der Landesämter für Geoinformation und OSM-Rohdaten im OSM- oder PBF-Format.
Diese Daten lassen sich zwar direkt ins QGIS laden und anschließend in ein anderes Format speichern. Wer jedoch sehr große oder viele Dateien konvertieren muss, ist im QGIS mit sehr langen Ladezeiten oder auch Programmhängern konfrontiert. Mit dem Kommandozeilen-Werkzeug ogr2ogr, welches mit QGIS automatisch installiert wird, lassen sich auch sehr große PBF-Dateien oder ein ganzes Verzeichnis von NAS-XML-Dateien konvertieren bzw. in eine Datenbank importieren. Zudem könne Inhalte schon beim Import über die eingebaute SQL-Schnittstelle gewählt und Geometrien direkt in ein anderes Koordinatenbezugssystem umprojiziert werden.
Mit der Integration der Werkzeuge in kurze Linux-Shell-Skripts oder Windows-Batch lassen sich ganze Daten-Verzeichnisse konvertieren und viele Abläufe automatisieren,
Im Workshop konvertieren wir verschiedene Formate, wählen dabei Inhalte aus und projizieren in andere Koordinatensysteme um.
Auch das umprojizieren ganzer Verzeichnisse mit Shapefiles via ogr2ogr wird durchgeführt.</p>
        <div class='abstract-bio'>
            <h3 class='abstract-bio-name'>Claas Leiner</h3>
            <p>Claas Leiner arbeitet miit seinem Büro GKG freiberuflich in Kassel und
bietet Schulungen, Dienstleistungen und Support rund um die freien Geoinformationssysteme QGIS, GRASS, SpatiaLite, Postgis sowie GDAL/OGR an. Desweiteren bearbeitet er Aufträge zu Geodatenaufbereitung, -analysen und thematische Kartografie.
Besonders verbunden ist er mit QGIS - als Mitglied des QGIS-Anwendervereins QGIS-DE, als Mitorganisator der QGIS-Anwendertreffen 2011 - 2018 sowie als Bronze-Sponsor des Projektes.</p>
        </div>
        </section>


	<footer>
	<ul class="main">
		<li>
			<a href="https://www.fossgis.de/impressum/">Impressum</a>
		</li>
		<li>
			<a href="./agb.php">AGB</a>
		</li>
		<li>
			<a href="https://www.fossgis.de/datenschutzerklärung">Datenschutzerklärung</a>
		</li>
	</ul>
</footer>

</body>

</html>