<!doctype html>
<html lang="de">

<head>
	<?php include "../inc/meta.inc"; ?>

	<base href="<?php echo dirname($_SERVER['SCRIPT_NAME']); ?>">
	<title>OSMRouteFix - Routen erfassen und monitoren – FOSSGIS 2020</title>

	<link rel="stylesheet" href="./css/normalize.css">
	<link rel="stylesheet" href="./css/base.css">
	<link rel="stylesheet" href="./css/print.css" media="print">
</head>

<body id="programm">
	<?php include "../inc/header.inc"; ?>

        <!-- This file was generated by a script. Do not edit this file in Git,
             edit contents in Pretalx, regenerate the PHP files and commit them
             in the Git repository of the website. -->
        <p><a href="programm/freitag.php#session_UADNMX">&#9668;&#9668; zurück zum Programm</a> <a href="sessions/lightning_talks_4.php">&#9668; zurück zur Session</a></p>
        <h2 class='abstract-title'>OSMRouteFix - Routen erfassen und monitoren</h2>
        <section>
            <p>
                <span class='abstract-sessiontype'>Lightning Talk</span> von                <span class='abstract-speakers'>Holger Bruch</span></p>
                            <p><span class='abstract-time-heading'>Zeit: </span>Freitag 13. März 09:00 Uhr<br><span class='abstract-room-heading'>Ort: </span>HS Weismannhaus</p>

            
            <p>Die Pflege von OSM-Relationen ist zeitaufwändig und stellt gerade für Anfänger eine Hürde dar.
Der Lightning-Talk stellt OSMRouteFix vor, ein Werkzeug zur halbautomatischen Generierung von Routen-Relation wie z.B. bus- und detour-Routes. OSMRouteFix kann damit bei der Erfassung dieser Routen unterstützen als auch existierende Routen überwachen.</p>
        </section>


	<?php include "../inc/footer.inc"; ?>

</body>

</html>