<!doctype html>
<html lang="de">

<head>
	<meta charset="utf-8">
<meta http-equiv="x-ua-compatible" content="ie=edge">
<meta name="description" content="Die FOSSGIS-Konferenz ist im D-A-CH Raum die führende Konferenz für Freie und Open Source Software für Geoinformationssysteme OpenStreetMap.">
<meta name="keywords" content="FOSSGIS, FOSSGIS-Konferenz, 2019, FOSSGIS-Konferenz 2019, Open Source, GIS, Konferenz, Geoinformatik, OpenStreetMap, HTW Dresden">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="apple-itunes-app" content="app-id=1453299630">

	<base href="/2020/sessions">
	<title>Digitale Bahnhofspläne für die Reisendeninformation der Deutschen Bahn – FOSSGIS 2020</title>

	<link rel="stylesheet" href="./css/normalize.css">
	<link rel="stylesheet" href="./css/base.css">
	<link rel="stylesheet" href="./css/print.css" media="print">
</head>

<body id="programm">
	<header class="page-header">
	<a href="./" alt="FOSSGIS Konferenz 2020">
		<img class="page-logo" src="./img/fossgis2020-bollenhut.png">
	</a>
	<h1 class="page-title">
		FOSSGIS-Konferenz 2020<br>
		<span class="amp">Freiburg</span> <br>
		<span class="amp">11.&ndash;14. März</span>
	</h1>
</header>

<nav>
	<ul class="main">
		<li id="navHome">
			<a href="./">Startseite</a>
		</li>
		<!--<li id="navAnmeldung">
			<a href="./anmeldung/">Anmeldung</a>
		</li>-->
		<li id="navProgramm">
		<a href="./programm/">Programm</a>
		</li>
		<!--<li id="navAnreise">
			<a href="./anreise/">Anreise</a>
		</li>-->
		<li id="navStandort">
			<a href="./standort/">Standort</a>
		</li>
		<li id="navEvents">
			<a href="./socialevents/">Social Events</a>
		</li>
		<li id="navTeam">
			<a href="./loc/loc.php">Team</a>
		</li>
	</ul>
</nav>

<div class="hero">
	<figure>
		<img class="img-fluid" src="./img/freiburg.jpg" alt="Freiburg Luftbild">
		<figcaption>Photo: Pixaby</figcaption>
	</figure>
</div>

        <!-- This file was generated by a script. Do not edit this file in Git,
             edit contents in Pretalx, regenerate the PHP files and commit them
             in the Git repository of the website. -->
        <p><a href="programm/freitag.php#session_UDVAAL">&#9668;&#9668; zurück zum Programm</a> </p>
        <h2 class='abstract-title'>Digitale Bahnhofspläne für die Reisendeninformation der Deutschen Bahn</h2>
        <section>
            <p>
                                <span class='abstract-speakers'>Dr. Dirk Schlierkamp-Voosen</span></p>
                            <p><span class='abstract-time-heading'>Zeit: </span>Freitag 13. März 10:00 Uhr<br><span class='abstract-room-heading'>Ort: </span>HS Anatomie</p>

                        <div class="video-container">
                <a href="https://media.ccc.de/v/fossgis2020-3080-digitale-bahnhofsplne-fr-die-reisendeninformation-der-deutschen-bahn">
                    <img class="video-preview" src="video_previews/3080-hd.jpg" alt="Vorschaubild des Videos">
                    <div class="video-preview-overlay"></div>
                </a>
            </div>
                        
            <p>Die Einheit Reisendeninformation der Deutschen Bahn AG hat zur Aufgabe, Lösungen zu entwickeln, die den Reisendenkomfort erhöhen. 
Im Rahmen dieses Auftrags soll Reisenden die Orientierung im Bahnhof vereinfacht werden.
Über digitale Bahnhofspläne soll ein Fußgängerrouting, das Reisenden im Bahnhof die Navigation zu bestimmten POI's (Geschäften, Geldautomaten, u.v.m.) erlaubt, angeboten werden.
Das Routing selber wird über die PostgreSQL-Erweiterung PG-Routing auf einem Routingnetz gerechnet. Als Grundlage dienen dabei eigene Bahnhofspläne, 
die mit Daten aus OpenStreetMap ergänzt wurden. Anschlusspunkte außerhalb des Bahnhofs sollen über das OSM-Strassennetz verbunden werden. 
Weiterhin wurden nicht-begehbare Flächen wie Infotafeln, Schächte (u.a.) sowie Rolltreppen, Treppen und Aufzüge für Übergänge zu den 
unterschiedlichen Ebenen bei der Erstellung des Routingnetzes berücksichtigt. Das Routingnetz wurde in verschiedenen Dichten mit 
GRASS GIS erzeugt und in die Datenbank importiert.
Der Vortrag stellt die gesamte, auf einem Open Source Stack basierende Lösung, sowie auch die Integration der OSM Daten vor.</p>
        <div class='abstract-bio'>
            <h3 class='abstract-bio-name'>Dr. Dirk Schlierkamp-Voosen</h3>
            <p>Dr. Dirk Schlierkamp-Voosen
Reisendeninformation
Team RI-Maps
Deutsche Bahn AG
Hahnstraße 40, 60528 Frankfurt am Main
Email: dirk.schlierkamp-voosen@deutschebahn.com
Mobil: +49 170 3300542</p>
        </div>
        </section>


	<footer>
	<ul class="main">
		<li>
			<a href="https://www.fossgis.de/impressum/">Impressum</a>
		</li>
		<li>
			<a href="./agb.php">AGB</a>
		</li>
		<li>
			<a href="https://www.fossgis.de/datenschutzerklärung">Datenschutzerklärung</a>
		</li>
	</ul>
</footer>

</body>

</html>