<!doctype html>
<html lang="de">

<head>
	<?php include "../inc/meta.inc"; ?>

	<base href="<?php echo dirname($_SERVER['SCRIPT_NAME']); ?>">
	<title>Was ist OpenStreetMap? – FOSSGIS 2020</title>

	<link rel="stylesheet" href="./css/normalize.css">
	<link rel="stylesheet" href="./css/base.css">
	<link rel="stylesheet" href="./css/print.css" media="print">
</head>

<body id="programm">
	<?php include "../inc/header.inc"; ?>

        <!-- This file was generated by a script. Do not edit this file in Git,
             edit contents in Pretalx, regenerate the PHP files and commit them
             in the Git repository of the website. -->
        <p><a href="programm/mittwoch.php#session_UEWFWR">&#9668;&#9668; zurück zum Programm</a> </p>
        <h2 class='abstract-title'>Was ist OpenStreetMap?</h2>
        <section>
            <p>
                                <span class='abstract-speakers'>Thomas Skowron</span></p>
                            <p><span class='abstract-time-heading'>Zeit: </span>Mittwoch 11. März 11:40 Uhr<br><span class='abstract-room-heading'>Ort: </span>HS Anatomie</p>

            
            <p>Was ist OpenStreetMap? In dieser Session wird das Projekt vorgestellt, warum es entstanden ist, wer es nutzt und was die Vorteile sind.</p>
<p>Es werden Anwendungen auf Basis von OpenStreetMap gezeigt und Anregungen geliefert, welche Möglichkeiten OSM eröffnet und wie sich Teilnehmer der Konferenz im Projekt einbringen können.</p>
        <div class='abstract-bio'>
            <h3 class='abstract-bio-name'>Thomas Skowron</h3>
            <p>OpenStreetMap-Enthusiast und professioneller Nutzer, freiberuflicher Softwareentwickler, Leiter des Programmkomitees FOSSGIS 2020</p>
<p><a href="https://thomas.skowron.eu">Webseite</a></p>
        </div>
        </section>


	<?php include "../inc/footer.inc"; ?>

</body>

</html>