<!doctype html>
<html lang="de">

<head>
	<?php include "../inc/meta.inc"; ?>

	<base href="<?php echo dirname($_SERVER['SCRIPT_NAME']); ?>">
	<title>AD und PostgreSQL Rollen verknüpfen mit dem Höllenhund – FOSSGIS 2020</title>

	<link rel="stylesheet" href="./css/normalize.css">
	<link rel="stylesheet" href="./css/base.css">
	<link rel="stylesheet" href="./css/print.css" media="print">
</head>

<body id="programm">
	<?php include "../inc/header.inc"; ?>

        <!-- This file was generated by a script. Do not edit this file in Git,
             edit contents in Pretalx, regenerate the PHP files and commit them
             in the Git repository of the website. -->
        <p><a href="programm/donnerstag.php#session_UPPG8U">&#9668;&#9668; zurück zum Programm</a> </p>
        <h2 class='abstract-title'>AD und PostgreSQL Rollen verknüpfen mit dem Höllenhund</h2>
        <section>
            <p>
                                <span class='abstract-speakers'>Michael Schulz</span></p>
                            <p><span class='abstract-time-heading'>Zeit: </span>Donnerstag 12. März 14:30 Uhr<br><span class='abstract-room-heading'>Ort: </span>HS Anatomie</p>

            
            <p>Rollen und Rechte in einer Geodatenbank zu verwalten, war schon immer eine komplizierte Aufgabe. Benutzerverwaltung up-to-date halten, wechselnde Aufgaben und ressortspezifische Zugriffe zu ermöglichen, eine administrative Herkulesaufgabe. In einer Stadtverwaltung wie Freiburg, mit mehreren hundert Mitarbeitenden aus vielen verschiedenen Ämtern und Projektgruppen, die alle auf eine zentrale Geodatenhaltung zugreifen wollen, bietet es sich daher an, diese Berechtigungen über die zentrale Benutzerverwaltung abzubilden. Das Zusammenspiel von Open-Source Komponenten wie PostgreSQL und QGIS mit dem Verzeichnisdienst ActiveDirectory wird durch Kerberos als Authentifizierungsdienst umgesetzt. Es ermöglicht z.B. Single-Sign-On bei der Nutzung der zentralen Geodatenbank in QGIS unter Windows. Die Konzeption der Rollen im AD und in der Datenbank stehen dabei an erster Stelle. Die automatische Übernahme der Rollen vom AD in die Datenbank ist eine weitere Herausforderung, ebenso wie die Weitergabe von QGIS-Projekten mit gespeicherten Datenbank-Verbindungen die mittels Kerberos authentifiziert werden. Wir stellen die bisherigen Erfahrungen bei der Anwendung dieses Vorgehens in der Stadtverwaltung Freiburg vor.</p>
        <div class='abstract-bio'>
            <h3 class='abstract-bio-name'>Michael Schulz</h3>
            <p>Stadt Freiburg, Digitales und IT</p>
        </div>
        </section>


	<?php include "../inc/footer.inc"; ?>

</body>

</html>