<!doctype html>
<html lang="de">

<head>
	<meta charset="utf-8">
<meta http-equiv="x-ua-compatible" content="ie=edge">
<meta name="description" content="Die FOSSGIS-Konferenz ist im D-A-CH Raum die führende Konferenz für Freie und Open Source Software für Geoinformationssysteme OpenStreetMap.">
<meta name="keywords" content="FOSSGIS, FOSSGIS-Konferenz, 2019, FOSSGIS-Konferenz 2019, Open Source, GIS, Konferenz, Geoinformatik, OpenStreetMap, HTW Dresden">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="apple-itunes-app" content="app-id=1453299630">

	<base href="/2020/sessions">
	<title>Automatische Korrektur von ÖV-Stationen in OSM – FOSSGIS 2020</title>

	<link rel="stylesheet" href="./css/normalize.css">
	<link rel="stylesheet" href="./css/base.css">
	<link rel="stylesheet" href="./css/print.css" media="print">
</head>

<body id="programm">
	<header class="page-header">
	<a href="./" alt="FOSSGIS Konferenz 2020">
		<img class="page-logo" src="./img/fossgis2020-bollenhut.png">
	</a>
	<h1 class="page-title">
		FOSSGIS-Konferenz 2020<br>
		<span class="amp">Freiburg</span> <br>
		<span class="amp">11.&ndash;14. März</span>
	</h1>
</header>

<nav>
	<ul class="main">
		<li id="navHome">
			<a href="./">Startseite</a>
		</li>
		<!--<li id="navAnmeldung">
			<a href="./anmeldung/">Anmeldung</a>
		</li>-->
		<li id="navProgramm">
		<a href="./programm/">Programm</a>
		</li>
		<!--<li id="navAnreise">
			<a href="./anreise/">Anreise</a>
		</li>-->
		<li id="navStandort">
			<a href="./standort/">Standort</a>
		</li>
		<li id="navEvents">
			<a href="./socialevents/">Social Events</a>
		</li>
		<li id="navTeam">
			<a href="./loc/loc.php">Team</a>
		</li>
	</ul>
</nav>

<div class="hero">
	<figure>
		<img class="img-fluid" src="./img/freiburg.jpg" alt="Freiburg Luftbild">
		<figcaption>Photo: Pixaby</figcaption>
	</figure>
</div>

        <!-- This file was generated by a script. Do not edit this file in Git,
             edit contents in Pretalx, regenerate the PHP files and commit them
             in the Git repository of the website. -->
        <p><a href="programm/donnerstag.php#session_VAXSHT">&#9668;&#9668; zurück zum Programm</a> </p>
        <h2 class='abstract-title'>Automatische Korrektur von ÖV-Stationen in OSM</h2>
        <section>
            <p>
                                <span class='abstract-speakers'>Patrick Brosi</span></p>
                            <p><span class='abstract-time-heading'>Zeit: </span>Donnerstag 12. März 16:30 Uhr<br><span class='abstract-room-heading'>Ort: </span>HS Weismannhaus</p>

                        <div class="video-container">
                <a href="https://media.ccc.de/v/fossgis2020-3183-automatische-korrektur-von-v-stationen-in-osm">
                    <img class="video-preview" src="video_previews/3183-hd.jpg" alt="Vorschaubild des Videos">
                    <div class="video-preview-overlay"></div>
                </a>
            </div>
                        <p><a href="/2020/attachments/VAXSHT_brosi_1630_7OlydO7.pdf">Vortragsfolien (PDF) </a></p>
            <p>Wir stellen ein Tool (staty) vor, das aus ÖV-Stationsdaten in OSM Tupel von Stationsnamen und -koordinaten extrahiert. Die in OSM bereits als gruppiert markierten Stationen werden als ground truth verwendet und damit ein Klassifikator trainiert, der entscheiden kann, ob zwei Name/Koordinate Tupel dieselbe Station beschreiben. Die Hauptschwierigkeit liegt darin, dass dieselben Stationen teilweis deutlich voneinander abweichende Bezeichnungen haben können (z.B. "Hbf" vs. "Freiburg im Breisgau, Hauptbahnhof"), dass z.B. Ortsnamen für die Ähnlichkeit zweier Stationen irrelevant sind, wenn sie nah beieinander liegen, oder dass die mittlere Distanz von z.B. Haltepunkten derselben Stationen abhängig ist von der Art der Stationen. Z.B. wird die mittlere paarweise Distanz zwischen Haltepunkten in einer Station "Hauptbahnhof" üblicherweise deutlich größer sein als in einer Station "Dorfstraße".</p>
<p>Wir nutzen unseren auf OSM-Daten trainierten Klassifikator, um die OSM-Daten selbst wieder zu korrigieren. Dazu führen wir ein auf den Ähnlichkeitswerten unseres Klassifikators beruhendes Clustering durch und geben die Differenz zwischen dem Clustering und der Stationsgruppierung in OSM als Editiervorschläge aus. Da unser Ansatz z.B. auch verschiedene Namen (ref_name, alt_name, name, ...) innerhalb einzelner Nodes als separate Elemente extrahiert, können auch Fehler innerhalb einzelner Nodes erkannt werden (z.B. ein nicht korrekt durch alle Namen nachgeführter Namenswechsel oder Schreibfehler).</p>
        </section>


	<footer>
	<ul class="main">
		<li>
			<a href="https://www.fossgis.de/impressum/">Impressum</a>
		</li>
		<li>
			<a href="./agb.php">AGB</a>
		</li>
		<li>
			<a href="https://www.fossgis.de/datenschutzerklärung">Datenschutzerklärung</a>
		</li>
	</ul>
</footer>

</body>

</html>