<!doctype html>
<html lang="de">

<head>
	<meta charset="utf-8">
<meta http-equiv="x-ua-compatible" content="ie=edge">
<meta name="description" content="Die FOSSGIS-Konferenz ist im D-A-CH Raum die führende Konferenz für Freie und Open Source Software für Geoinformationssysteme OpenStreetMap.">
<meta name="keywords" content="FOSSGIS, FOSSGIS-Konferenz, 2019, FOSSGIS-Konferenz 2019, Open Source, GIS, Konferenz, Geoinformatik, OpenStreetMap, HTW Dresden">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="apple-itunes-app" content="app-id=1453299630">

	<base href="/2020/sessions">
	<title>TEAM Engine: Vorstellung der neusten Tests für OGC-Standards wie OGC API Features oder GeoTIFF – FOSSGIS 2020</title>

	<link rel="stylesheet" href="./css/normalize.css">
	<link rel="stylesheet" href="./css/base.css">
	<link rel="stylesheet" href="./css/print.css" media="print">
</head>

<body id="programm">
	<header class="page-header">
	<a href="./" alt="FOSSGIS Konferenz 2020">
		<img class="page-logo" src="./img/fossgis2020-bollenhut.png">
	</a>
	<h1 class="page-title">
		FOSSGIS-Konferenz 2020<br>
		<span class="amp">Freiburg</span> <br>
		<span class="amp">11.&ndash;14. März</span>
	</h1>
</header>

<nav>
	<ul class="main">
		<li id="navHome">
			<a href="./">Startseite</a>
		</li>
		<!--<li id="navAnmeldung">
			<a href="./anmeldung/">Anmeldung</a>
		</li>-->
		<li id="navProgramm">
		<a href="./programm/">Programm</a>
		</li>
		<!--<li id="navAnreise">
			<a href="./anreise/">Anreise</a>
		</li>-->
		<li id="navStandort">
			<a href="./standort/">Standort</a>
		</li>
		<li id="navEvents">
			<a href="./socialevents/">Social Events</a>
		</li>
		<li id="navTeam">
			<a href="./loc/loc.php">Team</a>
		</li>
	</ul>
</nav>

<div class="hero">
	<figure>
		<img class="img-fluid" src="./img/freiburg.jpg" alt="Freiburg Luftbild">
		<figcaption>Photo: Pixaby</figcaption>
	</figure>
</div>

        <!-- This file was generated by a script. Do not edit this file in Git,
             edit contents in Pretalx, regenerate the PHP files and commit them
             in the Git repository of the website. -->
        <p><a href="programm/donnerstag.php#session_VDPQS7">&#9668;&#9668; zurück zum Programm</a> </p>
        <h2 class='abstract-title'>TEAM Engine: Vorstellung der neusten Tests für OGC-Standards wie OGC API Features oder GeoTIFF</h2>
        <section>
            <p>
                                <span class='abstract-speakers'>Dirk Stenger</span></p>
                            <p><span class='abstract-time-heading'>Zeit: </span>Donnerstag 12. März 14:00 Uhr<br><span class='abstract-room-heading'>Ort: </span>HS Rundbau</p>

                        <div class="video-container">
                <a href="https://media.ccc.de/v/fossgis2020-3028-team-engine-vorstellung-der-neusten-tests-fr-ogc-standards-wie-ogc-api-features-oder-geotiff">
                    <img class="video-preview" src="video_previews/3028-hd.jpg" alt="Vorschaubild des Videos">
                    <div class="video-preview-overlay"></div>
                </a>
            </div>
                        
            <p>Die TEAM Engine ist eine Engine, mit der Entwickler und Anwender Geodienste, wie WFS und WMS, und Geoformate, wie GML oder GeoPackage, testen können. Um die Implementierung und das Testen von GIS-Software basierend auf OGC Standards zu unterstützen, stellt das Open Geospatial Consortium (OGC) mehrere Testsuites für die TEAM Engine zur Verfügung.</p>
<p>Die TEAM Engine ist aktuell als OSGeo-Projekt in der Inkubationsphase. Sie ist sie ein wichtiges Werkzeug, um die Interoperabilität zwischen verschiedenen Implementierungen von OGC-Standards und Clients, die diese Standards in Form von Schnittstellen, wie WFS oder WMS, oder Formaten, wie GML oder GeoPackage, nutzen, zu gewährleisten.</p>
<p>Die TEAM Engine muss in Verbindung mit OGC Executable Test Suites (ETS) verwendet werden, um Instanzen von Geodiensten und -formaten auf Konformität mit OGC-Standards zu prüfen. Die Ausführung einer ETS erfolgt über eine Weboberfläche, eine REST Schnittstelle oder ein Kommandozeilentool. Um die Installation, Konfiguration und das Starten der TEAM Engine zu erleichtern, werden Docker-Images bereitgestellt.</p>
<p>Es werden aktuell mehrere neue Testsuites entwickelt, mit denen unter anderem Implementierungen der neuen OGC Standards OGC API - Features und GeoTIFF getestet werden können. Auch für weitere OGC Standards wurden in jüngster Zeit Tests erstellt oder erweitert.</p>
<p>Dieser Vortrag gibt eine Übersicht über alle neuen Testsuites und stellt einige von ihnen näher vor. Des Weiteren werden die aktuellen Entwicklungen im TEAM Engine Projekt aufgezeigt und ein Ausblick auf die Schwerpunkte der Weiterentwicklung in der Zukunft gegeben.</p>
        </section>


	<footer>
	<ul class="main">
		<li>
			<a href="https://www.fossgis.de/impressum/">Impressum</a>
		</li>
		<li>
			<a href="./agb.php">AGB</a>
		</li>
		<li>
			<a href="https://www.fossgis.de/datenschutzerklärung">Datenschutzerklärung</a>
		</li>
	</ul>
</footer>

</body>

</html>