<!doctype html>
<html lang="de">

<head>
	<?php include "../inc/meta.inc"; ?>

	<base href="<?php echo dirname($_SERVER['SCRIPT_NAME']); ?>">
	<title>NodeJS GeoServer und GeoWebCache Connectors – FOSSGIS 2020</title>

	<link rel="stylesheet" href="./css/normalize.css">
	<link rel="stylesheet" href="./css/base.css">
	<link rel="stylesheet" href="./css/print.css" media="print">
</head>

<body id="programm">
	<?php include "../inc/header.inc"; ?>

        <!-- This file was generated by a script. Do not edit this file in Git,
             edit contents in Pretalx, regenerate the PHP files and commit them
             in the Git repository of the website. -->
        <p><a href="programm/mittwoch.php#session_VTQQJR">&#9668;&#9668; zurück zum Programm</a> <a href="sessions/lightning_talks_1.php">&#9668; zurück zur Session</a></p>
        <h2 class='abstract-title'>NodeJS GeoServer und GeoWebCache Connectors</h2>
        <section>
            <p>
                <span class='abstract-sessiontype'>Lightning Talk</span> von                <span class='abstract-speakers'>Marco Scheuble</span></p>
                            <p><span class='abstract-time-heading'>Zeit: </span>Mittwoch 11. März 18:05 Uhr<br><span class='abstract-room-heading'>Ort: </span>HS Rundbau</p>

            
            <p>Mit den beiden Bibliotheken NodeJS-GeoServer-Connector und NodeJS-GeoWebCache-Connector hat die GEOINFO Applications AG zwei Bibliotheken entwickelt, die Anfang 2020 unter einer Open-Source-Lizenz veröffentlicht wurden. Die Node.js-Bibliotheken ermöglichen die Administration des GeoServers und des GeoWebCaches durch einfache Funktionsaufrufe aus Node.js basierten Applikationen heraus. Das aufwendige Erstellen und Parsen von XML-Dokumenten, sowie von HTTP-Requests und Responses fällt damit weg.</p>
<p>Im Lightning Talk wird der grobe Aufbau der Bibliotheken beschrieben, die wichtigsten Funktionen vorgestellt und alles Wesentliche angesprochen, um bei diesen Projekten mitzuwirken.</p>
<p>https://github.com/geoinfo-applications/nodejs-geoserver-connector
https://github.com/geoinfo-applications/nodejs-geowebcache-connector</p>
        </section>


	<?php include "../inc/footer.inc"; ?>

</body>

</html>