<!doctype html>
<html lang="de">

<head>
	<meta charset="utf-8">
<meta http-equiv="x-ua-compatible" content="ie=edge">
<meta name="description" content="Die FOSSGIS-Konferenz ist im D-A-CH Raum die führende Konferenz für Freie und Open Source Software für Geoinformationssysteme OpenStreetMap.">
<meta name="keywords" content="FOSSGIS, FOSSGIS-Konferenz, 2019, FOSSGIS-Konferenz 2019, Open Source, GIS, Konferenz, Geoinformatik, OpenStreetMap, HTW Dresden">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="apple-itunes-app" content="app-id=1453299630">

	<base href="/2020/sessions">
	<title>Dateneingabeformulare gestalten mit Qt-Designer und Python – FOSSGIS 2020</title>

	<link rel="stylesheet" href="./css/normalize.css">
	<link rel="stylesheet" href="./css/base.css">
	<link rel="stylesheet" href="./css/print.css" media="print">
</head>

<body id="programm">
	<header class="page-header">
	<a href="./" alt="FOSSGIS Konferenz 2020">
		<img class="page-logo" src="./img/fossgis2020-bollenhut.png">
	</a>
	<h1 class="page-title">
		FOSSGIS-Konferenz 2020<br>
		<span class="amp">Freiburg</span> <br>
		<span class="amp">11.&ndash;14. März</span>
	</h1>
</header>

<nav>
	<ul class="main">
		<li id="navHome">
			<a href="./">Startseite</a>
		</li>
		<!--<li id="navAnmeldung">
			<a href="./anmeldung/">Anmeldung</a>
		</li>-->
		<li id="navProgramm">
		<a href="./programm/">Programm</a>
		</li>
		<!--<li id="navAnreise">
			<a href="./anreise/">Anreise</a>
		</li>-->
		<li id="navStandort">
			<a href="./standort/">Standort</a>
		</li>
		<li id="navEvents">
			<a href="./socialevents/">Social Events</a>
		</li>
		<li id="navTeam">
			<a href="./loc/loc.php">Team</a>
		</li>
	</ul>
</nav>

<div class="hero">
	<figure>
		<img class="img-fluid" src="./img/freiburg.jpg" alt="Freiburg Luftbild">
		<figcaption>Photo: Pixaby</figcaption>
	</figure>
</div>

        <!-- This file was generated by a script. Do not edit this file in Git,
             edit contents in Pretalx, regenerate the PHP files and commit them
             in the Git repository of the website. -->
        <p><a href="programm/donnerstag.php#session_VUPGUK">&#9668;&#9668; zurück zum Programm</a> </p>
        <h2 class='abstract-title'>Dateneingabeformulare gestalten mit Qt-Designer und Python</h2>
        <section>
            <p>
                <span class='abstract-sessiontype'>Workshop</span> von                <span class='abstract-speakers'>Otto Dassau, Tristan</span></p>
                            <p><span class='abstract-time-heading'>Zeit: </span>Donnerstag 12. März 15:30 Uhr<br><span class='abstract-room-heading'>Ort: </span>SR R-100</p>

                        
            <p>Im Rahmen des Workshops soll es zunächst eine kurze Übersicht über die Anpassungsmöglichkeiten für Formulare in QGIS geben.
​
Anschließend wird es eine Einführung in den Qt-Designer geben.
Die Teilnehmer_innen lernen eigene Formulare im Qt-Designer zu entwerfen und diese schließlich in QGIS zu integrieren.
​
Um das ganze Potential der so erstellten Formulare zu wecken, wird es am Ende noch eine kurze Einführung in Python geben.
Die Teilnehmer_innen lernen, wie eigener Python-Code in das Formular eingebunden werden kann.
Außerdem werden beispielhaft Möglichkeiten aufgezeigt, wie die Dateneingabe über Python gesteuert werden kann.
Die Programmierung mit Python steht dabei nicht im Vordergrund. Dies ist kein Programmierkurs.</p>
        <div class='abstract-bio'>
            <h3 class='abstract-bio-name'>Otto Dassau</h3>
            <p>Otto Dassau ist Geschäftsführer der Geoinformatikbüro Dassau GmbH aus Düsseldorf. Das Unternehmen ist spezialisiert auf Open Source basierte Lösungen zum Thema WebGIS, GIS und GDI und engagiert sich auf verschiedenen Ebenen intensiv für deren Weiterentwicklung. Seit 2001 ist er Mitglied im FOSSGIS e.V., er ist Gründungsmitglied der QGIS Anwendergruppe Deutschland e.V. und war zwischen 2007 und 2016 Mitglied des QGIS Project Steering Committees.</p>
        </div>
        </section>


	<footer>
	<ul class="main">
		<li>
			<a href="https://www.fossgis.de/impressum/">Impressum</a>
		</li>
		<li>
			<a href="./agb.php">AGB</a>
		</li>
		<li>
			<a href="https://www.fossgis.de/datenschutzerklärung">Datenschutzerklärung</a>
		</li>
	</ul>
</footer>

</body>

</html>