<!doctype html>
<html lang="de">

<head>
	<?php include "../inc/meta.inc"; ?>

	<base href="<?php echo dirname($_SERVER['SCRIPT_NAME']); ?>">
	<title>Community Arbeit – ein Einblick in die Berliner OSM/FOSSGIS-Community – FOSSGIS 2020</title>

	<link rel="stylesheet" href="./css/normalize.css">
	<link rel="stylesheet" href="./css/base.css">
	<link rel="stylesheet" href="./css/print.css" media="print">
</head>

<body id="programm">
	<?php include "../inc/header.inc"; ?>

        <!-- This file was generated by a script. Do not edit this file in Git,
             edit contents in Pretalx, regenerate the PHP files and commit them
             in the Git repository of the website. -->
        <p><a href="programm/freitag.php#session_WC7SVB">&#9668;&#9668; zurück zum Programm</a> </p>
        <h2 class='abstract-title'>Community Arbeit – ein Einblick in die Berliner OSM/FOSSGIS-Community</h2>
        <section>
            <p>
                                <span class='abstract-speakers'>Christopher Lorenz, Lars Lingner</span></p>
                            <p><span class='abstract-time-heading'>Zeit: </span>Freitag 13. März 11:30 Uhr<br><span class='abstract-room-heading'>Ort: </span>HS Weismannhaus</p>

            
            <p>Ein Einblick in die Community-Arbeit von zwei engagierten OSM- und FOSSGIS-Mitgliedern. Es wird aufgezeigt, welche Aktivitäten in der Berliner Community statt fanden bzw. sich in Planung befinden. Dabei wird dargestellt, welche Schwierigkeiten es gibt. Warum ist es wichtig nie aufzugeben, sollte etwas nicht gleich so funktionieren, wie geplant. Es werden auch Wege gezeigt, wie man nicht nur aktive sondern auch Interessierte erreicht. Neben dem Einblick, den wir geben, möchten wir auch sehr gerne Feedback und Meinungen einsammeln. </p>
<p>Warum schlafen Communitieevents wieder ein? Wann sind Events erfolgreich und was für Ziele stellt man sich? Was sind geeignete Kommunikationskanäle? Wie vernetzt man sich und baut Brücken zu anderen Communities?   Welche Ressourcen sind nützlich und worauf kann man verzichten?</p>
<p>Folgende Aktivitäten aus Berlin werden vorgestellt:
 - Stammtisch
 - Six Feet Under
 - Workshop
 - Hackweekends
 - Gruppe Verkehrswende
 - Gruppe ÖPNV</p>
        <div class='abstract-bio'>
            <h3 class='abstract-bio-name'>Lars Lingner</h3>
            <p>Kommt noch</p>
        </div>
        </section>


	<?php include "../inc/footer.inc"; ?>

</body>

</html>