<!doctype html>
<html lang="de">

<head>
	<?php include "../inc/meta.inc"; ?>

	<base href="<?php echo dirname($_SERVER['SCRIPT_NAME']); ?>">
	<title>Sportliche Stadtführung – FOSSGIS 2020</title>

	<link rel="stylesheet" href="./css/normalize.css">
	<link rel="stylesheet" href="./css/base.css">
	<link rel="stylesheet" href="./css/print.css" media="print">
</head>

<body id="programm">
	<?php include "../inc/header.inc"; ?>

        <!-- This file was generated by a script. Do not edit this file in Git,
             edit contents in Pretalx, regenerate the PHP files and commit them
             in the Git repository of the website. -->
        <p><a href="programm/donnerstag.php#session_WFPTSP">&#9668;&#9668; zurück zum Programm</a> </p>
        <h2 class='abstract-title'>Sportliche Stadtführung</h2>
        <section>
            <p>
                <span class='abstract-sessiontype'>Workshop</span> von                <span class='abstract-speakers'>Marco Lechner</span></p>
                <p class='abstract-is-workshop'>Bitte melden Sie sich im <a href="https://pretix.eu/fossgis/2020/">Ticketshop</a> für diesen Workshop an, wenn Sie daran teilnehmen möchten. Workshopbuchungen sind auch nach der Ticketbuchung online und auf der Konferenz möglich.</p>            <p><span class='abstract-time-heading'>Zeit: </span>Donnerstag 12. März 07:00 Uhr<br><span class='abstract-room-heading'>Ort: </span>Rahmenprogramm</p>

            
            <p>Um richtig in Schwung zu kommen, werden wir in 3 verschiedenen Runden zu je 30 Minuten laufend die sonnigste Stadt Deutschlands und den Schwarzwaldrand erkunden. Je nach Laufniveau gibt es die Möglichkeit früher oder später ein- bzw. auszusteigen. So beginnen wir vor dem Haupteingang des Veranstaltungsortes und laufen in 3 Schleifen durch Freiburg, so dass wir jeweils um 07:30, 08:00 sowie abschließend um 08:30 am Haupteingang vorbei bzw. ankommen.
Die erste halbe Stunde wird es eher ruhig angegangen, genau richtig für Einsteiger oder Gelegenheitsläufer, oder um langsam warm zu werden. In der zweiten halben Stunde geht es dann schon etwas flotter zu und es werden auch etwas längere Distanzen geschafft, so dass uns die dritte und letzte Schleife über den Schwarzwaldrand auf den Freiburger Schlossberg führt und uns nochmal alles abverlangt. Belohnt werden wir mit einem wunderbaren Ausblick auf die Stadt und mit etwas Glück Fernsicht bis zu den Vogesen.</p>
        </section>


	<?php include "../inc/footer.inc"; ?>

</body>

</html>