<!doctype html>
<html lang="de">

<head>
	<?php include "../inc/meta.inc"; ?>

	<base href="<?php echo dirname($_SERVER['SCRIPT_NAME']); ?>">
	<title>OSGeo-Projekt deegree 2020 - Neuigkeiten zu OGC API - Features – FOSSGIS 2020</title>

	<link rel="stylesheet" href="./css/normalize.css">
	<link rel="stylesheet" href="./css/base.css">
	<link rel="stylesheet" href="./css/print.css" media="print">
</head>

<body id="programm">
	<?php include "../inc/header.inc"; ?>

        <!-- This file was generated by a script. Do not edit this file in Git,
             edit contents in Pretalx, regenerate the PHP files and commit them
             in the Git repository of the website. -->
        <p><a href="programm/donnerstag.php#session_WNARKE">&#9668;&#9668; zurück zum Programm</a> </p>
        <h2 class='abstract-title'>OSGeo-Projekt deegree 2020 - Neuigkeiten zu OGC API - Features</h2>
        <section>
            <p>
                                <span class='abstract-speakers'>Torsten Friebe, Dirk Stenger</span></p>
                            <p><span class='abstract-time-heading'>Zeit: </span>Donnerstag 12. März 14:30 Uhr<br><span class='abstract-room-heading'>Ort: </span>HS Rundbau</p>

                        <div class="video-container">
                <a href="https://media.ccc.de/v/fossgis2020-3072-osgeo-projekt-deegree-2020-neuigkeiten-zu-ogc-api-features">
                    <img class="video-preview" src="/2020/video_previews/3072-hd.jpg" alt="Vorschaubild des Videos">
                    <div class="video-preview-overlay"></div>
                </a>
            </div>
                        
            <p>Das OSGeo-Projekt deegree stellt seit mehreren Jahren umfassende Referenzimplementierungen für OGC-Webservices wie z.B. WFS, WMS und WMTS bereit. Wenn es um den Aufbau von Geodateninfrastrukturen geht, dann können Geodaten in unterschiedlichen Formaten mit den deegree OGC-Webservices publiziert werden.</p>
<p>Aktuell wird an der Implementierung des neuen Standard OGC API - Features, dem Nachfolger des Web Features Service (WFS), gearbeitet. </p>
<p>Die Präsentation zeigt die wichtigsten Neuerungen in deegree, eine kurze Übersicht des Standards OGC API - Features und dessen Umsetzung innerhalb von deegree.</p>
        <div class='abstract-bio'>
            <h3 class='abstract-bio-name'>Torsten Friebe</h3>
            <p>Torsten Friebe ist Committer und Mitglied des TMC im OSGeo-Projekt deegree (https://www.deegree.org). Seit 2011 ist er Gesellschafter und Geschäftsführer bei der lat/lon GmbH in Bonn.</p>
        </div>
        </section>


	<?php include "../inc/footer.inc"; ?>

</body>

</html>