<!doctype html>
<html lang="de">

<head>
	<meta charset="utf-8">
<meta http-equiv="x-ua-compatible" content="ie=edge">
<meta name="description" content="Die FOSSGIS-Konferenz ist im D-A-CH Raum die führende Konferenz für Freie und Open Source Software für Geoinformationssysteme OpenStreetMap.">
<meta name="keywords" content="FOSSGIS, FOSSGIS-Konferenz, 2019, FOSSGIS-Konferenz 2019, Open Source, GIS, Konferenz, Geoinformatik, OpenStreetMap, HTW Dresden">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="apple-itunes-app" content="app-id=1453299630">

	<base href="/2020/sessions">
	<title>Rettungspunkte - im Prinzip ganz einfach, aber ... – FOSSGIS 2020</title>

	<link rel="stylesheet" href="./css/normalize.css">
	<link rel="stylesheet" href="./css/base.css">
	<link rel="stylesheet" href="./css/print.css" media="print">
</head>

<body id="programm">
	<header class="page-header">
	<a href="./" alt="FOSSGIS Konferenz 2020">
		<img class="page-logo" src="./img/fossgis2020-bollenhut.png">
	</a>
	<h1 class="page-title">
		FOSSGIS-Konferenz 2020<br>
		<span class="amp">Freiburg</span> <br>
		<span class="amp">11.&ndash;14. März</span>
	</h1>
</header>

<nav>
	<ul class="main">
		<li id="navHome">
			<a href="./">Startseite</a>
		</li>
		<!--<li id="navAnmeldung">
			<a href="./anmeldung/">Anmeldung</a>
		</li>-->
		<li id="navProgramm">
		<a href="./programm/">Programm</a>
		</li>
		<!--<li id="navAnreise">
			<a href="./anreise/">Anreise</a>
		</li>-->
		<li id="navStandort">
			<a href="./standort/">Standort</a>
		</li>
		<li id="navEvents">
			<a href="./socialevents/">Social Events</a>
		</li>
		<li id="navTeam">
			<a href="./loc/loc.php">Team</a>
		</li>
	</ul>
</nav>

<div class="hero">
	<figure>
		<img class="img-fluid" src="./img/freiburg.jpg" alt="Freiburg Luftbild">
		<figcaption>Photo: Pixaby</figcaption>
	</figure>
</div>

        <!-- This file was generated by a script. Do not edit this file in Git,
             edit contents in Pretalx, regenerate the PHP files and commit them
             in the Git repository of the website. -->
        <p><a href="programm/freitag.php#session_XBCSPZ">&#9668;&#9668; zurück zum Programm</a> </p>
        <h2 class='abstract-title'>Rettungspunkte - im Prinzip ganz einfach, aber ...</h2>
        <section>
            <p>
                                <span class='abstract-speakers'>Christopher Lorenz, Joachim Kast</span></p>
                            <p><span class='abstract-time-heading'>Zeit: </span>Freitag 13. März 12:00 Uhr<br><span class='abstract-room-heading'>Ort: </span>HS Weismannhaus</p>

                        <div class="video-container">
                <a href="https://media.ccc.de/v/fossgis2020-3124-rettungspunkte-im-prinzip-ganz-einfach-aber-">
                    <img class="video-preview" src="video_previews/3124-hd.jpg" alt="Vorschaubild des Videos">
                    <div class="video-preview-overlay"></div>
                </a>
            </div>
                        
            <p>Forstliche Rettungspunkte sind definierte Orte (meistens) im Wald, die mithilfe von Koordinatenangaben Treffpunkte beschreiben. Im Falle eines Unfalls können diese Treffpunkte bei der Kommunikation des Verunfallten bzw. eines Helfers mit dem Rettungsdienst genutzt werden, um das Auffinden des Unfallortes zu erleichtern. An diesen Orten sind in den meisten Bundesländern fest installierte Schilder mit einer Referenznummer angebracht. Diese Standorte werden in OSM seit mindestens 2008 als <code>highway=emergency_access_point</code> erfasst.</p>
<p>Seit 2014 veröffentlicht das Kuratorium für Waldarbeit und Forsttechnik e.V. (KWF) die Rettungspunkte der meisten Bundesländer unter der zu OSM inkompatiblen Lizenz CC-BY-ND. Seitdem mache ich regelmäßige Abgleiche beider Datenbestände, kann aber aus lizenzrechtlichen Gründen die Detail-Ergebnisse nicht allgemein veröffentlichen. Als pragmatische Lösung erhalten je nach Fehlerart die entsprechenden Mapper oder  Forstverwaltungen einen Hinweis, die erfassten oder veröffentlichten Daten nochmals vor Ort zu überprüfen.</p>
<p>So hat sich im Laufe der Jahre ein unabhängiges QS-System entwickelt, durch das in OSM einige Erfassungsfehler korrigiert werden konnten. Aber auch in den Daten der Forstverwaltungen konnten  falsch aufgestellte oder verwechselte Schilder entdeckt werden.</p>
<p>In dem Vortrag werden die verwendeten Methoden und die teilweise überraschenden Ergebnisse vorgestellt.</p>
        <div class='abstract-bio'>
            <h3 class='abstract-bio-name'>Joachim Kast</h3>
            <p>Mapper seit 2008, Ansprechpartner der deutschen OSM-Community für Behörden</p>
        </div>
        </section>


	<footer>
	<ul class="main">
		<li>
			<a href="https://www.fossgis.de/impressum/">Impressum</a>
		</li>
		<li>
			<a href="./agb.php">AGB</a>
		</li>
		<li>
			<a href="https://www.fossgis.de/datenschutzerklärung">Datenschutzerklärung</a>
		</li>
	</ul>
</footer>

</body>

</html>