<!doctype html>
<html lang="de">

<head>
	<?php include "../inc/meta.inc"; ?>

	<base href="<?php echo dirname($_SERVER['SCRIPT_NAME']); ?>">
	<title>QGIS für Einsteiger – FOSSGIS 2020</title>

	<link rel="stylesheet" href="./css/normalize.css">
	<link rel="stylesheet" href="./css/base.css">
	<link rel="stylesheet" href="./css/print.css" media="print">
</head>

<body id="programm">
	<?php include "../inc/header.inc"; ?>

        <!-- This file was generated by a script. Do not edit this file in Git,
             edit contents in Pretalx, regenerate the PHP files and commit them
             in the Git repository of the website. -->
        <p><a href="programm/samstag.php#session_XEYDFE">&#9668;&#9668; zurück zum Programm</a> </p>
        <h2 class='abstract-title'>QGIS für Einsteiger</h2>
        <section>
            <p>
                <span class='abstract-sessiontype'>Workshop</span> von                <span class='abstract-speakers'>Stephan Herritsch, Arne Schubert</span></p>
                <p class='abstract-is-workshop'>Bitte melden Sie sich im <a href="https://pretix.eu/fossgis/2020/">Ticketshop</a> für diesen Workshop an, wenn Sie daran teilnehmen möchten.</p>            <p><span class='abstract-time-heading'>Zeit: </span>Samstag 14. März 10:30 Uhr<br><span class='abstract-room-heading'>Ort: </span>Rahmenprogramm</p>

            
            <p>Was mit den topographischen Landesaufnahmen vor über 200 Jahren mit Stift und Papier auf Messtischen geschaffen wurde, wird heute am Computer mit Geographischen Informationssystemen (GIS) fortgeführt. Dieser Workshop führt in die Arbeit mit QGIS ein. Es wird Basiswissen für Einsteiger vermittelt, dabei wird auf Kartengrundlagen, Projektionen, sowie Vektor- und Rasterdaten eingegangen. Der Kurs richtet sich an Anfänger die keine bis wenig Erfahrung im Umgang mit GIS im allgemeinen und QGIS im speziellen haben und dies gerne erlernen, auffrischen oder einfach mal ausprobieren möchten.</p>
<p>Wie gewohnt wird es wieder Kursmaterial zum Mitnehmen geben.</p>
        </section>


	<?php include "../inc/footer.inc"; ?>

</body>

</html>