<!doctype html>
<html lang="de">

<head>
	<meta charset="utf-8">
<meta http-equiv="x-ua-compatible" content="ie=edge">
<meta name="description" content="Die FOSSGIS-Konferenz ist im D-A-CH Raum die führende Konferenz für Freie und Open Source Software für Geoinformationssysteme OpenStreetMap.">
<meta name="keywords" content="FOSSGIS, FOSSGIS-Konferenz, 2019, FOSSGIS-Konferenz 2019, Open Source, GIS, Konferenz, Geoinformatik, OpenStreetMap, HTW Dresden">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="apple-itunes-app" content="app-id=1453299630">

	<base href="/2020/sessions">
	<title>Aufbereitung von vektorbasierten Geodaten als Grundlage für Landnutzungsmodelle mit QGIS und PostGIS – FOSSGIS 2020</title>

	<link rel="stylesheet" href="./css/normalize.css">
	<link rel="stylesheet" href="./css/base.css">
	<link rel="stylesheet" href="./css/print.css" media="print">
</head>

<body id="programm">
	<header class="page-header">
	<a href="./" alt="FOSSGIS Konferenz 2020">
		<img class="page-logo" src="./img/fossgis2020-bollenhut.png">
	</a>
	<h1 class="page-title">
		FOSSGIS-Konferenz 2020<br>
		<span class="amp">Freiburg</span> <br>
		<span class="amp">11.&ndash;14. März</span>
	</h1>
</header>

<nav>
	<ul class="main">
		<li id="navHome">
			<a href="./">Startseite</a>
		</li>
		<!--<li id="navAnmeldung">
			<a href="./anmeldung/">Anmeldung</a>
		</li>-->
		<li id="navProgramm">
		<a href="./programm/">Programm</a>
		</li>
		<!--<li id="navAnreise">
			<a href="./anreise/">Anreise</a>
		</li>-->
		<li id="navStandort">
			<a href="./standort/">Standort</a>
		</li>
		<li id="navEvents">
			<a href="./socialevents/">Social Events</a>
		</li>
		<li id="navTeam">
			<a href="./loc/loc.php">Team</a>
		</li>
	</ul>
</nav>

<div class="hero">
	<figure>
		<img class="img-fluid" src="./img/freiburg.jpg" alt="Freiburg Luftbild">
		<figcaption>Photo: Pixaby</figcaption>
	</figure>
</div>

        <!-- This file was generated by a script. Do not edit this file in Git,
             edit contents in Pretalx, regenerate the PHP files and commit them
             in the Git repository of the website. -->
        <p><a href="programm/donnerstag.php#session_XNXHGP">&#9668;&#9668; zurück zum Programm</a> </p>
        <h2 class='abstract-title'>Aufbereitung von vektorbasierten Geodaten als Grundlage für Landnutzungsmodelle mit QGIS und PostGIS</h2>
        <section>
            <p>
                                <span class='abstract-speakers'>Mirko Blinn</span></p>
                            <p><span class='abstract-time-heading'>Zeit: </span>Donnerstag 12. März 09:30 Uhr<br><span class='abstract-room-heading'>Ort: </span>HS Rundbau</p>

                        <div class="video-container">
                <a href="https://media.ccc.de/v/fossgis2020-3103-aufbereitung-von-vektorbasierten-geodaten-als-grundlage-fr-landnutzungsmodelle-mit-qgis-und-postgis">
                    <img class="video-preview" src="video_previews/3103-hd.jpg" alt="Vorschaubild des Videos">
                    <div class="video-preview-overlay"></div>
                </a>
            </div>
                        
            <p>In den vergangenen Jahren hat die öffentliche Verfügbarkeit von vektorbasierten Geodaten stark zugenommen. Diese Daten decken unterschiedlichste Themengebiete in verschiedensten räumlichen und zeitlichen Auflösungen ab. 
Dieser Fundus an Daten zur Entwicklung von Landnutzungsmodellen wird kaum genutzt. Dabei können vektorbasierte Landnutzungsmodelle und die dafür aufbereiteten Eingangsdaten eine wertvolle Ergänzung zu den etablierten Instrumenten in allen Bereichen der räumlichen Planung darstellen. 
Am Beispiel aus dem Forschungsprojekt „Nachwuchs“ wird gezeigt, wie Daten aus unterschiedlichsten Quellen mit QGIS aufbereitet, in eine zentrale Postgis-Datenbank eingespeist und aus dieser, die für das Modell benötigten Informationen extrahiert werden und welche spannenden Informationen aus den Daten bereits während der Aufbereitung gewonnen werden können. 
Abschließend werden erste Ergebnisse eines Landnutzungsmodells auf Grundlage der gezeigten Daten vorgestellt und ein Ausblick auf die weitere Entwicklung gegeben. 
„Nachwuchs“ ist ein vom BMBF gefördertes Forschungsprojekt mit Ziel, für den westlichen Teil der Stadtregion Köln innovative, attraktive und zugleich flächensparende Siedlungsformen zu entwickeln, um mit dem massiven Bevölkerungsdruck aus Köln in nachhaltiger Art und Weise umzugehen.</p>
        </section>


	<footer>
	<ul class="main">
		<li>
			<a href="https://www.fossgis.de/impressum/">Impressum</a>
		</li>
		<li>
			<a href="./agb.php">AGB</a>
		</li>
		<li>
			<a href="https://www.fossgis.de/datenschutzerklärung">Datenschutzerklärung</a>
		</li>
	</ul>
</footer>

</body>

</html>