<!doctype html>
<html lang="de">

<head>
	<meta charset="utf-8">
<meta http-equiv="x-ua-compatible" content="ie=edge">
<meta name="description" content="Die FOSSGIS-Konferenz ist im D-A-CH Raum die führende Konferenz für Freie und Open Source Software für Geoinformationssysteme OpenStreetMap.">
<meta name="keywords" content="FOSSGIS, FOSSGIS-Konferenz, 2019, FOSSGIS-Konferenz 2019, Open Source, GIS, Konferenz, Geoinformatik, OpenStreetMap, HTW Dresden">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="apple-itunes-app" content="app-id=1453299630">

	<base href="/2020/sessions">
	<title>Ein einheitlicher Frontend-Ansatz, um mehrere Routing-Lösungen im WebGIS zu nutzen – FOSSGIS 2020</title>

	<link rel="stylesheet" href="./css/normalize.css">
	<link rel="stylesheet" href="./css/base.css">
	<link rel="stylesheet" href="./css/print.css" media="print">
</head>

<body id="programm">
	<header class="page-header">
	<a href="./" alt="FOSSGIS Konferenz 2020">
		<img class="page-logo" src="./img/fossgis2020-bollenhut.png">
	</a>
	<h1 class="page-title">
		FOSSGIS-Konferenz 2020<br>
		<span class="amp">Freiburg</span> <br>
		<span class="amp">11.&ndash;14. März</span>
	</h1>
</header>

<nav>
	<ul class="main">
		<li id="navHome">
			<a href="./">Startseite</a>
		</li>
		<!--<li id="navAnmeldung">
			<a href="./anmeldung/">Anmeldung</a>
		</li>-->
		<li id="navProgramm">
		<a href="./programm/">Programm</a>
		</li>
		<!--<li id="navAnreise">
			<a href="./anreise/">Anreise</a>
		</li>-->
		<li id="navStandort">
			<a href="./standort/">Standort</a>
		</li>
		<li id="navEvents">
			<a href="./socialevents/">Social Events</a>
		</li>
		<li id="navTeam">
			<a href="./loc/loc.php">Team</a>
		</li>
	</ul>
</nav>

<div class="hero">
	<figure>
		<img class="img-fluid" src="./img/freiburg.jpg" alt="Freiburg Luftbild">
		<figcaption>Photo: Pixaby</figcaption>
	</figure>
</div>

        <!-- This file was generated by a script. Do not edit this file in Git,
             edit contents in Pretalx, regenerate the PHP files and commit them
             in the Git repository of the website. -->
        <p><a href="programm/mittwoch.php#session_YBRH7D">&#9668;&#9668; zurück zum Programm</a> </p>
        <h2 class='abstract-title'>Ein einheitlicher Frontend-Ansatz, um mehrere Routing-Lösungen im WebGIS zu nutzen</h2>
        <section>
            <p>
                                <span class='abstract-speakers'>Robert Klemm</span></p>
                            <p><span class='abstract-time-heading'>Zeit: </span>Mittwoch 11. März 17:00 Uhr<br><span class='abstract-room-heading'>Ort: </span>HS Anatomie</p>

                        <div class="video-container">
                <a href="https://media.ccc.de/v/fossgis2020-3068-ein-einheitlicher-frontend-ansatz-um-mehrere-routing-lsungen-im-webgis-zu-nutzen">
                    <img class="video-preview" src="video_previews/3068-hd.jpg" alt="Vorschaubild des Videos">
                    <div class="video-preview-overlay"></div>
                </a>
            </div>
                        <p><a href="/2020/attachments/YBRH7D_fossgis_2020_Klemm_Routing_Mapbender_8CvdmJn.pdf">Vortragsfolien (PDF) </a></p>
            <p>In der Vergangenheit sind mehrere Routing-Lösungen unter der Open-Source-Lizenz entstanden, die auch in der OpenSource-Community weit verbreitet und im Einsatz sind. Ich möchte ein Lösungsansatz darstellen, wo über ein einheitliches Web-Frontend verschiedene Routing-Lösungen angesprochen und benutzt werden können. </p>
<p>Der Lösungsansatz wird am Beispiel von Mapbender durchgeführt und soll auch Nutzer ansprechen, die eine Routing-Lösung in ihren WebGis benutzen möchten, aber sich nicht mit der Installation und Programmierung von Routing-Lösungen herumschlagen möchten.</p>
<p>Im Vortrag werden die Anforderungen an das User-Interface erläutert und welche Unterschiede es zwischen den Routing-Lösungen gibt, die betrachtet und später in die Lösung einfließen.</p>
<p>Außerdem soll es den User ermöglicht werden, mit ein paar Klicks eine Routinglösung zu erstellen, Routing- und Visualisierungs-Einstellungen vorzunehmen und zu speichern, damit eine Routing-Anfrage an die Routinglösung gesendet werden und im WebGIS dargestellt werden kann.</p>
        <div class='abstract-bio'>
            <h3 class='abstract-bio-name'>Robert Klemm</h3>
            <p>Ich bin studierter Geoinformatiker und Kartograph und seit 2017 als GIS-Consultant und Entwickler bei der <a href="https://wheregroup.com">WhereGroup</a>  in Berlin tätig.</p>
<p>Ich weise Erfahrung mit PostgreSQL und PostGIS, Imposm, Mapnik, MapServer, GeoServer, QGIS, QGIS Server und Mapbender auf. Weiterhin in Apache, Solr, OpenLayers, MapProxy, OGC Standards, GraphHopper und  im Skripting.</p>
        </div>
        </section>


	<footer>
	<ul class="main">
		<li>
			<a href="https://www.fossgis.de/impressum/">Impressum</a>
		</li>
		<li>
			<a href="./agb.php">AGB</a>
		</li>
		<li>
			<a href="https://www.fossgis.de/datenschutzerklärung">Datenschutzerklärung</a>
		</li>
	</ul>
</footer>

</body>

</html>