<!doctype html>
<html lang="de">

<head>
	<?php include "../inc/meta.inc"; ?>

	<base href="<?php echo dirname($_SERVER['SCRIPT_NAME']); ?>">
	<title>Open-Source-GIS-Komponenten im radiologischen Notfall-Informationssystem des Bundes – FOSSGIS 2020</title>

	<link rel="stylesheet" href="./css/normalize.css">
	<link rel="stylesheet" href="./css/base.css">
	<link rel="stylesheet" href="./css/print.css" media="print">
</head>

<body id="programm">
	<?php include "../inc/header.inc"; ?>

        <!-- This file was generated by a script. Do not edit this file in Git,
             edit contents in Pretalx, regenerate the PHP files and commit them
             in the Git repository of the website. -->
        <p><a href="programm/freitag.php#session_YFEKKC">&#9668;&#9668; zurück zum Programm</a> </p>
        <h2 class='abstract-title'>Open-Source-GIS-Komponenten im radiologischen Notfall-Informationssystem des Bundes</h2>
        <section>
            <p>
                                <span class='abstract-speakers'>Marco Lechner</span></p>
                            <p><span class='abstract-time-heading'>Zeit: </span>Freitag 13. März 11:00 Uhr<br><span class='abstract-room-heading'>Ort: </span>HS Rundbau</p>

                        <div class="video-container">
                <a href="https://media.ccc.de/v/fossgis2020-3049-open-source-gis-komponenten-im-radiologischen-notfall-informationssystem-des-bundes">
                    <img class="video-preview" src="video_previews/3049-hd.jpg" alt="Vorschaubild des Videos">
                    <div class="video-preview-overlay"></div>
                </a>
            </div>
                        <p><a href="/2020/attachments/YFEKKC_fossgis_2020_Lechner_OpenSource_im_Notfalschutz_yNAFCeT.pdf">Vortragsfolien (PDF) </a></p>
            <p>Zu den Aufgabenbereichen des Bundesamtes für Strahlenschutz (BfS) gehört es, bei einem radiologischen Notfall, eigene und anderweitig verfügbare relevante Daten zu sammeln und zu erfassen, zu verarbeiten und zu bewerten sowie Dokumente zu erstellen, die die notwendigen Informationen enthalten, um den Krisenstab zu befähigen, über geeignete Maßnahmen des Notfallschutzes zu entscheiden. Der dabei eingesetzte Softwarestack wird unter der Bezeichnung IMIS (integriertes Mess- und Informationssystem) betrieben. Nach mehreren Jahren Entwicklungszeit wurde das bisherige proprietäre System (IMIS2) durch ein konsequent auf freien Komponenten und mit deutlicher Erweiterung um räumliche Funktionen und jetzt web-basierendes System ersetzt. Das neue IMIS3 wird von nun an bei der Bewältigung radiologischer Ereignisse und Notfälle vom radiologischen Lagezentrum des Bundes eingesetzt. Die bei der Neuentwicklung des IMIS3 konsequent eingesetzte Open-Source-Strategie kombiniert mehrere OSGeo-Projekte und hat einerseits einigen Input in diese Projekte geliefert und andererseits weitere Projekte neu entstehen lassen, die vom BfS unter der GPL auf github.com veröffentlicht wurden. Diese offensive Vorgehensweise ist für ein Bundesamt wohl eher ungewöhnlich.
Im Vortrag wird die Architektur des IMIS3 im Bezug auf die verwendeten Open-Source-GIS-Komponenten dargestellt. Diese enthält zum einen den aus OpenLayers und GeoExt aufgebauten generischen Web-GIS-Klienten des BfS. Aussehen, Inhalt und Funktionalität des Web-GIS wird über ein eigenes in Geonetwork OS gepflegtes Metadatenschema gesteuert. Die Generik des Klienten erlaubt es diesen auch für andere Fachbereiche mit vergleichbaren Datenstrukturen abseits des radiologischen Notfallschutzes einzusetzen. Die Machbarkeit einer solchen universellen Verwendung wird im WS 2019/2020 im Rahmen eines Studierendenprojekts an der Hochschule Karlsruhe geprüft und dessen Ergebnisse und Erfahrungen im Vortrag mit eingebaut. Zudem kommen bei IMIS3 noch PostGIS, Geostyler, Mapfish Print sowie diverse andere Projekte zum Einsatz, die das Gesamtsystem zur Bewältigung radiologischer Notfälle befähigt.</p>
        <div class='abstract-bio'>
            <h3 class='abstract-bio-name'>Marco Lechner</h3>
            <p>Marco Lechner arbeitet beim Bundesamt für Strahlenschutz im Fachgebiet Koordination Notfallschutzsysteme und koordiniert dabei die Software-Entwicklung des Integrierten Mess- und Informationssystems (IMIS). Dies beinhaltet zudem die Realisierung internationaler und nationaler Daten- und Dokumentenflüsse in heterogenen Strukturen sowie Fragen der Verfügbarkeit und Sicherheit der Systeme in einem Not- oder gar Katastrophenfall.</p>
        </div>
        </section>


	<?php include "../inc/footer.inc"; ?>

</body>

</html>