<!doctype html>
<html lang="de">

<head>
	<meta charset="utf-8">
<meta http-equiv="x-ua-compatible" content="ie=edge">
<meta name="description" content="Die FOSSGIS-Konferenz ist im D-A-CH Raum die führende Konferenz für Freie und Open Source Software für Geoinformationssysteme OpenStreetMap.">
<meta name="keywords" content="FOSSGIS, FOSSGIS-Konferenz, 2019, FOSSGIS-Konferenz 2019, Open Source, GIS, Konferenz, Geoinformatik, OpenStreetMap, HTW Dresden">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="apple-itunes-app" content="app-id=1453299630">

	<base href="/2020/sessions">
	<title>GeoStyler - Eine UI für alle* Stile – FOSSGIS 2020</title>

	<link rel="stylesheet" href="./css/normalize.css">
	<link rel="stylesheet" href="./css/base.css">
	<link rel="stylesheet" href="./css/print.css" media="print">
</head>

<body id="programm">
	<header class="page-header">
	<a href="./" alt="FOSSGIS Konferenz 2020">
		<img class="page-logo" src="./img/fossgis2020-bollenhut.png">
	</a>
	<h1 class="page-title">
		FOSSGIS-Konferenz 2020<br>
		<span class="amp">Freiburg</span> <br>
		<span class="amp">11.&ndash;14. März</span>
	</h1>
</header>

<nav>
	<ul class="main">
		<li id="navHome">
			<a href="./">Startseite</a>
		</li>
		<!--<li id="navAnmeldung">
			<a href="./anmeldung/">Anmeldung</a>
		</li>-->
		<li id="navProgramm">
		<a href="./programm/">Programm</a>
		</li>
		<!--<li id="navAnreise">
			<a href="./anreise/">Anreise</a>
		</li>-->
		<li id="navStandort">
			<a href="./standort/">Standort</a>
		</li>
		<li id="navEvents">
			<a href="./socialevents/">Social Events</a>
		</li>
		<li id="navTeam">
			<a href="./loc/loc.php">Team</a>
		</li>
	</ul>
</nav>

<div class="hero">
	<figure>
		<img class="img-fluid" src="./img/freiburg.jpg" alt="Freiburg Luftbild">
		<figcaption>Photo: Pixaby</figcaption>
	</figure>
</div>

        <!-- This file was generated by a script. Do not edit this file in Git,
             edit contents in Pretalx, regenerate the PHP files and commit them
             in the Git repository of the website. -->
        <p><a href="programm/donnerstag.php#session_YKAGHX">&#9668;&#9668; zurück zum Programm</a> </p>
        <h2 class='abstract-title'>GeoStyler - Eine UI für alle* Stile</h2>
        <section>
            <p>
                <span class='abstract-sessiontype'>Workshop</span> von                <span class='abstract-speakers'>Christian Mayer, Jan Suleiman</span></p>
                <p class='abstract-is-workshop'>Bitte melden Sie sich im <a href="https://pretix.eu/fossgis/2020/">Ticketshop</a> für diesen Workshop an, wenn Sie daran teilnehmen möchten.</p>            <p><span class='abstract-time-heading'>Zeit: </span>Donnerstag 12. März 13:30 Uhr<br><span class='abstract-room-heading'>Ort: </span>SR R-100</p>

                        
            <p>In diesem Workshop lernen Sie die ersten Schritte mit dem GeoStyler und bekommen einen
Einblick in die Möglichkeiten, die der GeoStyler mit seinen Komponenten bietet.</p>
<p>Der GeoStyler ist eine JavaScript Bibliothek, die ein anpassbares ReactJS basiertes User Interface zur Erstellung von
geographischen Stilinformationen auf Layer-Ebene bietet. Dies umfasst unter anderem
SLD, OpenLayers- und QGIS-Stile.</p>
<p>Die Teilnehmer des Workshops lernen anhand einfacher Beispiele wie der GeoStyler
und einzelne Komponenten nahtlos in existierende Webanwendungen integriert werden können oder als
Standalone Applikation verwendet werden kann. Die vorgefertigten Styling Komponenten ermöglichen so, auf einfache Art eigene WebGIS-Anwendungen zu erweitern und Nutzern das Styling von Geodaten über eine graphische Schnittstelle zu erlauben.</p>
<p>Im Rahmen des Workshops werden u.a. folgende Themen behandelt:</p>
<ul>
<li>Grundlegende Verwendung und Integration der UI-Komponenten</li>
<li>Komposition der Editoren</li>
<li>Erstellung eigener Komponenten</li>
<li>Automatisiertes Konvertieren verschiedener Stilformate</li>
</ul>
<p>Dieser Workshop richtet sich an (zukünftige) Entwickler von WebGIS-Anwendungen, die die Möglichkeit bieten sollen, Nutzern das Styling von Geodaten zu erlauben. 
Vorkenntnisse in JavaScript oder ReactJS sind hilfreich, aber nicht zwingend erforderlich.</p>
<p>Informationen</p>
<p>GeoStyler:</p>
<ul>
<li>Quellcode auf github: https://github.com/geostyler/geostyler</li>
<li>Online-Dokumentation: https://geostyler.github.io/geostyler/latest/index.html</li>
<li>Demo: https://www.geostyler.org</li>
</ul>
<p>react: https://reactjs.org/</p>
        <div class='abstract-bio'>
            <h3 class='abstract-bio-name'>Christian Mayer</h3>
            <ul>
<li>Dipl.-Ing. Geoinformatik &amp; Vermessung</li>
<li>Gründer <a href="https://meggsimum.de">meggsimum</a></li>
<li>Softwareentwickler &amp; -architekt</li>
<li>❤ Open Source (Geospatial)</li>
<li>OpenLayers, Wegue, GeoExt, Vue.js, GeoStyler, GeoServer, PostGIS...</li>
<li>Sprecher &amp; Trainer</li>
<li>national &amp; international</li>
<li>OSGeo Foundation Charter Member</li>
</ul>
        </div>
        <div class='abstract-bio'>
            <h3 class='abstract-bio-name'>Jan Suleiman</h3>
            <p>https://github.com/jansule</p>
        </div>
        </section>


	<footer>
	<ul class="main">
		<li>
			<a href="https://www.fossgis.de/impressum/">Impressum</a>
		</li>
		<li>
			<a href="./agb.php">AGB</a>
		</li>
		<li>
			<a href="https://www.fossgis.de/datenschutzerklärung">Datenschutzerklärung</a>
		</li>
	</ul>
</footer>

</body>

</html>
