<!doctype html>
<html lang="de">

<head>
	<meta charset="utf-8">
<meta http-equiv="x-ua-compatible" content="ie=edge">
<meta name="description" content="Die FOSSGIS-Konferenz ist im D-A-CH Raum die führende Konferenz für Freie und Open Source Software für Geoinformationssysteme OpenStreetMap.">
<meta name="keywords" content="FOSSGIS, FOSSGIS-Konferenz, 2019, FOSSGIS-Konferenz 2019, Open Source, GIS, Konferenz, Geoinformatik, OpenStreetMap, HTW Dresden">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="apple-itunes-app" content="app-id=1453299630">

	<base href="/2020/sessions">
	<title>Verbindungen schaffen mit PostgreSQL Foreign Data Wrappern – FOSSGIS 2020</title>

	<link rel="stylesheet" href="./css/normalize.css">
	<link rel="stylesheet" href="./css/base.css">
	<link rel="stylesheet" href="./css/print.css" media="print">
</head>

<body id="programm">
	<header class="page-header">
	<a href="./" alt="FOSSGIS Konferenz 2020">
		<img class="page-logo" src="./img/fossgis2020-bollenhut.png">
	</a>
	<h1 class="page-title">
		FOSSGIS-Konferenz 2020<br>
		<span class="amp">Freiburg</span> <br>
		<span class="amp">11.&ndash;14. März</span>
	</h1>
</header>

<nav>
	<ul class="main">
		<li id="navHome">
			<a href="./">Startseite</a>
		</li>
		<!--<li id="navAnmeldung">
			<a href="./anmeldung/">Anmeldung</a>
		</li>-->
		<li id="navProgramm">
		<a href="./programm/">Programm</a>
		</li>
		<!--<li id="navAnreise">
			<a href="./anreise/">Anreise</a>
		</li>-->
		<li id="navStandort">
			<a href="./standort/">Standort</a>
		</li>
		<li id="navEvents">
			<a href="./socialevents/">Social Events</a>
		</li>
		<li id="navTeam">
			<a href="./loc/loc.php">Team</a>
		</li>
	</ul>
</nav>

<div class="hero">
	<figure>
		<img class="img-fluid" src="./img/freiburg.jpg" alt="Freiburg Luftbild">
		<figcaption>Photo: Pixaby</figcaption>
	</figure>
</div>

        <!-- This file was generated by a script. Do not edit this file in Git,
             edit contents in Pretalx, regenerate the PHP files and commit them
             in the Git repository of the website. -->
        <p><a href="programm/donnerstag.php#session_ZP3JZZ">&#9668;&#9668; zurück zum Programm</a> </p>
        <h2 class='abstract-title'>Verbindungen schaffen mit PostgreSQL Foreign Data Wrappern</h2>
        <section>
            <p>
                                <span class='abstract-speakers'>Astrid Emde</span></p>
                            <p><span class='abstract-time-heading'>Zeit: </span>Donnerstag 12. März 14:00 Uhr<br><span class='abstract-room-heading'>Ort: </span>HS Anatomie</p>

                        <div class="video-container">
                <a href="https://media.ccc.de/v/fossgis2020-2996-verbindungen-schaffen-mit-postgresql-foreign-data-wrappern">
                    <img class="video-preview" src="video_previews/2996-hd.jpg" alt="Vorschaubild des Videos">
                    <div class="video-preview-overlay"></div>
                </a>
            </div>
            <p>Über Foreign Data Wrapper (FDW) kann aus der Datenbank heraus eine Verbindung zu anderen Datenquellen aufgebaut werden. Dadurch ist es nicht mehr notwendig, dass alle Daten, die in einem Projekt innerhalb der PostgreSQL-Datenbank verwendet werden sollen, sich auch in der Datenbank befinden müssen.</p>
<p>Foreign Data Wrapper bringen mehr Flexibilität durch den einfachen Zugriff auf verschiedenste Datenquellen. Die Möglichkeit, auch schreibend auf externe Quellen zuzugreifen, macht das Ganze noch attraktiver.</p>
<p>Mit unterschiedlichen Erweiterungen können Verbindungen von PostgreSQL zu Oracle, MySQL, CSV, JSON, Geodaten, OSM und vielen weite­ren Quellen geschaffen werden.</p>
<p>Das Konzept des datenbankübergreifenden Zugriffs ist nicht PostgreSQL spezifisch, sondern wurde im SQL/MED Standard (MED – Management of External Data) bereits 2008 definiert (https://wiki.postgresql.org/wiki/SQL/MED). </p>
<p>Foreign Data Wrappers wurden bisher nur in wenigen Softwareprodukten implementiert, darunter PostgreSQL, MariaDB und IBM/DB2. </p>
<p>Dieser Vortrag versucht mit einfachen Beispielen das Thema zu beleuchten.</p>
        <div class='abstract-bio'>
            <h3 class='abstract-bio-name'>Astrid Emde</h3>
            <p>Astrid Emde war bisher bei allen FOSSGIS-Konferenzen dabei und freut sich auf die FOSSGIS 2020 in Freiburg!</p>
<p>Sie befasst sich seit vielen Jahren mit Geodaten und FOSSGIS und hat schon zahlreiche Projekte vor allem im WebGIS-Bereich umgesetzt.</p>
<p>Sie weist Erfahrung mit PostgreSQL und PostGIS, MapServer, GeoServer, QGIS, QGIS Server und Mapbender auf. Weiterhin Apache Solr, OpenLayers, MapProxy, OGC Standards &amp; Skripting.</p>
<p>Astrid Emde arbeitet bei der <a href="https://wheregroup.com">WhereGroup</a> in Bonn und hat schon viele Workshops und Präsentationen zu Mapbender, MapServer, GeoServer, PostgreSQL/PostGIS, OWS oder allgemein zum Aufbau einer GDI gehalten. Sie ist Dozentin der [FOSS Academy] (https://www.foss-academy.com), dem Schulungsinstitut der WhereGroup (https://www.wheregroup.com)</p>
<p>Seit über 10 Jahren engagiert sie sich im <a href="https://mapbender.org">Mapbender</a>-Projekt und gehört zum Mapbender Team (http://mapbender.org) und dem Mapbender PSC (Project Steering Committee).</p>
<p>Astrid Emde ist in der <a href="https://osgeo.org">OSGeo</a> Foundation (http://osgeo.org) aktiv. Sie ist 2010 zum Charter Member und 2017 in das OSGeo Board of Directors (Vorstand der OSGeo) und zur OSGeo Secretary gewählt worden. Dadurch übernimmt sie zahlreiche Aufgaben bei der OSGeo und ist darüber hinaus im Bereich Marketing, Presse, Community Meetings und OSGeoLive (https://live.osgeo.org/) aktiv. 2018 erhielt sie für ihr Engagement den <a href="https://www.osgeo.org/community/awards/">Sol Katz Award der OSGeo</a>.</p>
<p>Auch im <a href="https://fossgis.de">FOSSGIS e.V.</a> ist Astrid Emde aktiv. Sie gehört zum Team der jährlich stattfindenden FOSSGIS-Konferenz, engagiert sich in der Vereins-Öffentlichkeitsarbeit und der Organisation von Community Events (https://fossgis.de).</p>
        </div>
        </section>


	<footer>
	<ul class="main">
		<li>
			<a href="https://www.fossgis.de/impressum/">Impressum</a>
		</li>
		<li>
			<a href="./agb.php">AGB</a>
		</li>
		<li>
			<a href="https://www.fossgis.de/datenschutzerklärung">Datenschutzerklärung</a>
		</li>
	</ul>
</footer>

</body>

</html>
