<!doctype html>
<html lang="de">

<head>
	<meta charset="utf-8">
<meta http-equiv="x-ua-compatible" content="ie=edge">
<meta name="description" content="Die FOSSGIS-Konferenz ist im D-A-CH Raum die führende Konferenz für Freie und Open Source Software für Geoinformationssysteme OpenStreetMap.">
<meta name="keywords" content="FOSSGIS, FOSSGIS-Konferenz, 2019, FOSSGIS-Konferenz 2019, Open Source, GIS, Konferenz, Geoinformatik, OpenStreetMap, HTW Dresden">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="apple-itunes-app" content="app-id=1453299630">

	<base href="/2020/sessions">
	<title>Visualisierung und Analyse von Satellitenbildern mit der EnMAP-Box – FOSSGIS 2020</title>

	<link rel="stylesheet" href="./css/normalize.css">
	<link rel="stylesheet" href="./css/base.css">
	<link rel="stylesheet" href="./css/print.css" media="print">
</head>

<body id="programm">
	<header class="page-header">
	<a href="./" alt="FOSSGIS Konferenz 2020">
		<img class="page-logo" src="./img/fossgis2020-bollenhut.png">
	</a>
	<h1 class="page-title">
		FOSSGIS-Konferenz 2020<br>
		<span class="amp">Freiburg</span> <br>
		<span class="amp">11.&ndash;14. März</span>
	</h1>
</header>

<nav>
	<ul class="main">
		<li id="navHome">
			<a href="./">Startseite</a>
		</li>
		<!--<li id="navAnmeldung">
			<a href="./anmeldung/">Anmeldung</a>
		</li>-->
		<li id="navProgramm">
		<a href="./programm/">Programm</a>
		</li>
		<!--<li id="navAnreise">
			<a href="./anreise/">Anreise</a>
		</li>-->
		<li id="navStandort">
			<a href="./standort/">Standort</a>
		</li>
		<li id="navEvents">
			<a href="./socialevents/">Social Events</a>
		</li>
		<li id="navTeam">
			<a href="./loc/loc.php">Team</a>
		</li>
	</ul>
</nav>

<div class="hero">
	<figure>
		<img class="img-fluid" src="./img/freiburg.jpg" alt="Freiburg Luftbild">
		<figcaption>Photo: Pixaby</figcaption>
	</figure>
</div>

        <!-- This file was generated by a script. Do not edit this file in Git,
             edit contents in Pretalx, regenerate the PHP files and commit them
             in the Git repository of the website. -->
        <p><a href="programm/donnerstag.php#session_ZXTALA">&#9668;&#9668; zurück zum Programm</a> </p>
        <h2 class='abstract-title'>Visualisierung und Analyse von Satellitenbildern mit der EnMAP-Box</h2>
        <section>
            <p>
                <span class='abstract-sessiontype'>Demo-Session</span> von                <span class='abstract-speakers'>Andreas Rabe</span></p>
                            <p><span class='abstract-time-heading'>Zeit: </span>Donnerstag 12. März 09:00 Uhr<br><span class='abstract-room-heading'>Ort: </span>HS Anatomie</p>

                        <div class="video-container">
                <a href="https://media.ccc.de/v/fossgis2020-3107-visualisierung-und-analyse-von-satellitenbildern-mit-der-enmap-box">
                    <img class="video-preview" src="video_previews/3107-hd.jpg" alt="Vorschaubild des Videos">
                    <div class="video-preview-overlay"></div>
                </a>
            </div>
                        
            <p>Erdbeobachtungsdaten stellen eine immer wichtigere Grundlage für raumbezogene Analysen in Wirtschaft und Wissenschaft dar. Gleichzeitig steigt ihre Verfügbarkeit infolge neuer Fernerkundungssatelliten und offener Datenzugangsrichtlinien stetig an. Erdbeobachtungsprogramme wie das europäische Copernicus der ESA und das amerikanische Landsat der NASA/USGS erfassen multispektrale Fernerkundungsdaten flächendeckend weltweit und mit hoher zeitlicher Dichte. Komplementär dazu liefern hyperspektrale Satellitenmissionen, wie die deutsche EnMAP Mission (www.enmap.org), Daten mit hoher spektraler Auflösung.</p>
<p>Diese Entwicklung hat auch die Nachfrage nach freier und quelloffener Software zur Analyse großer und mehrdimensionaler Rasterdatenmengen in Kombination mit anderen GIS-Daten erhöht. Da die Anforderungen einer professionellen Fernerkundungsanalyse oft über die Möglichkeiten klassischer GIS-Software hinausgehen, entwickelt die Humboldt-Universität zu Berlin seit mehr als 10 Jahren die EnMAP-Box, die seit 2019 als QGIS Plugin zur Verfügung steht. </p>
<p>In der Demo-Session werden die EnMAP-Box und ihre Möglichkeiten anhand der folgenden Themen vorgestellt:</p>
<p>•   Multi- und Hyperspektrale Daten: was ist das? </p>
<p>•   Wo bekomme ich Landsat oder Sentinel Daten her, und wie kann ich sie sinnvoll visualisieren?</p>
<p>•   Kunstrasen, Wiese, Wald, Asphalt: Spektrale Eigenschaften unterschiedlicher Oberflächen und Landbedeckungen</p>
<p>•   Erstellung und Verwalten von Spektralbibliotheken: in situ, im Bild oder im Labor: wo kommen meine Spektren her? </p>
<p>•   Maschinelles Lernen einfach: Erstellung einer Landnutzungskarte mittels Random Forest oder Support Vector Machines Classification</p>
<p>•   Automatisieren einer Prozessierungskette mit Hilfe des QGIS Processing Frameworks: so einfach lassen sich EnMAP-Box Algorithmen zu einem Workflow kombinieren</p>
<p>•   EnMAP-Box für Programmierer: Möglichkeiten der EnMAP-Box Python API</p>
<p>Referenzen:
https://enmap-box.readthedocs.io
http://www.enmap.org</p>
<p>The EnMAP-Box project is part of the EnMAP Core Science Team activities (www.enmap.org), funded by the German Aerospace Center (DLR) and granted by the Federal Ministry of Economic Affairs and Energy (BMWi, grant no. 50EE1529).</p>
        </section>


	<footer>
	<ul class="main">
		<li>
			<a href="https://www.fossgis.de/impressum/">Impressum</a>
		</li>
		<li>
			<a href="./agb.php">AGB</a>
		</li>
		<li>
			<a href="https://www.fossgis.de/datenschutzerklärung">Datenschutzerklärung</a>
		</li>
	</ul>
</footer>

</body>

</html>