<header class="page-header">
	<a href="./" alt="FOSSGIS Konferenz 2027">
		<img class="page-logo" src="./img/fossgis-logo-2027.png">
	</a>
	<h2 class="page-title">
		FOSSGIS-Konferenz <br>
		<span class="amp">Heidelberg</span> <br>
		<span class="main">9.–13. März 2027</span>
	</h2>
</header>

<nav>
	<ul class="main">
		<li id="navHome">
			<a href="./">Startseite</a>
		</li>
<!-- 		<li id="navCall">
		<a href="./callforpapers/">Call for Participation</a>
		</li>-->
		<li id="navProgramm">
		<a href="./programm/">Programm</a>
		</li>
<!--		<li id="navEvents">
			<a href="./socialevents/">Rahmenprogramm</a>
		</li>
		<li id="navAnmeldung">
			<a href="./anmeldung/">Anmeldung</a>
		</li> -->
		<li id="navAnreise">
			<a href="./standort/">Standort</a>
		</li> 
		<li id="navhelfen">
			<a href="./helfen/">Helfen</a>
		</li>
<!--		<li id="navTeam">
			<a href="./team/team.php">Team</a>
		</li>
		<!--	<li id="navExpo">
			<a href="./expo/">Expo</a>
		</li>-->
	</ul>
</nav>

<div class="hero">
	<figure>
		<img class="img-fluid" src="./img/heigit-audimax_201_1_HP.jpg" width="880" height="350"  alt="wo ist das Bild!">
		<figcaption><b>Foto: Uni Heidelberg</b></figcaption>
	</figure>
</div>
