<meta charset="utf-8">
<meta http-equiv="x-ua-compatible" content="ie=edge">
<meta name="description" content="Die FOSSGIS-Konferenz ist im D-A-CH Raum die führende Konferenz für Freie und Open Source Software für Geoinformationssysteme OpenStreetMap.">
<meta name="keywords" content="FOSSGIS, FOSSGIS-Konferenz, 2023, 2024, 2025, FOSSGIS-Konferenz 2023, FOSSGIS-Konferenz 2024, FOSSGIS-Konferenz 2025, FOSSGIS-Konferenz 2026, FOSSGIS-Konferenz 2027, Hamburg, Münster, Göttingen, Heidelberg, Universität Münster, Institut für Geoinformatik Münster (ifgi), Schloss Münster, Universität Göttingen, Geographisches Institut Uni Göttingen, Universiät Heidelberg, HeiGIT gGmbH, Open Source, GIS, Konferenz, Geoinformatik, OpenStreetMap, OSM, Digitale Souveränität, DS, Call for Participation, Call for Papers, Call for Participation, Online-Event, Hybridevent, Venueless">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="apple-itunes-app" content="app-id=1453299630">
