<header class="page-header">
	<a href="./" alt="FOSSGIS Konferenz 2023">
		<img class="page-logo" src="./img/Stardortlogo_FOSSGIS2023_300dpi.png">
	</a>
	<h2 class="page-title">
		FOSSGIS-Konferenz <br>
		<span class="amp">Berlin</span> <br>
		<span class="main">15. - 18. März 2023</span>
	</h2>
</header>

<nav>
	<ul class="main">
		<li id="navHome">
			<a href="./">Startseite</a>
		</li>
		<!--<li id="navCall">
		<a href="./callforpapers/">Call for Participation</a>
		</li>-->
		<li id="navProgramm">
		<a href="./programm/">Programm</a>
		</li>
		<li id="navAnreise">
			<a href="./standort_anreise/">Standort und Anreise</a>
		</li>
		<li id="navEvents">
			<a href="./socialevents/">Rahmenprogramm</a>
		</li>
		<li id="navAnmeldung">
			<a href="./anmeldung/">Anmeldung</a>
		</li>
		<li id="navhelfen">
			<a href="./helfen/">Helfen</a>
		</li>		
		<li id="navTeam">
			<a href="./team/team.php">Team</a>
		</li>
		<!--	<li id="navExpo">
			<a href="./expo/">Expo</a>
		</li>-->
	</ul>
</nav>

<div class="hero">
	<figure>
		<img class="img-fluid" src="./img/Berliner_Fernsehturm_Adenie.abubakar_ccbysa_ohneSchrift.jpg" alt="Berliner Fernsehturm">
		<figcaption><b>Photo: Adenie.abubakar, CC BY-SA 4.0</b></figcaption>
	</figure>
</div>
