<meta charset="utf-8">
<meta http-equiv="x-ua-compatible" content="ie=edge">
<meta name="description" content="Die FOSSGIS-Konferenz ist im D-A-CH Raum die führende Konferenz für Freie und Open Source Software für Geoinformationssysteme OpenStreetMap.">
<meta name="keywords" content="FOSSGIS, FOSSGIS-Konferenz, 2023, FOSSGIS-Konferenz 2023, Open Source, GIS, Konferenz, Geoinformatik, OpenStreetMap, Humboldt-Universität zu Berlin, HU-Berlin, , Online-Event, Hybridevent, Venueless, Workadventure, Netzwerkwelt">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="apple-itunes-app" content="app-id=1453299630">
