<header class="page-header">
	<a href="./" alt="FOSSGIS Konferenz 2025">
		<img class="page-logo" src="./img/fossgis26-logo.png">
	</a>
	<h2 class="page-title">
		FOSSGIS-Konferenz <br>
		<span class="amp">Göttingen</span> <br>
		<span class="main">25.–28. März 2026</span>
	</h2>
</header>

<nav>
	<ul class="main">
		<li id="navHome">
			<a href="./">Startseite</a>
		</li>
<!-- 		<li id="navCall">
		<a href="./callforpapers/">Call for Participation</a>
		</li>
		<li id="navProgramm">
		<a href="./programm/">Programm</a>
		</li>
		<li id="navEvents">
			<a href="./socialevents/">Rahmenprogramm</a>
		</li>
		<li id="navAnmeldung">
			<a href="./anmeldung/">Anmeldung</a>
		</li>
		<li id="navAnreise">
			<a href="./standort_anreise/">Standort und Anreise</a>
			<a href="./standort/">Standort</a>
		</li>
		<li id="navhelfen">
			<a href="./helfen/">Helfen</a>
		</li>		
		<li id="navTeam">
			<a href="./team/team.php">Team</a>
		</li>
		<!--	<li id="navExpo">
			<a href="./expo/">Expo</a>
		</li>-->
	</ul>
</nav>

<div class="hero">
	<figure>
		<img class="img-fluid" src="./img/Vorschlag_Titelbild_Maik.jpg" width="880" height="350"  alt="wo ist das Bild!">
		<figcaption><b>Foto: pantherstrix</b></figcaption>
	</figure>
</div>
