<ul id="progNav">
    <li id="prog">
        <a href="/2016/programm/">Übersicht</a>
    </li>
    <li id="prog">
        <a href="/2016/programm/programm.php?day=1">Sonntag</a>
    </li>
    <li id="prog">
        <a href="/2016/programm/programm.php?day=2">Montag</a>
    </li>
    <li id="prog">
        <a href="/2016/programm/programm.php?day=3">Dienstag</a>
    </li>
    <li id="prog">
        <a href="/2016/programm/programm.php?day=4">Mittwoch</a>
    </li>
    <li id="prog">
        <a href="/2016/programm/referenten.php">Referenten</a>
    </li>
    <!-- li id="prog">
        <a href="https://frab.fossgis-konferenz.de/de/2016/public/schedule" target="_blank">Programmseite</a>
    </li -->
</ul>
