<ul id="progNav">
    <li id="prog">
        <a href="/2016/programm/">Übersicht</a>
    </li>
    <li id="prog">
        <a href="/2016/programm/day1.php">Sonntag</a>
    </li>
    <li id="prog">
        <a href="/2016/programm/day2.php">Montag</a>
    </li>
    <li id="prog">
        <a href="/2016/programm/day3.php">Dienstag</a>
    </li>
    <li id="prog">
        <a href="/2016/programm/day4.php">Mittwoch</a>
    </li>
    <li id="prog">
        <a href="/2016/programm/referenten.php">Referenten</a>
    </li>
</ul>
