<header class="page-header">
	<a href="./" alt="FOSSGIS Konferenz 2022">
		<img class="page-logo" src="./img/Logo_Triangulation_online.png">
	</a>
	<h2 class="page-title">
		FOSSGIS-Konferenz <br>
		<span class="amp">Online-Event</span> <br>
		<span class="main">9. - 12. März 2022</span>
	</h2>
</header>

<nav>
	<ul class="main">
		<li id="navHome">
			<a href="./">Startseite</a>
		</li>
		<!--<li id="navCall">
		<a href="./callforpapers/">Call for Participation</a>
		</li>-->
		<li id="navAnmeldung">
			<a href="./anmeldung/">Anmeldung</a>
		</li>
		<li id="navProgramm">
		<a href="./programm/">Programm</a>
		</li>
		<li id="navEvents">
			<a href="./socialevents/">Rahmenprogramm</a>
		</li>
		
		<!--<li id="navAnreise">
			<a href="./standort/">Standort und Anreise</a>
		</li>-->
		<li id="navhelfen">
			<a href="./helfen/">Helfen</a>
		</li>		
		<!--	<li id="navExpo">
			<a href="./expo/">Expo</a>
		</li>-->
		<li id="navTeam">
			<a href="./loc/loc.php">Team</a>
		</li>
	</ul>
</nav>

<div class="hero">
	<figure>
		<img class="img-fluid" src="./img/stadtansicht_marburg_c_markus_farnung.png" alt="Stadtansicht Marburg">
		<figcaption><b>Photo: (C) by Markus Farnung</b></figcaption>
	</figure>
</div>
