<?php

define("JAHR","2017");
define("BASIS_URL","https://frab.fossgis-konferenz.de");
define("CONF_URL","https://frab.fossgis-konferenz.de/de/2017/public/schedule.json");
define("JSON_SPEAKERS","https://frab.fossgis-konferenz.de/de/2017/public/speakers.json");
define("YT_URL","https://tracker.c3voc.de/api/v1/fossgis17/tickets/released.json");
define("YT_PLAYLIST","https://www.youtube.com/playlist?list=PLTli5-lbeoibm_kIG8rk-6XIffh6HfM7r");		// noch 2016
define("VID_URL","http://ftp5.gwdg.de/pub/misc/openstreetmap/FOSSGIS2016/");							// noch 2016
define("FRAB_EVENT_URL", "https://frab.fossgis-konferenz.de/de/2017/public/events/");
define("FRAB_PERSON_URL","https://frab.fossgis-konferenz.de/de/2017/public/speakers/");
define("LOGO_PATH","https://fossgis-konferenz.de/2017/img/fossgis-konferenz-2017.png");

define("ID_LEN", 6);
define("TIT_LEN", 60);
define("SUB_LEN", 60);
define("DESC_LEN", 200);
define("TIT_SHORT", 20);
define("SUB_SHORT", 20);
define("DESC_SHORT", 20);
define("PERS_LEN", 20);
define("YT_LEN", 11);
define("RAUM_LEN", 10);

define("HIDDEN_IDS", "||9999|");	// 5105 ist der Sektempfang
define("HIDDEN_ROOMS", "||Versteckter Hörsaal|");
  // || am Anfang, damit die matches immer >0 sind


?>
