<ul id="mainNav">
    <li id="navHome">
        <a href="/2017/">Startseite</a>
    </li>
     <li id="navProgramm">
        <a href="/2017/programm">Programm</a>
	</li>	
	 <li id="navAnmeldung">
        <a href="/2017/anmeldung">Anmeldung</a>
    </li>
	<li id="navAnreise">
        <a href="/2017/anreise">Anreise + Unterkunft</a>
    </li>
   <li id="navEvents">
        <a href="/2017/socialevents">Social Events</a>
    </li>
<!--
    <li id="navGreen">
        <a href="/2017/green">Green</a>
    </li>
 -->
</ul>
