<ul id="mainNav">
    <li id="navHome">
        <a href="/2016/">Startseite</a>
    </li>

    <li id="navAnmeldung">
        <a href="/2016/anmeldung">Anmeldung</a>
    </li>

    <li id="navAnreise">
        <a href="/2016/anreise">Anreise + Unterkunft</a>
    </li>

    <li id="navEvents">
        <a href="/2016/socialevents">Social Events</a>
    </li>

    <li id="navGreen">
        <a href="/2016/green">Green</a>
    </li>

</ul>
