<ul id="mainNav">
    <li id="navHome">
        <a href="/2016/">Startseite</a>
    </li>

<!--     <li>
        <a href="http://frab.fossgis-konferenz.de/de/2016/cfp/session/new">Beitrag einreichen</a>
    </li>

    <li id="navAnreise">
        <a href="/2016/anreise">Anreise + Unterkunft</a>
    </li>

    <li id="navEvents">
        <a href="/2016/socialevents">Social Events</a>
    </li> -->
</ul>
