                 <ul id="mainNav">
                    <li id="navHome">
                        <a href="/fossgis/index.php">Startseite</a>
                    </li>
					<li id="navCall">
                        <a href="/fossgis/callforpapers/index.php">Call for Papers</a>
                    </li>
					
                    <!--<li>
                        <a href="/fossgis/programm/">Programm</a>
                    </li>
					
                    <li>
                        <a href="https://www.fossgis.de/civicrm/event/register?id=2&reset=1">Anmeldung</a>
                    </li>
					<li id="navSocial">
                        <a href="/fossgis/socialevents/index.php">Social Events</a>
                    </li>
					<li id="navAnreise">
                        <a href="/fossgis/anreise/index.php">Anreise & Unterkunft</a>
                    </li>-->
					<li class="twitter">
						Folgen sie uns auf <a class="twLink" href="http://twitter.com/fossgis2013">Twitter</a>
						Hashtag: <a href="https://twitter.com/#!/search?q=%23fossgis2013">#fossgis2013</a>
					</li>
                </ul>