<header class="page-header">
	<a href="./" alt="FOSSGIS Konferenz 2024">
		<img class="page-logo" src="./img/fossgis24-logo_oR.png">
	</a>
	<h2 class="page-title">
		FOSSGIS-Konferenz <br>
		<span class="amp">Hamburg</span> <br>
		<span class="main">20. - 23. März 2024</span>
	</h2>
</header>

<nav>
	<ul class="main">
		<li id="navHome">
			<a href="./">Startseite</a>
		</li>
 		<!--<li id="navCall">
		<a href="./callforpapers/">Call for Participation</a>
		</li>-->
		<li id="navProgramm">
		<a href="./programm/">Programm</a>
		</li>
		<!--<li id="navAnreise">
			<a href="./standort_anreise/">Standort und Anreise</a>
		</li>
		<li id="navEvents">
			<a href="./socialevents/">Rahmenprogramm</a>
		</li>
		<li id="navAnmeldung">
			<a href="./anmeldung/">Anmeldung</a>
		</li>-->
		<li id="navhelfen">
			<a href="./helfen/">Helfen</a>
		</li>		
<!--	<li id="navTeam">
			<a href="./team/team.php">Team</a>
		</li>
		<!--	<li id="navExpo">
			<a href="./expo/">Expo</a>
		</li>-->
	</ul>
</nav>

<div class="hero">
	<figure>
		<img class="img-fluid" src="./img/Hauke_HH_06.jpeg" alt="wir brauchen noch ein Bild!">
		<figcaption><b>Foto: Hauke Stieler</b></figcaption>
	</figure>
</div>
