<ul id="mainNav">
    <li id="navHome"><a href="/2018/">Startseite</a></li>
    <li id="navProgramm"><a href="/2018/programm">Programm</a></li>
    <li id="navAnreise"><a href="/2018/anreise">Anreise</a></li>
    <li id="navEvents"><a href="/2018/socialevents">Social Events</a></li>
    <li id="navTeam"><a href="/2018/loc/loc.php">Das Team</a></li>
    <li id="navGallery"><a href="/2018/gallery">Bilder</a></li>
</ul>
