                 <ul id="mainNav">
                    <li id="navHome">
                        <a href="/2015/">Startseite</a>
                    </li>

                    <li>
                        <a href="/2015/programm/">Programm</a>
                    </li>

                    <!-- <li id="navCall">
                        <a href="/2015/callforpapers">Call for Papers</a>
                    </li>

                    <li>
                        <a href="http://pb.konferenz.de/submission/FOSSGIS2015">Beitrag einreichen</a>
                    </li> -->
                    </li>

                    <li id="navAnreise">
                        <a href="/2015/anreise">Anreise + Unterkunft</a>
                    </li>

                    <li id="navEvents">
                        <a href="/2015/socialevents">Social Events</a>
                    </li>



                </ul>
