                 <ul id="mainNav">
                    <li id="navHome">
                        <a href="/konferenz/2015/">Startseite</a>
                    </li>

                    <li id="navCall">
                        <a href="/konferenz/2015/callforpapers/">Call for Papers</a>
                    </li>

                    <li>
                        <a href="http://pb.fossgis.de/submission/FOSSGIS2015">Beitrag einreichen</a>
                    </li>

                    <li>
                        <a href="/konferenz/2015/anreise">Anreise + Unterkunft</a>
                    </li>
                </ul>
