                 <ul id="mainNav">
                    <li id="navHome">
                        <a href="/konferenz/2015/">Startseite</a>
                    </li>

                    <!-- <li id="navCall">
                        <a href="/konferenz/2015/callforpapers/">Call for Papers</a>
                    </li>

                    <li>
                        <a href="http://pb.konferenz.de/submission/FOSSGIS2015">Beitrag einreichen</a>
                    </li> -->

                    <li>
                        <a href="https://www.fossgis.de/civicrm/event/info?reset=1&id=5">Anmeldung</a>
                    </li>

                    <li id="navAnreise">
                        <a href="/konferenz/2015/anreise">Anreise + Unterkunft</a>
                    </li>

                    <li id="navEvents">
                        <a href="/konferenz/2015/socialevents">Social Events</a>
                    </li>



                </ul>
