                 <ul id="mainNav">
                    <li id="navHome">
                        <a href="/fossgis/2014/">Startseite</a>
                    </li>
					
					<li>
                        <a href="http://www.fossgis.de/konferenz/2014/programm/">Programm</a>
                    </li>

                    <li>
                        <a href="https://www.fossgis.de/civicrm/event/info?id=4&reset=1">Anmeldung</a>
                    </li>

                    <li id="navAnreise">
                        <a href="/fossgis/2014/anreise">Anreise/Unterkunft</a>
                    </li>
                </ul>