                 <ul id="mainNav">
                    <li id="navHome">
                        <a href="/fossgis/2013/">Startseite</a>
                    </li>
					
                    <li>
                        <a href="http://www.fossgis.de/konferenz/2013/programm/">Programm</a>
                    </li>
					
                    <li>
                        <a href="https://www.fossgis.de/civicrm/event/info?id=3&reset=1">Anmeldung</a>
                    </li>
					<li id="navSocial">
                        <a href="/fossgis/2013/socialevents/">Social Events</a>
                    </li>
					<li id="navAnreise">
                        <a href="/fossgis/2013/anreise/">Anreise &amp; Unterkunft</a>
                    </li>
					<li class="twitter">
						Folgen sie uns auf <a class="twLink" href="http://twitter.com/fossgis2013">Twitter</a>
						Hashtag: <a href="https://twitter.com/#!/search?q=%23fossgis2013">#fossgis2013</a>

					</li>
                </ul>