                 <ul id="mainNav">
                    <img src="img/Fossgis14-logo.png" width="247" height="247">
                    <!--<li id="navHome">
                        <a href="/fossgis/2013/">Startseite</a>
                    </li>
					
                    <li>
                        <a href="http://www.fossgis.de/konferenz/2013/programm/">Programm</a>
                    </li>
					
                    <li>
                        <a href="https://www.fossgis.de/civicrm/event/info?id=3&reset=1">Anmeldung</a>
                    </li>
					<li id="navSocial">
                        <a href="/fossgis/2013/socialevents/">Social Events</a>
                    </li>
					<li id="navAnreise">
                        <a href="/fossgis/2013/anreise/">Anreise &amp; Unterkunft</a>
                    </li>
					<li class="twitter">
						Folgen sie uns auf <a class="twLink" href="http://twitter.com/fossgis2013">Twitter</a>
						Hashtag: <a href="https://twitter.com/#!/search?q=%23fossgis2013">#fossgis2013</a>

                        <a class="twitter-timeline" href="https://twitter.com/search?q=fossgis2013" data-widget-id="319385367851696128" data-chrome="noheader nofooter" height="500">Tweets über "fossgis2013"</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>

					</li>-->
                </ul>