<ul id="mainNav">
    <li id="navHome">
        <a href=".">Startseite</a>
    </li>
    <li>
                        <a href="programm/">Programm</a>
                    </li>
                    <li id="navSocial">
                        <a href="socialevents/">Social Events</a>
                    </li>
                    <li id="navAnreise">
                        <a href="anreise/">Anreise &amp; Unterkunft</a>
                    </li>
                    <li><a href="http://www.fossgis.de/impressum.html">Impressum</a></li>
                    <li class="twitter">
                      Folgen sie uns auf <a class="twLink" href="http://twitter.com/fossgis2013">Twitter</a>
                      Hashtag: <a href="https://twitter.com/#!/search?q=%23fossgis2013">#fossgis2013</a>

                      <a class="twitter-timeline" href="https://twitter.com/search?q=fossgis2013" data-widget-id="319385367851696128" data-chrome="noheader nofooter" height="500">Tweets über "fossgis2013"</a>
                      <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>

                  </li>
              </ul>