<header class="page-header">
	<a href="./" alt="FOSSGIS Konferenz 2019">
		<img class="page-logo" src="./img/fossgis19-logo.png">
	</a>
	<h1 class="page-title">
		FOSSGIS-Konferenz 2019<br>
		<span class="amp">Dresden</span><br>
		<span class="amp">13.&ndash;16. März 2019</span>
	</h1>
</header>

<nav>
	<ul class="main">
		<li id="navHome">
			<a href="./">Startseite</a>
		</li>
		<!--<li id="navAnmeldung">
			<a href="./anmeldung/">Anmeldung</a>
		</li>-->
		<li id="navProgramm">
		<a href="./programm/">Programm</a>
		</li>
		<li id="navAnreise">
			<a href="./anreise/">Anreise</a>
		</li>
		<li id="navStandort">
			<a href="./standort/">Standort</a>
		</li>
		<li id="navEvents">
			<a href="./socialevents/">Social Events</a>
		</li>
		<li id="navTeam">
			<a href="./loc/loc.php">Team</a>
		</li>
	</ul>
</nav>

<div class="hero">
	<figure>
		<img class="img-fluid" src="./img/dresden.jpg" alt="Dresden Panorama">
		<figcaption>Photo: Kolossos</figcaption>
	</figure>
</div>
