<ul id="mainNav">
    <li id="navHome">
        <a href="/2019/">Startseite</a>
    </li>
	<li id="navAnreise">
		<a href="/2019/anreise">Anreise</a>
	</li>
	<li id="navCall">
        <a href="/2019/callforpapers">Call for Papers</a>
    </li>

<!--
    <li id="navProgramm">
        <a href="/2018/programm">Programm</a>
    </li>
	<li id="navAnmeldung">
        <a href="/2018/anmeldung">Anmeldung</a>
    </li>
	<li id="navEvents">
          <a href="/2018/socialevents">Social Events</a>
    </li>
-->    
    <li id="navEvents">
          <a href="/2019/loc/loc.php">Das Team</a>
    </li>

</ul>
