<ul id="progNav">
    <li id="prog">
        <a href="/2017/programm/">Übersicht</a>
    </li>
    <li id="prog">
        <a href="/2017/programm/day1.php">Mittwoch</a>
    </li>
    <li id="prog">
        <a href="/2017/programm/day2.php">Donnerstag</a>
    </li>
    <li id="prog">
        <a href="/2017/programm/day3.php">Freitag</a>
    </li>
    <li id="prog">
        <a href="/2017/programm/referenten.php">Referenten</a>
    </li>
</ul>
