<ul id="progNav">
    <li id="prog">
        <a href="/2017/programm/">Übersicht</a>
    </li>
    <li id="prog">
        <a href="/2017/programm/programm.php?day=1">Mittwoch</a>
    </li>
    <li id="prog">
        <a href="/2017/programm/programm.php?day=2">Donnerstag</a>
    </li>
    <li id="prog">
        <a href="/2017/programm/programm.php?day=3">Freitag</a>
    </li>
    <li id="prog">
        <a href="/2017/programm/referenten.php">Referenten</a>
    </li>
</ul>
