<ul id="progNav">
    <li id="prog">
        <a href="/2017/programm/">Übersicht</a>
    </li>
    <li id="prog">
        <a href="/2017/programm/programm.php?day=0">Mittwoch</a>
    </li>
    <li id="prog">
        <a href="/2017/programm/programm.php?day=1">Donnerstag</a>
    </li>
    <li id="prog">
        <a href="/2017/programm/programm.php?day=2">Freitag</a>
    </li>
    <li id="prog">
        <a href="/2017/programm/programm.php?day=3">Samstag</a>
    </li>
    <li id="prog">
        <a href="https://frab.fossgis-konferenz.de/de/2017/public/schedule" target="_blank">Programmseite</a>
    </li>
</ul>
