<header class="page-header">
	<a href="./" alt="FOSSGIS Konferenz 2021">
		<img class="page-logo" src="./img/FOSSGIS Konferenz Logo 2021_BGw.png">
	</a>
	<h2 class="page-title">
		FOSSGIS-Konferenz <br>
		<span class="amp">Online-Event</span> <br>
		<span class="main">06.&ndash;09. Juni 2021</span>
	</h2>
</header>

<nav>
	<ul class="main">
		<li id="navHome">
			<a href="./">Startseite</a>
		</li>
		<!--<li id="navAnmeldung">
			<a href="./anmeldung/">Anmeldung</a>
		</li>-->
		<li id="navProgramm">
		<a href="./programm/">Programm</a>
		</li>
		<!--<li id="navCall">
		<a href="./callforpapers/">Call for Participation</a>
		</li>
		
		<li id="navAnreise">
			<a href="./anreise/">Anreise</a>
		</li>
		<li id="navStandort">
			<a href="./standort/">Standort</a>
		</li>-->
		<li id="navEvents">
			<a href="./socialevents/">Rahmenprogramm</a>
		</li>		
		<li id="navExpo">
			<a href="./expo/">Expo</a>
		</li>
		<li id="navTeam">
			<a href="./loc/loc.php">Team</a>
		</li>
	</ul>
</nav>

<div class="hero">
	<figure>
		<img class="img-fluid" src="./img/hsr_arial.png.jpg" alt="Rapperswil Luftbild">
		<figcaption>Photo: (C) by HSR</figcaption>
	</figure>
</div>
